import Phaser from 'phaser';
import { CombatEvents } from '../../core/CombatEvents.js';

const alive = e => e?.active && !e.isDefeated;
const playerDamage = (scene, enemy, amount) => scene.combatSystem?.damagePlayer?.(enemy, amount);
export const approach = (scene, enemy, min=enemy.attackRange, max=null) => { if(!alive(enemy)||!enemy.body) return; const dx=scene.player.x-enemy.x; const d=Math.abs(dx); const sp=enemy.speed||scene.balance.enemies?.entrySpeed||40; const buffer=enemy.rangeBuffer ?? scene.balance.enemies?.rangeBuffer ?? 24; if(max){ if(d>max+buffer) enemy.body.setVelocityX(Math.sign(dx||1)*sp); else if(d<max-buffer) enemy.body.setVelocityX(-Math.sign(dx||1)*sp); else enemy.body.setVelocityX(0); return; } if(d>min+8) enemy.body.setVelocityX(Math.sign(dx||1)*sp); else enemy.body.setVelocityX(0); };
export const entryMove = (scene, enemy) => { if(alive(enemy)&&enemy.body) enemy.body.setVelocityX(-(enemy.speed||scene.balance.enemies?.entrySpeed||40)); };
export const resetBodyPosition = (enemy,x,y=enemy.y) => { if(enemy.body?.reset) enemy.body.reset(x,y); else { enemy.x=x; enemy.y=y; } enemy.body?.setVelocityX?.(0); };

class ChargerBehavior { constructor(scene,e){ this.scene=scene; this.e=e; this.state='idle'; this.next=0; this.hit=false; this.chargeDirection=0; } onRecycle(){ this.state='idle'; this.hit=false; this.chargeDirection=0; this.e.setFillStyle?.(this.e.baseColor); } update(t){ const e=this.e,s=this.scene;if(!alive(e))return; if(this.state==='windup'&&t>=this.next){ this.state='charge'; this.hit=false; this.end=t+520; e.setFillStyle(0xff3b1f); this.chargeDirection=Math.sign(s.player.x-e.x||1); e.body.setVelocityX(this.chargeDirection*360); } else if(this.state==='charge'){ if(!this.hit&&Math.abs(e.x-s.player.x)<70){ this.hit=true; playerDamage(s,e,e.chargeDamage||e.damage*2); } if(t>=this.end){ this.state='cooldown'; this.next=t+1500; e.setFillStyle(e.baseColor); e.body.setVelocityX(0); } } else if(this.state==='cooldown'&&t>=this.next) this.state='idle'; if(this.state==='idle'){ approach(s,e,e.attackRange); if(Math.abs(e.x-s.player.x)<(e.chargeTriggerRange||330)){ this.state='windup'; this.next=t+(e.chargeWindupMs||520); e.setFillStyle(0xfff1a8); } } } shiftTimers(d,a){ if(this.next>a)this.next+=d; if(this.end>a)this.end+=d; } pause(){ this.savedVelocityX=this.e.body?.velocity?.x||0; this.e.body?.setVelocityX(0); } resume(){ if(this.state==='charge'&&this.e.body) this.e.body.setVelocityX((this.chargeDirection||Math.sign(this.scene.player.x-this.e.x||1))*360); } destroy(){} }
class BomberBehavior { constructor(scene,e){ this.scene=scene; this.e=e; this.next=0; this.bombs=[]; } onRecycle(){ this.destroy(); this.next=0; } update(t){ const e=this.e,s=this.scene;if(!alive(e))return; approach(s,e,e.attackRange,e.preferredRange); if(Math.abs(e.x-s.player.x)<e.attackRange&&t>=this.next){ this.next=t+(e.attackIntervalMs||1800); this.drop(t); } this.bombs=this.bombs.filter(b=>{ if(!b.warn?.active)return false; if(!b.exploded&&t>=b.explodeAt){ b.exploded=true; b.warn.setFillStyle(0xff4d4d,0.45); if(Phaser.Math.Distance.Between(s.player.x,s.player.y,b.x,b.y)<70) playerDamage(s,e,e.bombDamage||14); b.destroyAt=t+160; } if(b.destroyAt&&t>=b.destroyAt){ b.warn.destroy(); return false; } return true; }); } drop(t){ const x=this.scene.player.x,y=this.scene.balance.groundTopY-8; const warn=this.scene.add.circle(x,y,72,0xffcc00,0.22).setStrokeStyle(4,0xfff3a3,0.9).setDepth(19); this.bombs.push({x,y,warn,explodeAt:t+(this.e.bombWarningMs||1050),exploded:false}); } shiftTimers(d,a){ if(this.next>a)this.next+=d; this.bombs.forEach(b=>{ if(b.explodeAt>a)b.explodeAt+=d; if(b.destroyAt>a)b.destroyAt+=d; }); } pause(){ this.savedVelocityX=this.e.body?.velocity?.x||0; this.e.body?.setVelocityX(0); } resume(){} destroy(){ this.bombs.forEach(b=>b.warn?.destroy()); this.bombs=[]; } }
class HealerBehavior { constructor(scene,e){ this.scene=scene; this.e=e; this.next=0; this.fx=[]; } onRecycle(){ this.next=0; } update(t){ const e=this.e,s=this.scene;if(!alive(e))return; approach(s,e,e.attackRange,e.preferredRange); if(t<this.next)return; this.next=t+(e.attackIntervalMs||2200); const targets=s.enemies.filter(x=>alive(x)&&x!==e&&x.hp<x.maxHp&&Phaser.Math.Distance.Between(x.x,x.y,e.x,e.y)<520).sort((a,b)=>(b.isBoss?4:b.isElite?3:b.enemyId==='armored_guard'?2:1)-(a.isBoss?4:a.isElite?3:a.enemyId==='armored_guard'?2:1)); const target=targets[0]; if(target){ const before=target.hp; target.hp=Math.min(target.maxHp,target.hp+(e.healAmount||20)); s.floatText(target.x,target.y-70,`+${target.hp-before}`,'#5cff8d'); const line=s.add.line(0,0,e.x,e.y-40,target.x,target.y-55,0x58ff8a,0.9).setOrigin(0).setDepth(23); s.tweens.add({targets:line,alpha:0,duration:360,onComplete:()=>line.destroy()}); } else if(Math.abs(e.x-s.player.x)<e.attackRange) playerDamage(s,e,Math.max(1,Math.round(e.damage*0.7))); } shiftTimers(d,a){ if(this.next>a)this.next+=d; } pause(){ this.savedVelocityX=this.e.body?.velocity?.x||0; this.e.body?.setVelocityX(0); } resume(){} destroy(){} }
class MidBossBehavior { constructor(scene,e){ this.scene=scene; this.e=e; this.next=0; this.state='idle'; this.hit=false; this.warn=null; this.chargeDirection=0; } onRecycle(){ this.warn?.destroy(); this.warn=null; this.state='idle'; this.hit=false; this.chargeDirection=0; } update(t){ const e=this.e,s=this.scene;if(!alive(e))return; if(!e.enraged&&e.hp<=e.maxHp/2){ e.enraged=true; e.attackIntervalMs=e.enragedAttackIntervalMs; e.setFillStyle(0xb91c1c); s.hud?.setStatus('铁甲暴君进入狂暴状态'); } if(this.state==='slamWind'&&t>=this.fireAt){ if(Phaser.Math.Distance.Between(s.player.x,s.player.y,this.sx,this.sy)<(e.enraged?135:115)) playerDamage(s,e,e.slamDamage||18); this.warn?.destroy(); this.warn=null; this.state='cool'; this.next=t+(e.enraged?1050:1350); }
 else if(this.state==='charge' ){ if(!this.hit&&Math.abs(e.x-s.player.x)<78){this.hit=true;playerDamage(s,e,e.chargeDamage||24);} if(t>=this.end){e.body.setVelocityX(0);this.state='cool';this.next=t+1200;} }
 else if(this.state==='cool'&&t>=this.next)this.state='idle'; if(this.state==='idle'){ const d=Math.abs(e.x-s.player.x); if(d>e.attackRange) approach(s,e,e.attackRange); else e.body.setVelocityX(0); if(t>=this.next){ if(Math.random()<0.55){ this.sx=s.player.x; this.sy=s.player.y; this.warn=s.add.circle(this.sx,this.sy,e.enraged?135:115,0xff3333,0.18).setStrokeStyle(5,0xffdddd,0.9).setDepth(18); this.state='slamWind'; this.fireAt=t+760; e.body.setVelocityX(0); } else { this.state='charge'; this.hit=false; this.end=t+620; this.chargeDirection=Math.sign(s.player.x-e.x||1); e.body.setVelocityX(this.chargeDirection*285); } } } } shiftTimers(d,a){ ['next','fireAt','end'].forEach(k=>{if(this[k]>a)this[k]+=d;}); } pause(){ this.savedVelocityX=this.e.body?.velocity?.x||0; this.e.body?.setVelocityX(0); } resume(){ if(this.state==='charge'&&this.e.body) this.e.body.setVelocityX((this.chargeDirection||Math.sign(this.scene.player.x-this.e.x||1))*285); } destroy(){ this.warn?.destroy(); } }

class BerserkerBossBehavior { constructor(scene,e){ this.scene=scene; this.e=e; this.state='idle'; this.nextChargeAt=0; this.windupUntil=0; this.recoverUntil=0; this.chargeEndAt=0; this.hit=false; this.chargeDirection=-1; this.warn=null; }
  onRecycle(){ this.warn?.destroy(); this.warn=null; this.state='idle'; this.hit=false; this.e.setFillStyle?.(this.e.baseColor); this.e.setScale?.(1); }
  update(t){ const e=this.e,s=this.scene;if(!alive(e))return; if(!this.nextChargeAt) this.nextChargeAt=t+(e.chargeCooldownMs||4000); if(this.state==='windup'){ e.body.setVelocityX(0); const flash=Math.floor(t/120)%2===0; e.setFillStyle(flash?0xfff1a8:e.baseColor); e.setScale(flash?1.08:1); if(t>=this.windupUntil){ this.state='charge'; this.hit=false; this.warn?.destroy(); this.warn=null; e.setFillStyle(0xff3b1f); e.setScale(1); e.body.setVelocityX(this.chargeDirection*(e.speed||80)*3); this.chargeEndAt=t+520; } return; }
    if(this.state==='charge'){ if(!this.hit&&Math.abs(e.x-s.player.x)<82){ this.hit=true; playerDamage(s,e,e.chargeDamage||20,{source:'bossCharge'}); } if(t>=this.chargeEndAt){ e.body.setVelocityX(0); this.state='recovery'; this.recoverUntil=t+(e.chargeRecoveryMs||800); e.setFillStyle(0x92400e); } return; }
    if(this.state==='recovery'){ e.body.setVelocityX(0); if(t>=this.recoverUntil){ this.state='idle'; this.nextChargeAt=t+(e.chargeCooldownMs||4000); e.setFillStyle(e.baseColor); } return; }
    approach(s,e,e.attackRange); if(t>=this.nextChargeAt){ this.state='windup'; this.chargeDirection=Math.sign(s.player.x-e.x||-1); this.windupUntil=t+(e.chargeWindupMs||600); e.body.setVelocityX(0); this.warn=s.add.triangle(e.x,e.y-e.height/2-58,0,32,56,32,28,0,0xffe066,0.9).setStrokeStyle(4,0xffffff,1).setDepth(24); }
  }
  shiftTimers(d,a){ ['nextChargeAt','windupUntil','recoverUntil','chargeEndAt'].forEach(k=>{if(this[k]>a)this[k]+=d;}); }
  pause(){ this.savedVelocityX=this.e.body?.velocity?.x||0; this.e.body?.setVelocityX(0); }
  resume(){ if(this.state==='charge'&&this.e.body) this.e.body.setVelocityX(this.chargeDirection*(this.e.speed||80)*3); }
  destroy(){ this.warn?.destroy(); }
}

export default class EnemyBehaviorManager { constructor(scene){this.scene=scene;this.items=new Map();this.paused=false;} attach(e){ let C={charger:ChargerBehavior,bomber:BomberBehavior,healer:HealerBehavior,midBoss:MidBossBehavior,berserkerBoss:BerserkerBossBehavior}[e.behavior]; if(C)this.items.set(e,new C(this.scene,e)); e.entryState='entering'; } updateEnemyApproach(e){ approach(this.scene,e,e.attackRange,e.preferredRange); } recycleEnemy(e){ const b=this.items.get(e); b?.onRecycle?.(); const jitter=Phaser.Math.Between?.(0,28) ?? Math.floor(Math.random()*29); const x=this.scene.targeting.getEnemyRightRespawnX(e,undefined,jitter); resetBodyPosition(e,x,e.y); e.entryState='recycled'; e.recycleCount=(e.recycleCount||0)+1; this.scene.enemyRecycleCount=(this.scene.enemyRecycleCount||0)+1; entryMove(this.scene,e); } update(t){ if(this.paused) return; this.scene.enemies?.forEach(e=>{ if(!alive(e)) return; if(this.scene.targeting?.shouldRecycleEnemyLeft(e)){ this.recycleEnemy(e); return; } const full=this.scene.targeting?.isEnemyFullyInsideViewport(e); e.entryState=full?'active':(e.entryState==='recycled'?'recycled':'entering'); if(!full) entryMove(this.scene,e); }); this.scene.enemies?.forEach(e=>{ if(!alive(e)||this.items.has(e)) return; if(this.scene.targeting?.isEnemyFullyInsideViewport(e)) this.updateEnemyApproach(e); }); this.items.forEach((b,e)=>{ if(!alive(e)){ b.destroy(); this.items.delete(e); return; } if(!this.scene.targeting?.isEnemyFullyInsideViewport(e)) return; b.update(t); }); } pause(){ if(this.paused) return; this.paused=true; this.items.forEach((b,e)=>alive(e)?b.pause?.():(b.destroy(),this.items.delete(e))); this.scene.enemies?.forEach(e=>{ if(alive(e)&&e.body) e.body.setVelocityX(0); }); } resume(){ if(!this.paused) return; this.paused=false; this.scene.enemies?.forEach(e=>{ if(alive(e)&&e.body) e.body.setVelocityX(0); }); this.items.forEach((b,e)=>alive(e)?b.resume?.():(b.destroy(),this.items.delete(e))); } shiftTimers(d,a){ this.items.forEach(b=>b.shiftTimers?.(d,a)); } destroyEnemy(e){ this.items.get(e)?.destroy(); this.items.delete(e); } destroy(){ this.paused=false; this.items.forEach(b=>b.destroy?.()); this.items.clear(); } }
