import { SKILLS } from '../../config/skills.js';
import { TAGS } from '../../config/tags.js';
import { BALANCE } from '../../config/balance.js';

export const DESIGN_WIDTH=720, DESIGN_HEIGHT=1280;
const N={singlePulseDamage:[72,80,90,101,113,128,144,162,184],sweepDamage:[54,60,68,77,87,99,113,129,148],cycleIntervalMs:[7200,7000,6800,6600,6400,6100,5900,5700,5400],pulseGapMs:[300,290,280,270,260,240,230,220,200],sweepChargeMs:[460,440,420,400,380,350,330,310,280],sweepDurationMs:[620,610,600,590,580,550,530,510,480],sweepHalfAngleDeg:[18,18,22,22,22,28,29,30,36],sameTargetSecondPulseBonus:[0,0,.45,.45,.45,.45,.45,.45,.45],pulseMarkedSweepBonus:[0,0,0,0,0,.30,.30,.30,.30],sweepDefenseIgnore:[0,0,0,0,0,0,0,0,.35],fullViewportSweep:[false,false,false,false,false,false,false,false,true]};
const W={damageReduction:[.12,.13,.15,.16,.17,.19,.20,.21,.24],guardReduction:[.55,.57,.60,.62,.64,.68,.70,.72,.78],guardRechargeMs:[8500,8200,7800,7500,7200,6800,6400,6000,5200],guardTriggerMaxHpRatio:[.10,.10,.09,.09,.08,.08,.07,.07,.06],criticalHpRatio:[.30,.30,.32,.32,.34,.34,.36,.36,.40],postGuardDamageReduction:[0,0,.12,.13,.14,.16,.17,.18,.20],postGuardDurationMs:[0,0,1200,1250,1300,1450,1500,1550,1800],burstDamage:[0,0,0,0,0,85,100,116,140],burstRadius:[0,0,0,0,0,175,185,195,225],burstKnockback:[0,0,0,0,0,48,54,60,72],guardCharges:[1,1,1,1,1,1,1,1,2],emergencyProjectedHpRatio:[0,0,0,0,0,0,0,0,.25],emergencyGuardReduction:[0,0,0,0,0,0,0,0,.92],orbitRadius:[82,84,88,90,92,96,98,100,108],orbitPeriodMs:[2400,2350,2300,2250,2200,2100,2050,2000,1850]};
export const NEUTRON_STAR_VALUES=N; export const WHITE_DWARF_VALUES=W;
const now=s=>s.getGameplayTime?.()??s.now??0, lvlData=(sys,id,lvl)=>SKILLS[id].levels[lvl-1];
const ok=e=>e&&e.active!==false&&!e.isDefeated&&(e.hp??1)>0;
const enemies=s=>(s.targeting?.all?.()||s.enemies||[]).filter(e=>ok(e)&&(s.targeting?.isEnemyFullyInsideViewport?.(e)!==false));
const node=(rt,n)=>{ if(n) rt.visuals.add(n); return n; }, destroy=n=>n?.destroy?.();
export function neutronStarScreenPosition(scene){ const groundTopY=scene.balance?.groundTopY??620; return {x:(DESIGN_WIDTH*BALANCE.camera.playerScreenAnchorX+DESIGN_WIDTH/2)/2,y:groundTopY-245}; }
function originWorld(s){ const p=neutronStarScreenPosition(s), cam=s.cameras?.main; return {x:(cam?.worldView?.x??((cam?.worldView?.centerX??DESIGN_WIDTH/2)-DESIGN_WIDTH/2))+p.x,y:(cam?.worldView?.y??0)+p.y,screen:p}; }
function damage(sys,e,d,extra={}){ if(!ok(e))return false; return sys.scene.combatSystem?.damageEnemy?.(e,Math.round(d),{source:'skill',skillId:'neutron_star',tags:[TAGS.MAGIC,TAGS.CELESTIAL,TAGS.BUILD_CELESTIAL],...extra}); }
function pick(s,exclude){ return enemies(s).filter(e=>e!==exclude).sort((a,b)=>(b.hp-a.hp)||Math.abs(a.x-s.player.x)-Math.abs(b.x-s.player.x))[0]||(!exclude?null:enemies(s)[0]); }
function ensureNeutron(sys){ const s=sys.scene; let rt=s.neutronStarRuntime; if(rt)return rt; rt=s.neutronStarRuntime={visuals:new Set(),phase:'idle',nextAt:now(s),pulseHits:new Set(),shutdown:null,updater:null}; rt.updater=()=>updateNeutron(sys); sys.passiveUpdaters.push(rt.updater); rt.shutdown=()=>NeutronStarSkill.destroyRuntime(sys); s.events?.once?.('shutdown',rt.shutdown); return rt; }
function cleanupSet(rt){ rt?.visuals?.forEach(destroy); rt?.visuals?.clear?.(); }
function updateNeutron(sys){ const s=sys.scene,l=sys.getLevel?.('neutron_star')||0,rt=s.neutronStarRuntime; if(!l){ if(rt) NeutronStarSkill.destroyRuntime(sys); return; } const d=lvlData(sys,'neutron_star',l), t=now(s); if(!rt.body&&s.add){ const p=neutronStarScreenPosition(s); rt.body=node(rt,s.add.circle?.(p.x,p.y,16,0x7dd3fc,.95)?.setScrollFactor?.(0)?.setDepth?.(18)); rt.ring=node(rt,s.add.circle?.(p.x,p.y,28,0x38bdf8,.25)?.setStrokeStyle?.(4,0xe0f2fe,.8)?.setScrollFactor?.(0)?.setDepth?.(18)); } const p=neutronStarScreenPosition(s); rt.body?.setPosition?.(p.x,p.y); rt.ring?.setPosition?.(p.x,p.y); if(t<rt.nextAt)return; if(rt.phase==='idle'){ rt.phase='pulse1'; rt.pulseHits.clear(); }
  if(rt.phase==='pulse1'||rt.phase==='pulse2'){ const second=rt.phase==='pulse2', first=rt.firstTarget; const target=second?pick(s,first):pick(s,null); if(target){ const same=second&&target===first, mult=same?1+d.sameTargetSecondPulseBonus:1; damage(sys,target,d.singlePulseDamage*mult,{defenseIgnore:0}); rt.pulseHits.add(target); if(!second)rt.firstTarget=target; const o=originWorld(s); rt.lastAttackOrigin=o; node(rt,s.add?.line?.(0,0,o.x,o.y,target.x,target.y,0xe0f2fe,.75)?.setDepth?.(20)); }
    rt.phase=second?'charge':'pulse2'; rt.nextAt=t+(second?d.sweepChargeMs:d.pulseGapMs); return; }
  if(rt.phase==='charge'){ const list=enemies(s), o=originWorld(s); const angle=list.length?Math.atan2(list.reduce((a,e)=>a+e.y,0)/list.length-o.y,list.reduce((a,e)=>a+e.x,0)/list.length-o.x):0; rt.sweep={start:t,end:t+d.sweepDurationMs,hit:new Set(),targets:d.fullViewportSweep?new Set(list):null,center:angle,half:d.fullViewportSweep?Math.PI: d.sweepHalfAngleDeg*Math.PI/180,origin:o}; rt.phase='sweep'; rt.nextAt=t; node(rt,s.add?.rectangle?.(o.screen.x,o.screen.y,500,18,0x7dd3fc,.20)?.setScrollFactor?.(0)?.setDepth?.(19)); return; }
  if(rt.phase==='sweep'){ const sw=rt.sweep, prog=Math.min(1,(t-sw.start)/Math.max(1,d.sweepDurationMs)), ang=sw.center-sw.half+2*sw.half*prog; const candidates=sw.targets?[...sw.targets].filter(ok):enemies(s).filter(e=>Math.abs(Math.atan2(e.y-sw.origin.y,e.x-sw.origin.x)-ang)<.12 || t>=sw.end); for(const e of candidates){ if(sw.hit.has(e))continue; const bonus=rt.pulseHits.has(e)?1+d.pulseMarkedSweepBonus:1; damage(sys,e,d.sweepDamage*bonus,{defenseIgnore:d.sweepDefenseIgnore}); sw.hit.add(e); } if(t>=sw.end){ rt.phase='idle'; rt.nextAt=t+d.cycleIntervalMs; rt.firstTarget=null; rt.pulseHits.clear(); rt.sweep=null; } }
}
export const NeutronStarSkill={bind(sys){ensureNeutron(sys);return()=>NeutronStarSkill.destroyRuntime(sys);},destroyRuntime(sys){ const s=sys.scene,rt=s.neutronStarRuntime; if(!rt)return; cleanupSet(rt); sys.passiveUpdaters=sys.passiveUpdaters.filter(f=>f!==rt.updater); if(rt.shutdown)s.events?.off?.('shutdown',rt.shutdown); s.neutronStarRuntime=null; }};
function ensureWD(sys){ const s=sys.scene; let rt=s.whiteDwarfRuntime; if(rt)return rt; rt=s.whiteDwarfRuntime={visuals:[],charges:[],angle:0,last:now(s),guardUntil:0,updater:null,shutdown:null,getSkillBarState(){ const t=now(s), ready=this.charges.filter(c=>c.readyAt<=t).length,total=this.charges.length,rem=Math.max(0,...this.charges.map(c=>c.readyAt-t)); return {text: ready===total?`护体 ${ready}/${total}`:`护体 ${ready}/${total} · ${Math.ceil(rem/1000)}s`}; }}; rt.updater=()=>updateWD(sys); sys.passiveUpdaters.push(rt.updater); rt.shutdown=()=>WhiteDwarfSkill.destroyRuntime(sys); s.events?.once?.('shutdown',rt.shutdown); return rt; }
function syncDR(sys){ const l=sys.getLevel?.('white_dwarf')||0,p=sys.scene.playerData; p.damageReductionBonuses??={}; if(l) p.damageReductionBonuses.white_dwarf=SKILLS.white_dwarf.levels[l-1].damageReduction; else {delete p.damageReductionBonuses.white_dwarf; delete p.damageReductionBonuses.white_dwarf_guard;} }
function updateWD(sys){ const s=sys.scene,l=sys.getLevel?.('white_dwarf')||0; if(!l){ if(s.whiteDwarfRuntime)WhiteDwarfSkill.destroyRuntime(sys); return;} const d=lvlData(sys,'white_dwarf',l),rt=ensureWD(sys),t=now(s); syncDR(sys); while(rt.charges.length<d.guardCharges)rt.charges.push({readyAt:t}); rt.charges.length=d.guardCharges; if(rt.guardUntil&&t>=rt.guardUntil){ delete s.playerData.damageReductionBonuses.white_dwarf_guard; rt.guardUntil=0; } const dt=t-rt.last; rt.last=t; rt.angle+=(dt/Math.max(1,d.orbitPeriodMs))*Math.PI*2; if(s.add&&!rt.visuals.length) for(let i=0;i<d.guardCharges;i++) rt.visuals.push(s.add.circle?.(s.player.x,s.player.y,22,0xe0f2fe,.9)?.setDepth?.(12)); while(rt.visuals.length<d.guardCharges) rt.visuals.push(s.add.circle?.(s.player.x,s.player.y,22,0xe0f2fe,.9)?.setDepth?.(12)); rt.visuals.forEach((v,i)=>{ const a=rt.angle+i*Math.PI*2/rt.visuals.length; v?.setPosition?.(s.player.x+Math.cos(a)*d.orbitRadius,s.player.y+Math.sin(a)*d.orbitRadius); v?.setAlpha?.(rt.charges[i]?.readyAt<=t?.9:.35); }); }
function burst(sys,d){ const s=sys.scene; for(const e of enemies(s)){ if(Math.hypot(e.x-s.player.x,e.y-s.player.y)>d.burstRadius)continue; s.combatSystem?.damageEnemy?.(e,d.burstDamage,{source:'skill',skillId:'white_dwarf',tags:[TAGS.MAGIC,TAGS.CELESTIAL,TAGS.BUILD_CELESTIAL,'area'],noLifeSteal:true}); if(!e.isBoss&&d.burstKnockback){ const m=e.isElite?.35:1, dir=e.x>=s.player.x?1:-1, nx=Math.max(0,Math.min(s.physics?.world?.bounds?.width??99999,e.x+dir*d.burstKnockback*m)); e.x=nx; e.body?.setVelocityX?.(0); } } }
export const WhiteDwarfSkill={bind(sys){ensureWD(sys);syncDR(sys);return()=>WhiteDwarfSkill.destroyRuntime(sys);},destroyRuntime(sys){ const s=sys.scene,rt=s.whiteDwarfRuntime; if(rt){ rt.visuals.forEach(destroy); sys.passiveUpdaters=sys.passiveUpdaters.filter(f=>f!==rt.updater); if(rt.shutdown)s.events?.off?.('shutdown',rt.shutdown); } delete s.playerData?.damageReductionBonuses?.white_dwarf; delete s.playerData?.damageReductionBonuses?.white_dwarf_guard; s.whiteDwarfRuntime=null; },beforePlayerHpDamage(sys,payload){ const s=sys.scene,l=sys.getLevel?.('white_dwarf')||0; if(!l||!payload.directAttack||payload.hpDamage<=0)return null; const d=lvlData(sys,'white_dwarf',l),rt=ensureWD(sys),t=now(s),idx=rt.charges.findIndex(c=>c.readyAt<=t); if(idx<0)return null; const max=s.playerData.maxHp||100, cur=s.playerData.hp??max, projected=(cur-payload.hpDamage)/max; let reduction=d.guardReduction, trigger=payload.hpDamage>=max*d.guardTriggerMaxHpRatio || cur/max<=d.criticalHpRatio; if(d.emergencyProjectedHpRatio&&projected<=d.emergencyProjectedHpRatio){ trigger=true; reduction=d.emergencyGuardReduction; s.floatText?.(s.player.x,s.player.y-40,'临界稳定',0xe0f2fe); } if(!trigger)return null; rt.charges[idx].readyAt=t+d.guardRechargeMs; const hpDamage=Math.max(1,Math.round(payload.hpDamage*(1-reduction))); if(d.postGuardDamageReduction){ s.playerData.damageReductionBonuses??={}; s.playerData.damageReductionBonuses.white_dwarf_guard=d.postGuardDamageReduction; rt.guardUntil=t+d.postGuardDurationMs; } if(d.burstDamage)burst(sys,d); s.floatText?.(s.player.x,s.player.y-28,'简并护体',0xe0f2fe); return {hpDamage}; }};
function arr(o,k){return o[k].map((v,i)=>({[k]:v}));}
export function configureCelestialFlowSkills(){ const n=Array.from({length:9},(_,i)=>({singlePulseCount:2,singlePulseVisualMs:140,sweepWarningAlpha:.20,sweepBeamWidthPx:18,sweepHitLimitPerEnemy:1,maxSinglePulseTargets:2,...Object.fromEntries(Object.keys(N).map(k=>[k,N[k][i]])),desc:`单体脉冲${N.singlePulseDamage[i]}，横扫${N.sweepDamage[i]}，循环${(N.cycleIntervalMs[i]/1000).toFixed(1)}秒。`,milestoneText:i===2?'脉冲聚焦':i===5?'脉冲共振':i===8?'全域星脉':undefined})); const w=Array.from({length:9},(_,i)=>({whiteDwarfVisualRadius:22,whiteDwarfGlowRadius:34,guardBurstVisualMs:260,guardFloatText:'简并护体',emergencyFloatText:'临界稳定',...Object.fromEntries(Object.keys(W).map(k=>[k,W[k][i]])),desc:`常驻减伤${Math.round(W.damageReduction[i]*100)}%，护体减伤${Math.round(W.guardReduction[i]*100)}%，恢复${(W.guardRechargeMs[i]/1000).toFixed(1)}秒。`,milestoneText:i===2?'简并星壳':i===5?'质量反冲':i===8?'双星稳定':undefined})); SKILLS.neutron_star={id:'neutron_star',name:'中子星',rarity:'MYTHIC',handler:'neutron_star',passive:true,ultimateSkill:true,maxLevel:9,targetType:'passive',manaCost:0,short:'星',color:0x7dd3fc,tags:[TAGS.MAGIC,TAGS.CELESTIAL,TAGS.BUILD_CELESTIAL,'mythicSkill'],description:'获得后永久悬浮于太阳与黑洞之间，周期释放两次单体脉冲，随后释放一次横扫脉冲。',milestones:{3:'脉冲聚焦：两次单体脉冲命中同一目标时，第二次脉冲伤害提高45%。',6:'脉冲共振：横扫脉冲对本轮已被单体脉冲命中的敌人额外造成30%伤害。',9:'全域星脉：横扫覆盖当前全部可视敌人，并无视35%防御。'},levels:n}; SKILLS.white_dwarf={id:'white_dwarf',name:'白矮星',rarity:'MYTHIC',handler:'white_dwarf',passive:true,ultimateSkill:true,maxLevel:9,targetType:'passive',manaCost:0,short:'矮',color:0xe0f2fe,tags:[TAGS.MAGIC,TAGS.CELESTIAL,TAGS.BUILD_CELESTIAL,TAGS.SHIELD,'mythicSkill'],description:'白矮星永久围绕玩家旋转，提供常驻减伤，并消耗护体次数压缩高额直接伤害。',milestones:{3:'简并星壳：护体触发后，短时间内获得额外伤害减免。',6:'质量反冲：护体触发时，对玩家周围敌人造成范围魔法伤害并推离普通敌人。',9:'双星稳定：生成第二颗白矮星，获得两次独立护体；致命重击将触发临界稳定。'},levels:w}; }
