import { SKILLS } from '../../config/skills.js';
import { TAGS } from '../../config/tags.js';
import { CombatEvents } from '../../core/CombatEvents.js';

export const CHARGED_SLAM_ID='charged_slam';
export const CHARGED_SLAM_DAMAGE_RATIOS=[.8,.9,1,1.1,1.2,1.3,1.4,1.5,1.6];
export const CHARGED_SLAM_RADII=[110,118,130,138,146,158,168,178,190];
export const CHARGED_SLAM_ATTACKS=[5,5,5,5,5,4,4,4,4];
const levels=CHARGED_SLAM_DAMAGE_RATIOS.map((damageRatio,i)=>{ const level=i+1; return {damageRatio,radius:CHARGED_SLAM_RADII[i],attacksRequired:CHARGED_SLAM_ATTACKS[i],knockback:level>=3?56:0,aftershockDelayMs:level>=9?250:0,aftershockDamageRatio:level>=9?.5:0,aftershockRadiusRatio:level>=9?.7:0,...(level===3?{milestoneText:'震地重击：主震轻度击退普通与精英敌人'}:{}),...(level===6?{milestoneText:'快速蓄势：触发需求降低为4次真实普通攻击'}:{}),...(level===9?{milestoneText:'二重崩击：250毫秒后在原地触发50%伤害余震'}:{}),desc:`每${CHARGED_SLAM_ATTACKS[i]}次真实普通攻击，在主要目标脚下造成${Math.round(damageRatio*100)}%基础伤害的${CHARGED_SLAM_RADII[i]}范围震地重击。`}; });
export function configureChargedSlamSkill(){ SKILLS[CHARGED_SLAM_ID]={id:CHARGED_SLAM_ID,name:'蓄势重击',rarity:'FINE',handler:CHARGED_SLAM_ID,passive:true,maxLevel:9,tags:['physical','area',TAGS.NORMAL_ATTACK],cooldownMs:999999,targetType:'passive',color:0xb58b3b,short:'蓄',description:'玩家本体连续完成真实普通攻击后，在主要目标脚下触发一次范围震地重击。',milestones:{3:'震地重击',6:'快速蓄势',9:'二重崩击'},levels}; }

function cleanupVisuals(state){ state.visuals.forEach(r=>{r.tween?.stop?.();r.tween?.remove?.();r.node?.destroy?.();}); state.visuals.clear(); }
function track(scene,state,node,config){ if(!node)return; const r={node,tween:null},done=()=>{state.visuals.delete(r);node.destroy?.();}; state.visuals.add(r); r.tween=scene.tweens?.add?.({targets:node,...config,onComplete:done})||null; }
function visual(scene,state,x,y,radius,aftershock,enhanced){ const alpha=aftershock?.22:(enhanced?.48:.36),color=enhanced?0xe1b75c:0xb58b3b; const ring=scene.add?.ellipse?.(x,y,radius*.7,radius*.18,color,alpha)?.setStrokeStyle?.(aftershock?3:5,0xf5d88a,alpha+.25)?.setDepth?.(143); track(scene,state,ring,{scaleX:2.1,scaleY:1.45,alpha:0,duration:aftershock?260:330,ease:'Cubic.easeOut'}); const cracks=aftershock?4:6; for(let i=0;i<cracks;i++){const a=Math.PI*2*i/cracks+.25,len=radius*(.25+(i%2)*.06),node=scene.add?.rectangle?.(x+Math.cos(a)*len*.55,y+Math.sin(a)*len*.16,len,3,0x725122,alpha)?.setRotation?.(a)?.setDepth?.(142);track(scene,state,node,{alpha:0,duration:aftershock?250:360});} const dust=aftershock?3:6; for(let i=0;i<dust;i++){const a=Math.PI*2*i/dust,node=scene.add?.circle?.(x+Math.cos(a)*radius*.2,y+Math.sin(a)*radius*.05,aftershock?3:5,0xc9a35b,alpha)?.setDepth?.(144);track(scene,state,node,{x:x+Math.cos(a)*radius*.55,y:y-10+Math.sin(a)*radius*.12,alpha:0,duration:aftershock?250:350});} }
const targetPosition=p=>{const target=p?.enemy||p?.targets?.[0];return target&&Number.isFinite(target.x)&&Number.isFinite(target.y)?{x:target.x,y:target.y}:null;};
function damageAt(system,state,slam,aftershock=false){const s=system.scene,radius=aftershock?slam.radius*slam.aftershockRadiusRatio:slam.radius,amount=Math.max(1,Math.round(slam.baseDamage*(aftershock?slam.aftershockDamageRatio:1)));visual(s,state,slam.x,slam.y,radius,aftershock,!aftershock&&slam.knockback>0);const professionMultiplier=s.professionSystem?.getDamageMultiplier?.({type:'normalAttack',damaging:true})||1;s.targeting.all().filter(e=>s.targeting.valid(e)&&Math.hypot(e.x-slam.x,e.y-slam.y)<=radius).forEach(e=>{const damaged=s.combatSystem.damageEnemy(e,Math.round(amount*professionMultiplier),{source:'skill',skillId:CHARGED_SLAM_ID,damageKind:aftershock?'chargedSlamAftershock':'chargedSlam',tags:['physical','area'],critResolved:true,crit:false,canCrit:false,allowLifeSteal:false,canTriggerArtifacts:false,professionApplied:true,professionMultiplier,baseAmountBeforeProfession:amount,noKnockback:true});if(damaged&&!aftershock&&slam.knockback>0&&!e.isBoss&&s.targeting.valid(e))s.combatSystem.applyKnockback(e,{source:'skill',knockback:slam.knockback});});}
export const getChargedSlamState=system=>{const state=system?.passiveState?.chargedSlam;if(!state)return null;const required=system.getData(CHARGED_SLAM_ID)?.attacksRequired||5;return Object.freeze({count:Math.min(state.count,required),required,ready:state.ready});};
export const ChargedSlamSkill={bind(system){const s=system.scene,state={count:0,ready:false,pending:[],visuals:new Set(),cleaned:false};system.passiveState.chargedSlam=state;const release=(position,payload,data,level)=>{const slam={...position,level,radius:data.radius,knockback:data.knockback,aftershockDelayMs:data.aftershockDelayMs,aftershockDamageRatio:data.aftershockDamageRatio,aftershockRadiusRatio:data.aftershockRadiusRatio,baseDamage:Math.max(1,Math.round((Number(payload.baseDamage)||0)*data.damageRatio))};state.count=0;state.ready=false;damageAt(system,state,slam);if(slam.aftershockDelayMs>0)state.pending.push({dueAt:(s.getGameplayTime?.()??0)+slam.aftershockDelayMs,slam});};const onAttack=p=>{const data=system.getData(CHARGED_SLAM_ID),level=system.getLevel(CHARGED_SLAM_ID);if(!data||!level)return;const pos=targetPosition(p);if(state.ready||state.count>=data.attacksRequired){state.ready=true;if(pos)release(pos,p,data,level);return;}state.count++;if(state.count<data.attacksRequired)return;state.ready=true;if(pos)release(pos,p,data,level);};const updater=()=>{if(state.cleaned)return;const data=system.getData(CHARGED_SLAM_ID);if(data&&state.count>=data.attacksRequired)state.ready=true;const now=s.getGameplayTime?.()??0,due=state.pending.filter(x=>x.dueAt<=now);state.pending=state.pending.filter(x=>x.dueAt>now);due.forEach(x=>damageAt(system,state,x.slam,true));};const off=s.eventBus.on(CombatEvents.PLAYER_ATTACK_RESOLVED,onAttack);system.passiveUpdaters.push(updater);return()=>{if(state.cleaned)return;state.cleaned=true;off?.();state.pending.length=0;cleanupVisuals(state);system.passiveUpdaters=system.passiveUpdaters.filter(x=>x!==updater);if(system.passiveState.chargedSlam===state)delete system.passiveState.chargedSlam;};}};
