import { SKILLS } from '../../config/skills.js';
import { TAGS } from '../../config/tags.js';
import { CombatEvents } from '../../core/CombatEvents.js';
import { NINEFOLD_DAO_ID, getCultivationSnapshot, grantCultivation } from './CultivationCoreSkill.js';

export const ALCHEMY_ID='alchemy';
export const MATERIAL_MULTIPLIERS=[1,1.1,1.2,1.35,1.5,1.7,1.9,2.15,2.5];
export const CRAFT_DURATIONS_MS=[1500,1400,1300,1200,1100,1000,900,800,700];
export const PILL_RECIPES=[
  {realm:'炼气',id:'qi',name:'聚气丹',short:'聚气',bone:12,blood:8,cultivation:25},
  {realm:'筑基',id:'foundation',name:'筑基丹',short:'筑基',bone:40,blood:30,cultivation:100},
  {realm:'金丹',id:'golden_core',name:'金元丹',short:'金元',bone:150,blood:110,cultivation:400},
  {realm:'元婴',id:'nascent',name:'婴元丹',short:'婴元',bone:800,blood:600,cultivation:1500},
  {realm:'化神',id:'spirit',name:'化神丹',short:'化神',bone:5000,blood:4000,cultivation:8000},
  {realm:'炼虚',id:'void',name:'炼虚丹',short:'炼虚',bone:50000,blood:40000,cultivation:60000},
  {realm:'合体',id:'union',name:'合道丹',short:'合道',bone:1000000,blood:800000,cultivation:1000000},
  {realm:'大乘',id:'mahayana',name:'大乘仙丹',short:'大乘',bone:30000000,blood:24000000,cultivation:10000000},
];
export const TRIBULATION_PILL={realm:'渡劫',id:'tribulation',name:'渡劫仙丹',short:'仙丹',bone:30000000,blood:24000000,cultivation:0,tribulation:true};
const stateOf=sys=>sys?.passiveState?.alchemy;
const levelOf=sys=>Math.max(0,Math.min(9,Number(sys?.getLevel?.(ALCHEMY_ID))||0));
const clean=n=>Math.max(0,Math.floor(Number(n)||0));
function destroy(o){ o?.destroy?.(); }
function removeTween(t){ t?.stop?.(); t?.remove?.(); t?.destroy?.(); }
export function getAlchemyState(sceneOrSystem){ const sys=sceneOrSystem?.skillSystem||sceneOrSystem; return stateOf(sys)||null; }
export function getAlchemyCultivationDamageMultiplier(sceneOrSystem){ const sc=sceneOrSystem?.scene||sceneOrSystem; const st=getAlchemyState(sceneOrSystem); const now=sc?.getGameplayTime?.()??0; return st && (st.alchemyBuffUntil||0)>now ? 1.5 : 1; }
export function getAlchemyRecipe(sceneOrSystem){ const snap=getCultivationSnapshot(sceneOrSystem); if(!snap.active) return PILL_RECIPES[0]; if(snap.isComplete||snap.realmIndex>=8) return TRIBULATION_PILL; return PILL_RECIPES[Math.max(0,Math.min(PILL_RECIPES.length-1,snap.realmIndex||0))]; }
export function alchemyEnemyMaterials(enemy={}, level=1){ const enemyLevel=Math.max(1,Math.floor(Number(enemy.level)||1)); let bone=2,blood=1,type='normal'; if(enemy.isFinalBoss){bone=200;blood=160;type='finalBoss';} else if(enemy.isMidBoss||enemy.isBoss){bone=60;blood=45;type='midBoss';} else if(enemy.isElite){bone=12;blood=8;type='elite';} return {type,enemyLevel,bone:bone*enemyLevel,blood:blood*enemyLevel}; }
export function applyAlchemyMaterialMultiplier(base, skillLevel, kind, enemyType){ const lv=Math.max(1,Math.min(9,skillLevel||1)); let value=(Number(base)||0)*MATERIAL_MULTIPLIERS[lv-1]; if(kind==='blood'&&lv>=3&&(enemyType==='elite'||enemyType==='midBoss'||enemyType==='finalBoss')) value*=1.5; const out=Math.floor(value); return base>0?Math.max(1,out):0; }
function ensure(sys){ if(levelOf(sys)<=0) return null; let st=stateOf(sys); if(st) return st; st={boneEssence:0,bloodEssence:0,crafting:false,currentPillId:null,craftProgressMs:0,craftDurationMs:1500,batchCount:0,nineTurnCounter:0,lastGameplayAt:sys.scene?.getGameplayTime?.()??0,alchemyBuffUntil:0,cauldronVisual:null,materialVisuals:[],pillVisuals:[],timers:[],tweens:[],updater:null,listener:null,completedPills:0,lastCultivationGranted:0}; sys.passiveState.alchemy=st; createCauldron(sys,st); return st; }
function canAdvance(sys){ const s=sys?.scene; return !s?.isGameplayPaused?.() && (s?.playerData?.hp??1)>0; }
function convertForLv6(st,r){ const needB=Math.max(0,r.bone-st.boneEssence), needL=Math.max(0,r.blood-st.bloodEssence); if(needB>0&&needL>0) return false; if(needL>0&&st.boneEssence>=r.bone+needL*2){ st.boneEssence-=needL*2; st.bloodEssence+=needL; return true; } if(needB>0&&st.bloodEssence>=r.blood+needB*2){ st.bloodEssence-=needB*2; st.boneEssence+=needB; return true; } return needB===0&&needL===0; }
function tryStart(sys){ const st=ensure(sys); if(!st||st.crafting) return false; const r=getAlchemyRecipe(sys); if(levelOf(sys)>=6) convertForLv6(st,r); if(st.boneEssence<r.bone||st.bloodEssence<r.blood) return false; st.crafting=true; st.currentPillId=r.id; st.craftProgressMs=0; st.craftDurationMs=CRAFT_DURATIONS_MS[levelOf(sys)-1]||1500; return true; }
function complete(sys){ const st=stateOf(sys), s=sys.scene, r=getAlchemyRecipe(sys); if(!st) return; st.boneEssence-=r.bone; st.bloodEssence-=r.blood; st.crafting=false; st.craftProgressMs=0; st.batchCount+=1; st.completedPills+=1; const nine=levelOf(sys)>=9 && ((st.nineTurnCounter+1)>=9); st.nineTurnCounter=nine?0:Math.min(8,(st.nineTurnCounter||0)+1); const p=s.playerData||{}; const heal=Math.round((p.maxHp||0)*(r.tribulation?0.2:0.1)); if(heal>0) s.healPlayer?.(heal,'skill',{skillId:ALCHEMY_ID}) ?? (p.hp=Math.min(p.maxHp,(p.hp||0)+heal)); if(r.tribulation){ sys.recoverMana?.(p.maxMana||0); st.alchemyBuffUntil=(s.getGameplayTime?.()??0)+10000; } else { sys.recoverMana?.(20); const base=r.cultivation*(nine?9:1); const res=grantCultivation(sys,base,{source:ALCHEMY_ID}); st.lastCultivationGranted=res?.actualAmount||0; }
 showPill(sys,st,r,nine,heal); s.hud?.update?.(); s.skillBar?.update?.(); tryStart(sys); }
function update(sys){ const st=ensure(sys); if(!st) return; const now=sys.scene?.getGameplayTime?.()??0; if(!canAdvance(sys)){ st.lastGameplayAt=now; return; } const elapsed=Math.max(0,now-(st.lastGameplayAt??now)); st.lastGameplayAt=now; if(!st.crafting) tryStart(sys); if(st.crafting){ st.craftProgressMs+=elapsed; if(st.craftProgressMs>=st.craftDurationMs) complete(sys); } syncVisual(sys,st); }
function onKill(sys,payload){ const st=ensure(sys); if(!st||!payload?.enemy) return; const lv=levelOf(sys), m=alchemyEnemyMaterials(payload.enemy); st.boneEssence+=applyAlchemyMaterialMultiplier(m.bone,lv,'bone',m.type); st.bloodEssence+=applyAlchemyMaterialMultiplier(m.blood,lv,'blood',m.type); materialVisual(sys,st); tryStart(sys); sys.scene?.skillBar?.update?.(); }
function createCauldron(sys,st){ const s=sys.scene; if(!s?.add||st.cauldronVisual) return; const c=s.add.container?.(0,0)?.setDepth?.(90); const pot=s.add.circle?.(0,0,12,0x4b3a31,.9); const lid=s.add.rectangle?.(0,-10,24,6,0x6b4c34,.95); c?.add?.([pot,lid].filter(Boolean)); st.cauldronVisual=c||pot; syncVisual(sys,st); }
function syncVisual(sys,st){ const p=sys.scene?.player; if(!p||!st?.cauldronVisual) return; const dir=p.flipX?-1:1; st.cauldronVisual.setPosition?.(p.x-dir*34,p.y-68); }
function materialVisual(sys,st){ const s=sys.scene; if(!s?.add) return; const p=s.player||{x:0,y:0}; for(const color of [0xd9d9d9,0x8b1f2d]){ const o=s.add.circle?.(p.x+40,p.y-90,4,color,.85)?.setDepth?.(95); if(!o) continue; st.materialVisuals.push(o); const tw=s.tweens?.add?.({targets:o,x:p.x-34,y:p.y-68,alpha:0,duration:260,onComplete:()=>{destroy(o); st.materialVisuals=st.materialVisuals.filter(v=>v!==o);}}); if(tw) st.tweens.push(tw); } }
function showPill(sys,st,r,nine,heal){ const s=sys.scene; s.floatText?.(s.player?.x||0,(s.player?.y||0)-120,nine?'九转丹成':r.name,'#ffd166'); if(!r.tribulation&&st.lastCultivationGranted) s.floatText?.(s.player?.x||0,(s.player?.y||0)-150,`修为+${Math.floor(st.lastCultivationGranted)}`,'#ffb347'); s.floatText?.(s.player?.x||0,(s.player?.y||0)-95,`生命+${heal}`,'#7dff8a'); s.floatText?.(s.player?.x||0,(s.player?.y||0)-70,r.tribulation?'法力全满':'法力+20','#66ccff'); const o=s.add?.circle?.(s.player?.x||0,(s.player?.y||0)-68,7,nine?0xff3322:0xffd166,1)?.setDepth?.(110); if(o){ st.pillVisuals.push(o); const tw=s.tweens?.add?.({targets:o,y:(s.player?.y||0)-20,alpha:0,duration:420,onComplete:()=>{destroy(o); st.pillVisuals=st.pillVisuals.filter(v=>v!==o);}}); if(tw) st.tweens.push(tw); } }
function cleanup(sys){ const st=stateOf(sys); if(!st) return; if(st.listener) sys.scene?.eventBus?.off?.(CombatEvents.ENEMY_KILLED,st.listener); if(st.updater) sys.passiveUpdaters=sys.passiveUpdaters.filter(fn=>fn!==st.updater); [st.cauldronVisual,...st.materialVisuals,...st.pillVisuals].forEach(destroy); st.timers.forEach(t=>t?.remove?.(false)); st.tweens.forEach(removeTween); delete sys.passiveState.alchemy; }
function setup(sys){ const st=ensure(sys); if(!st) return null; if(!st.listener){ st.listener=payload=>onKill(sys,payload); sys.scene?.eventBus?.on?.(CombatEvents.ENEMY_KILLED,st.listener); } if(!st.updater) st.updater=()=>update(sys); if(!sys.passiveUpdaters.includes(st.updater)) sys.passiveUpdaters.push(st.updater); return st; }
export const CultivationAlchemySkill={ bind(sys){ setup(sys); return ()=>cleanup(sys); }, onAcquire(sys){ setup(sys); }, cleanup, shiftTimers(sys,duration,pausedAt){ const st=stateOf(sys); if(st&&duration>0&&(st.lastGameplayAt??pausedAt)<=pausedAt) st.lastGameplayAt=(st.lastGameplayAt??pausedAt)+duration; }, syncAttachedVisuals(sys){ const st=stateOf(sys); if(st) syncVisual(sys,st); }, getSkillBarState(sys){ const st=stateOf(sys); if(!st) return {text:'骨 0 血 0'}; if(st.crafting){ const r=getAlchemyRecipe(sys); return {text:`${r.short} ${Math.floor((st.craftProgressMs/Math.max(1,st.craftDurationMs))*100)}%`}; } const suffix=levelOf(sys)>=9?` 九转 ${st.nineTurnCounter||0}/9`:''; return {text:`骨 ${clean(st.boneEssence)} 血 ${clean(st.bloodEssence)}${suffix}`.slice(0,16)}; } };
export function configureCultivationAlchemySkill(){ SKILLS[ALCHEMY_ID]={id:ALCHEMY_ID,name:'炼丹术',rarity:'EPIC',handler:ALCHEMY_ID,passive:true,maxLevel:9,cooldownMs:999999,targetType:'passive',short:'丹',color:0xd89a2e,tags:[TAGS.MAGIC,TAGS.CULTIVATION,TAGS.BUILD_CULTIVATION],description:'敌人死亡后收集尸骨精华与精血，材料足够时自动炼丹。丹药恢复生命和法力；拥有九转大道时额外增加修为，渡劫后改为渡劫仙丹增益。',milestones:{3:'精血提纯：精英和Boss精血提高50%。',6:'血骨相济：当前炉只缺一种材料时按2:1转换补足。',9:'九转丹成：每第9炉丹药修为×9。'},levels:CRAFT_DURATIONS_MS.map((craftDurationMs,i)=>({craftDurationMs,materialMultiplier:MATERIAL_MULTIPLIERS[i],desc:`材料获取×${MATERIAL_MULTIPLIERS[i]}，炼丹时间${craftDurationMs/1000}秒。`}))}; }
