import { SKILLS } from '../../config/skills.js';
import { TAGS } from '../../config/tags.js';

export const NINEFOLD_DAO_ID = 'ninefold_dao';
export const CULTIVATION_REALMS = Object.freeze(['炼气','筑基','金丹','元婴','化神','炼虚','合体','大乘','渡劫']);
export const CULTIVATION_THRESHOLDS = Object.freeze([100,500,2500,15000,100000,1000000,20000000,500000000]);
export const CULTIVATION_BASE_RATES = Object.freeze([1,1.3,1.6,2,2.5,3.1,3.8,4.6,5.5]);
export const CULTIVATION_REALM_STATS = Object.freeze([
  { maxHpPct:.05, maxMana:20, manaRegen:0.5, damageReduction:0, spell:{damageMultiplier:1,rangeMultiplier:1,cooldownMultiplier:1,manaCostMultiplier:1}},
  { maxHpPct:.10, maxMana:40, manaRegen:1, damageReduction:.03, spell:{damageMultiplier:1.3,rangeMultiplier:1.05,cooldownMultiplier:1,manaCostMultiplier:.95}},
  { maxHpPct:.20, maxMana:80, manaRegen:2, damageReduction:.05, spell:{damageMultiplier:1.8,rangeMultiplier:1.10,cooldownMultiplier:.95,manaCostMultiplier:.90}},
  { maxHpPct:.35, maxMana:140, manaRegen:3.5, damageReduction:.08, spell:{damageMultiplier:2.8,rangeMultiplier:1.20,cooldownMultiplier:.90,manaCostMultiplier:.85}},
  { maxHpPct:.55, maxMana:220, manaRegen:5.5, damageReduction:.12, spell:{damageMultiplier:4.5,rangeMultiplier:1.30,cooldownMultiplier:.85,manaCostMultiplier:.80}},
  { maxHpPct:.80, maxMana:350, manaRegen:8, damageReduction:.16, spell:{damageMultiplier:7.5,rangeMultiplier:1.45,cooldownMultiplier:.78,manaCostMultiplier:.75}},
  { maxHpPct:1.20, maxMana:550, manaRegen:12, damageReduction:.22, spell:{damageMultiplier:13,rangeMultiplier:1.65,cooldownMultiplier:.70,manaCostMultiplier:.70}},
  { maxHpPct:2.00, maxMana:900, manaRegen:18, damageReduction:.30, spell:{damageMultiplier:25,rangeMultiplier:2.00,cooldownMultiplier:.60,manaCostMultiplier:.60}},
  { maxHpPct:4.00, maxMana:1500, manaRegen:30, damageReduction:.40, spell:{damageMultiplier:60,rangeMultiplier:2.50,cooldownMultiplier:.45,manaCostMultiplier:.50}},
]);
const neutralSpell=Object.freeze({damageMultiplier:1,rangeMultiplier:1,cooldownMultiplier:1,manaCostMultiplier:1});
const stateOf=x=>x?.skillSystem?.passiveState?.ninefoldDao || x?.passiveState?.ninefoldDao || null;
const systemOf=x=>x?.skillSystem || x;
const levelOf=sys=>sys?.getLevel?.(NINEFOLD_DAO_ID) || 0;
const finite=n=>Number.isFinite(Number(n));
const stat=i=>CULTIVATION_REALM_STATS[Math.max(0,Math.min(8,i||0))];
function rate(sys, st=stateOf(sys)){ const lv=levelOf(sys); if(!lv||!st) return 0; return CULTIVATION_BASE_RATES[Math.max(0,Math.min(8,lv-1))]*(lv>=6?1.25:1)*(lv>=9?Math.min(2.6,1+(st.breakthroughCount||0)*.2):1); }
function snapshot(sys){ const st=stateOf(sys); if(!st) return { active:false, hidden:true }; const idx=st.realmIndex||0, need=CULTIVATION_THRESHOLDS[idx]??null; return { active:true, realmIndex:idx, realm:CULTIVATION_REALMS[idx], progress:st.progress||0, nextThreshold:need, isComplete:idx>=8, cycleProgressMs:st.cycleProgressMs||0, breakthroughCount:st.breakthroughCount||0, autoRate:rate(systemOf(sys),st), gainMultiplier:levelOf(systemOf(sys))>=6?1.25:1, stats:stat(idx), nextRealm:idx<8?CULTIVATION_REALMS[idx+1]:null, nextStats:idx<8?stat(idx+1):null } }
export function getCultivationSnapshot(sceneOrSystem){ return snapshot(systemOf(sceneOrSystem)); }
export function getCultivationSpellModifiers(sceneOrSystem){ const st=stateOf(sceneOrSystem); return st ? { ...stat(st.realmIndex).spell } : { ...neutralSpell }; }
function applyStats(sys){ const st=stateOf(sys), p=sys?.scene?.playerData; if(!st||!p) return; p.damageReductionBonuses??={}; const baseHp=Math.max(1,(p.maxHp||0)-(st.appliedMaxHpBonus||0)); const baseMana=Math.max(0,(p.maxMana||0)-(st.appliedMaxManaBonus||0)); const s=stat(st.realmIndex); const hpBonus=Math.round(baseHp*s.maxHpPct), manaBonus=s.maxMana; const hpDiff=hpBonus-(st.appliedMaxHpBonus||0), manaDiff=manaBonus-(st.appliedMaxManaBonus||0); p.maxHp=baseHp+hpBonus; p.maxMana=baseMana+manaBonus; if(hpDiff>0) p.hp=Math.min(p.maxHp,(p.hp||0)+hpDiff); else p.hp=Math.min(p.hp||0,p.maxHp); if(manaDiff>0) p.mana=Math.min(p.maxMana,(p.mana||0)+manaDiff); else p.mana=Math.min(p.mana||0,p.maxMana); p.damageReductionBonuses[NINEFOLD_DAO_ID]=s.damageReduction; st.appliedMaxHpBonus=hpBonus; st.appliedMaxManaBonus=manaBonus; }
function cleanupVisuals(st){ st?.visualTimers?.forEach(t=>t?.remove?.()); st?.visuals?.forEach(v=>v?.destroy?.()); if(st){ st.visualTimers=[]; st.visuals=[]; } }
function breakthroughVisual(sys, realm){ const sc=sys?.scene, st=stateOf(sys); if(!sc?.add||!st) return; try{ const x=sc.player?.x??360, y=(sc.player?.y??360)-90; const txt=sc.add.text(x,y,`突破·${realm}`,{fontFamily:'Arial',fontSize:'30px',color:'#ffd166',stroke:'#6b1200',strokeThickness:5}).setOrigin?.(.5)?.setDepth?.(2500); st.visuals.push(txt); const ring=sc.add.circle?.(x,y+50,24,0xff2d2d,.18)?.setStrokeStyle?.(4,0xffd166,.9)?.setDepth?.(2499); if(ring) st.visuals.push(ring); sc.tweens?.add?.({targets:[txt,ring].filter(Boolean),alpha:0,scale:1.8,duration:900,onComplete:()=>{txt?.destroy?.(); ring?.destroy?.();}}); }catch{} }
function addInternal(sys, amount){ const st=stateOf(sys); if(!st||st.realmIndex>=8||!finite(amount)||amount<=0) return {applied:0,breakthroughs:[],snapshot:getCultivationSnapshot(sys)}; st.progress+=(Number(amount)||0); const breakthroughs=[]; while(st.realmIndex<8 && st.progress >= CULTIVATION_THRESHOLDS[st.realmIndex]){ st.progress-=CULTIVATION_THRESHOLDS[st.realmIndex]; st.realmIndex+=1; st.breakthroughCount=st.realmIndex; breakthroughs.push(CULTIVATION_REALMS[st.realmIndex]); applyStats(sys); const p=sys.scene?.playerData; if(p){ p.hp=Math.min(p.maxHp,(p.hp||0)+p.maxHp*.3); p.mana=p.maxMana; } breakthroughVisual(sys,CULTIVATION_REALMS[st.realmIndex]); }
 if(st.realmIndex>=8) st.progress=0; sys.scene?.hud?.update?.(); sys.scene?.skillBar?.update?.(); return {applied:amount,breakthroughs,snapshot:getCultivationSnapshot(sys)}; }
export function grantCultivation(sceneOrSystem, baseAmount, options={}){ const sys=systemOf(sceneOrSystem); if(!levelOf(sys)||!stateOf(sys)) return {applied:false,actualAmount:0,breakthroughs:[],snapshot:getCultivationSnapshot(sys)}; if(!finite(baseAmount)||baseAmount<=0) return {applied:false,actualAmount:0,breakthroughs:[],snapshot:getCultivationSnapshot(sys)}; const actual=Number(baseAmount)*(levelOf(sys)>=6&&!options.skipLv6?1.25:1); const r=addInternal(sys,actual); return {applied:true,actualAmount:r.applied,breakthroughs:r.breakthroughs,snapshot:r.snapshot}; }
function ensure(sys){ if(levelOf(sys)<=0) return null; let st=stateOf(sys); if(st) return st; st={realmIndex:0,progress:0,cycleProgressMs:0,lastGameplayAt:sys.scene?.getGameplayTime?.()??0,appliedMaxHpBonus:0,appliedMaxManaBonus:0,breakthroughCount:0,visualTimers:[],visuals:[]}; sys.passiveState.ninefoldDao=st; applyStats(sys); return st; }
export const NinefoldDaoSkill={ bind(sys){ ensure(sys); const updater=()=>NinefoldDaoSkill.update(sys); if(!sys.passiveUpdaters.includes(updater)) sys.passiveUpdaters.push(updater); return ()=>{ sys.passiveUpdaters=sys.passiveUpdaters.filter(fn=>fn!==updater); NinefoldDaoSkill.cleanup(sys); }; }, onAcquire(sys){ ensure(sys); applyStats(sys); }, update(sys){ const st=ensure(sys); if(!st) return; applyStats(sys); const now=sys.scene?.getGameplayTime?.()??0; const elapsed=Math.max(0,now-(st.lastGameplayAt??now)); st.lastGameplayAt=now; if(elapsed<=0) return; const r=rate(sys,st); addInternal(sys,r*elapsed/1000); if(levelOf(sys)>=3){ st.cycleProgressMs+=elapsed; while(st.cycleProgressMs>=30000){ st.cycleProgressMs-=30000; addInternal(sys,r*10); } } const regen=stat(st.realmIndex).manaRegen*elapsed/1000; if(regen>0) sys.recoverMana?.(regen); }, cleanup(sys){ const st=stateOf(sys), p=sys?.scene?.playerData; if(st&&p){ p.maxHp=Math.max(1,(p.maxHp||0)-(st.appliedMaxHpBonus||0)); p.hp=Math.min(p.hp||0,p.maxHp); p.maxMana=Math.max(0,(p.maxMana||0)-(st.appliedMaxManaBonus||0)); p.mana=Math.min(p.mana||0,p.maxMana); if(p.damageReductionBonuses) delete p.damageReductionBonuses[NINEFOLD_DAO_ID]; } cleanupVisuals(st); if(sys?.passiveState) delete sys.passiveState.ninefoldDao; sys?.scene?.hud?.update?.(); sys?.scene?.skillBar?.update?.(); } };
export function configureCultivationCoreSkill(){ SKILLS[NINEFOLD_DAO_ID]={ id:NINEFOLD_DAO_ID,name:'九转大道',rarity:'MYTHIC',handler:NINEFOLD_DAO_ID,passive:true,maxLevel:9,cooldownMs:999999,targetType:'passive',short:'道',color:0xd83a1e,tags:[TAGS.MAGIC,TAGS.CULTIVATION,TAGS.BUILD_CULTIVATION],description:'开启独立修为系统，自动修炼并突破炼气、筑基、金丹、元婴、化神、炼虚、合体、大乘、渡劫九大境界。Lv3解锁周天运转：每30秒有效游戏时间获得当前10秒自动修为。Lv6大道自然：后续修为来源提高25%，只应用一次。Lv9九转归一：按已完成突破次数提高自动修炼速度，每次+20%，最高2.6倍。',milestones:{3:'周天运转：每30秒获得10秒自动修为。',6:'大道自然：后续修为来源提高25%。',9:'九转归一：突破次数提高自动修炼速度。'},levels:CULTIVATION_BASE_RATES.map((autoRate,i)=>({autoRate,desc:`基础自动修为 ${autoRate}/秒；独立修为系统持续突破九大境界。`}))}; }
