import { SKILLS } from '../../config/skills.js';
import { TAGS } from '../../config/tags.js';
import { CombatEvents } from '../../core/CombatEvents.js';
import { StatusEffects } from '../../systems/StatusEffectSystem.js';

const levels=(values,build,milestones={})=>values.map((value,index)=>({ ...build(value,index+1), ...(milestones[index+1]?{milestoneText:milestones[index+1]}:{}) }));

const CONFIGS={
  wildfire:{ id:'wildfire',name:'燎原',rarity:'EPIC',handler:'wildfire',passive:true,maxLevel:9,coreSkill:true,requiredSkillId:'burn_burst',tags:[TAGS.FIRE,TAGS.DOT,TAGS.BUILD_FIRE],cooldownMs:999999,targetType:'passive',color:0xff6d36,short:'燎',description:'燃烧跳伤时有概率把部分燃烧扩散给附近敌人，扩大火势。',levels:levels([[0.20,1,105,900],[0.23,1,110,860],[0.26,1,115,820],[0.29,1,120,780],[0.32,1,125,740],[0.35,2,130,700],[0.38,2,135,660],[0.42,2,140,620],[0.48,2,150,560]],([spreadChance,spreadStacks,radius,internalCooldownMs])=>({spreadChance,spreadStacks,radius,internalCooldownMs,burnMs:3000,burnIntervalMs:600,maxStacks:18,desc:`燃烧跳伤时有${Math.round(spreadChance*100)}%概率向附近目标扩散${spreadStacks}层燃烧。`}),{3:'扩散概率提高至26%，范围扩大',6:'每次扩散2层燃烧',9:'扩散概率提高至48%，范围扩大至150'}) },
  meteor:{ id:'meteor',name:'陨石',rarity:'EPIC',handler:'meteor',maxLevel:9,coreSkill:true,requiredSkillId:'wildfire',tags:[TAGS.FIRE,TAGS.DOT,TAGS.ACTIVE_SKILL,TAGS.BUILD_FIRE],cooldownMs:7600,targetType:'nearestAhead',color:0xffa24c,short:'陨',description:'召唤陨石砸向燃烧最旺盛的区域，造成范围伤害并铺设燃烧。',levels:levels([[104,2,125,7600],[120,2,130,7300],[138,2,135,7000],[158,2,140,6700],[180,3,145,6400],[206,3,150,6100],[234,3,158,5800],[264,4,166,5500],[300,4,178,5100]],([damage,burnStacks,radius,cooldownMs])=>({damage,burnStacks,radius,cooldownMs,burnDamage:14,burnMs:4200,burnIntervalMs:600,maxStacks:18,impactDelayMs:420,desc:`陨石造成${damage}点范围伤害，并叠加${burnStacks}层燃烧。`}),{3:'爆炸范围扩大至135',6:'叠加3层燃烧，冷却缩短',9:'叠加4层燃烧，爆炸范围扩大至178'}) }
};

export function configureFlameAdvancedSkills(){ Object.entries(CONFIGS).forEach(([id,cfg])=>{ SKILLS[id]={...cfg}; }); }

export const WildfireSkill={ bind(system){
  const s=system.scene; let readyAt=0;
  return s.eventBus.on(CombatEvents.STATUS_TICK,p=>{ const data=system.getData('wildfire'); if(!data||p.type!==StatusEffects.BURN||p.actualDamage<=0)return; const now=s.getGameplayTime(); if(now<readyAt||Math.random()>data.spreadChance)return; const target=s.targeting.all().filter(e=>e!==p.target&&Math.hypot(e.x-p.target.x,e.y-p.target.y)<=data.radius).sort((a,b)=>Math.hypot(a.x-p.target.x,a.y-p.target.y)-Math.hypot(b.x-p.target.x,b.y-p.target.y))[0]; if(!target)return; readyAt=now+data.internalCooldownMs; const sourceEffect=p.effect; const burnOptions={durationMs:data.burnMs,intervalMs:data.burnIntervalMs,value:sourceEffect?.value||4,stacks:data.spreadStacks,maxStacks:data.maxStacks,sourceId:'wildfire',damageMultiplier:sourceEffect?.damageMultiplier||1,baseDamageMultiplierWithoutProfession:sourceEffect?.baseDamageMultiplierWithoutProfession||1,professionMultiplier:sourceEffect?.professionMultiplier||1,professionApplied:!!sourceEffect?.professionApplied}; if(Number.isFinite(sourceEffect?.eternalSpreadDepth)) burnOptions.eternalSpreadDepth=sourceEffect.eternalSpreadDepth; s.statusEffects.add(StatusEffects.BURN,target,burnOptions); system.line(p.target.x,p.target.y-40,target.x,target.y-40,0xff6d36); s.floatText(target.x,target.y-96,`燎原 +${data.spreadStacks}`,'#ff7b45'); });
} };

export const MeteorSkill={ cast(system,cfg,data,level,ctx){
  const s=system.scene; const burning=s.targeting.all().filter(e=>s.statusEffects.getStackCount(e,StatusEffects.BURN)>0); const target=(burning.length?burning:s.targeting.all()).sort((a,b)=>s.statusEffects.getStackCount(b,StatusEffects.BURN)-s.statusEffects.getStackCount(a,StatusEffects.BURN))[0]; if(!target)return; const marker=s.add.circle(target.x,target.y,data.radius,0xffa24c,0.12).setStrokeStyle(4,0xffc36b,0.8).setDepth(138); const rock=s.add.circle(target.x,target.y-360,24,0x6f3520,1).setStrokeStyle(5,0xff8a3d,0.9).setDepth(150); s.tweens.add({targets:rock,y:target.y-20,duration:data.impactDelayMs,ease:'Cubic.In',onComplete:()=>{ marker.destroy(); rock.destroy(); if(!s.targeting.valid(target))return; system.ring(target.x,target.y,data.radius,cfg.color); const raw=data.damage; const damage=system.damageValue(raw,ctx); s.targeting.all().filter(e=>Math.hypot(e.x-target.x,e.y-target.y)<=data.radius).forEach(e=>{ system.hit(e,damage,cfg,level,ctx,system.baseDamageValue(raw,ctx)); s.statusEffects.add(StatusEffects.BURN,e,{durationMs:data.burnMs,intervalMs:data.burnIntervalMs,value:data.burnDamage,stacks:data.burnStacks,maxStacks:data.maxStacks,sourceId:'meteor',damageMultiplier:ctx.damageMultiplier,baseDamageMultiplierWithoutProfession:ctx.baseDamageMultiplierWithoutProfession,professionMultiplier:ctx.professionMultiplier,professionApplied:true}); }); s.floatText(target.x,target.y-115,'陨石','#ffc06a'); }});
} };
