import { TAGS } from '../../config/tags.js';
import { SKILLS } from '../../config/skills.js';
import { applyEnemyGravity, applyGravityPull, isGravitySuppressed, isExternallyGravitySuppressed, removeEnemyGravitySourcesByPrefix } from '../../systems/EnemyGravityControl.js';
const DESIGN_WIDTH=720, DESIGN_HEIGHT=1280;
const GRAVITY_SKILL_IDS=['gravity_crush','gravity_field','gravity_orb','black_hole'];
const GRAVITY_SKILL_SNAPSHOT=Object.fromEntries(GRAVITY_SKILL_IDS.map(id=>[id, structuredClone?.(SKILLS[id]) || JSON.parse(JSON.stringify(SKILLS[id]))]));
const alive=e=>e?.active!==false&&!e?.isDefeated&&e?.hp>0;
const now=s=>s.getGameplayTime?.()??s.now??0;
const allEnemies=s=>(s.enemies||[]).filter(alive);
const validEnemies=s=>allEnemies(s).filter(e=>s.targeting?.isEnemyFullyInsideViewport?.(e)!==false);
export function createGravityRuntime(system){ const s=system.scene; if(s.gravityRuntime) return s.gravityRuntime; return s.gravityRuntime={fields:[],residuals:[],blackHole:null,pendingStrikes:new Set(),pendingImplosions:new Set(),projectiles:new Set(),transients:new Set(),visuals:new Set(),updater:null,registeredSystem:null,shutdownHandler:null}; }
function destroyNode(s,node){ s?.tweens?.killTweensOf?.(node); node?.destroy?.(); }
function visual(rt,node){ if(node) rt.visuals.add(node); return node; }
function circle(system,x,y,r,color=0x5b21b6,alpha=.22){ const rt=createGravityRuntime(system), s=system.scene, n=visual(rt,s.add?.circle?.(x,y,r,color,alpha)?.setStrokeStyle?.(3,0xc084fc,.75)?.setDepth?.(18)); return n; }
function transientCircle(system,x,y,r,color=0x7c3aed,alpha=.25,durationMs=220,skillId=''){ const rt=createGravityRuntime(system), node=circle(system,x,y,r,color,alpha); if(node) rt.transients.add({skillId,cleanupAt:now(system.scene)+durationMs,visuals:[node]}); return node; }
function cleanupNodes(system,nodes=[]){ const rt=system.scene.gravityRuntime; nodes.forEach(n=>{ rt?.visuals?.delete?.(n); destroyNode(system.scene,n); }); }
function clearTransients(system,skillId){ const rt=system.scene.gravityRuntime; if(!rt) return; rt.transients.forEach(p=>{ if(p.skillId===skillId){ cleanupNodes(system,p.visuals); rt.transients.delete(p); } }); }
export function destroyGravityRuntime(system){ const s=system.scene, rt=s.gravityRuntime; if(!rt) return; rt.fields.forEach(f=>cleanupNodes(system,f.visuals)); rt.residuals.forEach(r=>cleanupNodes(system,r.visuals)); rt.pendingStrikes.forEach(p=>cleanupNodes(system,p.visuals)); rt.pendingImplosions.forEach(p=>cleanupNodes(system,p.visuals)); rt.projectiles.forEach(p=>cleanupNodes(system,p.visuals)); rt.transients.forEach(p=>cleanupNodes(system,p.visuals)); if(rt.blackHole) cleanupBlackHole(system); rt.visuals.forEach(v=>destroyNode(s,v)); allEnemies(s).forEach(e=>{ ['gravity_field_','gravity_orb_','black_hole'].forEach(prefix=>removeEnemyGravitySourcesByPrefix(e,prefix)); e.gravityPull=undefined; e.body?.setVelocityX?.(0); }); if(rt.registeredSystem?.passiveUpdaters) rt.registeredSystem.passiveUpdaters=rt.registeredSystem.passiveUpdaters.filter(fn=>fn!==rt.updater); if(rt.shutdownHandler) s.events?.off?.('shutdown',rt.shutdownHandler); s.gravityRuntime=null; }
export function ensureGravityUpdater(system){ const rt=createGravityRuntime(system), s=system.scene; if(!rt.updater) rt.updater=()=>updateGravityRuntime(system); if(rt.registeredSystem!==system || !system.passiveUpdaters.includes(rt.updater)){ rt.registeredSystem?.passiveUpdaters&&(rt.registeredSystem.passiveUpdaters=rt.registeredSystem.passiveUpdaters.filter(fn=>fn!==rt.updater)); system.passiveUpdaters.push(rt.updater); rt.registeredSystem=system; } if(!rt.shutdownHandler){ rt.shutdownHandler=()=>destroyGravityRuntime(system); s.events?.once?.('shutdown',rt.shutdownHandler); } }
export function cleanupSkillRuntime(system, skillId){ const s=system.scene, rt=s.gravityRuntime; if(!rt) return; if(skillId==='gravity_crush'){ rt.pendingStrikes.forEach(p=>{ if(p.skillId===skillId){ cleanupNodes(system,p.visuals); rt.pendingStrikes.delete(p); } }); clearTransients(system,skillId); }
  if(skillId==='gravity_field'){ rt.fields=rt.fields.filter(f=>{ if(f.skillId!==skillId) return true; cleanupNodes(system,f.visuals); allEnemies(s).forEach(e=>removeEnemyGravitySourcesByPrefix(e,f.sourceId)); return false; }); allEnemies(s).forEach(e=>removeEnemyGravitySourcesByPrefix(e,'gravity_field_')); clearTransients(system,skillId); }
  if(skillId==='gravity_orb'){ rt.projectiles.forEach(p=>{ cleanupNodes(system,p.visuals); rt.projectiles.delete(p); }); rt.pendingImplosions.forEach(p=>{ cleanupNodes(system,p.visuals); rt.pendingImplosions.delete(p); }); rt.residuals=rt.residuals.filter(r=>{ if(r.skillId!==skillId) return true; cleanupNodes(system,r.visuals); return false; }); clearTransients(system,skillId); allEnemies(s).forEach(e=>{ removeEnemyGravitySourcesByPrefix(e,'gravity_orb_'); if(e.gravityPull?.sourceId==='gravity_orb_pull') e.gravityPull=undefined; }); }
  if(skillId==='black_hole') cleanupBlackHole(system); }
function shiftAfter(value,d,a){ return Number.isFinite(value)&&value>a?value+d:value; }
export function shiftGravityTimers(system,d,a){ const rt=system.scene.gravityRuntime; if(!rt||d<=0) return; rt.fields.forEach(f=>{ f.expires=shiftAfter(f.expires,d,a); f.nextTick=shiftAfter(f.nextTick,d,a); }); rt.residuals.forEach(r=>{ r.expires=shiftAfter(r.expires,d,a); }); rt.pendingStrikes.forEach(p=>{ p.executeAt=shiftAfter(p.executeAt,d,a); p.cleanupAt=shiftAfter(p.cleanupAt,d,a); }); rt.pendingImplosions.forEach(p=>{ p.executeAt=shiftAfter(p.executeAt,d,a); }); rt.projectiles.forEach(p=>{ p.startedAt+=d; p.arriveAt+=d; }); rt.transients.forEach(p=>{ p.cleanupAt=shiftAfter(p.cleanupAt,d,a); }); const bh=rt.blackHole; if(bh){ bh.nextTick=shiftAfter(bh.nextTick,d,a); bh.nextCollapse=shiftAfter(bh.nextCollapse,d,a); if(bh.charging) bh.charging.explodeAt=shiftAfter(bh.charging.explodeAt,d,a); } allEnemies(system.scene).forEach(e=>{ e.gravitySources?.forEach(src=>{ if(Number.isFinite(src.expiresAt)&&src.expiresAt>a) src.expiresAt+=d; }); if(e.gravityPull){ e.gravityPull.startedAt+=d; e.gravityPull.expiresAt+=d; } }); }
function hit(system,e,amount,cfg,level,ctx={}){ if(alive(e)) system.hit?.(e,system.damageValue?system.damageValue(Math.round(amount),ctx):Math.round(amount),cfg,level,ctx,system.baseDamageValue?.(Math.round(amount),ctx)??Math.round(amount),[TAGS.MAGIC,TAGS.GRAVITY,TAGS.BUILD_GRAVITY]); }
export function mostDense(scene,radius=150,exclude=[]){ const list=validEnemies(scene).filter(e=>!exclude.some(x=>Math.hypot(e.x-x.x,e.y-x.y)<=x.radius)); return (list.length?list:validEnemies(scene)).map(e=>({x:e.x,y:e.y,count:validEnemies(scene).filter(o=>Math.hypot(o.x-e.x,o.y-e.y)<=radius).length})).sort((a,b)=>b.count-a.count)[0]||null; }
function scheduleStrike(system,cfg,data,level,ctx,ratio,delay=0){ const rt=createGravityRuntime(system), t=now(system.scene), centerAt=()=>mostDense(system.scene,data.radius); const warning=centerAt(); if(!warning) return false; const warn=circle(system,warning.x,warning.y,data.radius,0x7c3aed,.18), pillar=visual(rt,system.scene.add?.rectangle?.(warning.x,warning.y-220,28,220,0x2e1065,.0)?.setDepth?.(19)); const task={skillId:'gravity_crush',executeAt:t+delay+data.warningMs,centerAt,ratio,visuals:[warn,pillar],cfg,data,level,ctx,stage:'warning'}; rt.pendingStrikes.add(task); ensureGravityUpdater(system); return true; }
export const GravityCrushSkill={ cast(system,cfg,data,level,ctx={}){ let ok=false; for(let i=0;i<(data.strikeCount||1);i++) ok=scheduleStrike(system,cfg,data,level,ctx,i?data.followupDamageRatio||.65:1,i*(data.followupDelayMs||0))||ok; return ok; }, cleanup:system=>cleanupSkillRuntime(system,'gravity_crush') };
function resolveStrike(system,p){ const s=system.scene, c=p.centerAt(); if(!c){ cleanupNodes(system,p.visuals); return; } p.visuals.forEach(v=>v?.setPosition?.(c.x,c.y)); p.visuals[1]?.setFillStyle?.(0x2e1065,.75); const before=new Map(validEnemies(s).map(e=>[e,isGravitySuppressed(e,now(s))])); validEnemies(s).forEach(e=>{ const d=Math.hypot(e.x-c.x,e.y-c.y); if(d<=p.data.radius){ let dmg=p.data.damage*p.ratio; if(before.get(e)&&p.data.suppressedDamageBonus) dmg*=1+p.data.suppressedDamageBonus; hit(system,e,dmg,p.cfg,p.level,p.ctx); } else if(p.data.shockwaveDamageRatio&&d<=p.data.radius+(p.data.shockwaveRadiusBonus||0)){ let dmg=p.data.damage*p.data.shockwaveDamageRatio*p.ratio; if(before.get(e)&&p.data.suppressedDamageBonus) dmg*=1+p.data.suppressedDamageBonus; hit(system,e,dmg,p.cfg,p.level,p.ctx); } }); const shock=circle(system,c.x,c.y,p.data.radius+(p.data.shockwaveRadiusBonus||0),0x1e1b4b,.24); p.visuals.push(shock); p.cleanupAt=now(s)+220; }
function createField(system,cfg,data,level,ctx,c,idx=0){ const rt=createGravityRuntime(system), s=system.scene, sourceId=`gravity_field_${ctx.castId||now(s)}_${idx}`, expires=now(s)+data.durationMs; const ring=circle(system,c.x,c.y,data.radius,0x581c87,.25), core=circle(system,c.x,c.y,data.radius*.72,0x312e81,.10); const field={skillId:'gravity_field',sourceId,x:c.x,y:c.y,radius:data.radius,expires,nextTick:now(s)+data.tickIntervalMs,data,cfg,level,ctx,visuals:[ring,core]}; rt.fields.push(field); ensureGravityUpdater(system); return field; }
export const GravityFieldSkill={ cast(system,cfg,data,level,ctx={}){ const placed=[]; for(let i=0;i<(data.fieldCount||1);i++){ const c=mostDense(system.scene,data.radius,placed); if(!c) break; if(i&&placed.length&&Math.hypot(c.x-placed[0].x,c.y-placed[0].y)<8) c.x+=data.radius*.75; placed.push({x:c.x,y:c.y,radius:data.radius}); createField(system,cfg,data,level,ctx,c,i); } return placed.length>0; }, cleanup:system=>cleanupSkillRuntime(system,'gravity_field') };
function createResidual(system,data,c){ const rt=createGravityRuntime(system), sourceId=`gravity_orb_${now(system.scene)}_${Math.random().toString(36).slice(2)}`; rt.residuals.push({skillId:'gravity_orb',sourceId,x:c.x,y:c.y,radius:data.blastRadius,expires:now(system.scene)+data.residualDurationMs,data,visuals:[circle(system,c.x,c.y,data.blastRadius,0x312e81,.20)]}); }
function explodeOrb(system,cfg,data,level,ctx,c,target,ratio=1,secondary=false){ if(!secondary&&alive(target)) hit(system,target,data.impactDamage*ratio,cfg,level,ctx); validEnemies(system.scene).filter(e=>Math.hypot(e.x-c.x,e.y-c.y)<=data.blastRadius).forEach(e=>{ hit(system,e,data.blastDamage*ratio*(secondary?data.secondaryImplosionDamageRatio:1),cfg,level,ctx); applyGravityPull(e,c.x,data.pullDistance*(secondary?data.secondaryImplosionPullRatio:1),data.pullDurationMs,now(system.scene),system.scene); }); transientCircle(system,c.x,c.y,data.blastRadius,0x7c3aed,.25,220,'gravity_orb'); if(!secondary){ createResidual(system,data,c); if(data.secondaryImplosionDelayMs){ const warning=circle(system,c.x,c.y,data.blastRadius*.58,0xc084fc,.14); const task={skillId:'gravity_orb',executeAt:now(system.scene)+data.secondaryImplosionDelayMs,cfg,data,level,ctx,c,ratio,visuals:warning?[warning]:[]}; createGravityRuntime(system).pendingImplosions.add(task); } } ensureGravityUpdater(system); }
export const GravityOrbSkill={ cast(system,cfg,data,level,ctx={}){ const rt=createGravityRuntime(system), used=[]; for(let i=0;i<(data.orbCount||1);i++){ const c=mostDense(system.scene,data.blastRadius,used), target=validEnemies(system.scene).sort((a,b)=>Math.hypot(a.x-(c?.x||a.x),a.y-(c?.y||a.y))-Math.hypot(b.x-(c?.x||b.x),b.y-(c?.y||b.y)))[0]; if(!target) break; const same=used.some(u=>Math.hypot(target.x-u.x,target.y-u.y)<=data.blastRadius), ratio=same?data.sameTargetSecondOrbDamageRatio:1, from={x:system.scene.player?.x||0,y:(system.scene.player?.y||0)-80}, locked={x:target.x,y:target.y}; used.push({x:target.x,y:target.y,radius:data.blastRadius}); const orb=visual(rt,system.scene.add?.circle?.(from.x,from.y,13,0x4c1d95,.95)?.setDepth?.(24)), trail=visual(rt,system.scene.add?.circle?.(from.x,from.y,24,0x7c3aed,.18)?.setDepth?.(23)); rt.projectiles.add({skillId:'gravity_orb',cfg,data,level,ctx,target,locked,from,x:from.x,y:from.y,ratio,startedAt:now(system.scene),arriveAt:now(system.scene)+260,visuals:[orb,trail]}); } ensureGravityUpdater(system); return used.length>0; }, cleanup:system=>cleanupSkillRuntime(system,'gravity_orb') };
function visibleCenter(s){ return s.cameras?.main?.worldView?.centerX ?? s.player?.x ?? 0; }
function blackHoleScreenY(s){ return (s.balance?.groundTopY??620)-260; }
function syncBlackHoleOwnership(system){ const rt=createGravityRuntime(system), lvl=system.getLevel?.('black_hole')||0, data=system.getData?.('black_hole',lvl), s=system.scene; if(!data){ if(rt.blackHole) cleanupBlackHole(system); return; } if(rt.blackHole){ rt.blackHole.level=lvl; rt.blackHole.data=data; rt.blackHole.visual?.setPosition?.(DESIGN_WIDTH/2,blackHoleScreenY(s)); return; } const container=visual(rt,s.add?.container?.(DESIGN_WIDTH/2,blackHoleScreenY(s))?.setScrollFactor?.(0)?.setDepth?.(17)); const core=s.add?.circle?.(0,0,30,0x000000,1), ring=s.add?.circle?.(0,0,58,0x6d28d9,.35)?.setStrokeStyle?.(8,0x60a5fa,.55); const particles=Array.from({length:8},(_,i)=>s.add?.circle?.(Math.cos(i)*72,Math.sin(i)*18,3,0x93c5fd,.6)); container?.add?.([ring,core,...particles.filter(Boolean)]); rt.blackHole={skillId:'black_hole',visual:container,core,ring,particles,level:lvl,data,nextTick:now(s)+data.tickIntervalMs,nextCollapse:now(s)+data.collapseIntervalMs,collapseCount:0,charging:null}; }
function cleanupBlackHole(system){ const rt=system.scene.gravityRuntime, bh=rt?.blackHole; if(!bh) return; cleanupNodes(system,bh.charging?.visuals||[]); clearTransients(system,'black_hole'); destroyNode(system.scene,bh.visual); rt.visuals.delete(bh.visual); rt.blackHole=null; allEnemies(system.scene).forEach(e=>removeEnemyGravitySourcesByPrefix(e,'black_hole')); }
export const BlackHoleSkill={ bind(system){ ensureGravityUpdater(system); return ()=>cleanupSkillRuntime(system,'black_hole'); }, syncRuntime:syncBlackHoleOwnership, cleanup:system=>cleanupSkillRuntime(system,'black_hole'), shiftTimers:shiftGravityTimers, destroyRuntime:destroyGravityRuntime };
function updateGravityRuntime(system){ const s=system.scene, rt=createGravityRuntime(system), t=now(s); syncBlackHoleOwnership(system); rt.fields=rt.fields.filter(f=>{ if(f.expires>t) return true; cleanupNodes(system,f.visuals); return false; }); rt.residuals=rt.residuals.filter(r=>{ if(r.expires>t) return true; cleanupNodes(system,r.visuals); return false; }); rt.transients.forEach(p=>{ if(t>=p.cleanupAt){ cleanupNodes(system,p.visuals); rt.transients.delete(p); } }); const fieldHit=new Map(), orbHit=new Map(), dueFields=rt.fields.filter(f=>t>=f.nextTick&&f.data.tickDamage); validEnemies(s).forEach(e=>{ rt.fields.forEach(f=>{ const inside=Math.hypot(e.x-f.x,e.y-f.y)<=f.radius; if(inside){ fieldHit.set(e,true); applyEnemyGravity(e,{sourceId:f.sourceId,moveSlow:f.data.moveSlow,attackSlow:f.data.attackSlow,expiresAt:t+80,external:true}); } }); rt.residuals.forEach(r=>{ const inside=Math.hypot(e.x-r.x,e.y-r.y)<=r.radius; if(inside){ orbHit.set(e,true); applyEnemyGravity(e,{sourceId:r.sourceId,moveSlow:r.data.residualMoveSlow,attackSlow:r.data.residualAttackSlow,expiresAt:t+80,external:true}); } }); if(!fieldHit.has(e)) removeEnemyGravitySourcesByPrefix(e,'gravity_field_'); if(!orbHit.has(e)) removeEnemyGravitySourcesByPrefix(e,'gravity_orb_'); });
  if(dueFields.length){ const targets=new Set(); dueFields.forEach(f=>validEnemies(s).filter(e=>Math.hypot(e.x-f.x,e.y-f.y)<=f.radius).forEach(e=>targets.add(e))); const ref=dueFields[0]; targets.forEach(e=>hit(system,e,ref.data.tickDamage,ref.cfg,ref.level,ref.ctx)); dueFields.forEach(f=>{ f.nextTick=t+f.data.tickIntervalMs; }); }
  rt.pendingStrikes.forEach(p=>{ if(t>=p.executeAt && !p.resolved){ p.resolved=true; resolveStrike(system,p); } if(p.cleanupAt&&t>=p.cleanupAt){ cleanupNodes(system,p.visuals); rt.pendingStrikes.delete(p); } });
  rt.projectiles.forEach(p=>{ const u=Math.max(0,Math.min(1,(t-p.startedAt)/Math.max(1,p.arriveAt-p.startedAt))); p.x=p.from.x+(p.locked.x-p.from.x)*u; p.y=p.from.y+(p.locked.y-p.from.y)*u; p.visuals.forEach(v=>v?.setPosition?.(p.x,p.y)); if(t>=p.arriveAt){ explodeOrb(system,p.cfg,p.data,p.level,p.ctx,{x:p.locked.x,y:p.locked.y},p.target,p.ratio,false); cleanupNodes(system,p.visuals); rt.projectiles.delete(p); } });
  rt.pendingImplosions.forEach(p=>{ if(t>=p.executeAt){ explodeOrb(system,p.cfg,p.data,p.level,p.ctx,p.c,{x:p.c.x,y:p.c.y},p.ratio,true); cleanupNodes(system,p.visuals); rt.pendingImplosions.delete(p); } });
  updateBlackHole(system,rt.blackHole,t); }
function updateBlackHole(system,bh,t){ if(!bh) return; const s=system.scene, data=bh.data, cx=visibleCenter(s); bh.visual?.setPosition?.(DESIGN_WIDTH/2,blackHoleScreenY(s)); bh.ring&&(bh.ring.rotation=(bh.ring.rotation||0)+0.04); bh.particles?.forEach((p,i)=>p?.setPosition?.(Math.cos(t/220+i)*68,Math.sin(t/260+i)*20)); validEnemies(s).forEach(e=>{ const core=Math.abs(e.x-cx)<=data.coreHalfWidth; applyEnemyGravity(e,{sourceId:'black_hole',moveSlow:core?data.coreMoveSlow:data.outerMoveSlow,attackSlow:core?data.coreAttackSlow:data.outerAttackSlow,expiresAt:t+80,external:false}); }); if(t>=bh.nextTick){ validEnemies(s).forEach(e=>hit(system,e,data.tickDamage*(Math.abs(e.x-cx)<=data.coreHalfWidth?data.coreDamageMultiplier:1),SKILLS.black_hole,bh.level,{})); bh.nextTick=t+data.tickIntervalMs; } if(bh.charging&&t>=bh.charging.explodeAt){ const charge=bh.charging, ultimate=charge.ultimate; validEnemies(s).forEach(e=>{ const core=Math.abs(e.x-cx)<=data.coreHalfWidth; let dmg=data.collapseDamage; if(ultimate) dmg*=data.ultimateCollapseDamageMultiplier*(core?data.ultimateCoreDamageMultiplier:1); else { if(!core&&!e.isBoss) dmg*=data.collapseOuterDamageRatio; if(data.resonanceDamageBonus&&isExternallyGravitySuppressed(e,t)) dmg*=1+data.resonanceDamageBonus; } hit(system,e,dmg,SKILLS.black_hole,bh.level,{}); }); cleanupNodes(system,charge.visuals||[]); transientCircle(system,cx,s.balance?.groundTopY??620,ultimate?330:230,ultimate?0xdbeafe:0x7c3aed,ultimate?0.28:0.20,260,'black_hole'); bh.visual?.setScale?.(1); bh.charging=null; bh.nextCollapse=t+data.collapseIntervalMs; }
  if(!bh.charging&&t>=bh.nextCollapse){ bh.collapseCount++; const ultimate=!!(data.ultimateCollapseEvery&&bh.collapseCount%data.ultimateCollapseEvery===0), visuals=[]; if(ultimate){ const darkness=visual(createGravityRuntime(system),s.add?.rectangle?.(DESIGN_WIDTH/2,DESIGN_HEIGHT/2,DESIGN_WIDTH,DESIGN_HEIGHT,0x050816,.38)?.setScrollFactor?.(0)?.setDepth?.(16)); if(darkness) visuals.push(darkness); } bh.charging={ultimate,explodeAt:t+(ultimate?500:220),visuals}; bh.visual?.setScale?.(ultimate?0.35:0.72); if(ultimate) validEnemies(s).forEach(e=>applyEnemyGravity(e,{sourceId:'black_hole_ultimate',moveSlow:data.ultimateMoveSlow,attackSlow:data.ultimateAttackSlow,expiresAt:t+data.ultimateSlowDurationMs,external:false})); } }
export function configureGravityFlowSkills(){ GRAVITY_SKILL_IDS.forEach(id=>{ if(GRAVITY_SKILL_SNAPSHOT[id]) SKILLS[id]=structuredClone?.(GRAVITY_SKILL_SNAPSHOT[id]) || JSON.parse(JSON.stringify(GRAVITY_SKILL_SNAPSHOT[id])); }); }
