import { TAGS } from '../../config/tags.js';
import { SKILLS } from '../../config/skills.js';
import { applyEnemyGravity, applyGravityPull, applyGravityNudge, isGravitySuppressed, isExternallyGravitySuppressed, removeEnemyGravitySourcesByPrefix } from '../../systems/EnemyGravityControl.js';
const DESIGN_WIDTH=720;
const GRAVITY_SKILL_IDS=['gravity_crush','gravity_reversal','gravity_orb','black_hole'];
const GRAVITY_SKILL_SNAPSHOT=Object.fromEntries(GRAVITY_SKILL_IDS.map(id=>[id, structuredClone?.(SKILLS[id]) || JSON.parse(JSON.stringify(SKILLS[id]))]));
export const GRAVITY_CRUSH_COLUMN_HEIGHT=240;
export const GRAVITY_CRUSH_PRESS_DURATION_MS=120;
export const GRAVITY_CRUSH_START_OFFSET_Y=-250;
export const GRAVITY_CRUSH_IMPACT_OFFSET_Y=-80;
const GRAVITY_CRUSH_COLUMN_ALPHA=.18;
const GRAVITY_CRUSH_IMPACT_ALPHA=.55;
const alive=e=>e?.active!==false&&!e?.isDefeated&&e?.hp>0;
const now=s=>s.getGameplayTime?.()??s.now??0;
const allEnemies=s=>(s.enemies||[]).filter(alive);
const validEnemies=s=>allEnemies(s).filter(e=>s.targeting?.isEnemyFullyInsideViewport?.(e)!==false);
export function createGravityRuntime(system){ const s=system.scene; if(s.gravityRuntime) return s.gravityRuntime; return s.gravityRuntime={reversals:new Set(),residuals:[],blackHole:null,pendingStrikes:new Set(),pendingImplosions:new Set(),projectiles:new Set(),transients:new Set(),visuals:new Set(),updater:null,registeredSystem:null,shutdownHandler:null}; }
function destroyNode(s,node){ s?.tweens?.killTweensOf?.(node); node?.destroy?.(); }
function visual(rt,node){ if(node) rt.visuals.add(node); return node; }
function circle(system,x,y,r,color=0x5b21b6,alpha=.22){ const rt=createGravityRuntime(system), s=system.scene, n=visual(rt,s.add?.circle?.(x,y,r,color,alpha)?.setStrokeStyle?.(3,0xc084fc,.75)?.setDepth?.(18)); return n; }
function transientCircle(system,x,y,r,color=0x7c3aed,alpha=.25,durationMs=220,skillId=''){ const rt=createGravityRuntime(system), node=circle(system,x,y,r,color,alpha); if(node) rt.transients.add({skillId,cleanupAt:now(system.scene)+durationMs,visuals:[node]}); return node; }
function cleanupNodes(system,nodes=[]){ const rt=system.scene.gravityRuntime; nodes.forEach(n=>{ rt?.visuals?.delete?.(n); destroyNode(system.scene,n); }); }
function clearTransients(system,skillId){ const rt=system.scene.gravityRuntime; if(!rt) return; rt.transients.forEach(p=>{ if(p.skillId===skillId){ cleanupNodes(system,p.visuals); rt.transients.delete(p); } }); }
export function destroyGravityRuntime(system){ const s=system.scene, rt=s.gravityRuntime; if(!rt) return; rt.reversals?.forEach(r=>cleanupReversal(system,r,true)); rt.residuals.forEach(r=>cleanupNodes(system,r.visuals)); rt.pendingStrikes.forEach(p=>cleanupNodes(system,p.visuals)); rt.pendingImplosions.forEach(p=>cleanupNodes(system,p.visuals)); rt.projectiles.forEach(p=>cleanupNodes(system,p.visuals)); rt.transients.forEach(p=>cleanupNodes(system,p.visuals)); if(rt.blackHole) cleanupBlackHole(system); rt.visuals.forEach(v=>destroyNode(s,v)); allEnemies(s).forEach(e=>{ ['gravity_reversal_','gravity_orb_','black_hole'].forEach(prefix=>removeEnemyGravitySourcesByPrefix(e,prefix)); e.gravityPull=undefined; e.body?.setVelocityX?.(0); }); if(rt.registeredSystem?.passiveUpdaters) rt.registeredSystem.passiveUpdaters=rt.registeredSystem.passiveUpdaters.filter(fn=>fn!==rt.updater); if(rt.shutdownHandler) s.events?.off?.('shutdown',rt.shutdownHandler); s.gravityRuntime=null; }
export function ensureGravityUpdater(system){ const rt=createGravityRuntime(system), s=system.scene; if(!rt.updater) rt.updater=()=>updateGravityRuntime(system); if(rt.registeredSystem!==system || !system.passiveUpdaters.includes(rt.updater)){ rt.registeredSystem?.passiveUpdaters&&(rt.registeredSystem.passiveUpdaters=rt.registeredSystem.passiveUpdaters.filter(fn=>fn!==rt.updater)); system.passiveUpdaters.push(rt.updater); rt.registeredSystem=system; } if(!rt.shutdownHandler){ rt.shutdownHandler=()=>destroyGravityRuntime(system); s.events?.once?.('shutdown',rt.shutdownHandler); } }
export function cleanupSkillRuntime(system, skillId){ const s=system.scene, rt=s.gravityRuntime; if(!rt) return; if(skillId==='gravity_crush'){ rt.pendingStrikes.forEach(p=>{ if(p.skillId===skillId){ cleanupNodes(system,p.visuals); rt.pendingStrikes.delete(p); } }); clearTransients(system,skillId); }
  if(skillId==='gravity_reversal'){ rt.reversals?.forEach(r=>{ cleanupReversal(system,r,true); rt.reversals.delete(r); }); clearTransients(system,skillId); }
  if(skillId==='gravity_orb'){ rt.projectiles.forEach(p=>{ cleanupNodes(system,p.visuals); rt.projectiles.delete(p); }); rt.pendingImplosions.forEach(p=>{ cleanupNodes(system,p.visuals); rt.pendingImplosions.delete(p); }); rt.residuals=rt.residuals.filter(r=>{ if(r.skillId!==skillId) return true; cleanupNodes(system,r.visuals); return false; }); clearTransients(system,skillId); allEnemies(s).forEach(e=>{ removeEnemyGravitySourcesByPrefix(e,'gravity_orb_'); if(e.gravityPull?.sourceId==='gravity_orb_pull') e.gravityPull=undefined; }); }
  if(skillId==='black_hole') cleanupBlackHole(system); }
function shiftAfter(value,d,a){ return Number.isFinite(value)&&value>a?value+d:value; }
export function shiftGravityTimers(system,d,a){ const rt=system.scene.gravityRuntime; if(!rt||d<=0) return; rt.reversals?.forEach(r=>{ ['startedAt','riseEndAt','hoverEndAt','fallEndAt','devourEndAt','visualCleanupAt'].forEach(k=>{ r[k]=shiftAfter(r[k],d,a); }); r.entries?.forEach(e=>{ if(e.devourStartedAt) e.devourStartedAt+=d; }); }); rt.residuals.forEach(r=>{ r.expires=shiftAfter(r.expires,d,a); }); rt.pendingStrikes.forEach(p=>{ p.warningAt=shiftAfter(p.warningAt,d,a); p.executeAt=shiftAfter(p.executeAt,d,a); p.cleanupAt=shiftAfter(p.cleanupAt,d,a); }); rt.pendingImplosions.forEach(p=>{ p.executeAt=shiftAfter(p.executeAt,d,a); }); rt.projectiles.forEach(p=>{ p.startedAt+=d; p.arriveAt+=d; }); rt.transients.forEach(p=>{ p.cleanupAt=shiftAfter(p.cleanupAt,d,a); }); const bh=rt.blackHole; if(bh){ bh.nextTick=shiftAfter(bh.nextTick,d,a); bh.lastPullAt+=d; bh.tickFlashUntil=shiftAfter(bh.tickFlashUntil,d,a); } allEnemies(system.scene).forEach(e=>{ e.gravitySources?.forEach(src=>{ if(Number.isFinite(src.expiresAt)&&src.expiresAt>a) src.expiresAt+=d; }); if(e.gravityPull){ e.gravityPull.startedAt+=d; e.gravityPull.expiresAt+=d; } }); }
function hit(system,e,amount,cfg,level,ctx={}){ if(alive(e)) system.hit?.(e,system.damageValue?system.damageValue(Math.round(amount),ctx):Math.round(amount),cfg,level,ctx,system.baseDamageValue?.(Math.round(amount),ctx)??Math.round(amount),[TAGS.MAGIC,TAGS.GRAVITY,TAGS.BUILD_GRAVITY]); }
export function mostDense(scene,radius=150,exclude=[]){ const list=validEnemies(scene).filter(e=>!exclude.some(x=>Math.hypot(e.x-x.x,e.y-x.y)<=x.radius)); return (list.length?list:validEnemies(scene)).map(e=>({x:e.x,y:e.y,count:validEnemies(scene).filter(o=>Math.hypot(o.x-e.x,o.y-e.y)<=radius).length})).sort((a,b)=>b.count-a.count)[0]||null; }
export function mostDenseHorizontal(scene,halfWidth=150,exclude=[]){ const visible=validEnemies(scene); const list=visible.filter(e=>!exclude.some(x=>Math.abs(e.x-x.x)<=x.radius)); return (list.length?list:visible).map(e=>({x:e.x,y:e.y,count:visible.filter(o=>Math.abs(o.x-e.x)<=halfWidth).length})).sort((a,b)=>b.count-a.count)[0]||null; }
export function createGravityCrushColumn(system,task,center){ const rt=createGravityRuntime(system), s=system.scene, data=task.data; const lockedCenter={x:center.x,y:center.y}; const columnWidth=data.radius*2; const column=s.add?.rectangle?.(lockedCenter.x,lockedCenter.y+GRAVITY_CRUSH_START_OFFSET_Y,columnWidth,GRAVITY_CRUSH_COLUMN_HEIGHT,0x2e1065,GRAVITY_CRUSH_COLUMN_ALPHA)?.setStrokeStyle?.(3,0xa78bfa,.55)?.setDepth?.(19); if(column){ column.width=columnWidth; column.height=GRAVITY_CRUSH_COLUMN_HEIGHT; column.fillAlpha=GRAVITY_CRUSH_COLUMN_ALPHA; } task.columnVisual=column; task.lockedCenter=lockedCenter; task.centerAt=()=>task.lockedCenter; task.visuals=column?[column]:[]; if(column) rt.visuals.add(column); return column; }
function scheduleStrike(system,cfg,data,level,ctx,ratio,delay=0){ const rt=createGravityRuntime(system), t=now(system.scene), centerAt=()=>mostDenseHorizontal(system.scene,data.radius); const warning=centerAt(); if(!warning) return false; const task={skillId:'gravity_crush',warningAt:t+delay,executeAt:t+delay+data.warningMs,centerAt,ratio,visuals:[],cfg,data,level,ctx,stage:'warning'}; createGravityCrushColumn(system,task,warning); rt.pendingStrikes.add(task); ensureGravityUpdater(system); return true; }
export const GravityCrushSkill={ cast(system,cfg,data,level,ctx={}){ let ok=false; for(let i=0;i<(data.strikeCount||1);i++) ok=scheduleStrike(system,cfg,data,level,ctx,i?data.followupDamageRatio||.65:1,i*(data.followupDelayMs||0))||ok; return ok; }, cleanup:system=>cleanupSkillRuntime(system,'gravity_crush') };
function resolveStrike(system,p){ const s=system.scene, c=p.lockedCenter||p.centerAt(); if(!c){ cleanupNodes(system,p.visuals); return; } p.columnVisual?.setPosition?.(c.x,c.y+GRAVITY_CRUSH_IMPACT_OFFSET_Y); p.columnVisual?.setFillStyle?.(0x2e1065,.72); if(p.columnVisual) p.columnVisual.fillAlpha=.72; const before=new Map(validEnemies(s).map(e=>[e,isGravitySuppressed(e,now(s))])); validEnemies(s).forEach(e=>{ const d=Math.abs(e.x-c.x); if(d<=p.data.radius){ let dmg=p.data.damage*p.ratio; if(before.get(e)&&p.data.suppressedDamageBonus) dmg*=1+p.data.suppressedDamageBonus; hit(system,e,dmg,p.cfg,p.level,p.ctx); } else if(p.data.shockwaveDamageRatio&&d<=p.data.radius+(p.data.shockwaveRadiusBonus||0)){ let dmg=p.data.damage*p.data.shockwaveDamageRatio*p.ratio; if(before.get(e)&&p.data.suppressedDamageBonus) dmg*=1+p.data.suppressedDamageBonus; hit(system,e,dmg,p.cfg,p.level,p.ctx); } }); const width=(p.data.radius+(p.data.shockwaveRadiusBonus||0))*2; const flash=visual(createGravityRuntime(system),s.add?.rectangle?.(c.x,c.y+GRAVITY_CRUSH_IMPACT_OFFSET_Y+GRAVITY_CRUSH_COLUMN_HEIGHT/2,width,56,0xa78bfa,.28)?.setDepth?.(20)); if(flash){ flash.width=width; flash.height=56; p.visuals.push(flash); } p.cleanupAt=now(s)+180; }

export function canGravityReverse(enemy, scene){ return alive(enemy)&&!enemy.isBoss&&!enemy.isCharging&&!enemy.charging&&!enemy.isCasting&&!enemy.casting&&!enemy.skillActive&&!enemy.isKnockbackActive&&!['windup','charge','slamWind','skillActive','recovery','cool'].includes(scene?.enemyBehaviors?.items?.get?.(enemy)?.state||''); }
function bhWorld(s){ const cam=s.cameras?.main, sy=blackHoleScreenY(s); if(cam?.getWorldPoint) return cam.getWorldPoint(DESIGN_WIDTH/2,sy); return {x:cam?.worldView?.centerX??visibleCenter(s),y:(cam?.worldView?.y??0)+sy}; }
function makeReversalVisual(system,centerX,data){ const rt=createGravityRuntime(system), s=system.scene, y=(s.balance?.groundTopY??620)-150; const box=visual(rt,s.add?.rectangle?.(centerX,y,data.halfWidth*2,340,0x2e1065,.18)?.setStrokeStyle?.(3,0x8b5cf6,.65)?.setDepth?.(18)); return box?[box]:[]; }
function cleanupEntry(e,entry,forceY=false){ if(!e) return; if(e.gravityReversalState===entry) delete e.gravityReversalState; if(forceY&&alive(e)&&entry.startY!=null){ e.x=entry.startX; e.y=entry.startY; e.body?.reset?.(entry.startX,entry.startY); } if(entry.originalScaleX!=null) e.scaleX=entry.originalScaleX; if(entry.originalScaleY!=null) e.scaleY=entry.originalScaleY; if(entry.originalAlpha!=null) e.alpha=entry.originalAlpha; e.body&&(e.body.enable=entry.originalBodyState?.enable??e.body.enable); }
function cleanupReversal(system,task,forceY=false){ cleanupNodes(system,task.visuals||[]); (task.entries||[]).forEach(en=>{ removeEnemyGravitySourcesByPrefix(en.enemy, en.sourceId); cleanupEntry(en.enemy,en,forceY); }); }
function createReversal(system,cfg,data,level,ctx,c){ const rt=createGravityRuntime(system), s=system.scene, t=now(s), castId=ctx.castId||t; const hoverMax=data.hoverDurationMs; const entries=validEnemies(s).filter(e=>Math.abs(e.x-c.x)<=data.halfWidth).map((e,i)=>{ const control=canGravityReverse(e,s); const isElite=!!e.isElite&&!e.isBoss; const rise=data.riseHeight*(isElite?data.eliteLiftScale:1); const hover=data.hoverDurationMs*(isElite?data.eliteHoverScale:1); const entry={enemy:e,startX:e.x,startY:e.y,targetY:e.y-(control?rise:0),originalScaleX:e.scaleX,originalScaleY:e.scaleY,originalAlpha:e.alpha,originalBodyState:{enable:e.body?.enable},controlApplied:control,mode:control?'rise':'fall',hoverEndAt:t+data.riseDurationMs+hover,sourceId:`gravity_reversal_${castId}_${e.enemyId||i}`}; if(control){ e.gravityReversalState=entry; e.gravityPull=undefined; e.body?.setVelocityX?.(0); e.body&&(e.body.enable=false); } applyEnemyGravity(e,{sourceId:entry.sourceId,moveSlow:0,attackSlow:0,expiresAt:t+data.riseDurationMs+hoverMax+data.fallDurationMs+80,external:true}); return entry; }); if(!entries.length) return null; const task={skillId:'gravity_reversal',cfg,data,level,ctx,centerX:c.x,startedAt:t,riseEndAt:t+data.riseDurationMs,hoverEndAt:t+data.riseDurationMs+hoverMax,fallEndAt:t+data.riseDurationMs+hoverMax+data.fallDurationMs,visualCleanupAt:t+data.riseDurationMs+hoverMax+data.fallDurationMs+220,visuals:makeReversalVisual(system,c.x,data),entries}; rt.reversals.add(task); ensureGravityUpdater(system); return task; }
export const GravityReversalSkill={ cast(system,cfg,data,level,ctx={}){ const c=mostDenseHorizontal(system.scene,data.halfWidth); return !!(c&&createReversal(system,cfg,data,level,ctx,c)); }, cleanup:system=>cleanupSkillRuntime(system,'gravity_reversal') };
function hitMeta(system,e,amount,task,kind){ if(alive(e)) system.scene.combatSystem?.damageEnemy?.(e,Math.max(1,Math.round(amount)),{source:'skill',skillId:'gravity_reversal',damageKind:kind,tags:[TAGS.MAGIC,TAGS.GRAVITY,TAGS.BUILD_GRAVITY],level:task.level,professionApplied:true,professionMultiplier:task.ctx?.professionMultiplier||1,baseAmountBeforeProfession:Math.max(1,Math.round(amount)),noKnockback:true}); }
function executeDevour(system,e){ if(!alive(e)||e.isBoss) return; system.scene.combatSystem?.damageEnemy?.(e,Math.max(1,Math.ceil(e.hp||1)),{source:'skill',skillId:'gravity_reversal',damageKind:'black_hole_devour',tags:[TAGS.MAGIC,TAGS.GRAVITY,TAGS.BUILD_GRAVITY],damageAlreadyResolved:true,noKnockback:true}); }
function updateReversal(system,task,t){ const data=task.data, s=system.scene, hasBh=!!createGravityRuntime(system).blackHole; let active=0; task.entries.forEach(en=>{ const e=en.enemy; if(!alive(e)){ en.mode='finished'; return; } if(en.mode==='finished') return; active++; if(en.controlApplied) applyEnemyGravity(e,{sourceId:en.sourceId,moveSlow:0,attackSlow:0,expiresAt:t+80,external:true}); if(en.mode==='rise'){ const u=Math.max(0,Math.min(1,(t-task.startedAt)/Math.max(1,data.riseDurationMs))); e.x=en.startX; e.y=en.startY+(en.targetY-en.startY)*u; e.body?.reset?.(e.x,e.y); if(t>=task.riseEndAt) en.mode='hover'; } if(en.mode==='hover'){ e.x=en.startX; e.y=en.targetY; e.body?.reset?.(e.x,e.y); if(t>=en.hoverEndAt){ if(data.blackHoleDevour&&hasBh&&en.controlApplied&&!e.isBoss&&(!e.isElite || (e.hp/e.maxHp)<=data.eliteExecuteThreshold)){ en.mode='devour'; en.devourStartedAt=t; en.devourEndAt=t+data.devourDurationMs; en.devourFrom={x:e.x,y:e.y}; } else en.mode='fall'; } } if(en.mode==='devour'){ if(!createGravityRuntime(system).blackHole){ en.mode='fall'; return; } const u=Math.max(0,Math.min(1,(t-en.devourStartedAt)/Math.max(1,data.devourDurationMs))), end=bhWorld(s), cp={x:(en.devourFrom.x+end.x)/2,y:Math.min(en.devourFrom.y,end.y)-120}; e.x=(1-u)*(1-u)*en.devourFrom.x+2*(1-u)*u*cp.x+u*u*end.x; e.y=(1-u)*(1-u)*en.devourFrom.y+2*(1-u)*u*cp.y+u*u*end.y; e.scaleX=(en.originalScaleX||1)*(1-.92*u); e.scaleY=(en.originalScaleY||1)*(1-.92*u); e.alpha=(en.originalAlpha??1)*(1-.85*u); e.body?.reset?.(e.x,e.y); if(t>=en.devourEndAt){ createGravityRuntime(system).blackHole.devourFlashUntil=t+140; executeDevour(system,e); en.mode='finished'; cleanupEntry(e,en,false); removeEnemyGravitySourcesByPrefix(e,en.sourceId); } } if(en.mode==='fall'){ const fallStart=en.hoverEndAt||task.hoverEndAt, u=Math.max(0,Math.min(1,(t-fallStart)/Math.max(1,data.fallDurationMs))), q=u*u; if(en.controlApplied){ e.x=en.startX; e.y=en.targetY+(en.startY-en.targetY)*q; e.body?.reset?.(e.x,e.y); } if(t>=fallStart+data.fallDurationMs){ const boss=e.isBoss; const dmg=data.landingDamage*(boss?data.bossDamageScale:1); hitMeta(system,e,dmg,task,'gravityReversalLanding'); if(data.blackHoleDevour&&hasBh&&e.isElite&&en.controlApplied&&(e.hp/e.maxHp)>data.eliteExecuteThreshold) hitMeta(system,e,e.maxHp*data.eliteDevourDamageRatio,task,'blackHoleDevourEliteOverThreshold'); if(data.blackHoleDevour&&hasBh&&boss) hitMeta(system,e,Math.min(e.maxHp*data.bossDevourDamageRatio,data.bossDevourDamageCap),task,'blackHoleDevourBoss'); cleanupEntry(e,en,true); if(data.postGravityDurationMs>0) applyEnemyGravity(e,{sourceId:en.sourceId,moveSlow:data.postMoveSlow,attackSlow:data.postAttackSlow,expiresAt:t+data.postGravityDurationMs,external:true}); else removeEnemyGravitySourcesByPrefix(e,en.sourceId); en.mode='finished'; } } }); return active>0&&t<task.visualCleanupAt; }
function createResidual(system,data,c){ const rt=createGravityRuntime(system), sourceId=`gravity_orb_${now(system.scene)}_${Math.random().toString(36).slice(2)}`; rt.residuals.push({skillId:'gravity_orb',sourceId,x:c.x,y:c.y,radius:data.blastRadius,expires:now(system.scene)+data.residualDurationMs,data,visuals:[circle(system,c.x,c.y,data.blastRadius,0x312e81,.20)]}); }
function explodeOrb(system,cfg,data,level,ctx,c,target,ratio=1,secondary=false){ if(!secondary&&alive(target)) hit(system,target,data.impactDamage*ratio,cfg,level,ctx); validEnemies(system.scene).filter(e=>Math.hypot(e.x-c.x,e.y-c.y)<=data.blastRadius).forEach(e=>{ hit(system,e,data.blastDamage*ratio*(secondary?data.secondaryImplosionDamageRatio:1),cfg,level,ctx); applyGravityPull(e,c.x,data.pullDistance*(secondary?data.secondaryImplosionPullRatio:1),data.pullDurationMs,now(system.scene),system.scene); }); transientCircle(system,c.x,c.y,data.blastRadius,0x7c3aed,.25,220,'gravity_orb'); if(!secondary){ createResidual(system,data,c); if(data.secondaryImplosionDelayMs){ const warning=circle(system,c.x,c.y,data.blastRadius*.58,0xc084fc,.14); const task={skillId:'gravity_orb',executeAt:now(system.scene)+data.secondaryImplosionDelayMs,cfg,data,level,ctx,c,ratio,visuals:warning?[warning]:[]}; createGravityRuntime(system).pendingImplosions.add(task); } } ensureGravityUpdater(system); }
export const GravityOrbSkill={ cast(system,cfg,data,level,ctx={}){ const rt=createGravityRuntime(system), used=[]; for(let i=0;i<(data.orbCount||1);i++){ const c=mostDense(system.scene,data.blastRadius,used), target=validEnemies(system.scene).sort((a,b)=>Math.hypot(a.x-(c?.x||a.x),a.y-(c?.y||a.y))-Math.hypot(b.x-(c?.x||b.x),b.y-(c?.y||b.y)))[0]; if(!target) break; const same=used.some(u=>Math.hypot(target.x-u.x,target.y-u.y)<=data.blastRadius), ratio=same?data.sameTargetSecondOrbDamageRatio:1, from={x:system.scene.player?.x||0,y:(system.scene.player?.y||0)-80}, locked={x:target.x,y:target.y}; used.push({x:target.x,y:target.y,radius:data.blastRadius}); const orb=visual(rt,system.scene.add?.circle?.(from.x,from.y,13,0x4c1d95,.95)?.setDepth?.(24)), trail=visual(rt,system.scene.add?.circle?.(from.x,from.y,24,0x7c3aed,.18)?.setDepth?.(23)); rt.projectiles.add({skillId:'gravity_orb',cfg,data,level,ctx,target,locked,from,x:from.x,y:from.y,ratio,startedAt:now(system.scene),arriveAt:now(system.scene)+260,visuals:[orb,trail]}); } ensureGravityUpdater(system); return used.length>0; }, cleanup:system=>cleanupSkillRuntime(system,'gravity_orb') };
function visibleCenter(s){ return s.cameras?.main?.worldView?.centerX ?? s.player?.x ?? 0; }
function blackHoleScreenY(s){ return (s.balance?.groundTopY??620)-260; }
function syncBlackHoleOwnership(system){ const rt=createGravityRuntime(system), lvl=system.getLevel?.('black_hole')||0, data=system.getData?.('black_hole',lvl), s=system.scene; if(!data){ if(rt.blackHole) cleanupBlackHole(system); return; } if(rt.blackHole){ rt.blackHole.level=lvl; rt.blackHole.data=data; rt.blackHole.visual?.setPosition?.(DESIGN_WIDTH/2,blackHoleScreenY(s)); return; } const container=visual(rt,s.add?.container?.(DESIGN_WIDTH/2,blackHoleScreenY(s))?.setScrollFactor?.(0)?.setDepth?.(17)); const core=s.add?.circle?.(0,0,36,0x000000,1), ring=s.add?.circle?.(0,0,82,0x312e81,.38)?.setStrokeStyle?.(8,0x60a5fa,.60), outerRing=s.add?.circle?.(0,0,108,0x312e81,.14)?.setStrokeStyle?.(5,0xa78bfa,.32); const particles=Array.from({length:12},(_,i)=>s.add?.circle?.(Math.cos(i)*102,Math.sin(i)*30,3,0x93c5fd,.6)); container?.add?.([outerRing,ring,core,...particles.filter(Boolean)]); rt.blackHole={skillId:'black_hole',visual:container,core,ring,outerRing,particles,level:lvl,data,nextTick:now(s)+data.tickIntervalMs,lastPullAt:now(s),tickFlashUntil:null}; }
function cleanupBlackHole(system){ const rt=system.scene.gravityRuntime, bh=rt?.blackHole; if(!bh) return; destroyNode(system.scene,bh.visual); rt.visuals.delete(bh.visual); rt.blackHole=null; allEnemies(system.scene).forEach(e=>removeEnemyGravitySourcesByPrefix(e,'black_hole')); }
export const BlackHoleSkill={ bind(system){ ensureGravityUpdater(system); return ()=>cleanupSkillRuntime(system,'black_hole'); }, syncRuntime:syncBlackHoleOwnership, cleanup:system=>cleanupSkillRuntime(system,'black_hole'), shiftTimers:shiftGravityTimers, destroyRuntime:destroyGravityRuntime };
function updateGravityRuntime(system){ const s=system.scene, rt=createGravityRuntime(system), t=now(s); syncBlackHoleOwnership(system); rt.reversals?.forEach(r=>{ if(!updateReversal(system,r,t)){ cleanupReversal(system,r,false); rt.reversals.delete(r); } }); rt.residuals=rt.residuals.filter(r=>{ if(r.expires>t) return true; cleanupNodes(system,r.visuals); return false; }); rt.transients.forEach(p=>{ if(t>=p.cleanupAt){ cleanupNodes(system,p.visuals); rt.transients.delete(p); } }); const orbHit=new Map(); validEnemies(s).forEach(e=>{ rt.residuals.forEach(r=>{ const inside=Math.hypot(e.x-r.x,e.y-r.y)<=r.radius; if(inside){ orbHit.set(e,true); applyEnemyGravity(e,{sourceId:r.sourceId,moveSlow:r.data.residualMoveSlow,attackSlow:r.data.residualAttackSlow,expiresAt:t+80,external:true}); } }); if(!orbHit.has(e)) removeEnemyGravitySourcesByPrefix(e,'gravity_orb_'); });
  rt.pendingStrikes.forEach(p=>{ if(p.columnVisual && !p.resolved){ const pressStartAt=p.executeAt-GRAVITY_CRUSH_PRESS_DURATION_MS; const u=Math.max(0,Math.min(1,(t-pressStartAt)/GRAVITY_CRUSH_PRESS_DURATION_MS)); const c=p.lockedCenter; if(c){ const y=c.y+GRAVITY_CRUSH_START_OFFSET_Y+(GRAVITY_CRUSH_IMPACT_OFFSET_Y-GRAVITY_CRUSH_START_OFFSET_Y)*u; p.columnVisual.setPosition?.(c.x,y); const alpha=GRAVITY_CRUSH_COLUMN_ALPHA+(GRAVITY_CRUSH_IMPACT_ALPHA-GRAVITY_CRUSH_COLUMN_ALPHA)*u; p.columnVisual.setFillStyle?.(0x2e1065,alpha); p.columnVisual.fillAlpha=alpha; } } if(t>=p.executeAt && !p.resolved){ p.resolved=true; resolveStrike(system,p); } if(p.cleanupAt&&t>=p.cleanupAt){ cleanupNodes(system,p.visuals); rt.pendingStrikes.delete(p); } });
  rt.projectiles.forEach(p=>{ const u=Math.max(0,Math.min(1,(t-p.startedAt)/Math.max(1,p.arriveAt-p.startedAt))); p.x=p.from.x+(p.locked.x-p.from.x)*u; p.y=p.from.y+(p.locked.y-p.from.y)*u; p.visuals.forEach(v=>v?.setPosition?.(p.x,p.y)); if(t>=p.arriveAt){ explodeOrb(system,p.cfg,p.data,p.level,p.ctx,{x:p.locked.x,y:p.locked.y},p.target,p.ratio,false); cleanupNodes(system,p.visuals); rt.projectiles.delete(p); } });
  rt.pendingImplosions.forEach(p=>{ if(t>=p.executeAt){ explodeOrb(system,p.cfg,p.data,p.level,p.ctx,p.c,{x:p.c.x,y:p.c.y},p.ratio,true); cleanupNodes(system,p.visuals); rt.pendingImplosions.delete(p); } });
  updateBlackHole(system,rt.blackHole,t); }
function updateBlackHole(system,bh,t){ if(!bh) return; const s=system.scene, data=bh.data, cx=visibleCenter(s); bh.visual?.setPosition?.(DESIGN_WIDTH/2,blackHoleScreenY(s)); const elapsedMs=Math.max(0,Math.min(120,t-(bh.lastPullAt??t))); bh.lastPullAt=t; const delta=elapsedMs/1000; if(bh.ring) bh.ring.rotation=(bh.ring.rotation||0)+0.012*delta*60; if(bh.outerRing) bh.outerRing.rotation=(bh.outerRing.rotation||0)-0.008*delta*60; const pulse=1+Math.sin(t/360)*0.035; bh.ring?.setScale?.(pulse); bh.outerRing?.setScale?.(1+(2-pulse)*0.025); bh.particles?.forEach((p,i)=>{ const phase=(t/520+i/12)%1, r=102*(1-phase)+38*phase; p?.setPosition?.(Math.cos(i*1.9+t/900)*r,Math.sin(i*1.7+t/1100)*30*(1-phase)); }); validEnemies(s).forEach(e=>{ const core=Math.abs(e.x-cx)<=data.coreHalfWidth; applyEnemyGravity(e,{sourceId:'black_hole',moveSlow:core?data.coreMoveSlow:data.outerMoveSlow,attackSlow:core?data.coreAttackSlow:data.outerAttackSlow,expiresAt:t+80,external:false}); if(delta>0) applyGravityNudge(e,cx,(core?data.corePullSpeed:data.outerPullSpeed)*delta,s,{eliteScale:data.elitePullScale??.5,deadZonePx:data.pullDeadZonePx||18}); });
  if(t>=bh.nextTick){ validEnemies(s).forEach(e=>{ const core=Math.abs(e.x-cx)<=data.coreHalfWidth; let damage=data.tickDamage*(core?data.coreDamageMultiplier:1); if(data.resonanceDamageBonus&&isExternallyGravitySuppressed(e,t)) damage*=1+data.resonanceDamageBonus; hit(system,e,damage,SKILLS.black_hole,bh.level,{}); }); bh.core?.setFillStyle?.(0x312e81,1); bh.ring?.setFillStyle?.(0x6d28d9,.55); bh.tickFlashUntil=t+120; bh.nextTick=t+data.tickIntervalMs; } if(bh.tickFlashUntil&&t>=bh.tickFlashUntil){ bh.core?.setFillStyle?.(0x000000,1); bh.ring?.setFillStyle?.(0x312e81,.38); bh.tickFlashUntil=null; } }
export function configureGravityFlowSkills(){ GRAVITY_SKILL_IDS.forEach(id=>{ if(GRAVITY_SKILL_SNAPSHOT[id]) SKILLS[id]=structuredClone?.(GRAVITY_SKILL_SNAPSHOT[id]) || JSON.parse(JSON.stringify(GRAVITY_SKILL_SNAPSHOT[id])); }); delete SKILLS['gravity'+'_field']; }
