import { TAGS } from '../../config/tags.js';
import { SKILLS } from '../../config/skills.js';
import { applyEnemyGravity, applyGravityPull, isGravitySuppressed, isExternallyGravitySuppressed, clearAllEnemyGravity } from '../../systems/EnemyGravityControl.js';
const GRAVITY_SKILL_IDS=['gravity_crush','gravity_field','gravity_orb','black_hole'];
const GRAVITY_SKILL_SNAPSHOT=Object.fromEntries(GRAVITY_SKILL_IDS.map(id=>[id, structuredClone?.(SKILLS[id]) || JSON.parse(JSON.stringify(SKILLS[id]))]));
const alive=e=>e?.active!==false&&!e?.isDefeated&&e?.hp>0;
const now=s=>s.getGameplayTime?.()??s.now??0;
const enemies=s=>s.targeting?.all?.()||s.enemies?.filter(alive)||[];
export function mostDense(scene,radius=150,exclude=[]){ const list=enemies(scene).filter(e=>!exclude.some(x=>Math.hypot(e.x-x.x,e.y-x.y)<=x.radius)); return (list.length?list:enemies(scene)).map(e=>({x:e.x,y:e.y,count:enemies(scene).filter(o=>Math.hypot(o.x-e.x,o.y-e.y)<=radius).length})).sort((a,b)=>b.count-a.count)[0]||null; }
function hit(system,e,amount,cfg,level,ctx){ if(alive(e)) system.hit?.(e,system.damageValue?system.damageValue(Math.round(amount),ctx):Math.round(amount),cfg,level,ctx,system.baseDamageValue?.(Math.round(amount),ctx)??Math.round(amount),[TAGS.MAGIC,TAGS.GRAVITY,TAGS.BUILD_GRAVITY]); }
function visualCircle(s,x,y,r,c=0x5b21b6,a=.22,d=300){ const n=s.add?.circle?.(x,y,r,c,a)?.setStrokeStyle?.(3,0xc084fc,.75)?.setDepth?.(18); if(n) s.tweens?.add?.({targets:n,alpha:0,duration:d,onComplete:()=>n.destroy?.()}); return n; }
function strike(system,cfg,data,level,ctx,ratio=1){ const s=system.scene,c=mostDense(s,data.radius); if(!c) return false; visualCircle(s,c.x,c.y,data.radius,0x7c3aed,.18,data.warningMs); s.time?.delayedCall?.(data.warningMs,()=>{ const before=new Map(enemies(s).map(e=>[e,isGravitySuppressed(e,now(s))])); const all=enemies(s); for(const e of all){ const d=Math.hypot(e.x-c.x,e.y-c.y); if(d<=data.radius){ let dmg=data.damage*ratio; if(before.get(e)&&data.suppressedDamageBonus) dmg*=1+data.suppressedDamageBonus; hit(system,e,dmg,cfg,level,ctx); } else if(data.shockwaveDamageRatio&&d<=data.radius+(data.shockwaveRadiusBonus||0)){ let dmg=data.damage*data.shockwaveDamageRatio*ratio; if(before.get(e)&&data.suppressedDamageBonus) dmg*=1+data.suppressedDamageBonus; hit(system,e,dmg,cfg,level,ctx); } } visualCircle(s,c.x,c.y,data.radius+(data.shockwaveRadiusBonus||0),0x1e1b4b,.2,260); }); return true; }
export const GravityCrushSkill={ cast(system,cfg,data,level,ctx={}){ for(let i=0;i<(data.strikeCount||1);i++){ system.scene.time?.delayedCall?.(i*(data.followupDelayMs||0),()=>strike(system,cfg,data,level,ctx,i?data.followupDamageRatio||.65:1)); } return true; }};
function createField(system,cfg,data,level,ctx,c,idx=0){ const s=system.scene,id=`gravity_field_${ctx.castId||now(s)}_${idx}`,expires=now(s)+data.durationMs; visualCircle(s,c.x,c.y,data.radius,0x581c87,.25,data.durationMs); const rt=s.gravityRuntime ||= {fields:[],residuals:[],blackHoles:new Map(),updater:null}; const field={id,x:c.x,y:c.y,radius:data.radius,expires,nextTick:now(s)+data.tickIntervalMs,data,cfg,level,ctx}; rt.fields.push(field); ensureUpdater(system); return field; }
export const GravityFieldSkill={ cast(system,cfg,data,level,ctx={}){ const placed=[]; for(let i=0;i<(data.fieldCount||1);i++){ const c=mostDense(system.scene,data.radius,placed); if(!c) break; if(i&&placed.length&&Math.hypot(c.x-placed[0].x,c.y-placed[0].y)<8) c.x+=data.radius*.75; placed.push({x:c.x,y:c.y,radius:data.radius}); createField(system,cfg,data,level,ctx,c,i); } return placed.length>0; }};
function explodeOrb(system,cfg,data,level,ctx,target,ratio=1,secondary=false){ const s=system.scene,c={x:target.x,y:target.y}; if(!secondary) hit(system,target,data.impactDamage*ratio,cfg,level,ctx); enemies(s).filter(e=>Math.hypot(e.x-c.x,e.y-c.y)<=data.blastRadius).forEach(e=>{ hit(system,e,data.blastDamage*ratio*(secondary?data.secondaryImplosionDamageRatio:1),cfg,level,ctx); applyGravityPull(e,c.x,data.pullDistance*(secondary?data.secondaryImplosionPullRatio:1),data.pullDurationMs,now(s),s); }); if(!secondary){ const expires=now(s)+data.residualDurationMs; (s.gravityRuntime ||= {fields:[],residuals:[],blackHoles:new Map(),updater:null}).residuals.push({id:`gravity_orb_${ctx.castId||now(s)}_${Math.random()}`,x:c.x,y:c.y,radius:data.blastRadius,expires,data}); visualCircle(s,c.x,c.y,data.blastRadius,0x312e81,.2,data.residualDurationMs); ensureUpdater(system); if(data.secondaryImplosionDelayMs) s.time?.delayedCall?.(data.secondaryImplosionDelayMs,()=>explodeOrb(system,cfg,data,level,ctx,{x:c.x,y:c.y},ratio,true)); }}
export const GravityOrbSkill={ cast(system,cfg,data,level,ctx={}){ const used=[]; for(let i=0;i<(data.orbCount||1);i++){ const c=mostDense(system.scene,data.blastRadius,used), target=enemies(system.scene).sort((a,b)=>Math.hypot(a.x-(c?.x||a.x),a.y-(c?.y||a.y))-Math.hypot(b.x-(c?.x||b.x),b.y-(c?.y||b.y)))[0]; if(!target) break; const same=used.some(u=>Math.hypot(target.x-u.x,target.y-u.y)<=data.blastRadius); used.push({x:target.x,y:target.y,radius:data.blastRadius}); explodeOrb(system,cfg,data,level,ctx,target,same?data.sameTargetSecondOrbDamageRatio:1); } return used.length>0; }};
function visibleCenter(s){ return s.cameras?.main?.worldView?.centerX ?? s.player?.x ?? 0; }
export const BlackHoleSkill={ bind(system){ const s=system.scene, st=system.passiveState.gravityFlow ||= {}; if(st.blackHoleCleanup) return st.blackHoleCleanup; const rt=s.gravityRuntime ||= {fields:[],residuals:[],blackHoles:new Map(),updater:null}; const visual=s.add?.container?.(360,(s.groundTopY||620)-260)?.setScrollFactor?.(0)?.setDepth?.(17); const core=s.add?.circle?.(0,0,30,0x000000,1), ring=s.add?.circle?.(0,0,58,0x6d28d9,.35)?.setStrokeStyle?.(8,0x60a5fa,.55); visual?.add?.([ring,core]); const state={id:'black_hole',visual,nextTick:now(s),nextCollapse:now(s),collapseCount:0}; rt.blackHoles.set('black_hole',state); ensureUpdater(system); const cleanup=()=>{ visual?.destroy?.(); rt.blackHoles.delete('black_hole'); clearAllEnemyGravity(s); st.blackHoleCleanup=null; }; st.blackHoleCleanup=cleanup; return cleanup; }};
export function ensureUpdater(system){ const s=system.scene, rt=s.gravityRuntime ||= {fields:[],residuals:[],blackHoles:new Map(),updater:null}; if(rt.updater) return; rt.updater=()=>{ const t=now(s); rt.fields=rt.fields.filter(f=>f.expires>t); rt.residuals=rt.residuals.filter(r=>r.expires>t); const fieldDamaged=new Set(); for(const e of enemies(s)){ for(const f of rt.fields.filter(f=>Math.hypot(e.x-f.x,e.y-f.y)<=f.radius)){ applyEnemyGravity(e,{sourceId:f.id,moveSlow:f.data.moveSlow,attackSlow:f.data.attackSlow,expiresAt:f.expires,external:true}); if(f.data.tickDamage&&t>=f.nextTick&&!fieldDamaged.has(e)){ hit(system,e,f.data.tickDamage,f.cfg,f.level,f.ctx); fieldDamaged.add(e); } } for(const r of rt.residuals.filter(r=>Math.hypot(e.x-r.x,e.y-r.y)<=r.radius)) applyEnemyGravity(e,{sourceId:r.id,moveSlow:r.data.residualMoveSlow,attackSlow:r.data.residualAttackSlow,expiresAt:r.expires,external:true}); }
    rt.fields.forEach(f=>{ if(t>=f.nextTick) f.nextTick=t+f.data.tickIntervalMs; });
    rt.blackHoles.forEach(b=>{ const lvl=system.getLevel?.('black_hole')||0, data=system.getData?.('black_hole',lvl); if(!data) return; b.visual?.setPosition?.(360,(s.groundTopY||620)-260); const cx=visibleCenter(s); enemies(s).forEach(e=>{ const core=Math.abs(e.x-cx)<=data.coreHalfWidth; applyEnemyGravity(e,{sourceId:'black_hole',moveSlow:core?data.coreMoveSlow:data.outerMoveSlow,attackSlow:core?data.coreAttackSlow:data.outerAttackSlow,expiresAt:t+1000,external:false}); }); if(t>=b.nextTick){ enemies(s).forEach(e=>hit(system,e,data.tickDamage*(Math.abs(e.x-cx)<=data.coreHalfWidth?data.coreDamageMultiplier:1),{id:'black_hole',tags:[TAGS.MAGIC,TAGS.GRAVITY,TAGS.BUILD_GRAVITY]},lvl,{})); b.nextTick=t+data.tickIntervalMs; } if(t>=b.nextCollapse){ b.collapseCount++; const ultimate=data.ultimateCollapseEvery&&b.collapseCount%data.ultimateCollapseEvery===0; enemies(s).forEach(e=>{ let dmg=data.collapseDamage; const core=Math.abs(e.x-cx)<=data.coreHalfWidth; if(ultimate){ applyEnemyGravity(e,{sourceId:'black_hole_ultimate',moveSlow:data.ultimateMoveSlow,attackSlow:data.ultimateAttackSlow,expiresAt:t+data.ultimateSlowDurationMs,external:false}); dmg*=data.ultimateCollapseDamageMultiplier*(core?data.ultimateCoreDamageMultiplier:1); } else { if(!core&&!e.isBoss) dmg*=data.collapseOuterDamageRatio; if(data.resonanceDamageBonus&&isExternallyGravitySuppressed(e,t)) dmg*=1+data.resonanceDamageBonus; } hit(system,e,dmg,{id:'black_hole',tags:[TAGS.MAGIC,TAGS.GRAVITY,TAGS.BUILD_GRAVITY]},lvl,{}); }); b.nextCollapse=t+data.collapseIntervalMs; } }); };
  system.passiveUpdaters?.push?.(rt.updater);
}
export function configureGravityFlowSkills(){ GRAVITY_SKILL_IDS.forEach(id=>{ if(GRAVITY_SKILL_SNAPSHOT[id]) SKILLS[id]=structuredClone?.(GRAVITY_SKILL_SNAPSHOT[id]) || JSON.parse(JSON.stringify(GRAVITY_SKILL_SNAPSHOT[id])); }); }
