import { configureEntryArchetypeSkills, EntryFireballSkill, EntrySwordSkill, EntryPoisonNeedleSkill, EntryHeavyHitSkill, EntryIronWallSkill, EntryMovementSkill } from './EntryArchetypeSkills.js';
import { configureFlameCoreSkills, FireSeedSkill, BurnBurstSkill, SolarFlameSkill } from './FlameCoreSkills.js';
import { configureSwordCoreSkills, SplitSwordSkill, RotatingSwordSkill } from './SwordCoreSkills.js';
import { configureSwordAdvancedSkills, ExecutionSwordSkill, MyriadSwordsSkill } from './SwordAdvancedSkills.js';
import { configureSwordUltimateSkills, HeavenSplittingSwordSkill } from './SwordUltimateSkills.js';
import { configureStrengthCoreSkills, GiantForceSkill, BloodthirstSkill } from './StrengthCoreSkills.js';
import { configureStrengthAdvancedSkills, FrenzySkill, BloodRageBurstSkill } from './StrengthAdvancedSkills.js';
import { configureStrengthUltimateSkills, LastStandSkill } from './StrengthUltimateSkills.js';
import { configureDefenseCoreSkills, ThornArmorSkill, GuardianShieldSkill } from './DefenseCoreSkills.js';
import { configureDefenseAdvancedSkills, ArmorBreakShockwaveSkill, ImmovableMountainSkill } from './DefenseAdvancedSkills.js';
import { configureDefenseUltimateSkills, BlackTortoiseBodySkill } from './DefenseUltimateSkills.js';
import { configureAfterimageCoreSkills, PhantomStepSkill, ShadowAssaultSkill } from './AfterimageCoreSkills.js';
import { configureAfterimageAdvancedSkills, SwiftShadowSkill, InstantStepSkill } from './AfterimageAdvancedSkills.js';
import { configureAfterimageUltimateSkills, MyriadAfterimageSkill } from './AfterimageUltimateSkills.js';
import { configurePoisonSummonCoreSkills, ParasiticGuSkill, BoneEatingInsectSkill } from './PoisonSummonCoreSkills.js';
import { configurePoisonSummonAdvancedSkills, PoisonChainSkill, PoisonKingSkill } from './PoisonSummonAdvancedSkills.js';
import { configurePoisonSummonUltimateSkills, PlagueMotherSkill } from './PoisonSummonUltimateSkills.js';

configureEntryArchetypeSkills();
configureFlameCoreSkills();
configureSwordCoreSkills();
configureSwordAdvancedSkills();
configureSwordUltimateSkills();
configureStrengthCoreSkills();
configureStrengthAdvancedSkills();
configureStrengthUltimateSkills();
configureDefenseCoreSkills();
configureDefenseAdvancedSkills();
configureDefenseUltimateSkills();
configureAfterimageCoreSkills();
configureAfterimageAdvancedSkills();
configureAfterimageUltimateSkills();
configurePoisonSummonCoreSkills();
configurePoisonSummonAdvancedSkills();
configurePoisonSummonUltimateSkills();

export const SKILL_HANDLERS={entry_fireball:EntryFireballSkill,entry_sword:EntrySwordSkill,entry_poison_needle:EntryPoisonNeedleSkill,entry_heavy_hit:EntryHeavyHitSkill,entry_iron_wall:EntryIronWallSkill,entry_movement:EntryMovementSkill,fire_seed:FireSeedSkill,burn_burst:BurnBurstSkill,solar_flame:SolarFlameSkill,split_sword:SplitSwordSkill,rotating_sword:RotatingSwordSkill,execution_sword:ExecutionSwordSkill,myriad_swords:MyriadSwordsSkill,heaven_splitting_sword:HeavenSplittingSwordSkill,giant_force:GiantForceSkill,bloodthirst:BloodthirstSkill,thorn_armor:ThornArmorSkill,guardian_shield:GuardianShieldSkill,armor_break_shockwave:ArmorBreakShockwaveSkill,immovable_mountain:ImmovableMountainSkill,black_tortoise_body:BlackTortoiseBodySkill,phantom_step:PhantomStepSkill,shadow_assault:ShadowAssaultSkill,swift_shadow:SwiftShadowSkill,instant_step:InstantStepSkill,myriad_afterimage:MyriadAfterimageSkill,parasitic_gu:ParasiticGuSkill,bone_eating_insect:BoneEatingInsectSkill,poison_chain:PoisonChainSkill,poison_king:PoisonKingSkill,plague_mother:PlagueMotherSkill,frenzy:FrenzySkill,blood_rage_burst:BloodRageBurstSkill,last_stand:LastStandSkill};
