import { SKILLS } from '../../config/skills.js';
import { TAGS } from '../../config/tags.js';
import { getWeapon } from '../../config/weapons.js';
import { CombatEvents } from '../../core/CombatEvents.js';

export const KINETIC_RELEASE_ID='kinetic_release';
export const KINETIC_RELEASE_DAMAGE_RATIOS=[.9,1,1.1,1.25,1.4,1.55,1.7,1.9,2.15];
export const KINETIC_RELEASE_THRESHOLDS=[400,390,375,360,345,325,310,295,280];
export const KINETIC_RELEASE_RADII=[260,270,285,300,315,335,355,375,400];
export const KINETIC_RELEASE_MIN_INTERVAL_MS=700;
const levels=KINETIC_RELEASE_DAMAGE_RATIOS.map((damageRatio,index)=>{const level=index+1;return {damageRatio,kineticRequired:KINETIC_RELEASE_THRESHOLDS[index],radius:KINETIC_RELEASE_RADII[index],knockback:level>=3?52:0,dodgeKinetic:level>=6?120:0,...(level===3?{milestoneText:'动能震荡：造成伤害后轻度击退非Boss敌人'}:{}),...(level===6?{milestoneText:'闪避蓄能：真实闪避获得120点动能'}:{}),...(level===9?{milestoneText:'超速释放：额外移动速度按比例提高伤害，最高75%'}:{}),desc:`积蓄${KINETIC_RELEASE_THRESHOLDS[index]}动能后，释放半径${KINETIC_RELEASE_RADII[index]}、造成${Math.round(damageRatio*100)}%基础伤害的动能波。`};});
export function configureKineticReleaseSkill(){SKILLS[KINETIC_RELEASE_ID]={id:KINETIC_RELEASE_ID,name:'动能释放',rarity:'FINE',handler:KINETIC_RELEASE_ID,passive:true,maxLevel:9,targetType:'passive',short:'动',color:0x8bd8cf,tags:['physical','area','movement','dodge',TAGS.NORMAL_ATTACK],description:'移动、普通攻击和闪避会积蓄动能，蓄满后以角色为中心释放圆形动能波。',milestones:{3:'动能震荡',6:'闪避蓄能',9:'超速释放'},levels};}

const sumPositive=value=>Object.values(value||{}).reduce((sum,item)=>sum+Math.max(0,Number(item)||0),0);
const validEnemy=(scene,enemy)=>!!enemy&&enemy.hp>0&&scene.targeting?.valid?.(enemy)!==false&&scene.targeting?.isEnemyFullyInsideViewport?.(enemy)!==false;
const inRange=(scene,x,y,radius)=>scene.targeting.all().filter(enemy=>validEnemy(scene,enemy)&&Math.hypot(enemy.x-x,enemy.y-y)<=radius);
function cleanupVisuals(state){state.visuals.forEach(record=>{record.tween?.stop?.();record.tween?.remove?.();record.node?.destroy?.();});state.visuals.clear();}
function track(scene,state,node,tweenConfig){if(!node)return;const record={node,tween:null};const done=()=>{state.visuals.delete(record);node.destroy?.();};state.visuals.add(record);record.tween=scene.tweens?.add?.({targets:node,...tweenConfig,onComplete:done})||null;}
function visual(scene,state,x,y,radius,level,speedBonus){const enhanced=level>=3,boosted=level>=9&&speedBonus>0,alpha=.38+(enhanced?.1:0)+(boosted?Math.min(.1,speedBonus*.12):0),color=boosted?0xc7fff4:0x8bd8cf;const gather=scene.add?.circle?.(x,y-35,28,color,alpha)?.setStrokeStyle?.(3,0xe9fffb,alpha)?.setDepth?.(143);track(scene,state,gather,{scaleX:.35,scaleY:.35,alpha:0,duration:110,ease:'Sine.easeIn'});const ring=scene.add?.circle?.(x,y-35,34,color,.08)?.setStrokeStyle?.(enhanced?6:4,0xdffff9,alpha)?.setDepth?.(142);track(scene,state,ring,{scaleX:radius/34,scaleY:radius/34,alpha:0,duration:380,ease:'Cubic.easeOut'});const lineCount=6+(enhanced?2:0)+(boosted?Math.ceil(speedBonus*3):0);for(let i=0;i<lineCount;i++){const angle=Math.PI*2*i/lineCount+(i%2)*.12,length=22+(i%3)*6,node=scene.add?.rectangle?.(x+Math.cos(angle)*25,y-35+Math.sin(angle)*25,length,3,color,alpha)?.setRotation?.(angle)?.setDepth?.(144);track(scene,state,node,{x:x+Math.cos(angle)*radius*.7,y:y-35+Math.sin(angle)*radius*.7,alpha:0,duration:310+(i%3)*25,ease:'Cubic.easeOut'});}for(let i=0;i<6;i++){const angle=Math.PI*2*i/6+.3,node=scene.add?.circle?.(x+Math.cos(angle)*20,y+Math.sin(angle)*10,3+(i%2),0xbca77b,.42)?.setDepth?.(141);track(scene,state,node,{x:x+Math.cos(angle)*radius*.52,y:y+Math.sin(angle)*radius*.3,alpha:0,duration:340+(i%2)*40,ease:'Quad.easeOut'});}}
function baseDamage(scene,data,level){const weapon=getWeapon(scene.playerData.weaponId),profile=scene.professionSystem?.currentAttackProfile?.()||null,normalBase=scene.combatSystem.calcNonCritAttackBaseDamage(weapon,profile,false),speedBonus=level>=9?Math.min(.75,sumPositive(scene.playerData.moveSpeedMultiplierBonuses)):0;return {amount:Math.max(1,Math.round(normalBase*data.damageRatio*(1+speedBonus))),speedBonus};}
function release(system,state,data,level,x,y,targets){const scene=system.scene,{amount,speedBonus}=baseDamage(scene,data,level),professionMultiplier=scene.professionSystem?.getDamageMultiplier?.({type:'normalAttack',damaging:true})||1;visual(scene,state,x,y,data.radius,level,speedBonus);targets.forEach(enemy=>{const target=enemy,damaged=scene.combatSystem.damageEnemy(target,Math.round(amount*professionMultiplier),{source:'skill',skillId:KINETIC_RELEASE_ID,damageKind:'kineticRelease',tags:['physical','area'],critResolved:true,crit:false,canCrit:false,allowLifeSteal:false,canTriggerArtifacts:false,professionApplied:true,professionMultiplier,baseAmountBeforeProfession:amount,noKnockback:true});if(damaged&&data.knockback>0&&!target.isBoss&&validEnemy(scene,target))scene.combatSystem.applyKnockback(target,{source:'skill',knockback:data.knockback});});state.kinetic=0;state.ready=false;state.lastReleaseAt=scene.getGameplayTime?.()??0;}
export function getKineticReleaseState(system){const state=system?.passiveState?.kineticRelease;if(!state)return null;const required=system.getData(KINETIC_RELEASE_ID)?.kineticRequired||KINETIC_RELEASE_THRESHOLDS[0];return Object.freeze({kinetic:Math.min(state.kinetic,required),required,ready:state.ready||state.kinetic>=required});}
export const KineticReleaseSkill={shiftTimers(system){const state=system?.passiveState?.kineticRelease;if(state)state.lastPlayerX=system.scene.player?.x??state.lastPlayerX;},bind(system){const scene=system.scene,state={kinetic:0,ready:false,lastPlayerX:scene.player?.x??0,lastReleaseAt:-Infinity,lastDodgeEnemy:null,lastDodgeAt:-Infinity,visuals:new Set(),cleaned:false};system.passiveState.kineticRelease=state;const gain=amount=>{const data=system.getData(KINETIC_RELEASE_ID);if(!data||state.ready)return;state.kinetic=Math.min(data.kineticRequired,state.kinetic+amount);state.ready=state.kinetic>=data.kineticRequired;};const canAccumulate=()=>!scene.isGameplayPaused?.()&&(scene.playerData?.hp||0)>0;const onAttack=()=>{if(canAccumulate())gain(35);};const onDodge=payload=>{const level=system.getLevel(KINETIC_RELEASE_ID),data=system.getData(KINETIC_RELEASE_ID);if(!canAccumulate()||level<6||!data?.dodgeKinetic||payload?.forced!==false||payload?.directAttack!==true)return;const now=scene.getGameplayTime?.()??0;if(state.lastDodgeEnemy===payload.enemy&&state.lastDodgeAt===now)return;state.lastDodgeEnemy=payload.enemy;state.lastDodgeAt=now;gain(data.dodgeKinetic);};const updater=()=>{if(state.cleaned)return;const x=scene.player?.x??state.lastPlayerX,delta=x-state.lastPlayerX;state.lastPlayerX=x;if(!canAccumulate())return;if(delta>0)gain(delta);const data=system.getData(KINETIC_RELEASE_ID),level=system.getLevel(KINETIC_RELEASE_ID);if(!data||!level)return;if(state.kinetic>=data.kineticRequired){state.kinetic=data.kineticRequired;state.ready=true;}const now=scene.getGameplayTime?.()??0;if(!state.ready||now-state.lastReleaseAt<KINETIC_RELEASE_MIN_INTERVAL_MS)return;const centerX=scene.player.x,centerY=scene.player.y,targets=inRange(scene,centerX,centerY,data.radius);if(targets.length)release(system,state,data,level,centerX,centerY,targets);};const offAttack=scene.eventBus.on(CombatEvents.PLAYER_ATTACK_RESOLVED,onAttack),offDodge=scene.eventBus.on(CombatEvents.PLAYER_DODGED,onDodge);system.passiveUpdaters.push(updater);return()=>{if(state.cleaned)return;state.cleaned=true;offAttack?.();offDodge?.();cleanupVisuals(state);system.passiveUpdaters=system.passiveUpdaters.filter(item=>item!==updater);if(system.passiveState.kineticRelease===state)delete system.passiveState.kineticRelease;};}};
