import { SKILLS } from '../../config/skills.js';
import { TAGS } from '../../config/tags.js';
import { getCultivationSnapshot } from './CultivationCoreSkill.js';
import { getAlchemyDaoBuffModifiers } from './CultivationAlchemySkill.js';
import { rangeValue } from '../../systems/ActiveSkillModifierSystem.js';
import { applyEnemyGravity, removeEnemyGravitySourcesByPrefix } from '../../systems/EnemyGravityControl.js';
import { CombatEvents } from '../../core/CombatEvents.js';

export const MANTRA_HEAVENLY_BOOK_ID='mantra_heavenly_book';
export const MANTRA_MODES=Object.freeze(['life','spirit','slash','soul','curse','absorb']);
const names={life:'生',spirit:'灵',slash:'斩',soul:'神',curse:'咒',absorb:'纳'};
const help={life:'生命不足时恢复生命。',spirit:'恢复法力并推进其他主动技能冷却。',slash:'对残血敌人发动斩杀。',soul:'以元神压迫降低敌人移动和攻击速度。',curse:'施加倒计时诅咒，结束后造成高额伤害。',absorb:'将敌人收入天书炼化为临时己方单位。'};
const cooldown=[8000,7800,7600,7400,7200,6900,6600,6300,5800], mana=[14,14,15,15,16,16,17,18,20];
const life=[.06,.065,.07,.075,.08,.085,.09,.095,.10], spirit=[.08,.085,.09,.095,.10,.105,.11,.115,.12], slash=[80,90,102,116,132,150,171,195,225], curse=[70,79,90,102,116,132,150,171,195];
const execution=[.12,.13,.15,.16,.18,.18,.19,.20,.20], soulDuration=[4000,4100,4200,4300,4400,4800,5000,5200,5600];
const slow=[[.15,.10,.05],[.18,.12,.06],[.22,.15,.08],[.26,.18,.10],[.30,.21,.12],[.34,.24,.14],[.38,.27,.16],[.42,.30,.18],[.48,.34,.20]];
const valid=(s,e)=>!!e&&e.active!==false&&!e.isDefeated&&!e.dead&&Number(e.hp)>0&&s.targeting?.valid?.(e)!==false;
const now=s=>s.getGameplayTime?.()??s.now??0;
const realm=sys=>Math.max(0,Math.min(8,getCultivationSnapshot(sys).realmIndex||0));
const alchemy=sys=>getAlchemyDaoBuffModifiers(sys).cultivationSkillDamageMultiplier>1?1.5:1;
export function getMantraMode(sceneOrSystem){const p=(sceneOrSystem.scene||sceneOrSystem).playerData; return MANTRA_MODES.includes(p?.mantraHeavenlyBookMode)?p.mantraHeavenlyBookMode:null;}
export function chooseMantraMode(sceneOrSystem,mode){const s=sceneOrSystem.scene||sceneOrSystem;if(!MANTRA_MODES.includes(mode)||!s?.playerData)return false;s.playerData.mantraHeavenlyBookMode=mode;s.skillBar?.update?.();return true;}
function targets(sys){const s=sys.scene,p=s.player||{x:0,y:0};return (s.targeting?.all?.()||s.enemies||[]).filter(e=>valid(s,e)).sort((a,b)=>Math.hypot(a.x-p.x,a.y-p.y)-Math.hypot(b.x-p.x,b.y-p.y));}
function targetFor(sys,mode){const all=targets(sys),p=sys.scene.player||{};if(mode==='slash'){const r=realm(sys),within=all.filter(e=>e.hp/(e.maxHp||e.hp)<=execution[r]);return within.sort((a,b)=>(b.isBoss?2:b.isElite?1:0)-(a.isBoss?2:a.isElite?1:0)||b.hp-a.hp||Math.hypot(a.x-p.x,a.y-p.y)-Math.hypot(b.x-p.x,b.y-p.y))[0]||all.sort((a,b)=>a.hp/(a.maxHp||a.hp)-b.hp/(b.maxHp||b.hp))[0];}if(mode==='curse')return all.sort((a,b)=>(b.isBoss?2:b.isElite?1:0)-(a.isBoss?2:a.isElite?1:0)||b.hp-a.hp)[0];if(mode==='absorb')return all.filter(e=>!e.isBoss&&!e.isFinalBoss&&!(e.isElite&&realm(sys)<3)&&!e.mantraAbsorbed&&!e.mantraAlly).sort((a,b)=>(b.isElite?1:0)-(a.isElite?1:0)||b.hp-a.hp)[0];return all[0];}
function addActive(sys,a){sys.active.push(a);return a;}
function clean(a){a.visuals?.forEach(v=>v?.destroy?.());a.visuals=[];a.ended=true;}
function createAllyVisual(scene,ally,elite){
  const radius=elite?28:23;
  const body=scene.add?.circle?.(ally.x,ally.y,radius,elite?0x22d3ee:0x67e8f9,.92)?.setDepth?.(132);
  body?.setStrokeStyle?.(4,0xffffff,.95);
  const mark=scene.add?.text?.(ally.x,ally.y,'纳',{fontFamily:'Arial',fontSize:elite?'25px':'21px',color:'#083344',fontStyle:'bold'})?.setOrigin?.(.5)?.setDepth?.(133);
  const hpBack=scene.add?.rectangle?.(ally.x,ally.y-radius-13,56,7,0x082f49,.9)?.setDepth?.(133);
  const hpFill=scene.add?.rectangle?.(ally.x-28,ally.y-radius-13,56,7,0x4ade80,1)?.setOrigin?.(0,.5)?.setDepth?.(134);
  return {body,mark,hpBack,hpFill,radius,nodes:[body,mark,hpBack,hpFill].filter(Boolean)};
}
function syncAllyVisual(ally){
  const v=ally.visual;if(!v)return;
  v.body?.setPosition?.(ally.x,ally.y);v.mark?.setPosition?.(ally.x,ally.y);
  const y=ally.y-v.radius-13;v.hpBack?.setPosition?.(ally.x,y);v.hpFill?.setPosition?.(ally.x-28,y);
  v.hpFill?.setDisplaySize?.(56*Math.max(0,Math.min(1,ally.hp/Math.max(1,ally.maxHp))),7);
}
export const MantraHeavenlyBookSkill={
  runtimeBind:true,
  onAcquire(sys){if(getMantraMode(sys))return;queueMicrotask(()=>{if(sys.getLevel(MANTRA_HEAVENLY_BOOK_ID)>0&&!getMantraMode(sys))openMantraHeavenlyBookSelection(sys.scene);});},
  canCast(sys){const mode=getMantraMode(sys);if(!mode)return false;const p=sys.scene.playerData;if(mode==='life')return p.hp/p.maxHp<.8;if(mode==='spirit'){const active=sys.getOwned().filter(x=>x.id!==MANTRA_HEAVENLY_BOOK_ID&&!SKILLS[x.id]?.passive).filter(x=>(sys.cooldowns.get(x.id)||0)>now(sys.scene));return p.mana/p.maxMana<.7||active.length>=2;}if(mode==='absorb'&&sys.passiveState.mantraHeavenlyBook?.absorb)return false;if(['slash','curse','absorb'].includes(mode))return !!targetFor(sys,mode);return true;},
  cast(sys,cfg,data,level,ctx){const mode=getMantraMode(sys),s=sys.scene,t=now(s),p=s.playerData,bonus=alchemy(sys);if(!mode)return {failed:true};if(mode==='life'){const missing=Math.min(4,Math.floor((p.maxHp-p.hp)/(p.maxHp*.1)))*.01;s.healPlayer?.(p.maxHp*(life[level-1]+missing)*bonus,'skill',{skillId:cfg.id});if(level>=3){let hot=sys.active.find(a=>a.skillId===cfg.id&&a.kind==='lifeHot'&&!a.ended),total=Math.round(p.maxHp*.04*bonus);if(hot){hot.total=Math.max(hot.total,total);hot.nextAt=t+250;hot.endAt=t+4000;hot.ticks=0;}else addActive(sys,{skillId:cfg.id,kind:'lifeHot',nextAt:t+250,endAt:t+4000,ticks:0,total,data:{},visuals:[],tick(){while(!this.ended&&this.ticks<16&&now(s)>=this.nextAt){const amount=Math.floor(this.total*(this.ticks+1)/16)-Math.floor(this.total*this.ticks/16);s.healPlayer?.(amount,'skill',{skillId:cfg.id,periodic:true});this.ticks++;this.nextAt+=250;}if(this.ticks>=16)clean(this);},onEnd(){clean(this)}});}return {};}
    if(mode==='spirit'){sys.recoverMana(p.maxMana*spirit[level-1]*bonus);const st=sys.passiveState.mantraHeavenlyBook??={};sys.passiveState.mantraHeavenlyBook=st;st.spiritRegenMultiplier=1+.5*bonus;st.spiritRegenUntil=t+4000;if(level>=3){const ratio=[0,0,.08,.09,.10,.11,.12,.13,.15][level-1]||0;sys.getOwned().forEach(({id})=>{if(id===cfg.id||SKILLS[id]?.passive)return;const ready=sys.cooldowns.get(id)||0,remaining=Math.max(0,ready-t);if(remaining>0)sys.cooldowns.set(id,ready-Math.min(1000,remaining*ratio));});}return {};}
    if(mode==='slash'){const e=targetFor(sys,mode);if(!e)return {failed:true};const hpRatio=e.hp/(e.maxHp||e.hp),execute=!e.isBoss&&!e.isElite&&hpRatio<=execution[realm(sys)],before=e.hp,base=execute?e.hp:slash[level-1]*(1+Math.min(.4,(1-hpRatio)*.5));sys.hit(e,execute?e.hp:sys.damageValue(base,ctx),cfg,level,ctx,execute?e.hp:sys.baseDamageValue(base,ctx),[TAGS.CULTIVATION,TAGS.MAGIC,TAGS.SPELL],{damageAlreadyResolved:execute,defenseIgnore:execute?.9:0});return {cooldownRefundRatio:level>=3&&before>0&&!valid(s,e)?.25:0};}
    if(mode==='soul'){const duration=soulDuration[level-1]*bonus,idx=realm(sys),source=`mantra_soul_${ctx.castId}`;const affected=targets(sys);affected.forEach(e=>{const tier=e.isBoss?2:e.isElite?1:0;applyEnemyGravity(e,{sourceId:source,moveSlow:slow[idx][tier],attackSlow:level>=3?slow[idx][tier]/2:0,expiresAt:t+duration,external:true,countsAsGravitySuppression:false,ignoreBossScale:true});});const ghost=s.add?.text?.(s.player.x-70,s.player.y-140,'神',{fontFamily:'Arial',fontSize:'90px',color:'#d8b4fe',stroke:'#2e1065',strokeThickness:8})?.setDepth?.(130);return addActive(sys,{skillId:cfg.id,nextAt:t+80,endAt:t+duration,visuals:[ghost].filter(Boolean),tick(){affected.forEach(e=>valid(s,e)&&applyEnemyGravity(e,{sourceId:source,moveSlow:slow[idx][e.isBoss?2:e.isElite?1:0],attackSlow:level>=3?slow[idx][e.isBoss?2:e.isElite?1:0]/2:0,expiresAt:Math.min(this.endAt,now(s)+120),external:true,countsAsGravitySuppression:false,ignoreBossScale:true}));},onEnd(){affected.forEach(e=>removeEnemyGravitySourcesByPrefix(e,source));clean(this)}});}
    if(mode==='curse'){const e=targetFor(sys,mode);if(!e||e.mantraCurse)return {failed:true};const delay=[4000,3900,3800,3600,3300,3200,3100,3000,2800][realm(sys)],a={skillId:cfg.id,kind:'curse',nextAt:t+100,endAt:t+delay,target:e,data,level,ctx,stacks:0,lastHitAt:-Infinity,burst:false,visuals:[],finalDamage(){const base=curse[level-1]*(1+this.stacks*.05);return {damage:sys.damageValue(base,ctx),base:sys.baseDamageValue(base,ctx)};},tick(){if(now(s)>=this.endAt&&!this.burst){this.burst=true;if(valid(s,e)){const d=this.finalDamage();sys.hit(e,d.damage,cfg,level,ctx,d.base);}this.onEnd();}},onEnd(){if(this.ended)return;e.mantraCurse=null;this.offHit?.();this.offDeath?.();clean(this)}};a.offHit=s.eventBus?.on?.(CombatEvents.ENEMY_HIT,payload=>{if(a.ended||payload.enemy!==e||payload.damage<=0||payload.source==='mantraAlly'||payload.skillId===cfg.id||!['attack','skill'].includes(payload.source))return;if(now(s)-a.lastHitAt>=300&&a.stacks<6){a.stacks++;a.lastHitAt=now(s);}});a.offDeath=s.eventBus?.on?.(CombatEvents.ENEMY_KILLED,payload=>{if(a.ended||a.burst||payload.enemy!==e)return;a.burst=true;if(level>=3){const d=a.finalDamage(),radius=rangeValue(140,ctx),x=e.x,y=e.y;targets(sys).filter(o=>o!==e&&Math.hypot(o.x-x,o.y-y)<=radius).forEach(o=>sys.hit(o,d.damage*.6,cfg,level,ctx,d.base*.6));}a.onEnd();});e.mantraCurse=a;return addActive(sys,a);}
    if(mode==='absorb'){const original=targetFor(sys,mode),state=sys.passiveState.mantraHeavenlyBook??={};sys.passiveState.mantraHeavenlyBook=state;if(!original||state.absorb)return {failed:true};const elite=!!original.isElite,refineMs=Math.max(elite?2800:1800,(elite?6000:4000)*(level>=6?.75:1)*(realm(sys)>=5?.75:1)/bonus),saved={enemy:original,index:s.enemies.indexOf(original),x:original.x,y:original.y,hp:original.hp,active:original.active,body:original.body?.enable};state.absorb={saved,phase:'refining'};original.mantraAbsorbed=true;original.body&&(original.body.enable=false);original.setVisible?.(false);s.enemyBehaviors?.destroyEnemy?.(original);s.enemies=s.enemies.filter(x=>x!==original);const task={skillId:cfg.id,kind:'absorb',nextAt:t+50,endAt:t+refineMs,visuals:[],data:{},tick(){const current=now(s);if(state.absorb?.phase==='refining'){if(current<this.endAt)return;const hpRatio=elite?(level>=3?.5:.45):(level>=3?.75:.7),damageRatio=elite?(level>=3?.55:.5):(level>=3?.75:.7),ally={type:'mantraAlly',x:s.player.x+72,y:s.player.y,hp:Math.round(original.maxHp*hpRatio),maxHp:Math.round(original.maxHp*hpRatio),attack:Math.round(original.damage*damageRatio),attackRange:original.attackRange>200?380:95,attackIntervalMs:original.attackIntervalMs||1200,nextAttackAt:current,active:true,isAlive(){return this.active&&this.hp>0},takeDamage(n){this.hp=Math.max(0,this.hp-n);if(!this.hp)this.active=false;syncAllyVisual(this);}};ally.visual=createAllyVisual(s,ally,elite);this.visuals.push(...(ally.visual?.nodes||[]));syncAllyVisual(ally);state.absorb={saved,phase:'ally',ally};this.endAt=current+(elite?10000:12000)*(realm(sys)>=6?1.25:1);original.destroy?.();return;}const ally=state.absorb?.ally;if(!ally?.isAlive?.()||current>=this.endAt){this.onEnd();return;}ally.x+=(s.player.x+72-ally.x)*.12;ally.y+=(s.player.y-ally.y)*.12;syncAllyVisual(ally);if(current>=ally.nextAttackAt){const target=targets(sys).sort((a,b)=>Math.hypot(a.x-ally.x,a.y-ally.y)-Math.hypot(b.x-ally.x,b.y-ally.y))[0];if(target&&Math.hypot(target.x-ally.x,target.y-ally.y)<=ally.attackRange){s.combatSystem.damageEnemy(target,ally.attack,{source:'mantraAlly',skillId:cfg.id,tags:[TAGS.SUMMON],noKnockback:true});ally.nextAttackAt=current+ally.attackIntervalMs;s.tweens?.add?.({targets:ally.visual?.body,scaleX:1.25,scaleY:1.25,duration:70,yoyo:true});}}this.nextAt=current+50;},onEnd(){if(this.ended)return;if(state.absorb?.phase==='refining'){const q=saved.enemy;q.mantraAbsorbed=false;q.active=saved.active;q.hp=saved.hp;q.x=saved.x;q.y=saved.y;q.setVisible?.(true);q.body&&(q.body.enable=saved.body);s.enemies.splice(Math.max(0,saved.index),0,q);s.enemyBehaviors?.attach?.(q);}if(state.absorb?.ally)state.absorb.ally.active=false;delete state.absorb;clean(this)}};return addActive(sys,task);}
    return {failed:true};
  },
  cleanup(sys){const st=sys.passiveState.mantraHeavenlyBook;if(st){st.spiritRegenUntil=0;st.spiritRegenMultiplier=1;}sys.active.filter(a=>a.skillId===MANTRA_HEAVENLY_BOOK_ID).forEach(a=>a.onEnd?.('cleanup'));},
  shiftTimers(sys,d,pauseAt){const st=sys.passiveState.mantraHeavenlyBook;if(st?.spiritRegenUntil>pauseAt)st.spiritRegenUntil+=d;if(st?.absorb?.ally?.nextAttackAt>pauseAt)st.absorb.ally.nextAttackAt+=d;}
};
export function configureMantraHeavenlyBookSkill(){SKILLS[MANTRA_HEAVENLY_BOOK_ID]={id:MANTRA_HEAVENLY_BOOK_ID,name:'真言天书',rarity:'MYTHIC',type:'主动修仙法术',maxLevel:9,passive:false,targetType:'self',handler:MANTRA_HEAVENLY_BOOK_ID,short:'言',color:0xc084fc,tags:[TAGS.CULTIVATION,TAGS.MAGIC,TAGS.SPELL,TAGS.ACTIVE_SKILL,TAGS.BUILD_CULTIVATION,TAGS.MYTHIC_SKILL],description:'持有六种可随时切换的真言。当前真言会按统一冷却自动施放，切换不重置冷却。',milestones:{3:'真言显化',6:'天书敕令',9:'道法真言'},levels:cooldown.map((cooldownMs,i)=>({cooldownMs,manaCost:mana[i],lifeRatio:life[i],spiritRatio:spirit[i],slashDamage:slash[i],curseDamage:curse[i],soulDurationMs:soulDuration[i],desc:`当前真言：${names.life}/${names.spirit}/${names.slash}/${names.soul}/${names.curse}/${names.absorb}。${help.life}`}))};}
export { names as MANTRA_MODE_NAMES, help as MANTRA_MODE_HELP };
export function openMantraHeavenlyBookSelection(scene){
  if(!scene||scene.mantraHeavenlyBookSelectionOpen)return false;
  scene.mantraHeavenlyBookSelectionOpen=true;scene.beginGameplayPause?.();
  const nodes=[],depth=5100,cols=[0x4ade80,0x60a5fa,0xf59e0b,0xa78bfa,0x9f1239,0x164e63];
  const close=()=>{nodes.forEach(n=>{n.removeAllListeners?.();n.destroy?.();});scene.mantraHeavenlyBookSelectionOpen=false;scene.endGameplayPause?.();};
  const bg=scene.add.rectangle(360,640,720,1280,0x030712,.90).setScrollFactor(0).setDepth(depth).setInteractive();
  const title=scene.add.text(360,130,'真言天书·选择真言',{fontFamily:'Arial',fontSize:'36px',color:'#fff',stroke:'#000',strokeThickness:5}).setOrigin(.5).setScrollFactor(0).setDepth(depth+2);
  const cancel=scene.add.text(650,84,'取消',{fontFamily:'Arial',fontSize:'22px',color:'#fff',backgroundColor:'#4a2d38',padding:{left:14,right:14,top:8,bottom:8}}).setOrigin(.5).setScrollFactor(0).setDepth(depth+2).setInteractive({useHandCursor:true});
  nodes.push(bg,title,cancel);cancel.on('pointerdown',close);
  MANTRA_MODES.forEach((mode,i)=>{const x=190+(i%3)*170,y=350+Math.floor(i/3)*310,selected=getMantraMode(scene)===mode;const box=scene.add.rectangle(x,y,150,260,cols[i],.85).setStrokeStyle(selected?7:3,selected?0xffffff:0xcbd5e1,1).setScrollFactor(0).setDepth(depth+1).setInteractive({useHandCursor:true});const text=scene.add.text(x,y,`${names[mode]}\n${mode==='life'?'生字':mode==='spirit'?'灵字':mode==='slash'?'斩字':mode==='soul'?'神字':mode==='curse'?'咒字':'纳字'}\n${help[mode]}`,{fontFamily:'Arial',fontSize:'21px',align:'center',color:'#fff',stroke:'#000',strokeThickness:3,wordWrap:{width:130},lineSpacing:8}).setOrigin(.5).setScrollFactor(0).setDepth(depth+2);const select=()=>{chooseMantraMode(scene,mode);close();};box.on('pointerdown',select);text.setInteractive({useHandCursor:true}).on('pointerdown',select);nodes.push(box,text);});
  return true;
}
