import { SKILLS } from '../../config/skills.js';
import { TAGS } from '../../config/tags.js';
import { CombatEvents } from '../../core/CombatEvents.js';
import { StatusEffects } from '../../systems/StatusEffectSystem.js';

export const POISON_ADVANCED_TUNING=Object.freeze({
  chain:{ rebuildMs:1800, extendRadius:230, extendChance:0.38, extendChanceL3:0.62, checkMs:1200, checkMsL3:760, maxLinksPerNode:2, transferStacksOnDeathRatio:0.5 },
  king:{ reviveMs:4200, baseHp:180, biteIntervalMs:900, biteDamage:28, poisonDamage:8, poisonStacks:1, growthRatio:0.22, growthRatioL3:0.34, growthStage:45, maxStage:6, hpPerStage:35, damagePerStage:6, poisonPerStage:1, scalePerStage:0.08, stageHealL3:24, biteDamageMultiplierL6:1.45, biteStacksL6:2, biteHealRatioL6:0.12, biteHealCapMaxHpRatio:0.015, domainRadius:135, domainIntervalMs:900, domainDamage:7 }
});
const levels=(rows,build,milestones={})=>rows.map((row,i)=>({...build(row,i+1),...(milestones[i+1]?{milestoneText:milestones[i+1]}:{})}));
const removeUpdater=(system,fn)=>{ const i=system.passiveUpdaters.indexOf(fn); if(i>=0) system.passiveUpdaters.splice(i,1); };
const dist=(a,b)=>Math.hypot((a.x||0)-(b.x||0),(a.y||0)-(b.y||0));
const normalPoison=p=>p?.type===StatusEffects.POISON&&p.actualDamage>0&&!p.effect?.poisonMeta?.nonNormal&&!p.effect?.noPoisonKingRecursive;
function addPoison(system,target,stacks,durationMs,value,sourceId,meta={}){ const d=system.getData('poison_cloud')||{}; return system.scene.statusEffects.add(StatusEffects.POISON,target,{durationMs,intervalMs:d.poisonIntervalMs||700,value:value||d.poisonDamage||6,stacks,maxStacks:Math.max(d.maxStacks||15,stacks),sourceId,damageMultiplier:1,baseDamageMultiplierWithoutProfession:1,professionMultiplier:1,professionApplied:true,poisonMeta:meta}); }
function healEntity(entity,amount,max){ const before=entity.hp??0; entity.hp=Math.min(max??entity.maxHp??before,before+Math.max(0,amount)); return entity.hp-before; }

const CONFIGS={
  poison_chain:{ id:'poison_chain',name:'毒链',rarity:'EPIC',handler:'poison_chain',passive:true,maxLevel:9,requiredSkillId:'parasitic_gu',tags:[TAGS.POISON,TAGS.DOT,TAGS.SUMMON,TAGS.BUILD_POISON_SUMMON],cooldownMs:999999,targetType:'passive',color:0x42e76d,short:'链',description:'投出毒链建立会自行扩张的感染网络，节点逐步连接附近中毒敌人。',levels:levels([[0.38,1200],[0.42,1100],[0.62,760],[0.64,730],[0.66,700],[0.68,680],[0.7,650],[0.72,620],[0.74,600]],([extendChance,checkMs],level)=>({extendChance,checkMs,extendRadius:POISON_ADVANCED_TUNING.chain.extendRadius,maxLinksPerNode:2,rebuildMs:POISON_ADVANCED_TUNING.chain.rebuildMs,desc:level>=9?'节点死亡时会把毒网续接到附近目标。':level>=6?'新施加毒层会向相邻节点传递1层，但不会递归。':level>=3?'毒链更容易且更频繁扩张。':'选择一名中毒敌人作为初始节点并逐步扩张。'}),{3:'毒链蔓延：提高延伸概率并缩短判定间隔',6:'毒素传导：新毒层向相邻节点传递1层',9:'瘟疫不绝：节点死亡时立即续网'} )},
  poison_king:{ id:'poison_king',name:'毒王',rarity:'EPIC',handler:'poison_king',passive:true,maxLevel:9,requiredSkillId:'poison_chain',targetType:'passive',tags:[TAGS.POISON,TAGS.DOT,TAGS.SUMMON,TAGS.BUILD_POISON_SUMMON],color:0x1f9d45,short:'王',description:'召唤一只常驻毒王，拥有独立血量，撕咬上毒并吸收全场正常毒伤成长。',levels:levels([[180,28,0.22],[195,31,0.24],[210,34,0.34],[225,37,0.34],[240,40,0.34],[260,58,0.34],[280,63,0.36],[305,68,0.38],[330,74,0.4]],([hp,biteDamage,growthRatio],level)=>({hp,biteDamage,growthRatio,biteIntervalMs:POISON_ADVANCED_TUNING.king.biteIntervalMs,poisonDamage:POISON_ADVANCED_TUNING.king.poisonDamage,poisonStacks:level>=6?2:1,growthStage:POISON_ADVANCED_TUNING.king.growthStage,maxStage:POISON_ADVANCED_TUNING.king.maxStage,reviveMs:POISON_ADVANCED_TUNING.king.reviveMs,desc:level>=9?'毒王周围形成跟随移动的毒领域。':level>=6?'剧毒撕咬伤害提高，上毒层数增加并对中毒目标回血。':level>=3?'毒伤转化成长更快，阶段提升时额外回血。':'常驻毒王撕咬敌人并施加中毒。'}),{3:'吸毒成长：成长效率提高，升阶额外恢复生命',6:'剧毒撕咬：撕咬更强、上毒更多并回血',9:'毒领域：周围敌人周期性受毒伤并被上毒'} )}
};
export function configurePoisonSummonAdvancedSkills(){ Object.entries(CONFIGS).forEach(([id,cfg])=>{ SKILLS[id]={...cfg}; }); }

export const PoisonChainSkill={ bind(system){ const s=system.scene,nodes=new Map(),edges=new Set(),visuals=new Map(); let nextBuildAt=0;
  const nodeTargets=()=>[...nodes.keys()].filter(e=>s.targeting.valid(e)&&s.statusEffects.has(e,StatusEffects.POISON));
  const addNode=e=>{ if(!e||nodes.has(e)) return false; nodes.set(e,{nextAt:s.getGameplayTime()+200,links:new Set()}); return true; };
  const removeNode=e=>{ const n=nodes.get(e); if(!n) return; [...n.links].forEach(o=>{ nodes.get(o)?.links.delete(e); edges.delete(edgeKey(e,o)); visuals.get(edgeKey(e,o))?.destroy?.(); visuals.delete(edgeKey(e,o)); }); nodes.delete(e); };
  const edgeKey=(a,b)=>`${a.id||a.__uid||a.x}:${b.id||b.__uid||b.x}`;
  const connect=(a,b)=>{ const na=nodes.get(a),nb=nodes.get(b); if(!na||!nb||na.links.size>=2||nb.links.size>=2||na.links.has(b)) return; na.links.add(b); nb.links.add(a); edges.add(edgeKey(a,b)); const g=s.add.graphics().setDepth(145); visuals.set(edgeKey(a,b),g); };
  const chooseSeed=()=>s.targeting.all().find(e=>s.targeting.valid(e)&&s.statusEffects.has(e,StatusEffects.POISON));
  const extend=(e,data)=>{ const n=nodes.get(e); if(!n||n.links.size>=2||Math.random()>data.extendChance) return; const candidates=s.targeting.all().filter(t=>t!==e&&!nodes.has(t)&&s.targeting.valid(t)&&s.statusEffects.has(t,StatusEffects.POISON)&&dist(t,e)<=data.extendRadius); if(candidates[0]&&addNode(candidates[0])) connect(e,candidates[0]); };
  const offApply=s.eventBus.on(CombatEvents.STATUS_APPLIED,p=>{ if(p.type!==StatusEffects.POISON||!nodes.has(p.target)||p.effect?.poisonMeta?.chainTransfer) return; if(system.getLevel('poison_chain')<6) return; const n=nodes.get(p.target), adj=[...n.links].find(x=>s.targeting.valid(x)); if(adj) addPoison(system,adj,1,2600,system.getData('poison_cloud')?.poisonDamage||6,`poison_chain_transfer_${p.effect?.id||s.getGameplayTime()}`,{chainTransfer:true}); });
  const offKill=s.eventBus.on(CombatEvents.ENEMY_KILLED,p=>{ if(!nodes.has(p.enemy)) return; const data=system.getData('poison_chain'); const old=p.enemy, stacks=p.poisonStacksBeforeDeath||s.statusEffects.getStackCount(old,StatusEffects.POISON); removeNode(old); if(system.getLevel('poison_chain')<9) return; const near=s.targeting.all().filter(e=>s.targeting.valid(e)&&!nodes.has(e)).sort((a,b)=>dist(a,old)-dist(b,old)); const poisoned=near.find(e=>s.statusEffects.has(e,StatusEffects.POISON)); const target=poisoned||near[0]; if(target){ if(!poisoned) addPoison(system,target,1,2600,system.getData('poison_cloud')?.poisonDamage||6,`poison_chain_death_seed_${s.getGameplayTime()}`,{chainDeathRelay:true}); else addPoison(system,target,Math.max(1,Math.floor(stacks*POISON_ADVANCED_TUNING.chain.transferStacksOnDeathRatio)),2600,system.getData('poison_cloud')?.poisonDamage||6,`poison_chain_death_relay_${s.getGameplayTime()}`,{chainDeathRelay:true}); addNode(target); } });
  const updater=()=>{ const now=s.getGameplayTime(), data=system.getData('poison_chain'); if(!data){ nodes.clear(); visuals.forEach(v=>v.destroy?.()); visuals.clear(); return; } nodeTargets().forEach(e=>{ const n=nodes.get(e); if(now>=n.nextAt){ n.nextAt=now+data.checkMs; extend(e,data); } }); [...nodes.keys()].forEach(e=>{ if(!s.targeting.valid(e)||!s.statusEffects.has(e,StatusEffects.POISON)) removeNode(e); }); if(!nodes.size&&now>=nextBuildAt){ nextBuildAt=now+data.rebuildMs; addNode(chooseSeed()); } visuals.forEach(g=>g.clear()); nodes.forEach((n,a)=>n.links.forEach(b=>{ const k=edgeKey(a,b), g=visuals.get(k); if(g) g.lineStyle(4,0x66ff88,0.8).lineBetween(a.x,a.y-46,b.x,b.y-46); })); };
  system.passiveUpdaters.push(updater); updater(); return ()=>{ offApply(); offKill(); removeUpdater(system,updater); visuals.forEach(v=>v.destroy?.()); visuals.clear(); nodes.clear(); edges.clear(); } } };

export const PoisonKingSkill={ bind(system){ const s=system.scene; let king=null,nextRespawnAt=0,lastAt=s.getGameplayTime();
  const spawn=()=>{ const d=system.getData('poison_king'); if(!d||king) return; const view=s.add.container(s.player.x+90,s.player.y-55).setDepth(147); const body=s.add.ellipse(0,0,58,38,0x1f9d45,0.95).setStrokeStyle(4,0xb7ff82,0.8); const eye=s.add.circle(17,-5,4,0xf2ffd2,1); view.add([body,eye]); const hp=d.hp; king={view,hp,maxHp:hp,growth:0,stage:0,target:null,nextBiteAt:s.getGameplayTime()+500,nextDomainAt:s.getGameplayTime()+700,domain:null,dead:false}; };
  const die=()=>{ if(!king) return; king.view?.destroy?.(); king.domain?.destroy?.(); king=null; nextRespawnAt=s.getGameplayTime()+((system.getData('poison_king')||{}).reviveMs||4200); };
  const grow=amount=>{ const d=system.getData('poison_king'); if(!king||!d||king.stage>=d.maxStage) return; king.growth+=amount*d.growthRatio; while(king.growth>=d.growthStage&&king.stage<d.maxStage){ king.growth-=d.growthStage; king.stage++; king.maxHp+=POISON_ADVANCED_TUNING.king.hpPerStage; king.hp=Math.min(king.maxHp,king.hp+POISON_ADVANCED_TUNING.king.hpPerStage+(system.getLevel('poison_king')>=3?POISON_ADVANCED_TUNING.king.stageHealL3:0)); king.view.setScale(1+king.stage*POISON_ADVANCED_TUNING.king.scalePerStage); } };
  const offTick=s.eventBus.on(CombatEvents.STATUS_TICK,p=>{ if(normalPoison(p)) grow(p.actualDamage); });
  const choose=()=>s.targeting.all().filter(e=>s.targeting.valid(e)).sort((a,b)=>dist(a,king.view)-dist(b,king.view))[0]||null;
  const bite=(target,d)=>{ const lvl=system.getLevel('poison_king'), poisoned=s.statusEffects.has(target,StatusEffects.POISON); const dmg=Math.round((d.biteDamage+king.stage*POISON_ADVANCED_TUNING.king.damagePerStage)*(lvl>=6?POISON_ADVANCED_TUNING.king.biteDamageMultiplierL6:1)); const before=target.hp||0; s.combatSystem.damageEnemy(target,dmg,{source:'skill',skillId:'poison_king',damageKind:'poisonKingBite',tags:[TAGS.POISON,TAGS.SUMMON,TAGS.BUILD_POISON_SUMMON],allowLifeSteal:false,noKnockback:true,noPoisonChain:true}); const actual=Math.max(0,before-(target.hp||0)); addPoison(system,target,d.poisonStacks,3600,d.poisonDamage+king.stage*POISON_ADVANCED_TUNING.king.poisonPerStage,`poison_king_bite_${s.getGameplayTime()}`,{poisonKingApplied:true}); if(lvl>=6&&poisoned) healEntity(king,Math.min(actual*POISON_ADVANCED_TUNING.king.biteHealRatioL6,king.maxHp*POISON_ADVANCED_TUNING.king.biteHealCapMaxHpRatio),king.maxHp); };
  const domain=(d)=>{ if(system.getLevel('poison_king')<9) return; if(!king.domain) king.domain=s.add.circle(king.view.x,king.view.y,POISON_ADVANCED_TUNING.king.domainRadius,0x40e060,0.08).setStrokeStyle(3,0x7dff73,0.55).setDepth(143); king.domain.x=king.view.x; king.domain.y=king.view.y; s.targeting.all().filter(e=>s.targeting.valid(e)&&dist(e,king.view)<=POISON_ADVANCED_TUNING.king.domainRadius).forEach(e=>{ s.combatSystem.damageEnemy(e,POISON_ADVANCED_TUNING.king.domainDamage,{source:'skill',skillId:'poison_king',damageKind:'poisonKingDomain',tags:[TAGS.POISON,TAGS.DOT,TAGS.SUMMON,TAGS.BUILD_POISON_SUMMON],allowLifeSteal:false,noKnockback:true,noPoisonChain:true}); addPoison(system,e,1,2800,d.poisonDamage,`poison_king_domain_${s.getGameplayTime()}_${e.id||''}`,{poisonDomain:true}); }); };
  const updater=()=>{ const now=s.getGameplayTime(), dt=(now-lastAt)/1000; lastAt=now; const d=system.getData('poison_king'); if(!d){ die(); return; } if(!king&&now>=nextRespawnAt) spawn(); if(!king) return; king.hp-=0*dt; if(king.hp<=0) return die(); const t=choose(); king.target=t; const goal=t?{x:t.x-42,y:t.y-54}:{x:s.player.x+95,y:s.player.y-55}; king.view.x+=(goal.x-king.view.x)*0.1; king.view.y+=(goal.y-king.view.y)*0.1; if(t&&now>=king.nextBiteAt){ king.nextBiteAt=now+d.biteIntervalMs; bite(t,d); } if(now>=king.nextDomainAt){ king.nextDomainAt=now+POISON_ADVANCED_TUNING.king.domainIntervalMs; domain(d); } if(king.domain){ king.domain.x=king.view.x; king.domain.y=king.view.y; } };
  system.passiveUpdaters.push(updater); updater(); return ()=>{ offTick(); removeUpdater(system,updater); die(); } }, cleanup(system){} };
export const poisonSummonBonusUtils={ sumBonuses:b=>Object.values(b||{}).reduce((s,v)=>s+(Number(v)||0),0), ensureRuntime:p=>p, ensurePoisonRuntime:s=>({}) };
