import { SKILLS } from '../../config/skills.js';
import { TAGS } from '../../config/tags.js';
import { CombatEvents } from '../../core/CombatEvents.js';

export const SPELL_TIDE_ID='spell_tide';
export const SPELL_TIDE_REDUCTIONS=[400,500,650,750,850,1000,1100,1200,1400];
export const SPELL_TIDE_MANA=[0,0,0,0,0,4,4,4,6];
export const SPELL_TIDE_MIN_REMAINING_MS=300;
export function configureSpellTideSkill(){SKILLS[SPELL_TIDE_ID]={id:SPELL_TIDE_ID,name:'法术潮汐',rarity:'RARE',handler:SPELL_TIDE_ID,passive:true,maxLevel:9,targetType:'passive',short:'潮',color:0x7667e8,tags:[TAGS.MAGIC,'cooldown','mana'],description:'每成功释放3次真实主动技能，触发法术潮汐，缩短所有主动技能的剩余冷却。',milestones:{3:'潮汐涌动',6:'灵潮回涌',9:'法海无涯'},levels:SPELL_TIDE_REDUCTIONS.map((reductionMs,index)=>({reductionMs,manaRecovery:SPELL_TIDE_MANA[index],extraLongestReductionMs:index===8?1400:0,...(index===2?{milestoneText:'潮汐涌动：全体冷却减少650ms'}:{}),...(index===5?{milestoneText:'灵潮回涌：潮汐恢复4点法力'}:{}),...(index===8?{milestoneText:'法海无涯：最长剩余冷却额外减少1400ms'}:{}),desc:`每3次成功主动施法使全体剩余冷却缩短${reductionMs}ms${SPELL_TIDE_MANA[index]?`，并恢复${SPELL_TIDE_MANA[index]}点法力`:''}。`}))};}
function clearVisuals(state){state.visuals.forEach(({node,tween})=>{tween?.stop?.();tween?.remove?.();node?.destroy?.();});state.visuals.clear();}
function track(scene,state,node,config){if(!node)return;const record={node,tween:null};state.visuals.add(record);record.tween=scene.tweens?.add?.({targets:node,...config,onComplete:()=>{state.visuals.delete(record);node.destroy?.();}})||null;}
function showTide(system,state,level){const s=system.scene,x=s.player?.x,y=s.player?.y;if(!Number.isFinite(x)||!Number.isFinite(y))return;const ring=s.add?.circle?.(x,y,30,0x655ee8,.08)?.setStrokeStyle?.(4,0x8b8cff,.75)?.setDepth?.(142);track(s,state,ring,{scaleX:4.5,scaleY:2.2,alpha:0,duration:380,ease:'Cubic.easeOut'});if(level>=9){const outer=s.add?.circle?.(x,y,38,0x8d72e8,.04)?.setStrokeStyle?.(3,0xb9a7ff,.42)?.setDepth?.(141);track(s,state,outer,{scaleX:4.8,scaleY:2.35,alpha:0,duration:430,ease:'Cubic.easeOut'});}const count=level>=6?8:5;for(let i=0;i<count;i++){const dot=s.add?.circle?.(x-28+i*8,y-8-(i%2)*5,2+(i%3===0),i%2?0x8ad8ff:0xb09cff,.7)?.setDepth?.(143);track(s,state,dot,{x:x-38+i*11,y:y-48-(i%3)*14,alpha:0,duration:310+(i%3)*45,ease:'Sine.easeOut'});}}
function validCompletedCast(event){const cfg=event?.skillId&&SKILLS[event.skillId];return !!cfg&&event.skill===cfg&&!cfg.passive&&cfg.targetType!=='passive'&&cfg.tags?.includes(TAGS.ACTIVE_SKILL)&&event.ctx?.isActiveSkill===true&&Number.isInteger(event.ctx?.castId)&&!event.fromMyriadAfterimage&&!event.ctx?.fromMyriadAfterimage&&event.skillId!==SPELL_TIDE_ID;}
function execute(system,state){const s=system.scene,data=system.getData(SPELL_TIDE_ID),level=system.getLevel(SPELL_TIDE_ID);state.pendingTide=false;if(!data||!level)return;const now=s.getGameplayTime(),cooling=[];system.getOwned().forEach(({id},slot)=>{const cfg=SKILLS[id],readyAt=system.cooldowns.get(id);if(id!==SPELL_TIDE_ID&&cfg&&!cfg.passive&&readyAt>now)cooling.push({id,slot,readyAt});});cooling.forEach(item=>system.cooldowns.set(item.id,Math.max(now+SPELL_TIDE_MIN_REMAINING_MS,item.readyAt-data.reductionMs)));if(data.extraLongestReductionMs&&cooling.length){const longest=cooling.map(item=>({...item,readyAt:system.cooldowns.get(item.id)})).sort((a,b)=>b.readyAt-a.readyAt||a.slot-b.slot)[0];system.cooldowns.set(longest.id,Math.max(now+SPELL_TIDE_MIN_REMAINING_MS,longest.readyAt-data.extraLongestReductionMs));}if(data.manaRecovery)system.recoverMana(data.manaRecovery);showTide(system,state,level);s.skillBar?.update?.();}
export function getSpellTideState(system){const state=system?.passiveState?.spellTide;return state?Object.freeze({count:state.count,pendingTide:state.pendingTide}):null;}
export const SpellTideSkill={bind(system){const s=system.scene,state={count:0,pendingTide:false,visuals:new Set(),cleaned:false};system.passiveState.spellTide=state;const onCast=event=>{if(state.cleaned||!system.getLevel(SPELL_TIDE_ID)||!validCompletedCast(event))return;state.count+=1;if(state.count>=3){state.count=0;state.pendingTide=true;}};const updater=()=>{if(state.cleaned||!state.pendingTide||s.isGameplayPaused?.()||(s.playerData?.hp||0)<=0)return;execute(system,state);};const off=s.eventBus.on(CombatEvents.SKILL_CAST_COMPLETED,onCast);system.passiveUpdaters.push(updater);return()=>{if(state.cleaned)return;state.cleaned=true;off?.();state.count=0;state.pendingTide=false;clearVisuals(state);system.passiveUpdaters=system.passiveUpdaters.filter(fn=>fn!==updater);if(system.passiveState.spellTide===state)delete system.passiveState.spellTide;};}};
