import { TAGS } from '../../config/tags.js';
import { getEffectiveAttack } from '../../config/balance.js';

export const SPIRIT_SLIME_ID='spirit_slime';
const SOURCE='spirit_slime';
const ZERO=Object.freeze({powerBonus:0,maxHpBonus:0,damageReduction:0,actionSpeedBonus:0,healingReceivedBonus:0});
const alive=t=>!!t&&!t.destroyed&&!t.dead&&t.hp>0&&(t.isAlive?.()??true);
const idx=level=>Math.max(0,Math.min(8,(level||1)-1));
function dataFor(system){ return system.getData(SPIRIT_SLIME_ID,system.getLevel(SPIRIT_SLIME_ID))||{}; }
function modFrom(data){ return {powerBonus:data.summonPowerBonus||0,maxHpBonus:data.summonMaxHpBonus||0,damageReduction:data.summonDamageReduction||0,actionSpeedBonus:data.summonActionSpeedBonus||0,healingReceivedBonus:data.summonHealingReceivedBonus||0}; }
function viewportEnemy(scene,e){ return scene.targeting?.valid?.(e)&&scene.targeting?.isEnemyFullyInsideViewport?.(e)!==false&&e.hp>0; }
function nearestEnemy(scene,x,y){ return scene.targeting?.all?.().filter(e=>viewportEnemy(scene,e)).sort((a,b)=>Math.hypot(a.x-x,a.y-y)-Math.hypot(b.x-x,b.y-y))[0]||null; }
function setRatioHp(obj,newMax){ const old=Math.max(1,Number(obj.maxHp)||1),ratio=Math.max(0,Math.min(1,(Number(obj.hp)||0)/old)); obj.maxHp=Math.max(1,Math.round(newMax)); obj.hp=Math.max(obj.hp>0?1:0,Math.min(obj.maxHp,Math.round(obj.maxHp*ratio))); }
function summonList(scene){ const out=[]; const king=scene.poisonKingRuntime?.get?.(); if(alive(king)) out.push(king); (scene.skillSystem?.passiveState?.spiritWolves?.wolves||[]).filter(alive).sort((a,b)=>(a.index??0)-(b.index??0)).forEach(w=>out.push(w)); const bird=scene.spiritBirdRuntime?.get?.(); if(alive(bird)) out.push(bird); return out; }
function ensureBase(t){ if(!t||t.__spiritSlimeBase) return; t.__spiritSlimeBase={maxHp:t.baseMaxHp??t.unmodifiedMaxHp??t.maxHp,attack:t.baseAttack??t.attack,defense:t.baseDefense??t.defense,attackIntervalMs:t.baseAttackIntervalMs??t.attackIntervalMs??t.healIntervalMs??t.intervalMs}; t.baseMaxHp=t.__spiritSlimeBase.maxHp; if(t.attack!=null) t.baseAttack=t.__spiritSlimeBase.attack; if(t.defense!=null) t.baseDefense=t.__spiritSlimeBase.defense; }
function applyTarget(t,mod){ ensureBase(t); if(!t.__spiritSlimeBase) return; const b=t.__spiritSlimeBase; if(b.maxHp) setRatioHp(t,b.maxHp*(1+mod.maxHpBonus)); if(b.attack!=null) t.attack=Math.max(1,Math.round(b.attack*(1+mod.powerBonus))); if(b.defense!=null) t.defense=b.defense; if(b.attackIntervalMs!=null){ t.attackIntervalMs=Math.max(1,Math.round(b.attackIntervalMs/(1+mod.actionSpeedBonus))); t.healIntervalMs=t.attackIntervalMs; t.intervalMs=t.attackIntervalMs; } t.spiritSlimeModifier=mod; }
function clearTarget(t){ if(!t?.__spiritSlimeBase) return; const b=t.__spiritSlimeBase; if(b.maxHp) setRatioHp(t,b.maxHp); if(b.attack!=null) t.attack=b.attack; if(b.defense!=null) t.defense=b.defense; if(b.attackIntervalMs!=null){ t.attackIntervalMs=b.attackIntervalMs; t.healIntervalMs=b.attackIntervalMs; t.intervalMs=b.attackIntervalMs; } t.spiritSlimeModifier=ZERO; }
function playerBonus(system,data){ const p=system.scene.playerData,ratio=data.playerBonusRatio||0,oldMax=Math.max(1,p.maxHp||1),hpRatio=Math.max(0,Math.min(1,(p.hp||0)/oldMax)); p.skillDamageBonuses??={}; p.maxHpBonuses??={}; p.defenseBonuses??={}; p.skillDamageBonuses[SOURCE]=ratio; p.maxHpBonuses[SOURCE]=Math.round((p.baseMaxHp||p.maxHp||1)*ratio); p.defenseBonuses[SOURCE]=Math.round((p.baseDefense||0)*ratio); p.maxHp=(p.baseMaxHp||p.maxHp||1)+Object.values(p.maxHpBonuses).reduce((a,b)=>a+(Number(b)||0),0); p.defense=(p.baseDefense||0)+Object.values(p.defenseBonuses).reduce((a,b)=>a+(Number(b)||0),0); p.hp=Math.max(p.hp>0?1:0,Math.min(p.maxHp,Math.round(p.maxHp*hpRatio))); }
function clearPlayer(system){ const p=system.scene.playerData; const oldMax=Math.max(1,p.maxHp||1),r=Math.max(0,Math.min(1,(p.hp||0)/oldMax)); delete p.skillDamageBonuses?.[SOURCE]; delete p.maxHpBonuses?.[SOURCE]; delete p.defenseBonuses?.[SOURCE]; p.maxHp=(p.baseMaxHp||p.maxHp||1)+Object.values(p.maxHpBonuses||{}).reduce((a,b)=>a+(Number(b)||0),0); p.defense=(p.baseDefense||0)+Object.values(p.defenseBonuses||{}).reduce((a,b)=>a+(Number(b)||0),0); p.hp=Math.max(p.hp>0?1:0,Math.min(p.maxHp,Math.round(p.maxHp*r))); }
function createRuntime(system){ const scene=system.scene, state=system.passiveState.spiritSlime??={attached:new Set(),mode:null,visuals:[],projectiles:new Set(),nextShotAt:0,cleaned:false}; const destroyVisuals=()=>{state.visuals.forEach(v=>v.destroy?.()); state.visuals=[];}; const cancelShots=()=>{state.projectiles.forEach(p=>{p.tween?.remove?.();p.visual?.destroy?.();});state.projectiles.clear();}; const makeVisual=(x,y,r=18)=>scene.add?.circle?.(x,y,r,0x78e6b0,.55)?.setStrokeStyle?.(2,0xd8ffef,.8)?.setDepth?.(151)||{x,y,destroy(){},setPosition(x,y){this.x=x;this.y=y;return this;}}; const refresh=()=>{ if(state.cleaned) return; const data=dataFor(system), targets=summonList(scene), max=data.attachCount||1, chosen=targets.slice(0,max); const old=[...state.attached]; old.filter(t=>!chosen.includes(t)).forEach(clearTarget); state.attached=new Set(chosen); if(chosen.length){ clearPlayer(system); state.mode='attached'; cancelShots(); chosen.forEach(t=>applyTarget(t,modFrom(data))); } else { old.forEach(clearTarget); state.mode='companion'; playerBonus(system,data); if(!state.nextShotAt) state.nextShotAt=(scene.getGameplayTime?.()||0)+300; } destroyVisuals(); if(state.mode==='companion') state.visuals=[makeVisual((scene.player?.x||0)+34,(scene.player?.y||0)-38,18)]; else chosen.forEach(t=>state.visuals.push(makeVisual(t.x??t.view?.x??0,(t.visualY??t.y??t.view?.y??0)-22,12))); };
 const fire=now=>{ const data=dataFor(system); if(state.mode!=='companion'||scene.playerData.hp<=0) return; if(now<state.nextShotAt) return; const sx=(scene.player?.x||0)+34, sy=(scene.player?.y||0)-38, target=nearestEnemy(scene,sx,sy); state.nextShotAt=now+(data.mudShotIntervalMs||1500); if(!target) return; const visual=makeVisual(sx,sy,7); const shot={visual,target,tween:null}; state.projectiles.add(shot); const damage=Math.max(1,Math.round(getEffectiveAttack(scene.playerData)*(data.mudShotDamageRatio||0))); const hit=()=>{state.projectiles.delete(shot); visual.destroy?.(); if(state.mode!=='companion'||!viewportEnemy(scene,target)) return; scene.combatSystem?.damageEnemy?.(target,damage,{source:'skill',skillId:SPIRIT_SLIME_ID,damageKind:'spiritSlimeMudShot',tags:[TAGS.MAGIC,TAGS.SUMMON,TAGS.PROJECTILE,TAGS.BUILD_SUMMON],damageAlreadyResolved:true,critResolved:true,crit:false,professionApplied:true,professionMultiplier:1,baseAmountBeforeProfession:damage,allowLifeSteal:false,canTriggerArtifacts:false,noKnockback:true,damageTextColor:'#78e6b0'});}; shot.tween=scene.tweens?.add?.({targets:visual,x:target.x,y:target.y,duration:260,onComplete:hit}); if(!shot.tween) hit(); };
 const update=()=>{ const now=scene.getGameplayTime?.()||0; refresh(); if(state.mode==='companion'&&state.visuals[0]) state.visuals[0].setPosition?.((scene.player?.x||0)+34,(scene.player?.y||0)-38+Math.sin(now/250)*5); else [...state.attached].forEach((t,i)=>state.visuals[i]?.setPosition?.(t.x??t.view?.x??0,(t.visualY??t.y??t.view?.y??0)-22)); fire(now); };
 const cleanup=()=>{ if(state.cleaned) return; state.cleaned=true; clearPlayer(system); [...state.attached].forEach(clearTarget); state.attached.clear(); cancelShots(); destroyVisuals(); const i=system.passiveUpdaters.indexOf(update); if(i>=0) system.passiveUpdaters.splice(i,1); if(scene.spiritSlimeRuntime===runtime) scene.spiritSlimeRuntime=null; };
 const runtime={ getMode:()=>state.mode, getAttachedTargets:()=>[...state.attached], isAttached:t=>state.attached.has(t), getModifier:t=>state.attached.has(t)?modFrom(dataFor(system)):ZERO, refresh, cleanup, update };
 if(!system.passiveUpdaters.includes(update)) system.passiveUpdaters.push(update); scene.spiritSlimeRuntime=runtime; refresh(); return runtime; }
export function configureSpiritSlimeSkill(){}
export const SpiritSlimeSkill={ runtimeBind:true, bind(system){ const rt=system.scene.spiritSlimeRuntime||createRuntime(system); return ()=>rt.cleanup(); }, cleanup(system){ system.scene.spiritSlimeRuntime?.cleanup?.(); } };
