import { TAGS } from '../../config/tags.js';

const PhaserRef=globalThis.Phaser||{Scenes:{Events:{}},Math:{Distance:{Between:(x1,y1,x2,y2)=>Math.hypot(x2-x1,y2-y1)}}};
const SHUTDOWN_EVENT=PhaserRef.Scenes?.Events?.SHUTDOWN||'shutdown';
const POST_UPDATE_EVENT=PhaserRef.Scenes?.Events?.POST_UPDATE||'postupdate';
export const SPIRIT_BIRD_ID='spirit_bird';
export const SPIRIT_BIRD_HP_RATIOS=[.10,.11,.12,.13,.14,.15,.16,.18,.20];
export const SPIRIT_BIRD_DEFENSE_RATIOS=[.10,.11,.12,.13,.14,.15,.16,.18,.20];
export const SPIRIT_BIRD_HEAL_RATIOS=[.018,.020,.022,.025,.028,.031,.034,.036,.038];
export const SPIRIT_BIRD_HEAL_MULTIPLIERS=[1,1,1.3,1.3,1.3,1.3,1.3,1.3,1.3];
export const SPIRIT_BIRD_INTERVALS=[6000,5800,5600,5400,5200,4800,4600,4400,4200];
const REVIVE_MS=8000, VISUAL_OFFSET_Y=-100;
export const SPIRIT_BIRD_FOLLOW_DISTANCE=70;
export const SPIRIT_BIRD_CATCHUP_SPEED=260;
const idx=level=>Math.max(0,Math.min(8,(level||1)-1));
export const spiritBirdStatsForLevel=(level,playerData={})=>({
  hpRatio:SPIRIT_BIRD_HP_RATIOS[idx(level)],
  defenseRatio:SPIRIT_BIRD_DEFENSE_RATIOS[idx(level)],
  maxHp:Math.max(1,Math.round((Number(playerData.baseMaxHp)||Number(playerData.maxHp)||1)*SPIRIT_BIRD_HP_RATIOS[idx(level)])),
  defense:Math.max(0,Math.round((Number(playerData.baseDefense)||0)*SPIRIT_BIRD_DEFENSE_RATIOS[idx(level)])),
  healRatio:SPIRIT_BIRD_HEAL_RATIOS[idx(level)],
  healMultiplier:SPIRIT_BIRD_HEAL_MULTIPLIERS[idx(level)],
  intervalMs:SPIRIT_BIRD_INTERVALS[idx(level)],
  groupHeal:level>=9
});
const alive=b=>!!b&&!b.destroyed&&b.hp>0;
const stateOf=system=>system.passiveState.spiritBird??={ bird:null, fxs:new Set(), updater:null, postUpdater:null, off:null, cleaning:false, reviveAt:0, lastLevel:0 };
function destroyFx(state,fx){ state.fxs.delete(fx); fx?.destroy?.(); }
function renderCoords(b){ return {x:b.x, y:Math.round(b.visualY)}; }
function syncBar(b){ if(!b?.hpBarBg) return; const r=renderCoords(b); b.hpBarBg.setPosition?.(r.x,r.y-28); b.hpBar?.setPosition?.(r.x-20,r.y-28); b.hpBar?.setScale?.(Math.max(0,b.hp)/Math.max(1,b.maxHp),1); }
function setVisual(b){ b.visualY=b.y+VISUAL_OFFSET_Y; const r=renderCoords(b); b.view?.setPosition?.(r.x,r.y); syncBar(b); }
function stableGroundY(s,p){ const gy=Number(p?.groundY); if(Number.isFinite(gy)) return gy; const top=Number(s?.balance?.groundTopY), h=Number(p?.height); if(Number.isFinite(top)&&Number.isFinite(h)) return top-h/2; return Number(p?.y)||0; }
function destroyBird(b){ if(!b||b.destroyed) return; b.destroyed=true; b.view?.destroy?.(); b.hpBarBg?.destroy?.(); b.hpBar?.destroy?.(); }
function makeBird(system,level,x=null){ const s=system.scene,p=s.player,stats=spiritBirdStatsForLevel(level,s.playerData); const bx=x??(p.x-SPIRIT_BIRD_FOLLOW_DISTANCE), by=stableGroundY(s,p), renderY=Math.round(by+VISUAL_OFFSET_Y); const view=s.add?.container?.(bx,renderY)?.setDepth?.(146) || {x:bx,y:renderY,active:true,destroy(){this.active=false;},setPosition(x,y){this.x=x;this.y=y;return this;},add(){return this;}}; const body=s.add?.ellipse?.(0,0,34,22,0xf8fafc,.92)?.setStrokeStyle?.(2,0xdff7ff,.9); const l=s.add?.ellipse?.(-22,2,26,10,0xffffff,.62); const r=s.add?.ellipse?.(22,2,26,10,0xffffff,.62); view.add?.([l,body,r].filter(Boolean)); const hpBarBg=s.add?.rectangle?.(bx,renderY-28,44,7,0x111827,.85)?.setDepth?.(147); const hpBar=s.add?.rectangle?.(bx-20,renderY-28,40,5,0xbbf7d0,.95)?.setOrigin?.(0,.5)?.setDepth?.(148); const b={type:'spirit_bird',skillId:SPIRIT_BIRD_ID,level,x:bx,y:by,visualY:by+VISUAL_OFFSET_Y,view,hpBarBg,hpBar,baseMaxHp:stats.maxHp,baseDefense:stats.defense,baseHealIntervalMs:stats.intervalMs,maxHp:stats.maxHp,hp:stats.maxHp,defense:stats.defense,nextHealAt:(s.getGameplayTime?.()||0)+stats.intervalMs,lastMoveAt:(s.getGameplayTime?.()||0),destroyed:false,isAlive(){return alive(this);},get attackVisualY(){return this.visualY;}, takeDamage(amount,meta={}){return damageBird(system,this,amount,meta);}, heal(amount,meta={}){return healBird(system,this,amount,meta);}}; view.spiritBird=b; setVisual(b); return b; }
function damageBird(system,b,raw){ if(!alive(b)) return 0; const mod=system.scene.spiritSlimeRuntime?.getModifier?.(b)||{}; const before=b.hp, baseDamage=Math.max(1,Math.round((Number(raw)||0)-b.defense)), damage=Math.max(1,Math.round(baseDamage*(1-(mod.damageReduction||0)))); b.hp=Math.max(0,b.hp-damage); const actual=before-b.hp; if(actual>0) system.scene.floatText?.(b.x,b.visualY-40,`-${actual}`,'#ff7777'); syncBar(b); if(b.hp<=0) killBird(system,b,'death'); return actual; }
function healBird(system,b,amount){ if(!alive(b)) return 0; const mod=system.scene.spiritSlimeRuntime?.getModifier?.(b)||{}; const before=b.hp; b.hp=Math.min(b.maxHp,b.hp+Math.max(0,Math.round((Number(amount)||0)*(1+(mod.healingReceivedBonus||0))))); const actual=b.hp-before; syncBar(b); if(actual>0) system.scene.floatText?.(b.x,b.visualY-40,`+${actual}`,'#7dff8a'); return actual; }
function killBird(system,b,reason='death'){ const state=stateOf(system); if(!b||state.bird!==b) return; const natural=reason==='death'&&!state.cleaning; destroyBird(b); state.bird=null; system.scene.spiritBirdRuntime=null; if(natural&&system.scene.playerData.hp>0){ const now=system.scene.getGameplayTime?.()||0; state.reviveAt=now+REVIVE_MS; system.cooldowns.set(SPIRIT_BIRD_ID,state.reviveAt); } }
function playerTarget(system){ const s=system.scene,p=s.playerData; return {type:'player',get x(){return s.player.x;},get y(){return s.player.y;},get hp(){return p.hp;},get maxHp(){return p.maxHp;},isAlive:()=>p.hp>0,heal(amount,meta={}){ const actual=s.healPlayer?.(amount,'spirit_bird',meta)||0; if(actual>0) s.floatText?.(s.player.x,s.player.y-100,`+${actual}`,'#7dff8a'); return actual;}}; }
function healingTargets(system){ const out=[playerTarget(system)]; (system.scene.skillSystem?.passiveState?.spiritWolves?.wolves||[]).filter(w=>w?.isAlive?.()).forEach(w=>out.push(w)); const king=system.scene.poisonKingRuntime?.getHealingTarget?.(); if(king?.isAlive?.()) out.push(king); return out.filter(t=>t?.isAlive?.()&&t.type!=='spirit_bird'&&Number(t.maxHp)>0); }
function healAmount(system,level){ const s=system.scene,st=spiritBirdStatsForLevel(level,s.playerData); const b=stateOf(system).bird, mod=s.spiritSlimeRuntime?.getModifier?.(b)||{}; return Math.max(1,Math.round(Math.round((Number(s.playerData.maxHp)||1)*st.healRatio)*st.healMultiplier*(1+(mod.powerBonus||0)))); }
function healOne(system,target,amount,bird){ const actual=target.heal?.(amount,{source:'spirit_bird',skillId:SPIRIT_BIRD_ID})||0; if(actual>0){ const s=system.scene, state=stateOf(system); const fx=s.add?.line?.(0,0,bird.x,bird.visualY,target.x,target.y-40,0xbbf7d0,.65)?.setOrigin?.(0)?.setDepth?.(150); if(fx){ state.fxs.add(fx); s.tweens?.add?.({targets:fx,alpha:0,duration:260,onComplete:()=>destroyFx(state,fx)}); } } return actual; }
function doHeal(system,b){ const level=system.getLevel(SPIRIT_BIRD_ID), targets=healingTargets(system), amount=healAmount(system,level); if(level>=9) targets.forEach(t=>healOne(system,t,amount,b)); else { const t=targets.sort((a,b)=>((a.hp/a.maxHp)-(b.hp/b.maxHp))||(a.type==='player'?-1:b.type==='player'?1:0))[0]; if(t) healOne(system,t,amount,b); } }
function updateStats(system,b){ const level=system.getLevel(SPIRIT_BIRD_ID); if(!alive(b)||b.level===level) return; const ratio=b.hp/Math.max(1,b.maxHp), st=spiritBirdStatsForLevel(level,system.scene.playerData), mod=system.scene.spiritSlimeRuntime?.getModifier?.(b)||{}; b.level=level; b.baseMaxHp=st.maxHp; b.baseDefense=st.defense; b.baseHealIntervalMs=st.intervalMs; b.maxHp=Math.max(1,Math.round(st.maxHp*(1+(mod.maxHpBonus||0)))); b.defense=st.defense; b.hp=Math.max(1,Math.min(b.maxHp,Math.round(b.maxHp*ratio))); syncBar(b); }
function moveBirdAfterPhysics(system){ const s=system.scene, b=stateOf(system).bird; if(s.isGameplayPaused?.()||!alive(b)) return; const now=s.getGameplayTime?.()||0; const deltaMs=Math.max(0,Math.min(100,now-(Number.isFinite(b.lastMoveAt)?b.lastMoveAt:now))); b.lastMoveAt=now; const targetX=s.player.x-SPIRIT_BIRD_FOLLOW_DISTANCE; if(b.x<targetX) b.x=Math.min(targetX,b.x+SPIRIT_BIRD_CATCHUP_SPEED*(deltaMs/1000)); setVisual(b); }
function cleanup(system){ const state=stateOf(system); state.cleaning=true; if(state.postUpdater){ system.scene.events?.off?.(POST_UPDATE_EVENT,state.postUpdater); state.postUpdater=null; } state.fxs.forEach(fx=>fx.destroy?.()); state.fxs.clear(); destroyBird(state.bird); state.bird=null; state.reviveAt=0; system.cooldowns.delete(SPIRIT_BIRD_ID); if(system.scene.spiritBirdRuntime) system.scene.spiritBirdRuntime=null; state.cleaning=false; }
export const SpiritBirdSkill={ runtimeBind:true, shiftTimers(system,pausedDuration,pausedAt){ const state=stateOf(system); const b=state.bird; if(b?.nextHealAt>pausedAt) b.nextHealAt+=pausedDuration; if(Number.isFinite(b?.lastMoveAt)) b.lastMoveAt+=pausedDuration; if(state.reviveAt>pausedAt) state.reviveAt+=pausedDuration; }, canCast(system){ return !stateOf(system).bird; }, cast(system,cfg,data,level){ const state=stateOf(system); if(state.bird) return {failed:true}; state.bird=makeBird(system,level); state.reviveAt=0; system.cooldowns.delete(SPIRIT_BIRD_ID); bindRuntime(system); return {summoned:1,noCooldown:true}; }, bind(system){ const state=stateOf(system); if(state.updater) return state.off||(()=>{}); const update=()=>{ const s=system.scene, now=s.getGameplayTime?.()||0, level=system.getLevel(SPIRIT_BIRD_ID); if(s.playerData.hp<=0||level<=0) return; if(!state.bird&&state.reviveAt&&now>=state.reviveAt){ state.bird=makeBird(system,level); state.reviveAt=0; system.cooldowns.delete(SPIRIT_BIRD_ID); bindRuntime(system); } const b=state.bird; if(!alive(b)) return; updateStats(system,b); if(now>=b.nextHealAt){ doHeal(system,b); b.nextHealAt=now+Math.max(1,Math.round(spiritBirdStatsForLevel(level,s.playerData).intervalMs/(1+((s.spiritSlimeRuntime?.getModifier?.(b)||{}).actionSpeedBonus||0)))); } }; const postUpdate=()=>moveBirdAfterPhysics(system); const onShutdown=()=>state.off?.(); state.updater=update; state.postUpdater=postUpdate; system.passiveUpdaters.push(update); system.scene.events?.on?.(POST_UPDATE_EVENT,postUpdate); system.scene.events?.once?.(SHUTDOWN_EVENT,onShutdown); state.off=()=>{ system.scene.events?.off?.(SHUTDOWN_EVENT,onShutdown); if(state.postUpdater) system.scene.events?.off?.(POST_UPDATE_EVENT,state.postUpdater); state.postUpdater=null; const i=system.passiveUpdaters.indexOf(update); if(i>=0) system.passiveUpdaters.splice(i,1); cleanup(system); state.updater=null; state.off=null; }; bindRuntime(system); return state.off; }, cleanup };
function bindRuntime(system){ const state=stateOf(system), s=system.scene; s.spiritBirdRuntime={ get:()=>state.bird, getAttackTarget:()=>{ const b=state.bird; if(!alive(b)) return null; return b; }, getHealingTarget:()=>null, cleanup:()=>cleanup(system) }; }
