import { TAGS } from '../../config/tags.js';
import { getEffectiveAttack } from '../../config/balance.js';

export const SPIRIT_SLIME_ID='spirit_slime';
const SOURCE='spirit_slime';
const MODE_INACTIVE='inactive',MODE_COMPANION='companion',MODE_ATTACHED='attached';
const ZERO=Object.freeze({powerBonus:0,maxHpBonus:0,damageReduction:0,actionSpeedBonus:0,healingReceivedBonus:0});
const alive=t=>!!t&&!t.destroyed&&!t.dead&&t.hp>0&&(t.isAlive?.()??true);
const objPos=t=>({x:t?.view?.x??t?.x??0,y:t?.type==='spirit_bird'?(t.visualY??t.y??0):(t?.view?.y??t?.y??0)});
function hpRatioApply(o,newMax){const old=Math.max(1,Number(o.maxHp)||1),was=(Number(o.hp)||0)>0,ratio=(Number(o.hp)||0)/old;o.maxHp=Math.max(1,Math.round(newMax));o.hp=was?Math.max(1,Math.min(o.maxHp,Math.round(o.maxHp*ratio))):0;}
function dataFor(system,level=system.getLevel(SPIRIT_SLIME_ID)){return system.getData(SPIRIT_SLIME_ID,level)||{};}
function modFor(data){return Object.freeze({powerBonus:data.summonPowerBonus||0,maxHpBonus:data.summonMaxHpBonus||0,damageReduction:data.summonDamageReduction||0,actionSpeedBonus:data.summonActionSpeedBonus||0,healingReceivedBonus:data.summonHealingReceivedBonus||0});}
function targetId(t){if(t?.type==='poison_king')return'poison_king';if(t?.type==='spirit_bird')return'spirit_bird';if(t?.type==='spiritWolf')return`spirit_wolf_${t.index??0}`;return'unknown';}
function officialSummons(scene){const out=[],king=scene.poisonKingRuntime?.get?.();if(alive(king))out.push(king);(scene.skillSystem?.passiveState?.spiritWolves?.wolves||[]).filter(alive).sort((a,b)=>(a.index??0)-(b.index??0)).forEach(w=>out.push(w));const bird=scene.spiritBirdRuntime?.get?.();if(alive(bird))out.push(bird);return out;}
function validEnemy(scene,e){return scene.targeting?.valid?.(e)&&scene.targeting?.isEnemyFullyInsideViewport?.(e)!==false&&e.hp>0;}
function nearestEnemy(scene,x,y){return(scene.targeting?.all?.()||[]).filter(e=>validEnemy(scene,e)).sort((a,b)=>Math.hypot(a.x-x,a.y-y)-Math.hypot(b.x-x,b.y-y))[0]||null;}
function ensureBaseMax(t){if(!t)return 0;if(t.type==='poison_king')return Number(t.baseMaxHp)||Number(t.maxHp)||1;if(!Number.isFinite(t.baseMaxHp))t.baseMaxHp=Number(t.maxHp)||1;return t.baseMaxHp;}
function applySummonHp(t,mod){const base=ensureBaseMax(t);if(base>0)hpRatioApply(t,base*(1+(mod?.maxHpBonus||0)));}
function clearSummonHp(t){const base=ensureBaseMax(t);if(base>0)hpRatioApply(t,base);}
function recomputePlayerMaxHp(p){const old=Math.max(1,Number(p.maxHp)||1),was=(Number(p.hp)||0)>0,ratio=(Number(p.hp)||0)/old;p.maxHp=Math.max(1,Math.round((Number(p.baseMaxHp)||old)+Object.values(p.maxHpBonuses||{}).reduce((a,b)=>a+(Number(b)||0),0)));p.hp=was?Math.max(1,Math.min(p.maxHp,Math.round(p.maxHp*ratio))):0;}
function defenseBasis(p){return Math.max(0,(Number(p.defense)||0)+Object.entries(p.defenseBonuses||{}).filter(([key])=>key!==SOURCE).reduce((sum,[,value])=>sum+(Number(value)||0),0));}
function applyPlayer(system,data){const p=system.scene.playerData,ratio=data.playerBonusRatio||0;p.attackBonuses??={};p.maxHpBonuses??={};p.defenseBonuses??={};p.attackBonuses[SOURCE]=Math.round((Number(p.baseAttack)||Number(p.attack)||0)*ratio);p.maxHpBonuses[SOURCE]=Math.round((Number(p.baseMaxHp)||Number(p.maxHp)||1)*ratio);p.defenseBonuses[SOURCE]=ratio>0?Math.max(1,Math.round(defenseBasis(p)*ratio)):0;recomputePlayerMaxHp(p);}
function clearPlayer(system){const p=system.scene.playerData;if(p.attackBonuses)delete p.attackBonuses[SOURCE];if(p.maxHpBonuses)delete p.maxHpBonuses[SOURCE];if(p.defenseBonuses)delete p.defenseBonuses[SOURCE];recomputePlayerMaxHp(p);}
function makeState(){return{active:false,mode:MODE_INACTIVE,level:0,attached:new Set(),visuals:new Map(),companionVisual:null,projectiles:new Set(),nextShotAt:0,lastAttachmentKey:'',playerBonusApplied:false,updater:null,currentModifier:ZERO};}
function createRuntime(system){const scene=system.scene,state=system.passiveState.spiritSlime??=makeState();const makeVisual=(x,y,r=14)=>scene.add?.circle?.(x,y,r,0x78e6b0,.55)?.setStrokeStyle?.(2,0xd8ffef,.85)?.setDepth?.(151)||{x,y,active:true,destroy(){this.active=false;},setPosition(x,y){this.x=x;this.y=y;return this;}};
 const cancelShots=()=>{state.projectiles.forEach(p=>{p.tween?.remove?.();p.visual?.destroy?.();});state.projectiles.clear();};
 const destroyCompanion=()=>{state.companionVisual?.destroy?.();state.companionVisual=null;};
 const destroyAttachedVisual=t=>{state.visuals.get(t)?.destroy?.();state.visuals.delete(t);};
 const deactivate=()=>{cancelShots();destroyCompanion();state.visuals.forEach(v=>v.destroy?.());state.visuals.clear();if(state.playerBonusApplied){clearPlayer(system);state.playerBonusApplied=false;}state.attached.forEach(clearSummonHp);state.attached.clear();state.active=false;state.mode=MODE_INACTIVE;state.level=0;state.lastAttachmentKey='';state.currentModifier=ZERO;state.nextShotAt=0;};
 const refreshAssignments=()=>{const level=system.getLevel(SPIRIT_SLIME_ID);if(level<=0){if(state.active||state.mode!==MODE_INACTIVE)deactivate();return;}const data=dataFor(system,level),all=officialSummons(scene),chosen=all.slice(0,data.attachCount||1),companionKey=`${Number(scene.playerData.baseAttack)||Number(scene.playerData.attack)||0}:${Number(scene.playerData.baseMaxHp)||Number(scene.playerData.maxHp)||1}:${defenseBasis(scene.playerData)}`,key=chosen.length?`${level}:${chosen.map(targetId).join(',')}`:`${level}:companion:${companionKey}`;if(state.active&&key===state.lastAttachmentKey)return;const wasMode=state.mode,old=[...state.attached];state.active=true;state.level=level;state.currentModifier=modFor(data);state.lastAttachmentKey=key;state.attached=new Set(chosen);
  old.filter(t=>!state.attached.has(t)).forEach(t=>{clearSummonHp(t);destroyAttachedVisual(t);});
  if(chosen.length){if(state.playerBonusApplied){clearPlayer(system);state.playerBonusApplied=false;}destroyCompanion();if(wasMode!==MODE_ATTACHED)cancelShots();state.mode=MODE_ATTACHED;state.nextShotAt=0;chosen.forEach(t=>{applySummonHp(t,state.currentModifier);if(!state.visuals.has(t)){const p=objPos(t);state.visuals.set(t,makeVisual(p.x,p.y-22,12));}});}
  else{old.forEach(clearSummonHp);state.visuals.forEach(v=>v.destroy?.());state.visuals.clear();state.mode=MODE_COMPANION;applyPlayer(system,data);state.playerBonusApplied=true;if(!state.companionVisual){const p=scene.player||{x:0,y:0};state.companionVisual=makeVisual(p.x+34,p.y-38,18);}if(wasMode!==MODE_COMPANION)state.nextShotAt=(scene.getGameplayTime?.()||0)+300;}};
 const syncVisualPositions=()=>{const now=scene.getGameplayTime?.()||0;if(state.mode===MODE_COMPANION&&state.companionVisual){const p=scene.player||{x:0,y:0};state.companionVisual.setPosition?.(p.x+34,p.y-38+Math.sin(now/250)*5);}if(state.mode===MODE_ATTACHED){[...state.visuals.entries()].forEach(([t,v])=>{if(!state.attached.has(t)||!alive(t))return;const p=objPos(t);v.setPosition?.(p.x,p.y-22+Math.sin(now/250)*3);});}};
 const updateMudShot=()=>{const now=scene.getGameplayTime?.()||0;if(state.mode!==MODE_COMPANION||scene.playerData.hp<=0||now<state.nextShotAt)return;const data=dataFor(system,state.level),p=scene.player||{x:0,y:0},sx=p.x+34,sy=p.y-38,target=nearestEnemy(scene,sx,sy);state.nextShotAt=now+(data.mudShotIntervalMs||1500);if(!target)return;const visual=makeVisual(sx,sy,7),shot={visual,target,tween:null};state.projectiles.add(shot);const damage=Math.max(1,Math.round(getEffectiveAttack(scene.playerData)*(data.mudShotDamageRatio||0)));const hit=()=>{state.projectiles.delete(shot);visual.destroy?.();if(state.mode!==MODE_COMPANION||!validEnemy(scene,target))return;scene.combatSystem?.damageEnemy?.(target,damage,{source:'skill',skillId:SPIRIT_SLIME_ID,damageKind:'spiritSlimeMudShot',tags:[TAGS.MAGIC,TAGS.SUMMON,TAGS.PROJECTILE,TAGS.BUILD_SUMMON],damageAlreadyResolved:true,critResolved:true,crit:false,professionApplied:true,professionMultiplier:1,baseAmountBeforeProfession:damage,allowLifeSteal:false,canTriggerArtifacts:false,noKnockback:true,damageTextColor:'#78e6b0'});};shot.tween=scene.tweens?.add?.({targets:visual,x:target.x,y:target.y,duration:260,onComplete:hit});if(!shot.tween)hit();};
 const update=()=>{refreshAssignments();if(!state.active)return;syncVisualPositions();updateMudShot();};
 let runtime=null;const cleanup=()=>deactivate();const dispose=()=>{deactivate();if(state.updater){const index=system.passiveUpdaters.indexOf(state.updater);if(index>=0)system.passiveUpdaters.splice(index,1);state.updater=null;}if(scene.spiritSlimeRuntime===runtime)scene.spiritSlimeRuntime=null;};runtime={getMode:()=>state.mode,getAttachedTargets:()=>[...state.attached],isAttached:t=>state.attached.has(t),getModifier:t=>state.attached.has(t)?state.currentModifier:ZERO,refresh:refreshAssignments,cleanup,dispose,update,_state:state};scene.spiritSlimeRuntime=runtime;if(!state.updater){state.updater=update;system.passiveUpdaters.push(update);}return runtime;}
export const SpiritSlimeSkill={runtimeBind:true,bind(system){return createRuntime(system).dispose;},cleanup(system){system.scene.spiritSlimeRuntime?.dispose?.();}};
