import { TAGS } from '../../config/tags.js';
import { SKILLS } from '../../config/skills.js';

const PhaserRef=globalThis.Phaser||{Math:{Distance:{Between:(x1,y1,x2,y2)=>Math.hypot(x2-x1,y2-y1)}}};
export const SPIRIT_WOLVES_ID='spirit_wolves';
const COOLDOWN_MS=8000, MAX_WOLVES=2, ATTACK_INTERVAL_MS=900, ATTACK_RANGE=58, MOVE_SPEED=170, LEASH=520, SNAP=760;
export const inheritRatioForLevel=level=>[.20,.21,.22,.23,.24,.25,.26,.28,.30][Math.max(0,Math.min(8,(level||1)-1))];
export const basePlayerStats=p=>({ attack:Number(p?.baseAttack??10), maxHp:Number(p?.baseMaxHp??500), defense:Number(p?.baseDefense??0) });

const alive=w=>!!w&&!w.destroyed&&w.hp>0&&w.view?.active!==false;
const st=s=>s.passiveState.spiritWolves??={ wolves:[], initialized:false, cleaning:false, cooldownStartedAt:0, cooldownStarts:0 };
const validEnemy=(scene,e)=>scene.targeting?.valid?.(e)&&e.hp>0;
const nearestAhead=(scene,w)=>scene.targeting?.all?.().filter(e=>validEnemy(scene,e)&&e.x>=w.x-20).sort((a,b)=>PhaserRef.Math.Distance.Between(w.x,w.y,a.x,a.y)-PhaserRef.Math.Distance.Between(w.x,w.y,b.x,b.y))[0]||null;
function destroyWolf(w,reason='cleanup'){ if(!w||w.destroyed) return; w.destroyed=true; w.target=null; w.view?.destroy?.(); w.hpBarBg?.destroy?.(); w.hpBar?.destroy?.(); w.body=null; }
function syncBar(w){ if(!w.hpBarBg)return; w.hpBarBg.setPosition?.(w.x,w.y-54); w.hpBar?.setPosition?.(w.x-22,w.y-54); w.hpBar?.setScale?.(Math.max(0,w.hp)/Math.max(1,w.maxHp),1); }
function makeWolf(system,cfg,data,level,index){ const scene=system.scene,p=scene.player,ratio=inheritRatioForLevel(level),base=basePlayerStats(scene.playerData); const x=p.x+(index===0?72:-56),y=p.y+(index===0?-18:26),scale=level>=9?1.15:1; const view=scene.add?.circle?.(x,y,22*scale,0x9fd7ff,.72)?.setStrokeStyle?.(4,0xffffff,.85)?.setDepth?.(118) || {x,y,active:true,destroy(){this.active=false;},setPosition(x,y){this.x=x;this.y=y;return this;},setScale(){return this;}}; view.setScale?.(scale); const hpBarBg=scene.add?.rectangle?.(x,y-54,48,7,0x111827,.85)?.setDepth?.(119); const hpBar=scene.add?.rectangle?.(x-22,y-54,44,5,0x7dd3fc,.95)?.setOrigin?.(0,.5)?.setDepth?.(120); const wolf={ type:'spiritWolf', skillId:SPIRIT_WOLVES_ID, level, x,y, view, hpBarBg, hpBar, body:view.body, maxHp:Math.max(1,Math.round(base.maxHp*ratio)), hp:Math.max(1,Math.round(base.maxHp*ratio)), attack:Math.max(1,Math.round(base.attack*ratio)), defense:Math.max(0,Math.round(base.defense*ratio)), ratio, target:null, nextAttackAt:0, knockbackUntil:0, isAlive(){return alive(this);}, takeDamage(amount,meta={}){ damageWolf(system,this,amount,meta); } }; view.spiritWolf=wolf; return wolf; }
function damageWolf(system,w,raw,meta={}){ if(!alive(w)) return 0; const before=w.hp; const damage=Math.max(1,Math.round((Number(raw)||0)-w.defense)); w.hp=Math.max(0,w.hp-damage); system.scene.floatText?.(w.x,w.y-72,`-${before-w.hp}`,'#bae6fd'); syncBar(w); if(meta.enemy&&meta.attackType) applyWolfKnockback(system.scene,w,meta); if(w.hp<=0) killWolf(system,w,'death'); return before-w.hp; }
function applyWolfKnockback(scene,w,meta={}){ const enemy=meta.enemy,dir=Math.sign(w.x-(enemy?.x??w.x))||1,dist=enemy?.isBoss?10:(enemy?.isElite?18:34); w.knockbackUntil=(scene.getGameplayTime?.()||0)+260; w.x+=dir*dist; w.view?.setPosition?.(w.x,w.y); syncBar(w); }
function killWolf(system,w,reason='death'){ if(!w||w.destroyed) return; const state=st(system); const natural=reason==='death'&&!state.cleaning; if(natural&&w.level>=6){ system.scene.add?.circle?.(w.x,w.y,120,0x7dd3fc,.16)?.setStrokeStyle?.(4,0xffffff,.8)?.setDepth?.(130); system.scene.targeting?.all?.().filter(e=>validEnemy(system.scene,e)&&PhaserRef.Math.Distance.Between(e.x,e.y,w.x,w.y)<=120).forEach(e=>system.scene.combatSystem.damageEnemy(e,Math.max(1,Math.round(w.attack*.8)),{source:'skill',skillId:SPIRIT_WOLVES_ID,damageKind:'summonDeathBurst',tags:[TAGS.SUMMON,'area'],allowLifeSteal:false,noKnockback:true,professionApplied:true,professionMultiplier:1,baseAmountBeforeProfession:Math.max(1,Math.round(w.attack*.8))})); }
  destroyWolf(w,reason); state.wolves=state.wolves.filter(x=>alive(x)); if(natural&&state.wolves.length===0) startCooldown(system); }
function startCooldown(system){ const state=st(system); const now=system.scene.getGameplayTime?.()||0; if(system.cooldowns.get(SPIRIT_WOLVES_ID)>now) return; state.cooldownStartedAt=now; state.cooldownStarts+=1; system.cooldowns.set(SPIRIT_WOLVES_ID,now+COOLDOWN_MS); }
function attack(system,w,target){ const cfg=SKILLS[SPIRIT_WOLVES_ID]; const level=w.level,damage=w.attack; const scene=system.scene; if(!validEnemy(scene,target)) return; scene.combatSystem.damageEnemy(target,damage,{source:'skill',skillId:SPIRIT_WOLVES_ID,damageKind:'summonMelee',tags:[TAGS.SUMMON,'physical',TAGS.MELEE],allowLifeSteal:false,noKnockback:true,canTriggerArtifacts:false,critResolved:true,crit:false,professionApplied:true,professionMultiplier:1,baseAmountBeforeProfession:damage,summon:true}); if(level>=3){ scene.targeting.all().filter(e=>e!==target&&validEnemy(scene,e)&&PhaserRef.Math.Distance.Between(e.x,e.y,target.x,target.y)<=90).forEach(e=>scene.combatSystem.damageEnemy(e,Math.max(1,Math.round(damage*.35)),{source:'skill',skillId:SPIRIT_WOLVES_ID,damageKind:'summonSplash',tags:[TAGS.SUMMON,'physical','area'],allowLifeSteal:false,noKnockback:true,canTriggerArtifacts:false,critResolved:true,crit:false,professionApplied:true,professionMultiplier:1,baseAmountBeforeProfession:Math.max(1,Math.round(damage*.35)),summon:true})); }
}
function updateWolf(system,w){ const scene=system.scene,now=scene.getGameplayTime?.()||0,p=scene.player; if(!alive(w)||scene.playerData.hp<=0) return killWolf(system,w,'cleanup'); if(PhaserRef.Math.Distance.Between(w.x,w.y,p.x,p.y)>SNAP){ w.x=p.x+(Math.random()<.5?70:-60); w.y=p.y; } if(now<w.knockbackUntil){ w.view?.setPosition?.(w.x,w.y); syncBar(w); return; } if(!validEnemy(scene,w.target)) w.target=nearestAhead(scene,w); const t=w.target; if(t){ const dx=t.x-w.x,dy=t.y-w.y,d=Math.hypot(dx,dy); if(d>ATTACK_RANGE){ const step=Math.min(MOVE_SPEED/60,d); w.x+=dx/d*step; w.y+=dy/d*step; } else if(now>=w.nextAttackAt){ w.nextAttackAt=now+ATTACK_INTERVAL_MS; attack(system,w,t); } } const pd=PhaserRef.Math.Distance.Between(w.x,w.y,p.x,p.y); if(pd>LEASH){ w.x+=(p.x-w.x)*.08; w.y+=(p.y-w.y)*.08; } w.view?.setPosition?.(w.x,w.y); syncBar(w); }
function cleanup(system){ const state=st(system); state.cleaning=true; state.wolves.forEach(w=>destroyWolf(w,'cleanup')); state.wolves=[]; state.initialized=false; system.cooldowns.delete(SPIRIT_WOLVES_ID); state.cleaning=false; }
export const SpiritWolvesSkill={ canCast(system){ const state=st(system),now=system.scene.getGameplayTime?.()||0; state.wolves=state.wolves.filter(alive); if(!state.initialized){ state.initialized=true; system.cooldowns.set(SPIRIT_WOLVES_ID,now+COOLDOWN_MS); return {failed:true}; } return state.wolves.length===0; }, cast(system,cfg,data,level){ const state=st(system); state.wolves=state.wolves.filter(alive); if(state.wolves.length>0) return {failed:true}; state.wolves=[0,1].map(i=>makeWolf(system,cfg,data,level,i)); return {summoned:state.wolves.length}; }, bind(system){ const update=()=>{ const state=st(system); state.wolves=state.wolves.filter(alive); state.wolves.forEach(w=>updateWolf(system,w)); }; system.passiveUpdaters.push(update); const off=system.scene.eventBus?.on?.('PLAYER_DIED',()=>cleanup(system)); return ()=>{ off?.(); cleanup(system); }; }, cleanup };
