const PhaserRef=globalThis.Phaser||{Math:{Distance:{Between:(x1,y1,x2,y2)=>Math.hypot(x2-x1,y2-y1)}}};
import { TAGS } from '../../config/tags.js';
import { SKILLS } from '../../config/skills.js';
import { CombatEvents } from '../../core/CombatEvents.js';

export function configureSuperheroFlowSkills(){
  const ss=[[.06,.04,0,0],[.08,.05,0,0],[.10,.07,.05,2000],[.12,.08,.05,2000],[.14,.10,.05,2000],[.16,.12,.08,3000],[.17,.14,.08,3000],[.19,.16,.08,3000],[.20,.18,.10,3000]].map(([moveSpeedBonus,attackSpeedBonus,highSpeedAttackSpeedBonus,graceMs],i)=>({moveSpeedBonus,attackSpeedBonus,highSpeedAttackSpeedBonus,graceMs,chargeMs:i>=2?1000:0,weaponWaitCutRatio:i>=5?.5:0,killExtendMs:i>=8?500:0,maxKillExtendMs:i>=8?2000:0,desc:`移动速度 +${Math.round(moveSpeedBonus*100)}%，常驻攻击速度 +${Math.round(attackSpeedBonus*100)}%${i>=2?`；连续实际前进1秒进入高速状态，停止后保留${graceMs/1000}秒并额外提供${Math.round(highSpeedAttackSpeedBonus*100)}%攻击速度`:''}${i>=5?'；每次高速状态停止后下一次玩家本体真实武器攻击剩余等待缩短50%（仅一次）':''}${i>=8?'；保留阶段击杀延长0.5秒，单次高速状态最多延长2秒':''}.`}));
  const le=[18,20,22,24,26,22,24,26,28].map((damage,i)=>({damage,cooldownMs:Math.max(4200,5000-i*80),durationMs:i>=8?1800:1200,intervalMs:200,overloadIntervalMs:i>=8?150:200,manaCost:5,width:34+i*2,range:760,beamCount:i>=5?2:1,beamDamageScale:i>=5?.7:1,focusPerTick:i>=2?.1:0,maxFocus:i>=2?5:0,retargetOnKill:i>=8,killExtendMs:i>=8?300:0,maxExtendMs:i>=8?1200:0,retargetFocusLoss:i>=8?2:5,desc:`自动向前方最近敌人发射${i>=5?'两道平行':'一道'}红色贯穿光束，持续${i>=8?'1.8':'1.2'}秒，每${i>=8?'0.2秒（满焦点后0.15秒）':'0.2秒'}造成${damage}点技能伤害${i>=5?'，每道为原单道70%伤害，可分别命中同一敌人':''}${i>=2?'；连续命中锁定目标每跳使后续对其伤害+10%，最多5层/50%':''}${i>=8?'；击杀自动换前方目标、焦点减少2层，每杀延长0.3秒，最多延长1.2秒':''}.`}));
  const fb=[10,11,12,13,14,15,16,17,18].map((damage,i)=>({damage,cooldownMs:6800-i*80,durationMs:1500,intervalMs:250,manaCost:6,range:i>=2?500:400,angleDeg:i>=2?58:46,coldDurationMs:i>=2?4200:3400,slowPerStack:.04,attackSlowPerStack:.03,maxStacks:i>=8?10:8,normalFreezeStacks:i>=2?4:5,eliteFreezeStacks:i>=2?7:8,normalFreezeMs:1200,eliteFreezeMs:600,refreezeGuardMs:800,shatterDamage:i>=5?Math.round(damage*2.2):0,shatterRadius:110,deathShatterScale:i>=8?.5:0,deathShatterRadius:90,zoneDurationMs:i>=8?3000:0,zoneIntervalMs:500,bossMaxMoveSlow:.45,bossMaxAttackSlow:.75,bossBreathDamageBonus:.3,desc:`向前喷出${i>=2?'扩大后的':''}浅蓝锥形寒气，持续1.5秒，每0.25秒造成${damage}点技能伤害并叠加1层寒气；普通敌人${i>=2?4:5}层冻结1.2秒，精英${i>=2?7:8}层冻结0.6秒，Boss不会冻结${i>=5?'；冻结目标受到合法玩家本体直接伤害时碎冰，110范围造成冰系技能伤害并给周围2层寒气':''}${i>=8?'；结束后留下3秒极寒区域，每0.5秒叠1层寒气，冻结死亡产生50%小碎冰，Boss满层只受更强减速/攻速降低和冰冻吐息本体+30%伤害':''}.`}));
  SKILLS.super_speed={id:'super_speed',name:'超级速度',rarity:'COMMON',handler:'super_speed',passive:true,maxLevel:9,tags:[TAGS.SUPERPOWER,TAGS.BUILD_SUPERHERO],targetType:'passive',manaCost:0,color:0xfff066,short:'速',description:'提高移动速度与常驻攻击速度；Lv3后根据实际前进移动进入高速状态。',milestones:{3:'极速起步：连续实际移动1秒进入高速状态，停止后保留2秒并获得额外5%攻击速度。',6:'超音速反应：高速额外攻速提高至8%，停止保留3秒，并让下一次玩家本体真实武器攻击剩余等待缩短50%（每次高速一次）。',9:'神速不息：高速额外攻速提高至10%，保留阶段击杀延长0.5秒，单次最多延长2秒。'},levels:ss};
  SKILLS.laser_eyes={id:'laser_eyes',name:'镭射眼',rarity:'FINE',handler:'laser_eyes',maxLevel:9,tags:[TAGS.SUPERPOWER,TAGS.MAGIC,TAGS.SPELL,TAGS.ACTIVE_SKILL,TAGS.BUILD_SUPERHERO],targetType:'nearestAhead',manaCost:5,cooldownMs:5000,color:0xff3333,short:'镭',description:'从眼部持续发出红色贯穿光束，造成直接技能伤害，不触发普通攻击附带效果。',milestones:{3:'焦点灼穿：连续命中锁定目标时焦点提升，每层+10%后续伤害，最多5层/50%。',6:'双瞳齐射：变为两道平行光束，每道造成原单道70%伤害，覆盖宽度提高。',9:'热视线超载：持续1.8秒，满焦点后间隔缩短至0.15秒，击杀自动换目标并延长持续时间。'},levels:le};
  SKILLS.freezing_breath={id:'freezing_breath',name:'冰冻吐息',rarity:'RARE',handler:'freezing_breath',maxLevel:9,tags:[TAGS.SUPERPOWER,TAGS.ICE,TAGS.MAGIC,TAGS.SPELL,TAGS.ACTIVE_SKILL,TAGS.BUILD_SUPERHERO],targetType:'nearestAhead',manaCost:6,cooldownMs:6800,color:0x8eeaff,short:'冻',description:'向前方喷出浅蓝锥形寒气，低伤害叠加寒气并控制普通/精英敌人，Boss永不冻结。',milestones:{3:'寒潮扩散：吐息距离提高约25%，角度扩大，寒气持续更久，普通/精英冻结门槛降低。',6:'碎冰爆裂：冻结目标被合法玩家本体直接伤害命中时触发一次碎冰爆炸。',9:'绝对零度：吐息结束后留下3秒极寒区域；冻结死亡会小型碎冰；Boss满寒气只受强化减速和吐息增伤。'},levels:fb};
}

const COLD=Symbol('freezingBreathCold');
const now=s=>s.getGameplayTime?.()??0;
const valid=(s,e)=>!!e&&s.targeting?.valid?.(e)!==false&&!e.isDefeated&&(e.hp??1)>0;
const dist=(a,b)=>PhaserRef.Math.Distance.Between(a.x,a.y,b.x,b.y);
const eye=s=>({x:(s.player?.x??0)+12,y:(s.player?.y??0)-72});
const inCone=(s,e,d)=>{ const a=eye(s), dx=(e.x??0)-a.x, dy=(e.y??0)-a.y; if(dx<0||Math.hypot(dx,dy)>d.range) return false; return Math.abs(Math.atan2(dy,dx)) <= (d.angleDeg*Math.PI/180)/2; };
const cleanupVisual=v=>{ try{v?.destroy?.();}catch{} };
function ensureBonuses(p){ p.moveSpeedMultiplierBonuses??={}; p.attackSpeedMultiplierBonuses??={}; }
function syncSuperSpeed(system,state){ const p=system.scene.playerData,data=system.getData('super_speed'); ensureBonuses(p); if(!data){ delete p.moveSpeedMultiplierBonuses.super_speed; delete p.attackSpeedMultiplierBonuses.super_speed; return; } p.moveSpeedMultiplierBonuses.super_speed=data.moveSpeedBonus||0; p.attackSpeedMultiplierBonuses.super_speed=(data.attackSpeedBonus||0)+(state.highSpeed?(data.highSpeedAttackSpeedBonus||0):0); }
export const SuperSpeedSkill={ bind(system){ const s=system.scene,p=s.playerData; let lastX=s.player?.x??0,lastAt=now(s),movingMs=0,graceUntil=0,extended=0,cutReady=false,wasMoving=false; const state={highSpeed:false}; syncSuperSpeed(system,state); const updater=()=>{ const data=system.getData('super_speed'), t=now(s); if(!data||p.hp<=0){ state.highSpeed=false; syncSuperSpeed(system,state); return; } const x=s.player?.x??lastX, dt=Math.max(0,t-lastAt), moving=x>lastX+0.5; if(moving){ movingMs+=dt; if((data.chargeMs||0)>0&&movingMs>=data.chargeMs&&!state.highSpeed){ state.highSpeed=true; extended=0; cutReady=false; } graceUntil=t+(data.graceMs||0); } else { if(wasMoving&&state.highSpeed&&data.weaponWaitCutRatio>0) cutReady=true; movingMs=0; if(state.highSpeed&&t>graceUntil) { state.highSpeed=false; cutReady=false; extended=0; } } wasMoving=moving; lastX=x; lastAt=t; syncSuperSpeed(system,state); }; const offAtk=s.eventBus.on(CombatEvents.PLAYER_ATTACK,p=>{ const data=system.getData('super_speed'); if(!data||!cutReady||!p||p.fromSummon||p.afterimage) return; const ready=Number(p.readyAt??s.combatSystem?.nextAttackAt??0); if(ready>now(s)){ const next=now(s)+(ready-now(s))*(1-(data.weaponWaitCutRatio||0)); if('readyAt' in p) p.readyAt=next; if(s.combatSystem&&s.combatSystem.nextAttackAt===ready) s.combatSystem.nextAttackAt=next; } cutReady=false; }); const offKill=s.eventBus.on(CombatEvents.ENEMY_KILLED,()=>{ const data=system.getData('super_speed'),t=now(s); if(!data?.killExtendMs||!state.highSpeed||t>graceUntil) return; const add=Math.min(data.killExtendMs,(data.maxKillExtendMs||0)-extended); if(add>0){ extended+=add; graceUntil+=add; } }); system.passiveUpdaters.push(updater); return ()=>{ offAtk?.(); offKill?.(); system.passiveUpdaters=system.passiveUpdaters.filter(f=>f!==updater); delete p.moveSpeedMultiplierBonuses?.super_speed; delete p.attackSpeedMultiplierBonuses?.super_speed; state.highSpeed=false; }; }, shiftTimers(system,d,pausedAt){ const st=system.passiveState.superSpeed; if(st?.graceUntil>pausedAt) st.graceUntil+=d; } };
function beamTargets(s,a,end,width){ return (s.targeting?.all?.()||[]).filter(e=>valid(s,e)&&e.x>=Math.min(a.x,end.x)&&e.x<=Math.max(a.x,end.x)+20&&Math.abs((e.y??0)-a.y)<=width/2); }
export const LaserEyesSkill={ canCast(sys,cfg,d){ return !!sys.scene.targeting?.nearestAhead?.(d.range||760); }, cast(system,cfg,data,level,ctx){ const s=system.scene; let target=s.targeting.nearestAhead(data.range); if(!valid(s,target)) return {failed:true}; const active={skillId:cfg.id,cfg,data,level,ctx,nextAt:now(s),endAt:now(s)+data.durationMs,count:0,focus:0,extended:0,visuals:[],target,onEnd(){ this.visuals.forEach(cleanupVisual); this.visuals=[]; }}; active.tick=()=>{ const a=eye(s); if(!valid(s,active.target)){ if(data.retargetOnKill){ const nt=s.targeting.nearestAhead(data.range); if(valid(s,nt)){ active.target=nt; active.focus=Math.max(0,active.focus-(data.retargetFocusLoss||0)); } else { active.ended=true; return; } } } const dir=valid(s,active.target)?{x:active.target.x-a.x,y:active.target.y-a.y}:{x:1,y:0}; const len=Math.max(1,Math.hypot(dir.x,dir.y)); const end={x:a.x+dir.x/len*(data.range||760),y:a.y+dir.y/len*(data.range||760)}; active.visuals.forEach(cleanupVisual); active.visuals=[]; const beams=data.beamCount||1; for(let i=0;i<beams;i++){ const off=(i-(beams-1)/2)*(data.width*.35); const g=s.add?.graphics?.()?.setDepth?.(150); g?.lineStyle?.(6,0xff2222,.9); g?.lineBetween?.(a.x,a.y+off,end.x,end.y+off); if(g) active.visuals.push(g); const targets=beamTargets(s,{x:a.x,y:a.y+off},{x:end.x,y:end.y+off},data.width*(beams>1?.65:1)); targets.forEach(e=>{ const isLock=e===active.target; const scale=(data.beamDamageScale||1)*(isLock?1+Math.min(active.focus,data.maxFocus||0)*(data.focusPerTick||0):1); system.hit(e,system.damageValue(data.damage*scale,ctx),cfg,level,ctx,system.baseDamageValue(data.damage*scale,ctx),[TAGS.MAGIC,TAGS.SPELL,TAGS.SUPERPOWER]); }); } if(data.maxFocus&&valid(s,active.target)) active.focus=Math.min(data.maxFocus,active.focus+1); active.nextAt=now(s)+(active.focus>=5?data.overloadIntervalMs:data.intervalMs); }; const offKill=s.eventBus.on(CombatEvents.ENEMY_KILLED,p=>{ if(p?.skillId!==cfg.id&&p?.enemy!==active.target) return; if(data.killExtendMs&&active.extended<data.maxExtendMs){ const add=Math.min(data.killExtendMs,data.maxExtendMs-active.extended); active.extended+=add; active.endAt+=add; } }); const oldEnd=active.onEnd.bind(active); active.onEnd=(r)=>{ offKill?.(); oldEnd(r); }; system.active.push(active); return {ok:true}; }, cleanup(system){ system.active.filter(a=>a.skillId==='laser_eyes').forEach(a=>a.onEnd?.('cleanup')); } };
function cold(e){ return e[COLD] ||= {stacks:0,expiresAt:0,frozenUntil:0,guardUntil:0,shattered:false}; }
function applyCold(system,e,data,stacks=1){ const s=system.scene,t=now(s),st=cold(e); st.stacks=Math.min(data.maxStacks||8,st.stacks+stacks); st.expiresAt=t+(data.coldDurationMs||3400); const threshold=e.isBoss?Infinity:(e.isElite?data.eliteFreezeStacks:data.normalFreezeStacks); if(st.stacks>=threshold&&t>=st.guardUntil){ st.frozenUntil=t+(e.isElite?data.eliteFreezeMs:data.normalFreezeMs); st.guardUntil=st.frozenUntil+(data.refreezeGuardMs||800); st.shattered=false; } return st; }
function clearCold(e){ if(e?.[COLD]) delete e[COLD]; }
function shatter(system,e,data,scale=1){ const s=system.scene,base=Math.max(1,Math.round((data.shatterDamage||data.damage*2)*scale)); (s.targeting.all()||[]).filter(x=>valid(s,x)&&dist(x,e)<= (scale<1?data.deathShatterRadius:data.shatterRadius)).forEach(x=>{ s.combatSystem.damageEnemy(x,Math.round(base*(x===e?1:.65)),{source:'skill',skillId:'freezing_breath',damageKind:scale<1?'deathShatter':'shatter',tags:[TAGS.MAGIC,TAGS.SPELL,TAGS.ICE,TAGS.BUILD_SUPERHERO],allowLifeSteal:false,noKnockback:true,noColdShatter:true}); if(x!==e) applyCold(system,x,data,scale<1?1:2); }); const st=cold(e); st.frozenUntil=0; st.shattered=true; }
export const FreezingBreathSkill={ canCast(sys,cfg,d){ return !!sys.scene.targeting?.nearestAhead?.(d.range||500); }, cast(system,cfg,data,level,ctx){ const s=system.scene; const active={skillId:cfg.id,cfg,data,level,ctx,nextAt:now(s),endAt:now(s)+data.durationMs,visual:null,onEnd(){ cleanupVisual(this.visual); if(data.zoneDurationMs) createZone(system,cfg,data,level,ctx); }}; active.tick=()=>{ cleanupVisual(active.visual); active.visual=s.add?.graphics?.()?.setDepth?.(145); const a=eye(s), ang=data.angleDeg*Math.PI/180, r=data.range; active.visual?.fillStyle?.(0x8eeaff,.22); active.visual?.slice?.(a.x,a.y,r,-ang/2,ang/2,false); active.visual?.fillPath?.(); (s.targeting.all()||[]).filter(e=>valid(s,e)&&inCone(s,e,data)).forEach(e=>{ const st=applyCold(system,e,data,1); const bonus=e.isBoss&&st.stacks>=(data.maxStacks||8)?data.bossBreathDamageBonus||0:0; system.hit(e,system.damageValue(data.damage*(1+bonus),ctx),cfg,level,ctx,system.baseDamageValue(data.damage*(1+bonus),ctx),[TAGS.MAGIC,TAGS.SPELL,TAGS.ICE]); }); active.nextAt=now(s)+data.intervalMs; }; system.active.push(active); return {ok:true}; }, bind(system){ const s=system.scene; const updater=()=>{ const t=now(s); (s.enemies||[]).forEach(e=>{ const st=e?.[COLD]; if(!st) return; if(!valid(s,e)||t>st.expiresAt) clearCold(e); }); }; const offHit=s.eventBus.on(CombatEvents.ENEMY_HIT,p=>{ if(p?.skillId==='freezing_breath'||p?.noColdShatter||p?.tags?.includes?.(TAGS.DOT)||p?.tags?.includes?.(TAGS.SUMMON)) return; const data=system.getData('freezing_breath'), st=p?.enemy?.[COLD]; if(data?.shatterDamage&&st?.frozenUntil>now(s)&&!st.shattered) shatter(system,p.enemy,data,1); }); const offKill=s.eventBus.on(CombatEvents.ENEMY_KILLED,p=>{ const data=system.getData('freezing_breath'), st=p?.enemy?.[COLD]; if(data?.deathShatterScale&&st?.frozenUntil>now(s)&&!p?.deathShatter) shatter(system,p.enemy,data,data.deathShatterScale); clearCold(p?.enemy); }); system.passiveUpdaters.push(updater); return ()=>{ offHit?.(); offKill?.(); system.passiveUpdaters=system.passiveUpdaters.filter(f=>f!==updater); (s.enemies||[]).forEach(clearCold); }; }, cleanup(system){ (system.scene.enemies||[]).forEach(clearCold); } };
function createZone(system,cfg,data,level,ctx){ const s=system.scene,a=eye(s), end=now(s)+data.zoneDurationMs; const visual=s.add?.rectangle?.(a.x+data.range/2,a.y,data.range,Math.max(80,data.range*Math.tan((data.angleDeg*Math.PI/180)/2)),0x8eeaff,.12)?.setDepth?.(120); const active={skillId:'freezing_breath_zone',data:{intervalMs:data.zoneIntervalMs},nextAt:now(s)+data.zoneIntervalMs,endAt:end,onEnd(){ cleanupVisual(visual); },tick(){ (s.targeting.all()||[]).filter(e=>valid(s,e)&&inCone(s,e,data)).forEach(e=>applyCold(system,e,data,1)); this.nextAt=now(s)+data.zoneIntervalMs; }}; system.active.push(active); }
