import { SKILLS } from '../../config/skills.js';
import { TAGS } from '../../config/tags.js';
import { CombatEvents } from '../../core/CombatEvents.js';

const PhaserRef = globalThis.Phaser || { Math:{ Distance:{ Between:(x1,y1,x2,y2)=>Math.hypot(x2-x1,y2-y1) } } };
const RATIOS=[0.12,0.14,0.18,0.20,0.22,0.24,0.27,0.30,0.34];
const ENCHANT_DURATION_MS=8000;
const ENCHANT_COOLDOWN_MS=7000;
const ENCHANT_CYCLE_MS=ENCHANT_DURATION_MS+ENCHANT_COOLDOWN_MS;
const LIGHTNING_MARK_STACKS=[5,5,4,4,4,4,4,4,3];
const LIGHTNING_MARK_RATIOS=[0.25,0.28,0.32,0.36,0.40,0.45,0.50,0.56,0.65];
const LIGHTNING_MARK_RADII=[90,96,108,114,120,132,140,148,160];
const LIGHTNING_MARK_SPREAD=[0,0,0,0,0,1,1,1,2];
const LIGHTNING_MARK_STATE=Symbol('lightningMarkState');
const markLevelData=LIGHTNING_MARK_STACKS.map((stackThreshold,index)=>{ const level=index+1, explosionRatio=LIGHTNING_MARK_RATIOS[index], explosionRadius=LIGHTNING_MARK_RADII[index], spreadMarks=LIGHTNING_MARK_SPREAD[index]; return { stackThreshold, explosionRatio, explosionRadius, spreadMarks, normalMarkGain:1, enchantActiveMarkGain:2, desc: level>=9?'玩家本体武器命中叠加雷印；3层引爆，造成累计实际武器伤害65%的范围雷伤，并向其他命中敌人传播2层但不会连爆。':level>=6?`玩家本体武器命中叠加雷印；${stackThreshold}层引爆，造成累计实际武器伤害${Math.round(explosionRatio*100)}%的范围雷伤，并向其他命中敌人传播1层。`:`玩家本体武器命中叠加雷印；${stackThreshold}层引爆，造成累计实际武器伤害${Math.round(explosionRatio*100)}%的范围雷伤。`, ...(level===3?{milestoneText:'迅印'}:{}), ...(level===6?{milestoneText:'雷纹蔓延'}:{}), ...(level===9?{milestoneText:'万钧雷印'}:{}) }; });
const levelData=RATIOS.map((damageRatio,index)=>{ const level=index+1; const chainCount=level>=9?2:(level>=6?1:0); const chainRatio=level>=9?0.65:(level>=6?0.50:0); const chainRadius=level>=9?150:(level>=6?130:0); const cycle='附魔持续8秒，随后冷却7秒并自动循环。'; return { durationMs:ENCHANT_DURATION_MS, cooldownMs:ENCHANT_COOLDOWN_MS, damageRatio, chainCount, chainRatio, chainRadius, desc: level>=9?`${cycle} 玩家本体武器攻击命中时，追加34%魔法雷电伤害；并向150范围内最多2名其他敌人传导65%电伤。`:level>=6?`${cycle} 玩家本体武器攻击命中时，追加${Math.round(damageRatio*100)}%魔法雷电伤害；并向130范围内1名其他敌人传导50%电伤。`:`${cycle} 玩家本体武器攻击命中时，以该次实际武器伤害为基数，追加${Math.round(damageRatio*100)}%魔法雷电伤害。`, ...(level===3?{milestoneText:'高压附魔'}:{}), ...(level===6?{milestoneText:'电弧传导'}:{}), ...(level===9?{milestoneText:'雷霆传导'}:{}) }; });

export function configureWeaponCoreSkills(){ SKILLS.lightning_enchant={ id:'lightning_enchant', name:'青雷附魔', rarity:'FINE', handler:'lightning_enchant', passive:true, maxLevel:9, tags:[TAGS.MAGIC,TAGS.LIGHTNING,TAGS.NORMAL_ATTACK,TAGS.BUILD_WEAPON], cooldownMs:ENCHANT_COOLDOWN_MS, targetType:'passive', color:0x55ff88, short:'雷', description:'为当前武器附加青雷。附魔生效8秒，随后冷却7秒并自动循环。附魔期间，玩家本体武器攻击命中时，根据该次实际武器伤害追加魔法雷电伤害，升级后可向附近敌人传导。', milestones:{ 3:'高压附魔：附加电伤提高至本次武器实际伤害的18%。', 6:'电弧传导：青雷命中后，向130范围内另一名敌人传导50%电伤。', 9:'雷霆传导：附加电伤提高至34%，并向150范围内最多2名其他敌人传导65%电伤。' }, levels:levelData }; SKILLS.lightning_mark={ id:'lightning_mark', name:'雷印', rarity:'RARE', handler:'lightning_mark', passive:true, maxLevel:9, tags:[TAGS.MAGIC,TAGS.LIGHTNING,TAGS.NORMAL_ATTACK,TAGS.BUILD_WEAPON], cooldownMs:999999, targetType:'passive', color:0x63ff8f, short:'印', description:'玩家本体真实武器命中敌人时叠加雷印，达到层数后基于该目标累计实际武器伤害产生青绿色范围雷爆。青雷附魔active阶段每击叠2层。', milestones:{ 3:'迅印：雷印引爆要求降低至4层。', 6:'雷纹蔓延：雷印爆炸命中的其他敌人获得1层雷印，但不会立即连环引爆。', 9:'万钧雷印：3层即可引爆；爆炸命中的其他敌人获得2层雷印，但不会立即引爆。' }, levels:markLevelData }; }

const anchor=s=>({ x:(s.player?.x||0)+36, y:(s.player?.y||0)-52 });
const nowOf=s=>s.getGameplayTime?.() ?? s.time?.now ?? 0;
const validTarget=(s,e)=>!!e&&s.targeting?.valid?.(e)&&s.targeting?.isEnemyFullyInsideViewport?.(e)&&Math.max(0,Number(e.hp)||0)>0;
const damageMeta=damage=>({ source:'skill', skillId:'lightning_enchant', damageKind:'lightningEnchant', tags:[TAGS.MAGIC,TAGS.LIGHTNING,TAGS.BUILD_WEAPON], damageAlreadyResolved:true, critResolved:true, crit:false, professionApplied:true, professionMultiplier:1, baseAmountBeforeProfession:damage, canTriggerArtifacts:false, allowLifeSteal:false, noKnockback:true, fromLightningEnchant:true, damageTextColor:'#63ff8f' });

function drawArc(system,from,to){ const s=system.scene, state=system.passiveState.lightningEnchant; if(!s.add?.graphics) return; const g=s.add.graphics().setDepth?.(170)||s.add.graphics(); const color=0x55ff88; g.lineStyle?.(7,0xd8ffe6,0.55); const pts=[from]; const bends=2+Math.floor(Math.random()*3); for(let i=1;i<=bends;i+=1){ const t=i/(bends+1), x=from.x+(to.x-from.x)*t+(Math.random()*28-14), y=from.y+(to.y-from.y)*t+(Math.random()*28-14); pts.push({x,y}); } pts.push(to); for(let i=0;i<pts.length-1;i+=1) g.lineBetween?.(pts[i].x,pts[i].y,pts[i+1].x,pts[i+1].y); g.lineStyle?.(3,color,1); for(let i=0;i<pts.length-1;i+=1) g.lineBetween?.(pts[i].x,pts[i].y,pts[i+1].x,pts[i+1].y); state?.arcs?.add(g); const tw=s.tweens?.add?.({targets:g,alpha:0,duration:150,onComplete:()=>{ state?.arcs?.delete(g); state?.arcTweens?.delete(tw); g.destroy?.(); }}); if(tw) state?.arcTweens?.add(tw); }
function ensureVisual(system){ const s=system.scene, state=system.passiveState.lightningEnchant; if(!state||state.phase!=='active'||state.container||!s.add?.container||(s.playerData?.hp||0)<=0) return; const a=anchor(s); const c=s.add.container(a.x,a.y).setDepth?.(160)||s.add.container(a.x,a.y); const ring=s.add.circle?.(0,0,15,0x55ff88,0.18)?.setStrokeStyle?.(2,0x99ffbb,0.55); const bolt1=s.add.rectangle?.(4,-3,4,24,0x63ff8f,0.55); const bolt2=s.add.rectangle?.(-8,5,3,18,0xcaffdd,0.45); if(bolt1) bolt1.rotation=0.55; if(bolt2) bolt2.rotation=-0.65; [ring,bolt1,bolt2].filter(Boolean).forEach(o=>c.add?.(o)); state.container=c; state.visualTween=s.tweens?.add?.({targets:c,alpha:{from:0.45,to:0.85},scale:{from:0.92,to:1.08},duration:520,yoyo:true,repeat:-1}); }
function destroyPersistentVisual(st){ st?.visualTween?.stop?.(); st?.visualTween?.remove?.(); st?.container?.destroy?.(); if(st){ st.container=null; st.visualTween=null; } }
function destroyActiveArcs(st){ st?.arcTweens?.forEach(t=>{ t.stop?.(); t.remove?.(); }); st?.arcs?.forEach(g=>g.destroy?.()); st?.arcTweens?.clear?.(); st?.arcs?.clear?.(); }
function clearActiveVisuals(st){ destroyPersistentVisual(st); destroyActiveArcs(st); }
function destroyState(system){ const st=system.passiveState.lightningEnchant; if(!st) return; clearActiveVisuals(st); delete system.passiveState.lightningEnchant; }
function startActive(system,now){ const st=system.passiveState.lightningEnchant; st.phase='active'; st.phaseEndsAt=now+ENCHANT_DURATION_MS; st.wasOwned=true; ensureVisual(system); }
function setInactive(st){ st.phase='inactive'; st.phaseEndsAt=0; st.wasOwned=false; clearActiveVisuals(st); }
function advancePhase(system,now){ const st=system.passiveState.lightningEnchant; if(!st) return null; const has=system.getLevel('lightning_enchant')>0; if(!has){ if(st.wasOwned||st.phase!=='inactive') setInactive(st); return st; } if(!st.wasOwned||st.phase==='inactive'){ startActive(system,now); return st; } if(st.phaseEndsAt>now){ if(st.phase==='active') ensureVisual(system); else if(st.phase==='cooldown') clearActiveVisuals(st); return st; } const step=()=>{ if(st.phase==='active'){ st.phase='cooldown'; st.phaseEndsAt+=ENCHANT_COOLDOWN_MS; clearActiveVisuals(st); } else if(st.phase==='cooldown'){ st.phase='active'; st.phaseEndsAt+=ENCHANT_DURATION_MS; ensureVisual(system); } }; step(); if(st.phase==='cooldown'&&st.phaseEndsAt<=now) step(); if(st.phaseEndsAt<=now){ const completeCycles=Math.floor((now-st.phaseEndsAt)/ENCHANT_CYCLE_MS); if(completeCycles>0) st.phaseEndsAt+=completeCycles*ENCHANT_CYCLE_MS; while(st.phaseEndsAt<=now) step(); } if(st.phase==='active') ensureVisual(system); else if(st.phase==='cooldown') clearActiveVisuals(st); return st; }

export function isLightningEnchantActive(system,now){ const st=advancePhase(system,now); return st?.phase==='active'&&system.getLevel('lightning_enchant')>0; }
const isDead=e=>!e||e.isDefeated||Math.max(0,Number(e.hp)||0)<=0;
const markMeta=damage=>({ source:'skill', skillId:'lightning_mark', damageKind:'lightningMarkExplosion', tags:[TAGS.MAGIC,TAGS.LIGHTNING,TAGS.BUILD_WEAPON,'area'], damageAlreadyResolved:true, critResolved:true, crit:false, professionApplied:true, professionMultiplier:1, baseAmountBeforeProfession:damage, canTriggerArtifacts:false, allowLifeSteal:false, noKnockback:true, fromLightningMark:true, noSwordTrigger:true, noHeavenSplit:true, noInstantStep:true, damageTextColor:'#63ff8f' });
function getMarkState(enemy){ if(!enemy) return null; enemy[LIGHTNING_MARK_STATE]??={stacks:0,storedActualDamage:0,visual:null,dead:false,deathX:0,deathY:0}; return enemy[LIGHTNING_MARK_STATE]; }
function destroyMarkVisual(system,st){ const s=system.scene; if(st?.visualTween){ st.visualTween.stop?.(); st.visualTween.remove?.(); } if(st?.visual){ s?.tweens?.killTweensOf?.(st.visual); st.visual.destroy?.(); } if(st){ st.visual=null; st.visualTween=null; } }
function clearMark(system,enemy,{removeState=true}={}){ const st=enemy?.[LIGHTNING_MARK_STATE]; if(!st) return; destroyMarkVisual(system,st); st.stacks=0; st.storedActualDamage=0; if(removeState) delete enemy[LIGHTNING_MARK_STATE]; }
function updateMarkVisual(system,enemy,data){ const s=system.scene, st=getMarkState(enemy); if(!st||st.stacks<=0||st.dead||isDead(enemy)){ destroyMarkVisual(system,st); return; } if(!st.visual&&s.add?.container){ const c=s.add.container(enemy.x,enemy.y-92).setDepth?.(166)||s.add.container(enemy.x,enemy.y-92); const ring=s.add.circle?.(0,0,13,0x63ff8f,0.18)?.setStrokeStyle?.(2,0x63ff8f,0.85); const text=s.add.text?.(0,0,'',{fontSize:'14px',color:'#63ff8f',stroke:'#042a16',strokeThickness:3})?.setOrigin?.(.5,.5); [ring,text].filter(Boolean).forEach(o=>c.add?.(o)); st.visual=c; st.text=text; st.visualTween=s.tweens?.add?.({targets:c,scale:{from:.96,to:1.06},duration:420,yoyo:true,repeat:-1}); } st.text?.setText?.(`印 ${st.stacks}/${data.stackThreshold}`); st.visual?.setPosition?.(enemy.x,(enemy.y||0)-92); st.visual?.setVisible?.(true); }
function drawMarkExplosion(system,x,y,r){ const s=system.scene, st=system.passiveState.lightningMark; if(!s.add?.circle) return; const o=s.add.circle(x,y,r,0x63ff8f,0.14).setStrokeStyle?.(5,0x63ff8f,0.9).setDepth?.(150)||s.add.circle(x,y,r,0x63ff8f,0.14); st?.explosions?.add(o); const tw=s.tweens?.add?.({targets:o,alpha:0,scale:1.18,duration:260,onComplete:()=>{ st?.explosions?.delete(o); st?.explosionTweens?.delete(tw); o.destroy?.(); }}); if(tw) st?.explosionTweens?.add(tw); }
function explodeMark(system,enemy,data,center,primaryAlive){ const s=system.scene, st=enemy?.[LIGHTNING_MARK_STATE]; if(!st) return 0; const damage=Math.max(1,Math.round(st.storedActualDamage*data.explosionRatio)); clearMark(system,enemy,{removeState:true}); drawMarkExplosion(system,center.x,center.y,data.explosionRadius); const damagedOthers=[]; const targets=[...(primaryAlive&&!isDead(enemy)?[enemy]:[]),...(s.targeting?.all?.()||[]).filter(e=>e!==enemy&&validTarget(s,e)&&PhaserRef.Math.Distance.Between(e.x,e.y,center.x,center.y)<=data.explosionRadius)]; const seen=new Set(); targets.forEach(t=>{ if(seen.has(t)) return; seen.add(t); const before=Math.max(0,Number(t.hp)||0); if(s.combatSystem?.damageEnemy?.(t,damage,markMeta(damage))&&t!==enemy&&Math.max(0,Number(t.hp)||0)<before&&!isDead(t)) damagedOthers.push(t); }); if(data.spreadMarks>0){ const cap=Math.max(0,data.stackThreshold-1); damagedOthers.forEach(t=>{ const ts=getMarkState(t); ts.stacks=Math.min(cap,(ts.stacks||0)+data.spreadMarks); if(ts.stacks>0) updateMarkVisual(system,t,data); }); } return 1; }
function cleanupMarkState(system){ const st=system.passiveState.lightningMark; st?.explosionTweens?.forEach(t=>{t.stop?.();t.remove?.();}); st?.explosions?.forEach(o=>o.destroy?.()); (system.scene.enemies||[]).forEach(e=>clearMark(system,e,{removeState:true})); st?.explosionTweens?.clear?.(); st?.explosions?.clear?.(); delete system.passiveState.lightningMark; }

export const LightningMarkSkill={
  bind(system){ const s=system.scene; cleanupMarkState(system); const state={explosions:new Set(),explosionTweens:new Set()}; system.passiveState.lightningMark=state; const updater=()=>{ const data=system.getData('lightning_mark'); (s.enemies||[]).forEach(e=>{ const st=e?.[LIGHTNING_MARK_STATE]; if(!st) return; if(st.stacks<=0||isDead(e)) clearMark(system,e,{removeState:true}); else if(data) updateMarkVisual(system,e,data); }); }; system.passiveUpdaters.push(updater); const offKill=s.eventBus.on(CombatEvents.ENEMY_KILLED,p=>{ const e=p?.enemy, st=e?.[LIGHTNING_MARK_STATE]; if(!st) return; st.dead=true; st.deathX=Number(e.x)||0; st.deathY=Number(e.y)||0; destroyMarkVisual(system,st); }); const offHit=s.eventBus.on(CombatEvents.PLAYER_HIT,p=>{ const data=system.getData('lightning_mark'); if(!data||system.getLevel('lightning_mark')<=0) return; if(p?.source!=='attack'||!p?.enemy||Math.max(0,Math.round(Number(p.actualDamage)||0))<=0) return; if(!(p.tags||[]).includes(TAGS.NORMAL_ATTACK)) return; const enemy=p.enemy; if(isDead(enemy)&&!enemy[LIGHTNING_MARK_STATE]) return; const st=getMarkState(enemy), actual=Math.max(0,Math.round(Number(p.actualDamage)||0)); const gain=isLightningEnchantActive(system,nowOf(s))?data.enchantActiveMarkGain:data.normalMarkGain; st.storedActualDamage+=actual; st.stacks+=gain; const center={x:st.dead?st.deathX:(Number(enemy.x)||0),y:st.dead?st.deathY:(Number(enemy.y)||0)}; if(st.stacks>=data.stackThreshold) explodeMark(system,enemy,data,center,!st.dead); else if(st.dead) clearMark(system,enemy,{removeState:true}); else updateMarkVisual(system,enemy,data); }); let cleaned=false; return ()=>{ if(cleaned) return; cleaned=true; offHit?.(); offKill?.(); system.passiveUpdaters=system.passiveUpdaters.filter(fn=>fn!==updater); cleanupMarkState(system); }; },
  cleanup:cleanupMarkState
};

export const LightningEnchantSkill={
  bind(system){ const s=system.scene; destroyState(system); const state={phase:'inactive',phaseEndsAt:0,wasOwned:false,container:null,visualTween:null,arcs:new Set(),arcTweens:new Set()}; system.passiveState.lightningEnchant=state; const getSkillBarState=()=>{ const st=advancePhase(system,nowOf(s)); if(!st||!system.getLevel('lightning_enchant')||(s.playerData?.hp||0)<=0) return null; if(st.phase==='active'||st.phase==='cooldown') return { phase:st.phase, label:st.phase==='active'?'附魔':'冷却', remainingMs:Math.max(0,st.phaseEndsAt-nowOf(s)) }; return null; }; const runtime={getSkillBarState}; s.lightningEnchantRuntime=runtime; const updater=()=>{ const st=advancePhase(system,nowOf(s)); if(!st) return; if((s.playerData?.hp||0)<=0){ clearActiveVisuals(st); return; } if(st.phase==='active') ensureVisual(system); else clearActiveVisuals(st); st.container?.setVisible?.(true); }; system.passiveUpdaters.push(updater); updater(); const off=s.eventBus.on(CombatEvents.PLAYER_HIT,payload=>{ const st=advancePhase(system,nowOf(s)); const data=system.getData('lightning_enchant'); if(!data||st?.phase!=='active') return; if((s.playerData?.hp||0)<=0) return; if(payload?.source!=='attack'||!payload?.enemy) return; if(!(payload?.tags||[]).includes(TAGS.NORMAL_ATTACK)) return; if(payload?.fromLightningEnchant) return; const weaponActualDamage=Math.max(0,Math.round(Number(payload.actualDamage)||0)); if(weaponActualDamage<=0) return; const main=payload.enemy; const chainOrigin={x:Number(main.x)||0,y:Number(main.y)||0}; const mainVisualPoint={x:chainOrigin.x,y:chainOrigin.y-50}; const enchantDamage=Math.max(1,Math.round(weaponActualDamage*data.damageRatio)); if(validTarget(s,main)){ drawArc(system,anchor(s),mainVisualPoint); s.combatSystem.damageEnemy(main,enchantDamage,damageMeta(enchantDamage)); } const count=Math.max(0,data.chainCount||0); if(count<=0) return; const radius=data.chainRadius||0, chainDamage=Math.max(1,Math.round(enchantDamage*(data.chainRatio||0))); const distanceFromMain=e=>PhaserRef.Math.Distance.Between(e.x,e.y,chainOrigin.x,chainOrigin.y); const indexed=s.targeting.all().map((enemy,index)=>({enemy,index})); const targets=indexed.filter(({enemy})=>enemy!==main&&validTarget(s,enemy)&&distanceFromMain(enemy)<=radius).sort((a,b)=>distanceFromMain(a.enemy)-distanceFromMain(b.enemy)||a.index-b.index).slice(0,count).map(entry=>entry.enemy); targets.forEach(e=>{ drawArc(system,mainVisualPoint,{x:e.x,y:e.y-50}); s.combatSystem.damageEnemy(e,chainDamage,damageMeta(chainDamage)); }); }); let cleaned=false; return ()=>{ if(cleaned) return; cleaned=true; off?.(); system.passiveUpdaters=system.passiveUpdaters.filter(fn=>fn!==updater); if(s.lightningEnchantRuntime===runtime) s.lightningEnchantRuntime=null; destroyState(system); } },
  cleanup:destroyState,
  shiftTimers(system,pausedDuration,pausedAt){ const st=system.passiveState.lightningEnchant; if(st?.phaseEndsAt>pausedAt) st.phaseEndsAt+=pausedDuration; },
  syncAttachedVisuals(system){ const st=system.passiveState.lightningEnchant; if(!st) return; advancePhase(system,nowOf(system.scene)); if(st.phase!=='active'||!system.getLevel('lightning_enchant')) return; ensureVisual(system); if(!st.container) return; const a=anchor(system.scene); st.container.setPosition?.(a.x,a.y); st.container.setVisible?.((system.scene.playerData?.hp||0)>0); }
};
