import { DESIGN_WIDTH, DESIGN_HEIGHT } from '../config/gameConfig.js';
import { formatArtifactSelectionOption, SELECTION_ICON_STYLE, SelectionState } from './selectionFormatters.js';

const DEPTH=3700, WHITE='#f2f6ff', MUTED='#cbd6ee', GREEN='#62e883';

export default class ArtifactRewardPanel {
  constructor(scene){ this.scene=scene; this.nodes=[]; this.cards=[]; this.detailNodes=[]; this.state=new SelectionState(); this.isOpen=false; }
  show({ title='获得一个法宝奖励', options=[], onConfirm }={}){ this.hide(); this.isOpen=true; this.options=options; this.onConfirm=onConfirm; this.formatted=options.map(formatArtifactSelectionOption); this.state.open(); const bg=this.scene.add.rectangle(DESIGN_WIDTH/2,DESIGN_HEIGHT/2,DESIGN_WIDTH,DESIGN_HEIGHT,0x07101f,0.18).setScrollFactor(0).setDepth(DEPTH); const panel=this.scene.add.rectangle(DESIGN_WIDTH/2,315,650,360,0x0b1020,0.82).setStrokeStyle(3,0x74a7ff,0.62).setScrollFactor(0).setDepth(DEPTH+1); const label=this.scene.add.text(DESIGN_WIDTH/2,160,title,{fontFamily:'Arial',fontSize:'34px',color:'#fff',stroke:'#000',strokeThickness:4}).setOrigin(0.5).setScrollFactor(0).setDepth(DEPTH+2); this.nodes.push(bg,panel,label); this.createOptions(); this.createDetails(null); this.createDebug(); }
  text(x,y,s,style={},origin=[0,0]){ const n=this.scene.add.text(x,y,s,{fontFamily:'Arial',fontSize:'21px',color:WHITE,wordWrap:{width:540,useAdvancedWrap:true},...style}).setOrigin(...origin).setScrollFactor(0).setDepth(DEPTH+3); this.nodes.push(n); return n; }
  createOptions(){ this.formatted.forEach((f,i)=>{ const x=DESIGN_WIDTH/2-200+i*200,y=315,color=f.iconColor||SELECTION_ICON_STYLE.colors[i%SELECTION_ICON_STYLE.colors.length]; const hit=this.scene.add.rectangle(x,y,156,190,0x1b2c55,0.24).setStrokeStyle(4,f.rarityColor||color,0.7).setScrollFactor(0).setDepth(DEPTH+2); const icon=this.scene.add.circle(x,y-42,46,color,0.86).setStrokeStyle(4,0xffffff,0.26).setScrollFactor(0).setDepth(DEPTH+3); const glyph=this.text(x,y-64,f.iconText||'宝',{fontSize:'36px',color:'#10172a',fontStyle:'bold'},[0.5,0]); const name=this.text(x,y+14,f.title,{fontSize:'24px',align:'center',wordWrap:{width:150}},[0.5,0]); const rarity=this.text(x,y+52,f.rarity||f.subtitle||'法宝',{fontSize:'18px',color:GREEN,align:'center',wordWrap:{width:150}},[0.5,0]); const group=[hit,icon,glyph,name,rarity]; this.nodes.push(hit,icon); group.forEach(n=>n.setInteractive?.({useHandCursor:true}).on('pointerdown',()=>this.select(i))); this.cards[i]={root:hit,nodes:group,x,y,color}; }); }
  select(i){ const result=this.state.selectOrConfirm(i,this.options[i],(o)=>this.onConfirm?.(o)); if(result==='locked') return; if(result==='rejected'){ this.updateDebug(); return; } if(result==='confirmed'){ this.cards.forEach(c=>c.nodes.forEach(n=>n.disableInteractive?.())); this.hide(); return; } this.cards.forEach((c,idx)=>{ const on=idx===i; c.root.setStrokeStyle(on?6:4,on?0x9fffb6:c.color,on?1:0.62); c.nodes.forEach(n=>n.setAlpha?.(on?1:0.68)); c.root.y=c.y+(on?-8:0); }); this.createDetails(this.formatted[i]); this.updateDebug(); }
  createDetails(f){ this.detailNodes.forEach(n=>{n.removeAllListeners?.();n.destroy();}); this.detailNodes=[]; const lines=f?(f.detailLines||[]):[]; const title=lines[0]||'点击上方法宝查看详情'; const body=lines.slice(1).join('\n'); const titleNode=this.scene.add.text(DESIGN_WIDTH/2,535,title,{fontFamily:'Arial',fontSize:f?'38px':'23px',color:f?WHITE:MUTED,stroke:'#000',strokeThickness:5,align:'center',wordWrap:{width:620,useAdvancedWrap:true}}).setOrigin(0.5,0).setScrollFactor(0).setDepth(DEPTH+3); const bodyNode=this.scene.add.text(DESIGN_WIDTH/2,600,body,{fontFamily:'Arial',fontSize:'23px',color:WHITE,stroke:'#000',strokeThickness:3,lineSpacing:9,align:'center',wordWrap:{width:620,useAdvancedWrap:true}}).setOrigin(0.5,0).setScrollFactor(0).setDepth(DEPTH+3); this.detailNodes.push(titleNode,bodyNode); this.nodes.push(titleNode,bodyNode); }
  createDebug(){ if(!this.scene.debugMode)return; this.debugText=this.text(28,1220,'',{fontSize:'14px',color:'#ffd166'}); this.updateDebug(); }
  updateDebug(){ if(this.debugText) this.debugText.setText(`artifact index=${this.state.selectedIndex} id=${this.state.selectedOption?.artifactId||this.state.selectedOption?.id||'-'} locked=${this.state.confirmed}`); }
  hide(){ this.nodes.forEach(n=>{n.removeAllListeners?.();n.destroy();}); this.nodes=[]; this.cards=[]; this.detailNodes=[]; this.state.close(); this.isOpen=false; }
  destroy(){ this.hide(); }
}
