import { DESIGN_WIDTH, DESIGN_HEIGHT } from '../config/gameConfig.js';
import { TUNING } from '../config/tuning.js';
import { SKILLS } from '../config/skills.js';
import { ARTIFACTS } from '../config/artifacts.js';
import { CombatEvents, RunStates } from '../core/CombatEvents.js';

const sec = (ms) => ms == null ? '-' : `${Math.floor(ms/1000)}s`;
export default class PlaytestPanel {
  constructor(scene){ this.scene=scene; this.nodes=[]; this.isOpen=false; this.button=scene.add.text(DESIGN_WIDTH-22,90,'试玩数据',{fontFamily:'Arial',fontSize:'22px',color:'#fff',backgroundColor:'#6b4bd8',padding:{left:10,right:10,top:8,bottom:8}}).setOrigin(1,0).setScrollFactor(0).setInteractive({useHandCursor:true}).setDepth(2500); this.button.on('pointerdown',()=>this.show()); }
  show(){ if(this.scene.upgradePanel?.isOpen||this.scene.rewardPanel?.isOpen||this.scene.resultPanel?.isOpen) return; this.hideNodes(); this.isOpen=true; this.scene.beginGameplayPause(); this.bg=this.scene.add.rectangle(DESIGN_WIDTH-230,DESIGN_HEIGHT/2,430,940,0x080b12,0.86).setScrollFactor(0).setDepth(3600); this.text=this.scene.add.text(DESIGN_WIDTH-430,180,'',{fontFamily:'monospace',fontSize:'17px',color:'#eaf2ff',lineSpacing:5,wordWrap:{width:390}}).setScrollFactor(0).setDepth(3601); this.close=this.scene.add.text(DESIGN_WIDTH-48,150,'关闭',{fontFamily:'Arial',fontSize:'20px',color:'#fff',backgroundColor:'#444',padding:{left:10,right:10,top:6,bottom:6}}).setOrigin(1,0).setScrollFactor(0).setInteractive({useHandCursor:true}).setDepth(3602); this.close.on('pointerdown',()=>this.hide()); this.makeButtons(); this.nodes.push(this.bg,this.text,this.close,...this.debugButtons); this.update(); }
  makeButtons(){ const defs=[['+1级',()=>{ this.scene.playerData.level+=1; this.scene.upgradeSystem.pending+=1; this.scene.hud?.update(); this.hide(); this.scene.upgradeSystem.maybeShow(); }],['召唤精英',()=>this.scene.stageSystem.spawn(this.scene.stageSystem.stage.elite.enemyId,this.scene.player.x+520)],['召唤Boss',()=>{ if(!this.scene.enemies.some(e=>e.isBoss&&!e.isDefeated)){ const b=this.scene.stageSystem.spawn(this.scene.stageSystem.stage.boss.enemyId,this.scene.player.x+650); this.scene.stageSystem.bossSpawned=true; this.scene.runState=RunStates.BOSS; this.scene.eventBus.emit(CombatEvents.BOSS_SPAWNED,{enemy:b}); }}],['玩家回满',()=>{ this.scene.playerData.hp=this.scene.playerData.maxHp; this.scene.statusEffects?.clearNegativeEffects(this.scene.playerData); this.scene.hud?.update(); }],['清空敌人',()=>{ this.scene.enemies.forEach(e=>{ this.scene.statusEffects?.clearTarget(e); [e.hpBarBg,e.hpBar,e.nameText,e].forEach(o=>o?.destroy()); }); this.scene.enemies=[]; this.scene.currentTarget=null; }]]; this.debugButtons=defs.map(([label,fn],i)=>{ const b=this.scene.add.text(DESIGN_WIDTH-430+(i%2)*145,DESIGN_HEIGHT-270+Math.floor(i/2)*48,label,{fontFamily:'Arial',fontSize:'18px',color:'#fff',backgroundColor:'#285b38',padding:{left:8,right:8,top:6,bottom:6}}).setScrollFactor(0).setInteractive({useHandCursor:true}).setDepth(3602); b.on('pointerdown',fn); return b; }); }
  warnings(s){ const out=[]; const total=s.damageDealt; if(!s.firstSkillObtainedAt&&s.activePlayTimeMs>TUNING.pacing.targetFirstSkillSeconds*1000) out.push('🟡 首技能过慢'); if(!s.firstArtifactObtainedAt&&s.activePlayTimeMs>TUNING.pacing.targetFirstArtifactSeconds*1000) out.push('🟡 首法宝过慢'); if(s.msSinceLastUpgrade>TUNING.pacing.warningNoUpgradeSeconds*1000) out.push('🔴 升级间隔过长'); if((s.bossFightDurationMs??(s.bossFightStartedAt?s.activePlayTimeMs-s.bossFightStartedAt:0))>30000) out.push('🟡 Boss战过长'); if(total>0){ this.scene.playerData.skills.filter(x=>x.id!=='healing').forEach(({id})=>{ const r=(s.skillDamage[id]||0)/total; if(r>0.8) out.push(`🔴 ${SKILLS[id]?.short||id}占比>80%`); if(r<0.03) out.push(`🟡 ${SKILLS[id]?.short||id}占比<3%`); }); } if(this.scene.playerData.skills.length>0 && s.buildTags?.length===0) out.push('🟡 未形成流派'); return out; }
  update(){ if(!this.isOpen) return; const s=this.scene.runStats.snapshot(), p=this.scene.playerData, warns=this.warnings(s); const lines=[`有效时间 ${sec(s.activePlayTimeMs)}  Lv.${p.level}`,`击杀 ${s.enemiesKilled+s.elitesKilled+s.bossesKilled} 普攻 ${s.playerAttacks}`,`总伤害 ${s.damageDealt} 承伤 ${s.damageTaken}`,`护盾 ${s.shieldAbsorbed} 治疗 ${s.healingDone}`,`距上次升级 ${sec(s.msSinceLastUpgrade)}`,`首技能 ${sec(s.firstSkillObtainedAt)} 首法宝 ${sec(s.firstArtifactObtainedAt)}`,'','技能释放:',...Object.entries(SKILLS).map(([id,c])=>`${c.short||c.name}: ${s.skillCasts[id]||0}`),'','技能伤害:',...Object.entries(SKILLS).map(([id,c])=>`${c.short||c.name}: ${s.skillDamage[id]||0}`),'','法宝触发:',...Object.entries(ARTIFACTS).map(([id,c])=>`${c.name}: ${s.artifactTriggers[id]||0}`),'',`警告: ${warns.join(' / ')||'无'}`]; this.text?.setText(lines.join('\n')); }
  hide(){ this.hideNodes(); this.isOpen=false; this.scene.endGameplayPause(); }
  hideNodes(){ this.nodes.forEach(n=>{n.removeAllListeners?.();n.destroy();}); this.nodes=[]; }
  destroy(){ this.hideNodes(); this.button?.destroy(); }
}
