import { DESIGN_WIDTH, DESIGN_HEIGHT } from '../config/gameConfig.js';
import { getProfessionChoices } from '../config/professions.js';
import { formatProfessionSelectionOption, SELECTION_ICON_STYLE, SelectionState } from './selectionFormatters.js';
const DEPTH=3900, WHITE='#f2f6ff', MUTED='#cbd6ee';
export default class ProfessionPanel {
  constructor(scene){ this.scene=scene; this.nodes=[]; this.cards=[]; this.detailNodes=[]; this.state=new SelectionState(); this.isOpen=false; }
  show(onChoose){ this.hide(); this.isOpen=true; this.onChoose=onChoose; this.state.open(); const bg=this.scene.add.rectangle(DESIGN_WIDTH/2,DESIGN_HEIGHT/2,680,1040,0x0b101a,0.96).setScrollFactor(0).setDepth(DEPTH); const title=this.scene.add.text(DESIGN_WIDTH/2,118,'选择职业',{fontFamily:'Arial',fontSize:'42px',color:'#fff',stroke:'#000',strokeThickness:5}).setOrigin(0.5).setScrollFactor(0).setDepth(DEPTH+1); this.nodes.push(bg,title); this.options=getProfessionChoices({ currentSkills:this.scene.playerData.skills, currentArtifacts:this.scene.playerData.artifacts }); this.formatted=this.options.map(formatProfessionSelectionOption); this.createOptions(); this.createDetails(null); this.createConfirm(); this.createDebug(); }
  text(x,y,s,style={},origin=[0,0]){ const n=this.scene.add.text(x,y,s,{fontFamily:'Arial',fontSize:'22px',color:WHITE,wordWrap:{width:560,useAdvancedWrap:true},...style}).setOrigin(...origin).setScrollFactor(0).setDepth(DEPTH+2); this.nodes.push(n); return n; }
  createOptions(){ this.formatted.forEach((f,i)=>{ const x=160+i*200,y=300,color=f.iconColor||SELECTION_ICON_STYLE.colors[i]; const hit=this.scene.add.rectangle(x,y,155,180,0x18233d,0.5).setStrokeStyle(4,color,0.75).setScrollFactor(0).setDepth(DEPTH+1); const icon=this.scene.add.circle(x,y-30,48,color,0.85).setStrokeStyle(4,0xffffff,0.3).setScrollFactor(0).setDepth(DEPTH+2); const glyph=this.text(x,y-52,f.iconText,{fontSize:'38px',color:'#10172a',fontStyle:'bold'},[0.5,0]); const name=this.text(x,y+32,f.title,{fontSize:'25px',align:'center',wordWrap:{width:150}},[0.5,0]); const badge=this.text(x,y-120,'已选中',{fontSize:'17px',color:'#10172a',backgroundColor:'#80ffb0',padding:{left:7,right:7,top:3,bottom:3}},[0.5,0]); badge.setVisible(false); const group=[hit,icon,glyph,name,badge]; this.nodes.push(hit,icon); group.forEach(n=>n.setInteractive?.({useHandCursor:true}).on('pointerdown',()=>this.select(i))); this.cards[i]={root:hit,nodes:group,badge,x,y,color}; }); }
  select(i){ if(!this.state.select(i,this.options[i])) return; this.cards.forEach((c,idx)=>{ const on=idx===i; c.badge.setVisible(on); c.root.setStrokeStyle(on?6:4,on?0x9fffb6:c.color,on?1:0.65); c.nodes.forEach(n=>n.setAlpha?.(on?1:0.72)); c.root.y=c.y+(on?-8:0); c.nodes.forEach(n=>{ if(n!==c.root) this.scene.tweens.add({targets:n,scale:on?1.05:1,duration:150}); }); }); this.createDetails(this.formatted[i]); this.updateConfirm(); this.updateDebug(); }
  createDetails(f){ this.detailNodes.forEach(n=>{n.removeAllListeners?.();n.destroy();}); this.detailNodes=[]; const box=this.scene.add.rectangle(DESIGN_WIDTH/2,670,620,410,0x10172a,0.95).setStrokeStyle(3,0x46639b,0.8).setScrollFactor(0).setDepth(DEPTH+1); this.detailNodes.push(box); this.nodes.push(box); const s=f?`${f.title}\n${(f.detailLines||[]).join('\n')}\n适合方向：${(f.tags||[]).slice(0,8).join('、')||'无'}\n参考标签：${(f.tags||[]).slice(0,10).join('、')||'无'}`:'点击职业图标预览详情，确认后才会选择职业。'; const t=this.scene.add.text(72,485,s,{fontFamily:'Arial',fontSize:'22px',color:f?WHITE:MUTED,lineSpacing:7,wordWrap:{width:580,useAdvancedWrap:true}}).setScrollFactor(0).setDepth(DEPTH+2); this.detailNodes.push(t); this.nodes.push(t); }
  createConfirm(){ this.confirmButton=this.scene.add.text(DESIGN_WIDTH/2,1168,'选择职业',{fontFamily:'Arial',fontSize:'30px',color:'#8b93a8',backgroundColor:'#2a3144',padding:{left:42,right:42,top:16,bottom:16}}).setOrigin(0.5).setScrollFactor(0).setDepth(DEPTH+2).setInteractive({useHandCursor:true}); this.confirmButton.on('pointerdown',()=>{ if(this.state.selectedIndex<0||this.state.confirmed) return; this.state.confirmed=true; this.confirmButton.disableInteractive(); this.confirmButton.setText('处理中...'); const p=this.state.selectedOption; const accepted=this.onChoose?.(p.id); if(accepted===false){ this.state.confirmed=false; this.updateConfirm(); this.confirmButton.setInteractive({useHandCursor:true}); return; } this.hide(); }); this.nodes.push(this.confirmButton); this.updateConfirm(); }
  updateConfirm(){ if(!this.confirmButton)return; const on=this.state.selectedIndex>=0&&!this.state.confirmed; this.confirmButton.setColor(on?'#fff':'#8b93a8'); this.confirmButton.setBackgroundColor(on?'#2d8f55':'#2a3144'); }
  createDebug(){ if(!this.scene.debugMode)return; this.debugText=this.text(28,1220,'',{fontSize:'14px',color:'#ffd166'}); this.updateDebug(); }
  updateDebug(){ if(this.debugText) this.debugText.setText(`mode=icon index=${this.state.selectedIndex} id=${this.state.selectedOption?.id||'-'} locked=${this.state.confirmed}`); }
  hide(){ this.nodes.forEach(n=>{n.removeAllListeners?.();n.destroy();}); this.nodes=[]; this.cards=[]; this.detailNodes=[]; this.state.close(); this.isOpen=false; }
  destroy(){ this.hide(); }
}
