import { DESIGN_WIDTH, DESIGN_HEIGHT } from '../config/gameConfig.js';
import { getProfessionChoices } from '../config/professions.js';
import { formatProfessionSelectionOption, SELECTION_ICON_STYLE, SelectionState } from './selectionFormatters.js';
const DEPTH=3900, WHITE='#f2f6ff', MUTED='#cbd6ee';
export default class ProfessionPanel {
  constructor(scene){ this.scene=scene; this.nodes=[]; this.cards=[]; this.detailNodes=[]; this.state=new SelectionState(); this.isOpen=false; }
  show(onChoose){ this.hide(); this.isOpen=true; this.onChoose=onChoose; this.state.open(); const bg=this.scene.add.rectangle(DESIGN_WIDTH/2,DESIGN_HEIGHT/2,DESIGN_WIDTH,DESIGN_HEIGHT,0x07101f,0.34).setScrollFactor(0).setDepth(DEPTH); const title=this.scene.add.text(DESIGN_WIDTH/2,118,'选择职业',{fontFamily:'Arial',fontSize:'42px',color:'#fff',stroke:'#000',strokeThickness:5}).setOrigin(0.5).setScrollFactor(0).setDepth(DEPTH+1); this.nodes.push(bg,title); this.options=getProfessionChoices({ currentSkills:this.scene.playerData.skills, currentArtifacts:this.scene.playerData.artifacts }); this.formatted=this.options.map(formatProfessionSelectionOption); this.createOptions(); this.createDetails(null); this.createDebug(); }
  text(x,y,s,style={},origin=[0,0]){ const n=this.scene.add.text(x,y,s,{fontFamily:'Arial',fontSize:'22px',color:WHITE,wordWrap:{width:560,useAdvancedWrap:true},...style}).setOrigin(...origin).setScrollFactor(0).setDepth(DEPTH+2); this.nodes.push(n); return n; }
  createOptions(){ this.formatted.forEach((f,i)=>{ const x=160+i*200,y=300,color=f.iconColor||SELECTION_ICON_STYLE.colors[i]; const hit=this.scene.add.rectangle(x,y,155,180,0x18233d,0.28).setStrokeStyle(4,color,0.75).setScrollFactor(0).setDepth(DEPTH+1); const icon=this.scene.add.circle(x,y-30,48,color,0.85).setStrokeStyle(4,0xffffff,0.3).setScrollFactor(0).setDepth(DEPTH+2); const glyph=this.text(x,y-52,f.iconText,{fontSize:'38px',color:'#10172a',fontStyle:'bold'},[0.5,0]); const name=this.text(x,y+32,f.title,{fontSize:'25px',align:'center',wordWrap:{width:150}},[0.5,0]); const badge=this.text(x,y-120,'再次点击确认',{fontSize:'17px',color:'#10172a',backgroundColor:'#80ffb0',padding:{left:7,right:7,top:3,bottom:3}},[0.5,0]); badge.setVisible(false); const group=[hit,icon,glyph,name,badge]; this.nodes.push(hit,icon); group.forEach(n=>n.setInteractive?.({useHandCursor:true}).on('pointerdown',()=>this.select(i))); this.cards[i]={root:hit,nodes:group,badge,x,y,color}; }); }
  select(i){ const result=this.state.selectOrConfirm(i,this.options[i],(p)=>this.onChoose?.(p.id)); if(result==='locked') return; if(result==='rejected'){ this.updateDebug(); return; } if(result==='confirmed'){ this.cards.forEach(c=>c.nodes.forEach(n=>n.disableInteractive?.())); this.hide(); return; } this.cards.forEach((c,idx)=>{ const on=idx===i; c.badge.setVisible(on); c.root.setStrokeStyle(on?6:4,on?0x9fffb6:c.color,on?1:0.65); c.nodes.forEach(n=>n.setAlpha?.(on?1:0.66)); c.root.y=c.y+(on?-8:0); c.nodes.forEach(n=>{ if(n!==c.root) this.scene.tweens.add({targets:n,scale:on?1.05:1,duration:140}); }); }); this.createDetails(this.formatted[i]); this.updateDebug(); }
  createDetails(f){ this.detailNodes.forEach(n=>{n.removeAllListeners?.();n.destroy();}); this.detailNodes=[]; const box=this.scene.add.rectangle(DESIGN_WIDTH/2,690,620,430,0x10172a,0.62).setStrokeStyle(3,0x46639b,0.65).setScrollFactor(0).setDepth(DEPTH+1); this.detailNodes.push(box); this.nodes.push(box); const s=f?(f.detailLines||[]).join('\n'):'点击上方选项查看详情'; const t=this.scene.add.text(72,500,s,{fontFamily:'Arial',fontSize:'22px',color:f?WHITE:MUTED,lineSpacing:7,wordWrap:{width:580,useAdvancedWrap:true}}).setScrollFactor(0).setDepth(DEPTH+2); this.detailNodes.push(t); this.nodes.push(t); }
  createDebug(){ if(!this.scene.debugMode)return; this.debugText=this.text(28,1220,'',{fontSize:'14px',color:'#ffd166'}); this.updateDebug(); }
  updateDebug(){ if(this.debugText) this.debugText.setText(`mode=icon index=${this.state.selectedIndex} id=${this.state.selectedOption?.id||'-'} locked=${this.state.confirmed}`); }
  hide(){ this.nodes.forEach(n=>{n.removeAllListeners?.();n.destroy();}); this.nodes=[]; this.cards=[]; this.detailNodes=[]; this.state.close(); this.isOpen=false; }
  destroy(){ this.hide(); }
}
