import { DESIGN_WIDTH, DESIGN_HEIGHT } from '../config/gameConfig.js';
import { SKILLS } from '../config/skills.js';
import { ARTIFACTS, ARTIFACT_CATEGORIES } from '../config/artifacts.js';
import { PROFESSIONS } from '../config/professions.js';

const sec=(ms)=>ms==null?'-':`${Math.floor(ms/1000)}s`;
const pct=(n,d)=>d?`${Math.round(n/d*100)}%`:'0%';
const skillName=(skill)=>skill.name||SKILLS[skill.id]?.name||skill.id;
const artifactName=(artifact)=>artifact.name||ARTIFACTS[artifact.id]?.name||artifact.id;
const artifactCategory=(artifact)=>ARTIFACT_CATEGORIES[artifact.category||ARTIFACTS[artifact.id]?.category]?.name||artifact.category||'-';

export default class ResultPanel {
  constructor(scene){ this.scene=scene; this.nodes=[]; this.detailNodes=[]; this.isOpen=false; }
  show(won,onRestart){ this.hide(); this.isOpen=true; const p=this.scene.playerData; const skills=p.skills.map(s=>`${SKILLS[s.id]?.name||s.id} Lv.${s.level}`).join('、')||'无'; const arts=p.artifacts.map(a=>{ const id=typeof a==='string'?a:a.id; return `${ARTIFACTS[id]?.name||id}(${ARTIFACT_CATEGORIES[ARTIFACTS[id]?.category]?.name||'-'})`; }).join('、')||'无'; const professionName=PROFESSIONS[p.professionId]?.name||'-'; const summary=`职业：${professionName}  职业机制触发：${this.scene.runStats.snapshot().professionMechanicTriggers||0}次  职业额外伤害：${this.scene.runStats.snapshot().professionBonusDamage||0}\n等级 ${p.level}  击杀 ${this.scene.killCount}\n技能：${skills}\n法宝：${arts}\n攻击 ${p.attack}  暴击 ${Math.round(p.critChance*100)}%  技能伤害 ${Math.round(p.skillDamageMultiplier*100)}%  冷却缩减 ${Math.round(p.cooldownReduction*100)}%`; const bg=this.scene.add.rectangle(DESIGN_WIDTH/2,DESIGN_HEIGHT/2,680,520,0x111111,0.94).setScrollFactor(0).setDepth(4000); const t=this.scene.add.text(DESIGN_WIDTH/2,DESIGN_HEIGHT/2-190,won?'胜利！':'失败',{fontFamily:'Arial',fontSize:'52px',color:'#fff'}).setOrigin(0.5).setScrollFactor(0).setDepth(4001); const info=this.scene.add.text(DESIGN_WIDTH/2,DESIGN_HEIGHT/2-105,summary,{fontFamily:'Arial',fontSize:'22px',color:'#e8f1ff',align:'center',wordWrap:{width:620}}).setOrigin(0.5,0).setScrollFactor(0).setDepth(4001); const d=this.scene.add.text(DESIGN_WIDTH/2-135,DESIGN_HEIGHT/2+190,'详细数据',{fontFamily:'Arial',fontSize:'26px',color:'#fff',backgroundColor:'#674bd8',padding:{left:20,right:20,top:12,bottom:12}}).setOrigin(0.5).setScrollFactor(0).setInteractive({useHandCursor:true}).setDepth(4001); d.on('pointerdown',()=>this.showDetails()); const b=this.scene.add.text(DESIGN_WIDTH/2+145,DESIGN_HEIGHT/2+190,'重新开始',{fontFamily:'Arial',fontSize:'26px',color:'#fff',backgroundColor:'#2d6cdf',padding:{left:20,right:20,top:12,bottom:12}}).setOrigin(0.5).setScrollFactor(0).setInteractive({useHandCursor:true}).setDepth(4001); b.on('pointerdown',onRestart); this.nodes.push(bg,t,info,d,b); }
  skillDetailLines(s,skillTotal){ if(!s.finalSkills.length) return ['无']; return s.finalSkills.map((skill)=>{ const damage=s.skillDamage[skill.id]||0; const casts=s.skillCasts[skill.id]||0; const name=skillName(skill); if(skill.id==='healing'&&damage<=0) return `${name} Lv.${skill.level}：释放 ${casts} 次`; return `${name} Lv.${skill.level}：${casts}次 / ${damage}伤害 / ${pct(damage,skillTotal)}`; }); }
  artifactDetailLines(s){ if(!s.finalArtifacts.length) return ['无']; return s.finalArtifacts.map((artifact)=>`${artifactName(artifact)}【${artifactCategory(artifact)}】：${s.artifactTriggers[artifact.id]||0}次`); }
  showDetails(){ this.detailNodes.forEach(n=>n.destroy()); const s=this.scene.runStats.snapshot(); const skillTotal=s.finalSkills.reduce((sum,skill)=>sum+(s.skillDamage[skill.id]||0),0); const lines=['节奏数据',`有效时长 ${sec(s.activePlayTimeMs)}`,`首次技能时间 ${sec(s.firstSkillObtainedAt)}`,`首次法宝时间 ${sec(s.firstArtifactObtainedAt)}`,`升级次数 ${s.levelsGained}`,`平均升级间隔 ${sec(s.levelsGained?s.activePlayTimeMs/s.levelsGained:0)}`,`最长升级间隔 ${sec(s.longestUpgradeGapMs)}`,'战斗数据',`职业：${s.professionName||'-'}`,`职业机制触发 ${s.professionMechanicTriggers||0}次`,`职业额外伤害 ${s.professionBonusDamage||0}`,`总伤害 ${s.damageDealt}`,`普攻伤害 ${s.attackDamage}`,`技能伤害 ${skillTotal}`,`燃烧伤害 ${s.statusDamage.burn}`,`中毒伤害 ${s.statusDamage.poison}`,`承受伤害 ${s.damageTaken}`,`护盾吸收 ${s.shieldAbsorbed}`,`技能抵挡 ${s.damageBlockedBySkills||0}`,`治疗量 ${s.healingDone}`,`暴击次数 ${s.criticalHits}`,`中途 Boss：${s.midBossesKilled?'已击杀':'未击杀'}`,`中途 Boss 时长 ${sec(s.midBossFightDurationMs)}`,`最终 Boss 时长 ${sec(s.finalBossFightDurationMs ?? s.bossFightDurationMs)}`,`休息选择：${s.restChoice==='heal'?'恢复':s.restChoice==='skill'?'技能强化':'-'}`,`休息恢复：${s.restHealing||0}`,`休息技能：${s.restSkillChosen||'-'}`,`击杀分类 ${Object.entries(s.enemyKillsByType||{}).map(([k,v])=>`${k}:${v}`).join(' ')||'-'}`,'最终技能',...this.skillDetailLines(s,skillTotal),'最终法宝',...this.artifactDetailLines(s)]; const bg=this.scene.add.rectangle(DESIGN_WIDTH/2,DESIGN_HEIGHT/2,690,1040,0x07101c,0.97).setScrollFactor(0).setDepth(4100); const txt=this.scene.add.text(45,118,lines.join('\n'),{fontFamily:'Arial',fontSize:'19px',color:'#eef6ff',lineSpacing:2,wordWrap:{width:630}}).setScrollFactor(0).setDepth(4101); const close=this.scene.add.text(DESIGN_WIDTH-42,82,'关闭',{fontFamily:'Arial',fontSize:'22px',color:'#fff',backgroundColor:'#444',padding:{left:12,right:12,top:8,bottom:8}}).setOrigin(1,0).setScrollFactor(0).setInteractive({useHandCursor:true}).setDepth(4102); close.on('pointerdown',()=>{this.detailNodes.forEach(n=>n.destroy());this.detailNodes=[];}); this.detailNodes=[bg,txt,close]; }
  hide(){ [...this.nodes,...this.detailNodes].forEach(n=>{ n.removeAllListeners?.(); n.destroy(); }); this.nodes=[]; this.detailNodes=[]; this.isOpen=false; }
}
