import { DESIGN_WIDTH, DESIGN_HEIGHT } from '../config/gameConfig.js';
import { SKILLS } from '../config/skills.js';
import { ARTIFACTS } from '../config/artifacts.js';
import { getBuildTags } from '../systems/RunStatsSystem.js';
const sec=(ms)=>ms==null?'-':`${Math.floor(ms/1000)}s`;
const pct=(n,d)=>d?`${Math.round(n/d*100)}%`:'0%';
export default class ResultPanel {
  constructor(scene){ this.scene=scene; this.nodes=[]; this.detailNodes=[]; this.isOpen=false; }
  show(won,onRestart){ this.hide(); this.isOpen=true; const p=this.scene.playerData; const skills=p.skills.map(s=>`${SKILLS[s.id]?.name||s.id} Lv.${s.level}`).join('、')||'无'; const arts=p.artifacts.map(id=>ARTIFACTS[id]?.name||id).join('、')||'无'; const tags=getBuildTags(p); const summary=`等级 ${p.level}  击杀 ${this.scene.killCount}\n技能：${skills}\n法宝：${arts}\n攻击 ${p.attack}  暴击 ${Math.round(p.critChance*100)}%  技能伤害 ${Math.round(p.skillDamageMultiplier*100)}%  冷却缩减 ${Math.round(p.cooldownReduction*100)}%\n流派标签：${tags.join('、')||'无'}`; const bg=this.scene.add.rectangle(DESIGN_WIDTH/2,DESIGN_HEIGHT/2,680,560,0x111111,0.94).setScrollFactor(0).setDepth(4000); const t=this.scene.add.text(DESIGN_WIDTH/2,DESIGN_HEIGHT/2-210,won?'胜利！':'失败',{fontFamily:'Arial',fontSize:'52px',color:'#fff'}).setOrigin(0.5).setScrollFactor(0).setDepth(4001); const info=this.scene.add.text(DESIGN_WIDTH/2,DESIGN_HEIGHT/2-120,summary,{fontFamily:'Arial',fontSize:'22px',color:'#e8f1ff',align:'center',wordWrap:{width:620}}).setOrigin(0.5,0).setScrollFactor(0).setDepth(4001); const d=this.scene.add.text(DESIGN_WIDTH/2-135,DESIGN_HEIGHT/2+205,'详细数据',{fontFamily:'Arial',fontSize:'26px',color:'#fff',backgroundColor:'#674bd8',padding:{left:20,right:20,top:12,bottom:12}}).setOrigin(0.5).setScrollFactor(0).setInteractive({useHandCursor:true}).setDepth(4001); d.on('pointerdown',()=>this.showDetails()); const b=this.scene.add.text(DESIGN_WIDTH/2+145,DESIGN_HEIGHT/2+205,'重新开始',{fontFamily:'Arial',fontSize:'26px',color:'#fff',backgroundColor:'#2d6cdf',padding:{left:20,right:20,top:12,bottom:12}}).setOrigin(0.5).setScrollFactor(0).setInteractive({useHandCursor:true}).setDepth(4001); b.on('pointerdown',onRestart); this.nodes.push(bg,t,info,d,b); }
  showDetails(){ this.detailNodes.forEach(n=>n.destroy()); const s=this.scene.runStats.snapshot(); const skillTotal=Object.values(s.skillDamage).reduce((a,b)=>a+b,0); const lines=['节奏数据',`有效时长 ${sec(s.activePlayTimeMs)}`,`首技能 ${sec(s.firstSkillObtainedAt)}  首法宝 ${sec(s.firstArtifactObtainedAt)}`,`升级次数 ${s.levelsGained}  平均间隔 ${sec(s.levelsGained?s.activePlayTimeMs/s.levelsGained:0)}`,`最长升级间隔 ${sec(s.longestUpgradeGapMs)}`,'','战斗数据',`总伤害 ${s.damageDealt}  普攻伤害 ${s.attackDamage}`,`技能伤害 ${skillTotal}  燃烧 ${s.statusDamage.burn}  中毒 ${s.statusDamage.poison}`,`承受 ${s.damageTaken}  护盾 ${s.shieldAbsorbed}  治疗 ${s.healingDone}`,`暴击次数 ${s.criticalHits}`,'','构筑数据',`最终技能 ${s.finalSkills.map(x=>`${x.name}Lv.${x.level}`).join('、')||'无'}`,`最终法宝 ${s.finalArtifacts.map(x=>x.name).join('、')||'无'}`,`流派 ${s.buildTags.join('、')||'无'}`,'技能释放/伤害占比:',...Object.entries(SKILLS).map(([id,c])=>`${c.name}: ${s.skillCasts[id]||0}次 / ${s.skillDamage[id]||0} (${pct(s.skillDamage[id]||0,skillTotal)})`),'法宝触发:',...Object.entries(ARTIFACTS).map(([id,c])=>`${c.name}: ${s.artifactTriggers[id]||0}次`)]; const bg=this.scene.add.rectangle(DESIGN_WIDTH/2,DESIGN_HEIGHT/2,690,1040,0x07101c,0.97).setScrollFactor(0).setDepth(4100); const txt=this.scene.add.text(45,135,lines.join('\n'),{fontFamily:'Arial',fontSize:'20px',color:'#eef6ff',lineSpacing:4,wordWrap:{width:630}}).setScrollFactor(0).setDepth(4101); const close=this.scene.add.text(DESIGN_WIDTH-42,92,'关闭',{fontFamily:'Arial',fontSize:'22px',color:'#fff',backgroundColor:'#444',padding:{left:12,right:12,top:8,bottom:8}}).setOrigin(1,0).setScrollFactor(0).setInteractive({useHandCursor:true}).setDepth(4102); close.on('pointerdown',()=>{this.detailNodes.forEach(n=>n.destroy());this.detailNodes=[];}); this.detailNodes=[bg,txt,close]; }
  hide(){ [...this.nodes,...this.detailNodes].forEach(n=>{ n.removeAllListeners?.(); n.destroy(); }); this.nodes=[]; this.detailNodes=[]; this.isOpen=false; }
}
