import { SKILLS } from '../config/skills.js';
import { getRarity } from '../config/rarities.js';
import { ARTIFACTS, ARTIFACT_CATEGORIES, getArtifactLevelText } from '../config/artifacts.js';
import { PROFESSIONS, PROFESSION_ATTACK_PROFILES } from '../config/professions.js';

export const TAG_DISPLAY_NAMES = Object.freeze({
  fire:'火焰', poison:'剧毒', lightning:'雷电', dot:'持续伤害', critical:'暴击', normalAttack:'普攻', activeSkill:'主动技能', summon:'召唤', shield:'护盾', healing:'治疗', melee:'近战', projectile:'投射物', physical:'物理', area:'范围', survival:'生存', magic:'魔法', mark:'标记', shadow:'暗影', curse:'诅咒', holy:'神圣', time:'时间', burn:'燃烧', attack:'攻击', speed:'速度', damage:'伤害'
});
export const SELECTION_ICON_STYLE = Object.freeze({ colors:[0xff6533,0x66ccff,0x42c978,0xd8b4ff,0xffd166,0x58d7ff], shapes:['circle','square','diamond'] });
export const resolveSelectionMode = (options=[], explicitMode=null) => explicitMode || (options?.some(o=>o.artifactId||o.kind==='artifact'||o.type==='fallback')?'icon':'card');
const text = (v, fallback='') => (v===0 ? '0' : (v == null ? fallback : String(v)));
const lines = (v) => Array.isArray(v) ? v.map(x=>text(x)).filter(Boolean) : text(v).split('\n').filter(Boolean);
export const formatTags = (tags=[]) => (Array.isArray(tags)?tags:[]).map(t=>TAG_DISPLAY_NAMES[t]||t).filter(Boolean);
const attrLabels = { attack_15:['攻击强化','属性升级','攻击力 +15%'], hp_20:['生命强化','属性升级','最大生命 +20'], as_10:['速度强化','属性升级','攻击速度 +10%'], skill_15:['技能强化','属性升级','技能伤害 +15%'], cdr_8:['冷却强化','属性升级','冷却缩减 +8%'], crit_5:['暴击强化','属性升级','暴击率 +5%'] };
export function formatSkillSelectionOption(option={}, playerData={}){
  const skill = option.skillId ? SKILLS[option.skillId] : null;
  if(!skill){ const m=attrLabels[option.id]||[text(option.title,'属性提升').split('\n')[0]||'属性提升','属性升级',lines(option.title).slice(1).join(' / ')||'属性提升']; return { ...option, kind:'attribute', title:m[0], subtitle:m[1], iconText:m[0][0], rarity:'属性', rarityColor:0x62e883, levelText:'立即生效', summaryLines:[m[2]], detailLines:[m[2]], tags:['属性'], confirmText:'确认选择' }; }
  const owned=(playerData.skills||[]).find(s=>s.id===skill.id); const cur=owned?.level||0; const target=option.type==='skillLevel'?Math.min(skill.maxLevel||cur+1,cur+1):1; const data=skill.levels?.[Math.max(0,target-1)]||skill.levels?.[0]||{}; const curData=cur>0 ? skill.levels?.[cur-1] : null; const rarity=getRarity(skill.rarity)||{}; const summary=lines(data.changes).slice(0,3); if(!summary.length) summary.push(data.desc||skill.description||'获得新的技能效果');
  return { ...option, kind:'skill', title:skill.name||option.skillId||'未知技能', subtitle: skill.passive?'被动技能':'技能', iconText:skill.short||skill.name?.[0]||'技', iconColor:skill.color, rarity:rarity.name||skill.rarity||'普通', rarityColor:rarity.color||0x5278c8, rarityUiColor:rarity.uiColor, levelText: option.type==='skillLevel'?`Lv.${cur} → Lv.${target}`:'获得 Lv.1', acquireText: option.type==='skillLevel'?'升级技能':'获得技能', summaryLines:summary, detailLines:[`当前：${curData?.desc|| (cur ? skill.description : '尚未获得')}`, `目标：${data.desc||skill.description||'无说明'}`, ...summary], tags:formatTags(skill.tags), confirmText: option.type==='skillLevel'?'升级技能':'获得技能' };
}
export function formatArtifactSelectionOption(option={}){
  if(option.type==='fallback'){ const titleLines=lines(option.title||option.name||'保底奖励'); const name=(titleLines[0]||'保底奖励').split('｜')[0]||'保底奖励'; const category=(titleLines[0]||'').split('｜')[1]||'属性奖励'; const effects=[...titleLines.slice(1), ...lines(option.description)].filter(Boolean); const detailLines=effects.length?effects:['获得属性奖励']; return { ...option, kind:'artifact', title:name, subtitle:category.includes('属性')?'属性奖励':'保底', iconText:name[0], levelText:'', summaryLines:detailLines.slice(0,2), detailLines, category, tags:formatTags(option.tags||[]), confirmText:'获得奖励' }; }
  const artifact=ARTIFACTS[option.artifactId]||{}; const name=artifact.name||option.name||option.title||option.artifactId||'法宝奖励'; const category=ARTIFACT_CATEGORIES[artifact.category]?.name||artifact.category||option.category||'法宝'; const isUp=option.type==='upgrade'; const levelText=isUp?`Lv.${text(option.level,0)} → Lv.${text(option.nextLevel, (option.level||0)+1)}`:`Lv.${text(option.nextLevel,1)}`; const cur=isUp?getArtifactLevelText(option.artifactId,option.level):''; const next=getArtifactLevelText(option.artifactId,option.nextLevel||1)||artifact.description||option.description||'获得法宝奖励'; return { ...option, kind:'artifact', title:name, subtitle:isUp?'升级':'获得', iconText:name[0], iconColor:artifact.color, levelText, summaryLines:[next], detailLines:[...(cur?[`当前：${cur}`]:[]), `${isUp?'升级后':'效果'}：${next}`, ...(option.requiredSkillName?[`所需技能：${option.requiredSkillName}`]:[])], category, tags:formatTags([...(artifact.tags||[]),...(artifact.supportedTags||[]),...(artifact.affectedTags||[])]), confirmText:isUp?'升级法宝':'获得法宝' };
}
export function formatProfessionSelectionOption(id){ const p=typeof id==='string'?PROFESSIONS[id]:id||{}; const profile=PROFESSION_ATTACK_PROFILES[p.professionAttackProfile]||{}; return { ...p, kind:'profession', title:p.name||p.id||'未知职业', subtitle:'职业', iconText:(p.name||'?')[0], iconColor:p.color, summaryLines:[p.description||'暂无定位'], detailLines:[`职业定位：${p.description||'暂无'}`, `普攻方式：${profile.type||p.professionAttackProfile||'默认'}`, `核心被动：${p.mechanic||'暂无'}`, `优缺点：定位清晰，需围绕推荐标签构筑。`], tags:formatTags(p.supportedTags), confirmText:'选择职业' }; }
export class SelectionState { constructor(){this.reset();} reset(){this.selectedIndex=-1;this.selectedOption=null;this.confirmed=false;this.isOpen=false;} open(){this.reset();this.isOpen=true;} select(i,o){ if(!this.isOpen||this.confirmed) return false; this.selectedIndex=i; this.selectedOption=o; return true;} confirm(cb){ if(!this.isOpen||this.confirmed||this.selectedIndex<0) return false; this.confirmed=true; cb?.(this.selectedOption,this.selectedIndex); return true;} close(){this.reset();} }
