import Phaser from 'phaser';
import { DESIGN_WIDTH, DESIGN_HEIGHT } from '../config/gameConfig.js';
import { SKILLS } from '../config/skills.js';

const PAGE_SIZE = 4;

export default class SkillBar {
  constructor(scene){ this.scene=scene; this.page=0; this.nodes=[]; this.create(); }
  create(){ const y=DESIGN_HEIGHT-86; this.bg=this.scene.add.rectangle(DESIGN_WIDTH/2,y,690,132,0x0c1324,0.72).setScrollFactor(0).setDepth(2100); this.prev=this.scene.add.text(22,y,'‹',{fontFamily:'Arial',fontSize:'44px',color:'#fff',backgroundColor:'#203a74',padding:{left:12,right:12,top:2,bottom:2}}).setOrigin(0,0.5).setScrollFactor(0).setInteractive({useHandCursor:true}).setDepth(2101); this.next=this.scene.add.text(DESIGN_WIDTH-22,y,'›',{fontFamily:'Arial',fontSize:'44px',color:'#fff',backgroundColor:'#203a74',padding:{left:12,right:12,top:2,bottom:2}}).setOrigin(1,0.5).setScrollFactor(0).setInteractive({useHandCursor:true}).setDepth(2101); this.pageText=this.scene.add.text(DESIGN_WIDTH/2,DESIGN_HEIGHT-24,'',{fontFamily:'Arial',fontSize:'18px',color:'#d7e6ff',stroke:'#000',strokeThickness:3}).setOrigin(0.5).setScrollFactor(0).setDepth(2101); this.prev.on('pointerdown',()=>this.changePage(-1)); this.next.on('pointerdown',()=>this.changePage(1)); this.nodes.push(this.bg,this.prev,this.next,this.pageText); this.slots=Array.from({ length:PAGE_SIZE },(_,i)=>this.createSlot(100+i*132,y)); }
  createSlot(x,y){ const box=this.scene.add.rectangle(x,y,104,104,0x172646,0.94).setStrokeStyle(3,0x5f85d6,1).setScrollFactor(0).setDepth(2101); const name=this.scene.add.text(x,y-24,'',{fontFamily:'Arial',fontSize:'28px',color:'#fff',stroke:'#000',strokeThickness:4}).setOrigin(0.5).setScrollFactor(0).setDepth(2102); const level=this.scene.add.text(x,y+26,'',{fontFamily:'Arial',fontSize:'18px',color:'#d7e6ff',stroke:'#000',strokeThickness:3}).setOrigin(0.5).setScrollFactor(0).setDepth(2102); const cooldown=this.scene.add.text(x,y,'',{fontFamily:'Arial',fontSize:'30px',color:'#ffe16a',stroke:'#000',strokeThickness:5}).setOrigin(0.5).setScrollFactor(0).setDepth(2103); const overlay=this.scene.add.rectangle(x,y,104,104,0x000000,0.45).setScrollFactor(0).setDepth(2102); const slot={box,name,level,cooldown,overlay}; this.nodes.push(box,name,level,cooldown,overlay); return slot; }
  changePage(delta){ const total=this.totalPages(); this.page=Phaser.Math.Wrap(this.page+delta,0,total); this.update(); }
  totalPages(){ return Math.max(1,Math.ceil((this.scene.playerData?.skills?.length||0)/PAGE_SIZE)); }
  update(){ const skills=this.scene.playerData?.skills||[]; const total=this.totalPages(); if(this.page>=total) this.page=total-1; this.prev.setVisible(total>1); this.next.setVisible(total>1); this.pageText.setText(total>1?`${this.page+1}/${total}`:''); const now=this.scene.getGameplayTime?.() ?? this.scene.time.now; this.slots.forEach((slot,i)=>{ const owned=skills[this.page*PAGE_SIZE+i]; const visible=!!owned; [slot.box,slot.name,slot.level,slot.cooldown,slot.overlay].forEach(n=>n.setVisible(visible)); if(!owned) return; const cfg=SKILLS[owned.id]; const readyAt=this.scene.skillSystem?.cooldowns.get(owned.id)||0; const remaining=Math.max(0,Math.ceil((readyAt-now)/1000)); slot.name.setText(cfg?.short||'?'); slot.level.setText(`Lv.${owned.level}`); slot.cooldown.setText(remaining>0?`${remaining}`:''); slot.overlay.setVisible(remaining>0); }); }
  destroy(){ this.nodes.forEach(n=>{ n.removeAllListeners?.(); n.destroy(); }); this.nodes=[]; this.slots=[]; }
}
