import { ARTIFACTS } from '../config/artifacts.js';
import { CombatEvents, ACTIVE_STATES } from '../core/CombatEvents.js';
export default class ArtifactSystem { constructor(scene){ this.scene=scene; this.unsubs=[]; this.cooldowns=new Map(); this.burns=new Map(); } load(){ this.cleanup(); this.scene.playerData.artifacts.forEach(id=>this.register(id)); } add(id){ if(!this.scene.playerData.artifacts.includes(id)) this.scene.playerData.artifacts.push(id); this.register(id); this.scene.hud?.update(); }
  register(id){ const cfg=ARTIFACTS[id]; if(!cfg) return; const off=this.scene.eventBus.on(cfg.listenEvent,(p)=>this.tryTrigger(cfg,p)); this.unsubs.push(off); }
  shiftTimers(pausedDuration, pausedAt){ this.cooldowns.forEach((readyAt,id)=>{ if(readyAt>pausedAt) this.cooldowns.set(id, readyAt+pausedDuration); }); this.burns.forEach((burn, enemy)=>{ if(!this.scene.targeting.valid(enemy)){ this.burns.delete(enemy); return; } if(burn.nextTickAt>pausedAt) burn.nextTickAt+=pausedDuration; }); }
  tryTrigger(cfg,payload){ const now=this.scene.getGameplayTime(); if(now<(this.cooldowns.get(cfg.id)||0)) return; if(cfg.id==='flame_heart' && !payload.tags?.includes('fire')) return; if(payload.source==='burn') return; this.cooldowns.set(cfg.id, now+cfg.internalCooldownMs); this.scene.eventBus.emit(CombatEvents.ARTIFACT_TRIGGERED,{ artifact:cfg, payload }); if(cfg.id==='thunder_orb'){ const e=this.scene.targeting.random(); if(e) this.scene.combatSystem.damageEnemy(e,18,{ source:'artifact', artifactId:cfg.id, tags:cfg.tags }); }
    if(cfg.id==='blood_jade'){ const heal=6; this.scene.playerData.hp=Math.min(this.scene.playerData.maxHp,this.scene.playerData.hp+heal); this.scene.floatText(this.scene.player.x,this.scene.player.y-96,`+${heal}`,'#ff6f9f'); this.scene.hud?.update(); }
    if(cfg.id==='flame_heart' && payload.enemy) this.applyBurn(payload.enemy); }
  applyBurn(enemy){ if(!this.scene.targeting.valid(enemy)) return; this.burns.set(enemy,{ enemy, ticksRemaining:3, nextTickAt:this.scene.getGameplayTime()+500, intervalMs:500 }); }
  clearBurn(enemy){ this.burns.delete(enemy); }
  update(time){ if(this.scene.isGameplayPaused?.()||!ACTIVE_STATES.has(this.scene.runState)) return; this.burns.forEach((burn, enemy)=>{ if(!this.scene.targeting.valid(enemy)){ this.burns.delete(enemy); return; } while(burn.ticksRemaining>0 && time>=burn.nextTickAt && this.scene.targeting.valid(enemy)){ burn.ticksRemaining-=1; this.scene.combatSystem.damageEnemy(enemy,5,{ source:'burn', tags:['burn'], canTriggerArtifacts:false }); burn.nextTickAt+=burn.intervalMs; } if(burn.ticksRemaining<=0||!this.scene.targeting.valid(enemy)) this.burns.delete(enemy); }); }
  cleanup(){ this.unsubs.forEach(off=>off()); this.unsubs=[]; this.cooldowns.clear(); this.burns.clear(); }
}
