const Phaser = globalThis.Phaser || { Math:{ Distance:{ Between:(x1,y1,x2,y2)=>Math.hypot(x2-x1,y2-y1) } } };
import { CombatEvents } from '../core/CombatEvents.js';
import { getWeapon } from '../config/weapons.js';
import { syncEnemyUi } from '../entities/createEnemy.js';
import { TAGS } from '../config/tags.js';
import { mergeTags } from '../utils/tagUtils.js';
import { applyLifeStealFromDamage } from './LifeSteal.js';

const BEHAVIOR_ATTACKERS = new Set(['charger', 'bomber', 'healer', 'midBoss', 'berserkerBoss']);

export default class CombatSystem {
  constructor(scene){ this.scene=scene; this.nextPlayerAttackAt=0; }
  reset(){ this.nextPlayerAttackAt=0; }
  shiftTimers(pausedDuration, pausedAt){ if(this.nextPlayerAttackAt>pausedAt) this.nextPlayerAttackAt+=pausedDuration; this.scene.enemies?.forEach(e=>{ if(!e.isDefeated&&e.nextAttackAt>pausedAt) e.nextAttackAt+=pausedDuration; }); }
  update(time){ const s=this.scene; if(s.isGameplayPaused?.()||s.playerData.hp<=0) return; const enemies=s.targeting.all(); enemies.forEach(e=>this.updateEnemyAttack(e,time)); const weapon=getWeapon(s.playerData.weaponId); const profile=s.professionSystem?.currentAttackProfile?.(); const range=profile?.range ?? weapon.attackRange; const target=s.targeting.nearestAhead(range); if(target && time>=this.nextPlayerAttackAt){ const interval=(weapon.attackIntervalMs*(profile?.intervalMultiplier||1))/Math.max(0.2,s.playerData.attackSpeedMultiplier); this.nextPlayerAttackAt=time+interval; this.performAttack(target, weapon, profile); } }
  performAttack(target, weapon, profile){ if(!profile) return this.performDefaultAttack(target, weapon); if(profile.type==='swordSlash') return this.performSwordSlashAttack(profile, weapon); if(profile.type==='arcaneBolt') return this.performArcaneBoltAttack(target, profile, weapon); if(profile.type==='hunterArrow') return this.performHunterArrowAttack(target, profile, weapon); return this.performDefaultAttack(target, weapon); }
  calcAttackDamage(weapon, profile=null){ const s=this.scene; const crit=Math.random()<s.playerData.critChance; const artifactMult=s.artifactSystem?.highHpDamageMultiplier?.() || 1; const professionMult=s.professionSystem?.getDamageMultiplier?.({ type:'normalAttack' })||1; const baseBeforeProfession=Math.round(s.playerData.attack*weapon.damageMultiplier*(profile?.damageMultiplier||1)*(crit?s.playerData.critMultiplier:1)*artifactMult); return { crit, professionMult, baseBeforeProfession, damage:Math.round(baseBeforeProfession*professionMult) }; }
  applyAttackDamage(enemy, result, tags=['physical'], extra={}){ const s=this.scene; const sourceTags=mergeTags([TAGS.NORMAL_ATTACK], tags); const damaged=this.damageEnemy(enemy,result.damage,{ source:'attack', tags:sourceTags, canTriggerArtifacts:true, allowLifeSteal:true, professionMultiplier:result.professionMult, baseAmountBeforeProfession:result.baseBeforeProfession, professionApplied:true, ...extra }); if(!damaged) return; s.professionSystem?.onDirectHit?.({ enemy, source:'attack', baseDamage:result.baseBeforeProfession }); if(result.crit) s.eventBus.emit(CombatEvents.PLAYER_CRIT,{ enemy, damage:result.damage, forcedCrit:false }); s.eventBus.emit(CombatEvents.PLAYER_HIT,{ enemy, damage:result.damage, crit:result.crit, forcedCrit:false, tags:sourceTags, source:'attack' }); }
  performDefaultAttack(enemy, weapon){ const s=this.scene; if(!s.targeting.valid(enemy)) return; s.eventBus.emit(CombatEvents.PLAYER_ATTACK,{ enemy, weapon }); this.applyAttackDamage(enemy,this.calcAttackDamage(weapon),['physical',TAGS.MELEE]); }
  performSwordSlashAttack(profile, weapon){ const s=this.scene; s.eventBus.emit(CombatEvents.PLAYER_ATTACK,{ enemy:null, weapon, profile }); s.professionWeaponView?.playAttack(profile.id); const x=s.player.x+112, y=s.player.y-42; const arc=s.add.arc(x,y,118,210,330,false,0xcff5ff,0.34).setStrokeStyle(14,0xe8fbff,0.95).setDepth(135); s.tweens.add({targets:arc,scaleX:1.16,alpha:0,duration:150,onComplete:()=>arc.destroy()}); const targets=s.targeting.all().filter(e=>e.x>=s.player.x-25 && e.x-s.player.x<=profile.range && Math.abs(e.y-s.player.y)<145).sort((a,b)=>a.x-b.x).slice(0,profile.pierce); targets.forEach(e=>{ const r=this.calcAttackDamage(weapon,profile); this.applyAttackDamage(e,r,['physical','slash',TAGS.MELEE]); this.slashHit(e); if(e.body) e.x+=18; }); }
  performArcaneBoltAttack(enemy, profile, weapon){ const s=this.scene; if(!s.targeting.valid(enemy)) return; s.eventBus.emit(CombatEvents.PLAYER_ATTACK,{ enemy, weapon, profile }); s.professionWeaponView?.playAttack(profile.id); this.flyProjectile({ enemy, profile, weapon, color:0x9ee8ff, radius:15, fromX:s.player.x+72, fromY:s.player.y-100, tags:['arcane',TAGS.PROJECTILE] }); }
  performHunterArrowAttack(enemy, profile, weapon){ const s=this.scene; if(!s.targeting.valid(enemy)) return; s.eventBus.emit(CombatEvents.PLAYER_ATTACK,{ enemy, weapon, profile }); s.professionWeaponView?.playAttack(profile.id); this.flyProjectile({ enemy, profile, weapon, color:0xd8f5ff, radius:6, fromX:s.player.x+82, fromY:s.player.y-64, tags:['physical',TAGS.PROJECTILE], arrow:true }); }
  flyProjectile({ enemy, profile, weapon, color, radius, fromX, fromY, tags, arrow=false }){ const s=this.scene; const dist=Phaser.Math.Distance.Between(fromX,fromY,enemy.x,enemy.y-42); const duration=Math.max(80,dist/(profile.projectileSpeed||520)*1000); const obj=arrow ? s.add.rectangle(fromX,fromY,86,7,color,1).setStrokeStyle(2,0x1d4660,1) : s.add.circle(fromX,fromY,radius,color,1).setStrokeStyle(4,0xffffff,0.7); obj.setDepth(145); if(arrow) obj.rotation=Phaser.Math.Angle.Between(fromX,fromY,enemy.x,enemy.y-42); s.tweens.add({targets:obj,x:enemy.x,y:enemy.y-42,duration,onComplete:()=>{ obj.destroy(); if(!s.targeting.valid(enemy)) return; const r=this.calcAttackDamage(weapon,profile); this.applyAttackDamage(enemy,r,tags,{ allowLifeSteal:true }); profile.hitEffectId==='arcane_burst'?this.arcaneHit(enemy):this.pierceHit(enemy); }}); }
  slashHit(e){ const o=this.scene.add.circle(e.x,e.y-50,34,0xffffff,0.22).setStrokeStyle(5,0xcff5ff,1).setDepth(150); this.scene.tweens.add({targets:o,alpha:0,scale:1.25,duration:180,onComplete:()=>o.destroy()}); }
  arcaneHit(e){ const o=this.scene.add.circle(e.x,e.y-48,42,0x7d6fff,0.2).setStrokeStyle(5,0xb7fbff,1).setDepth(150); this.scene.tweens.add({targets:o,alpha:0,scale:1.35,duration:240,onComplete:()=>o.destroy()}); }
  pierceHit(e){ const g=this.scene.add.graphics().setDepth(150); g.lineStyle(5,0xd8f5ff,1).lineBetween(e.x-32,e.y-58,e.x+32,e.y-34); this.scene.tweens.add({targets:g,alpha:0,duration:160,onComplete:()=>g.destroy()}); }
  damageEnemy(enemy, amount, meta={}){ if(!this.scene.targeting.valid(enemy)) return false; if(!this.scene.targeting.isEnemyFullyInsideViewport(enemy)) return false; const professionMult=meta.professionApplied ? (meta.professionMultiplier||1) : (this.scene.professionSystem?.getDamageMultiplier?.({ type:meta.source==='skill'?'activeSkill':meta.source, damaging:true })||1); const baseBeforeProfession=Math.max(0, Math.round(meta.baseAmountBeforeProfession ?? (meta.professionApplied && professionMult>0 ? amount/professionMult : amount))); const boosted=meta.professionApplied ? Math.round(amount) : Math.round(amount*professionMult); const reduced=Math.max(0, Math.round(boosted*(1-(enemy.damageReduction||0))-(enemy.defense||0))); const baseReduced=Math.max(0, Math.round(baseBeforeProfession*(1-(enemy.damageReduction||0))-(enemy.defense||0))); const hpBefore=enemy.hp; enemy.hp=Math.max(0, enemy.hp-reduced); const actualDamage=hpBefore-enemy.hp; const actualWithoutProfession=Math.min(hpBefore,baseReduced); const professionBonus=professionMult>1 ? Math.min(actualDamage, Math.max(0, actualDamage-actualWithoutProfession)) : 0; if(actualDamage>0){ this.scene.floatText(enemy.x, enemy.y-60, `-${actualDamage}`, meta.source==='burn'?'#ff8a33':'#fff'); syncEnemyUi(enemy); this.scene.eventBus.emit(CombatEvents.ENEMY_HIT,{ enemy, damage:actualDamage, professionBonusDamage:professionBonus, ...meta }); if(meta.source==='attack'||meta.source==='normalAttack') this.applyKnockback(enemy, meta); this.applyLifeSteal(actualDamage, meta); } else syncEnemyUi(enemy); if(enemy.hp<=0) this.handleDeathReactions(enemy, meta); if(enemy.hp<=0) this.killEnemy(enemy, meta); return actualDamage > 0; }


  applyKnockback(enemy, meta={}){ if(!enemy?.body||enemy.isDefeated) return; const base=meta.knockback ?? 18; const mult=enemy.isBoss?0.12:(enemy.isElite?0.35:(enemy.enemyId==='armored_guard'?0.6:1)); const dx=Math.max(2,Math.round(base*mult)); const maxX=(this.scene.balance.stageWorldWidth||14900)-enemy.width/2-8; enemy.x=Math.min(maxX, enemy.x+dx); enemy.body?.reset?.(enemy.x, enemy.y); }

  applyLifeSteal(actualDamage, meta={}){ return applyLifeStealFromDamage(this.scene, actualDamage, meta); }
  damagePlayer(enemy, rawDamage, meta={}){ const s=this.scene; if(s.isGameplayPaused?.()||s.playerData.hp<=0) return; const base=Math.max(1, Math.round(rawDamage*(1-s.playerData.damageReduction)-s.playerData.defense)); const damage=Math.max(1, Math.round(base*(1-(s.playerData.temporaryDamageReduction||0)))); const intercepted=s.skillSystem?.beforePlayerDamage({ enemy, damage, rawDamage, ...meta }); if(intercepted?.blocked){ const blocked=intercepted.absorbed||damage; s.floatText(s.player.x, s.player.y-92, '吞弹抵挡', '#58d7ff'); s.eventBus.emit(CombatEvents.PLAYER_DAMAGED,{ enemy, damage, hpDamage:0, shieldAbsorbed:0, skillBlocked:blocked, blocked:true, blockedBySkillId:intercepted.blockedBySkillId||'bullet_eater', ...meta }); s.hud?.update(); return; } const shieldResult=s.statusEffects?.absorbShield(damage)||{absorbed:0,remainingDamage:damage}; const absorbed=shieldResult.absorbed; const hpDmg=shieldResult.remainingDamage; s.playerData.hp=Math.max(0,s.playerData.hp-hpDmg); s.floatText(s.player.x, s.player.y-80, absorbed&&hpDmg?`盾-${absorbed} -${hpDmg}`:absorbed?`盾-${absorbed}`:`-${hpDmg}`, absorbed?'#8fd7ff':'#ff7777'); s.eventBus.emit(CombatEvents.PLAYER_DAMAGED,{ enemy, damage, hpDamage:hpDmg, shieldAbsorbed:absorbed, ...meta }); if(s.playerData.hp/s.playerData.maxHp <=0.3) s.eventBus.emit(CombatEvents.PLAYER_LOW_HP,{ hp:s.playerData.hp }); s.hud?.update(); if(s.playerData.hp<=0) s.finishRun(false); }
  killEnemy(enemy, meta={}){ if(!enemy||enemy.isDefeated) return; const s=this.scene; enemy.isDefeated=true; s.statusEffects?.clearTarget(enemy); enemy.body&&(enemy.body.enable=false); s.enemies=s.enemies.filter(e=>e!==enemy); s.killCount += enemy.isBoss ? 0 : 1; const gold=enemy.isMidBoss?40:enemy.isElite?15:(enemy.isBoss?0:1); if(gold) s.awardGold?.(gold, enemy.isMidBoss?'midBoss':enemy.isElite?'eliteEnemy':'normalEnemy'); s.eventBus.emit(CombatEvents.ENEMY_KILLED,{ enemy, ...meta }); if(enemy.isBoss){ const flowBossType=enemy.enemyId==='berserker_boss'?'boss1':(enemy.isMidBoss?'boss2':'boss3'); s.eventBus.emit(CombatEvents.BOSS_KILLED,{ enemy, bossType:enemy.isMidBoss?'mid':(enemy.isFinalBoss?'final':'boss1'), flowBossType }); s.stageSystem?.clearBossMinions?.(); s.stageSystem?.onBossKilled?.(flowBossType); if(enemy.isMidBoss) s.runStats?.endMidBossFight?.(); } else if(enemy.isElite){ /* no experience in 0.10.0 */ } else { /* no experience in 0.10.0 */ } [enemy.hpBarBg, enemy.hpBar, enemy.nameText].forEach(o=>o?.destroy()); s.tweens.add({ targets:enemy, alpha:0, duration:s.balance.enemyFadeMs, onComplete:()=>enemy.destroy() }); }
  handleDeathReactions(enemy, meta={}){ const s=this.scene; if(enemy._deathReacted) return; enemy._deathReacted=true; const all=s.targeting.all().filter(e=>e!==enemy); if(s.statusEffects?.has(enemy,'BURN')&&!meta.noDeathExplosion){ all.filter(e=>Phaser.Math.Distance.Between(e.x,e.y,enemy.x,enemy.y)<=95).forEach(e=>this.damageEnemy(e,8,{source:'burn_burst',tags:[TAGS.FIRE,TAGS.DOT],noDeathExplosion:true})); } const spreadingPoison=s.statusEffects?.getEffects(enemy,'POISON').find(e=>e.canSpread); if(spreadingPoison&&!meta.noPoisonSpread){ const r=spreadingPoison.spreadRadius||105; all.filter(e=>Phaser.Math.Distance.Between(e.x,e.y,enemy.x,enemy.y)<=r).forEach(e=>s.statusEffects.add('POISON',e,{durationMs:spreadingPoison.spreadDurationMs||2200,intervalMs:650,value:spreadingPoison.spreadDamage||5,sourceId:'poison_spread',canSpread:false,damageMultiplier:spreadingPoison.damageMultiplier||1,baseDamageMultiplierWithoutProfession:spreadingPoison.baseDamageMultiplierWithoutProfession||spreadingPoison.damageMultiplier||1,professionMultiplier:spreadingPoison.professionMultiplier||1,professionApplied:!!spreadingPoison.professionApplied})); } }
  updateEnemyAttack(enemy,time){ const s=this.scene; if(!s.targeting.valid(enemy)) return; if(BEHAVIOR_ATTACKERS.has(enemy.behavior)) return; if(enemy.isBoss && !enemy.enraged && enemy.hp <= enemy.maxHp/2){ enemy.enraged=true; enemy.attackIntervalMs=enemy.enragedAttackIntervalMs; s.hud?.setStatus('Boss 半血狂暴：攻击速度提升！'); } const d=Math.abs(enemy.x-s.player.x); if(d>enemy.attackRange) return; if(time < enemy.nextAttackAt) return; enemy.nextAttackAt=time+enemy.attackIntervalMs; this.damagePlayer(enemy, enemy.damage, { source:'enemyMelee' }); }
}
