import Phaser from 'phaser';
import { CombatEvents } from '../core/CombatEvents.js';
import { getWeapon } from '../config/weapons.js';
import { syncEnemyUi } from '../entities/createEnemy.js';
export default class CombatSystem { constructor(scene){ this.scene=scene; this.nextPlayerAttackAt=0; } reset(){ this.nextPlayerAttackAt=0; } shiftTimers(pausedDuration, pausedAt){ if(this.nextPlayerAttackAt>pausedAt) this.nextPlayerAttackAt+=pausedDuration; this.scene.enemies?.forEach(e=>{ if(!e.isDefeated&&e.nextAttackAt>pausedAt) e.nextAttackAt+=pausedDuration; }); } update(time){ const s=this.scene; if(s.isGameplayPaused?.()||s.playerData.hp<=0) return; const enemies=s.targeting.all(); enemies.forEach(e=>this.updateEnemyAttack(e,time)); const weapon=getWeapon(s.playerData.weaponId); const target=s.targeting.nearestAhead(weapon.attackRange); if(target && time>=this.nextPlayerAttackAt){ this.nextPlayerAttackAt=time+weapon.attackIntervalMs/Math.max(0.2,s.playerData.attackSpeedMultiplier); this.playerAttack(target, weapon); } }
  playerAttack(enemy, weapon){ const s=this.scene; if(!s.targeting.valid(enemy)) return; s.eventBus.emit(CombatEvents.PLAYER_ATTACK,{ enemy, weapon }); const crit=Math.random()<s.playerData.critChance; const dmg=Math.round(s.playerData.attack*weapon.damageMultiplier*(crit?s.playerData.critMultiplier:1)); this.damageEnemy(enemy,dmg,{ source:'attack', tags:['physical'], canTriggerArtifacts:true }); if(crit) s.eventBus.emit(CombatEvents.PLAYER_CRIT,{ enemy, damage:dmg });  s.eventBus.emit(CombatEvents.PLAYER_HIT,{ enemy, damage:dmg, crit, tags:['physical'] }); }
  damageEnemy(enemy, amount, meta={}){ if(!this.scene.targeting.valid(enemy)) return; const hpBefore=enemy.hp; enemy.hp=Math.max(0, enemy.hp-amount); const actualDamage=hpBefore-enemy.hp; if(actualDamage>0){ this.scene.floatText(enemy.x, enemy.y-60, `-${actualDamage}`, meta.source==='burn'?'#ff8a33':'#fff'); syncEnemyUi(enemy); this.scene.eventBus.emit(CombatEvents.ENEMY_HIT,{ enemy, damage:actualDamage, ...meta }); } else syncEnemyUi(enemy); if(enemy.hp<=0) this.handleDeathReactions(enemy, meta); if(enemy.hp<=0) this.killEnemy(enemy, meta); }
  killEnemy(enemy, meta={}){ if(!enemy||enemy.isDefeated) return; const s=this.scene; enemy.isDefeated=true; s.statusEffects?.clearTarget(enemy); enemy.body&&(enemy.body.enable=false); s.enemies=s.enemies.filter(e=>e!==enemy); s.killCount += enemy.isBoss ? 0 : 1; s.eventBus.emit(CombatEvents.ENEMY_KILLED,{ enemy, ...meta }); if(enemy.isBoss){ s.upgradeSystem.gainExperience(enemy.xp||0,{ defer:true }); s.eventBus.emit(CombatEvents.BOSS_KILLED,{ enemy }); s.finishRun(true); } else if(enemy.isElite){ s.upgradeSystem.gainExperience(enemy.xp||0,{ defer:true }); s.queueArtifactReward(enemy); s.resumeModalFlow(); } else { s.upgradeSystem.gainExperience(enemy.xp||0,{ defer:false }); } [enemy.hpBarBg, enemy.hpBar, enemy.nameText].forEach(o=>o?.destroy()); s.tweens.add({ targets:enemy, alpha:0, duration:s.balance.enemyFadeMs, onComplete:()=>enemy.destroy() }); }
  handleDeathReactions(enemy, meta={}){ const s=this.scene; if(enemy._deathReacted) return; enemy._deathReacted=true; const all=s.targeting.all().filter(e=>e!==enemy); if(s.statusEffects?.has(enemy,'BURN')&&!meta.noDeathExplosion){ all.filter(e=>Phaser.Math.Distance.Between(e.x,e.y,enemy.x,enemy.y)<=95).forEach(e=>this.damageEnemy(e,8,{source:'burn_burst',tags:['fire'],noDeathExplosion:true})); } const spreadingPoison=s.statusEffects?.getEffects(enemy,'POISON').find(e=>e.canSpread); if(spreadingPoison&&!meta.noPoisonSpread){ const r=spreadingPoison.spreadRadius||105; all.filter(e=>Phaser.Math.Distance.Between(e.x,e.y,enemy.x,enemy.y)<=r).forEach(e=>s.statusEffects.add('POISON',e,{durationMs:spreadingPoison.spreadDurationMs||2200,intervalMs:650,value:spreadingPoison.spreadDamage||5,sourceId:'poison_spread',canSpread:false,damageMultiplier:spreadingPoison.damageMultiplier||1})); } }
  updateEnemyAttack(enemy,time){ const s=this.scene; if(!s.targeting.valid(enemy)) return; if(enemy.isBoss && !enemy.enraged && enemy.hp <= enemy.maxHp/2){ enemy.enraged=true; enemy.attackIntervalMs=enemy.enragedAttackIntervalMs; s.hud?.setStatus('Boss 半血狂暴：攻击速度提升！'); } const d=Math.abs(enemy.x-s.player.x); if(d>enemy.attackRange) return; if(time < enemy.nextAttackAt) return; enemy.nextAttackAt=time+enemy.attackIntervalMs; const base=Math.max(1, Math.round(enemy.damage*(1-s.playerData.damageReduction)-s.playerData.defense)); const dmg=Math.max(1, Math.round(base*(1-(s.playerData.temporaryDamageReduction||0)))); const shieldResult=s.statusEffects?.absorbShield(dmg)||{absorbed:0,remainingDamage:dmg}; const absorbed=shieldResult.absorbed; const hpDmg=shieldResult.remainingDamage; s.playerData.hp=Math.max(0,s.playerData.hp-hpDmg); s.floatText(s.player.x, s.player.y-80, absorbed&&hpDmg?`盾-${absorbed} -${hpDmg}`:absorbed?`盾-${absorbed}`:`-${hpDmg}`, absorbed?'#8fd7ff':'#ff7777'); s.eventBus.emit(CombatEvents.PLAYER_DAMAGED,{ enemy, damage:dmg, hpDamage:hpDmg, shieldAbsorbed:absorbed }); if(s.playerData.hp/s.playerData.maxHp <=0.3) s.eventBus.emit(CombatEvents.PLAYER_LOW_HP,{ hp:s.playerData.hp }); s.hud?.update(); if(s.playerData.hp<=0) s.finishRun(false); }
}
