const alive=e=>e?.active!==false&&!e?.isDefeated;
const bossScale=e=>e?.isBoss?0.4:1;
const sourceMap=e=>e&&(e.gravitySources ||= new Map());
export function applyEnemyGravity(enemy, source){ if(!enemy||!source?.sourceId) return; sourceMap(enemy).set(source.sourceId,{...source}); }
export function removeEnemyGravitySource(enemy, sourceId){ enemy?.gravitySources?.delete?.(sourceId); }
export function removeEnemyGravitySourcesByPrefix(enemy, prefix){ if(!enemy?.gravitySources) return; [...enemy.gravitySources.keys()].forEach(id=>{ if(String(id).startsWith(prefix)) enemy.gravitySources.delete(id); }); }
export function getEnemyGravityState(enemy, now=0){ const state={moveSlow:0,attackSlow:0,suppressed:false,externalSuppressed:false}; if(!enemy?.gravitySources) return state; for(const [id,src] of [...enemy.gravitySources.entries()]){ if(src.expiresAt!==Infinity&&src.expiresAt<=now){ enemy.gravitySources.delete(id); continue; } const scale=bossScale(enemy); state.moveSlow=Math.max(state.moveSlow,Math.max(0,src.moveSlow||0)*scale); state.attackSlow=Math.max(state.attackSlow,Math.max(0,src.attackSlow||0)*scale); state.suppressed=true; if(src.external) state.externalSuppressed=true; } return state; }
export function getEnemyMoveSpeed(enemy, baseSpeed=0, now=0){ const st=getEnemyGravityState(enemy,now); return Math.max(0,Number(baseSpeed||0)*(1-Math.min(0.95,st.moveSlow))); }
export function getEnemyAttackDelay(enemy, baseDelayMs=1000, now=0){ const st=getEnemyGravityState(enemy,now); const slow=Math.min(0.95,Math.max(0,st.attackSlow)); return Math.max(120,Number(baseDelayMs||1000)/(1-slow)); }
export const isGravitySuppressed=(enemy,now=0)=>getEnemyGravityState(enemy,now).suppressed;
export const isExternallyGravitySuppressed=(enemy,now=0)=>getEnemyGravityState(enemy,now).externalSuppressed;
export function clearEnemyGravity(enemy){ if(enemy){ enemy.gravitySources?.clear?.(); enemy.gravitySources=undefined; enemy.gravityPull=undefined; } }
export function canGravityPull(enemy, scene){ return alive(enemy)&&!enemy.isBoss&&!enemy.isCharging&&!enemy.charging&&!enemy.isCasting&&!enemy.casting&&!enemy.skillActive&&!enemy.isKnockbackActive&&scene?.targeting?.isEnemyFullyInsideViewport?.(enemy)!==false; }
function setPullPosition(enemy,x,y,scene){ const max=scene?.physics?.world?.bounds?.width?scene.physics.world.bounds.width-(enemy.width||40)/2-8:x; const bounded=Math.max((enemy.width||40)/2+8,Math.min(max,x)); enemy.body?.reset?.(bounded,y); enemy.x=bounded; enemy.y=y; enemy.body?.setVelocityX?.(0); }
export function applyGravityPull(enemy, centerX, distance, durationMs, now, scene){ if(!canGravityPull(enemy,scene)) return false; const dir=Math.sign(centerX-enemy.x); if(!dir) return false; const scaled=distance*(enemy.isElite?0.5:1); const targetX=enemy.x+dir*Math.min(Math.abs(centerX-enemy.x),scaled); const existing=enemy.gravityPull; if(existing&&existing.expiresAt>now&&Math.abs(existing.targetX-enemy.x)>=Math.abs(targetX-enemy.x)) return false; enemy.gravityPull={sourceId:'gravity_orb_pull',startX:enemy.x,startY:enemy.y,targetX,centerX,startedAt:now,expiresAt:now+durationMs,durationMs}; return true; }
export function updateGravityPull(enemy, now, scene){ const p=enemy?.gravityPull; if(!p) return false; if(!canGravityPull(enemy,scene)){ enemy.gravityPull=undefined; enemy.body?.setVelocityX?.(0); return false; } if(now>=p.expiresAt){ setPullPosition(enemy,p.targetX,p.startY,scene); enemy.gravityPull=undefined; return false; } const t=Math.max(0,Math.min(1,(now-p.startedAt)/Math.max(1,p.durationMs))); setPullPosition(enemy,p.startX+(p.targetX-p.startX)*t,p.startY,scene); return true; }
export function clearAllEnemyGravity(scene){ scene?.enemies?.forEach(clearEnemyGravity); }
