import { CombatEvents } from '../core/CombatEvents.js';
import { getProfession, PROFESSION_STATE_DEFAULTS } from '../config/professions.js';

const cloneState = () => ({ ...PROFESSION_STATE_DEFAULTS });

export default class ProfessionSystem {
  constructor(scene){ this.scene=scene; this.unsubs=[]; this.appliedId=null; this.appliedBonuses=null; }
  selectProfession(id){ const cfg=getProfession(id); if(!cfg) return false; this.reset(); const p=this.scene.playerData; p.professionId=id; p.professionState=cloneState(); this.applyBonuses(cfg.bonuses); this.appliedId=id; this.appliedBonuses=cfg.bonuses; this.bind(); this.scene.runStats?.setProfession?.(id); this.scene.eventBus.emit(CombatEvents.PROFESSION_CHOSEN,{ professionId:id, profession:cfg }); this.scene.hud?.update(); return true; }
  applyBonuses(b={}){ const p=this.scene.playerData; if(b.attackMultiplier) p.attack=Math.max(1,Math.round(p.attack*b.attackMultiplier)); if(b.maxHp){ p.maxHp+=b.maxHp; p.hp+=b.maxHp; } if(b.skillDamageMultiplier) p.skillDamageMultiplier+=b.skillDamageMultiplier; if(b.cooldownReduction) p.cooldownReduction=Math.min(0.8,(p.cooldownReduction||0)+b.cooldownReduction); if(b.attackSpeedMultiplier) p.attackSpeedMultiplier+=b.attackSpeedMultiplier; if(b.critChance) p.critChance+=b.critChance; }
  removeBonuses(b={}){ const p=this.scene.playerData; if(b.attackMultiplier) p.attack=Math.max(1,Math.round(p.attack/b.attackMultiplier)); if(b.maxHp){ p.maxHp-=b.maxHp; p.hp=Math.min(p.hp,p.maxHp); } if(b.skillDamageMultiplier) p.skillDamageMultiplier-=b.skillDamageMultiplier; if(b.cooldownReduction) p.cooldownReduction-=b.cooldownReduction; if(b.attackSpeedMultiplier) p.attackSpeedMultiplier-=b.attackSpeedMultiplier; if(b.critChance) p.critChance-=b.critChance; }
  bind(){ const off=this.scene.eventBus.on(CombatEvents.PLAYER_DAMAGED,p=>this.onPlayerDamaged(p)); this.unsubs.push(off); }
  onPlayerDamaged(payload){ if(this.scene.playerData.professionId!=='warrior') return; if((payload.hpDamage||0)<=0 || payload.blocked) return; this.scene.playerData.professionState.warriorBuffUntil=this.scene.getGameplayTime()+4000; this.scene.runStats?.recordProfessionTrigger?.('warrior'); this.scene.hud?.update(); }
  getDamageMultiplier(source){ const p=this.scene.playerData; let mult=1; if(p.professionId==='warrior' && this.scene.getGameplayTime() < (p.professionState.warriorBuffUntil||0)) mult*=1.2; if(p.professionId==='mage' && source?.type==='activeSkill' && source?.damaging && p.professionState.mageEmpoweredNext){ mult*=1.5; if(!source.preview){ p.professionState.mageEmpoweredNext=false; p.professionState.mageCastCount=0; this.scene.runStats?.recordProfessionTrigger?.('mage'); this.scene.hud?.update(); } } return mult; }
  onActiveSkillCast({ damaging=false }={}){ const p=this.scene.playerData; if(p.professionId!=='mage') return; if(p.professionState.mageEmpoweredNext) return; p.professionState.mageCastCount=Math.min(5,(p.professionState.mageCastCount||0)+1); if(p.professionState.mageCastCount>=5 && damaging) p.professionState.mageEmpoweredNext=true; this.scene.hud?.update(); }
  shouldForceCrit(){ return this.scene.playerData.professionId==='ranger' && (this.scene.playerData.professionState.rangerHitCount||0)>=3; }
  onNormalAttackHit({ forcedCrit=false }={}){ const p=this.scene.playerData; if(p.professionId!=='ranger') return; if(forcedCrit){ p.professionState.rangerHitCount=0; this.scene.runStats?.recordProfessionTrigger?.('ranger'); } else p.professionState.rangerHitCount=Math.min(3,(p.professionState.rangerHitCount||0)+1); this.scene.hud?.update(); }
  shiftTimers(pausedDuration, pausedAt){ const st=this.scene.playerData.professionState; if(st?.warriorBuffUntil>pausedAt) st.warriorBuffUntil+=pausedDuration; }
  reset(){ this.unsubs.forEach(off=>off()); this.unsubs=[]; if(this.appliedBonuses) this.removeBonuses(this.appliedBonuses); this.appliedBonuses=null; this.appliedId=null; if(this.scene.playerData){ this.scene.playerData.professionId=null; this.scene.playerData.professionState=cloneState(); } }
  destroy(){ this.reset(); }
}
