import Phaser from 'phaser';
import { CombatEvents } from '../core/CombatEvents.js';
import { SKILLS } from '../config/skills.js';
import { StatusEffects } from './StatusEffectSystem.js';
import { SKILL_HANDLERS } from '../skills/handlers/index.js';
export default class SkillSystem { constructor(scene){ this.scene=scene; this.cooldowns=new Map(); this.active=[]; this.nextCastId=1; this.boundPassives=new Map(); this.passiveState={}; this.passiveUpdaters=[]; this.bindGlobalPassives(); } shiftTimers(pausedDuration, pausedAt){ this.cooldowns.forEach((readyAt,id)=>{ if(readyAt>pausedAt) this.cooldowns.set(id, readyAt+pausedDuration); }); this.active.forEach(a=>{ if(a.nextAt>pausedAt)a.nextAt+=pausedDuration; if(a.endAt>pausedAt)a.endAt+=pausedDuration; }); } reset(){ this.cooldowns.clear(); this.active.forEach(a=>a.onEnd?.()); this.active=[]; this.nextCastId=1; this.passiveState={}; this.passiveUpdaters=[]; } getOwned(){ return this.scene.playerData.skills; } getLevel(id){ return this.getOwned().find(s=>s.id===id)?.level||0; } getConfig(id){ return SKILLS[id]; } getData(id,level=this.getLevel(id)){ return SKILLS[id]?.levels[level-1]; } addOrLevel(id,{starting=false}={}){ const owned=this.getOwned().find(s=>s.id===id); if(owned) owned.level=Math.min(SKILLS[id].maxLevel, owned.level+1); else this.scene.playerData.skills.push({ id, level:1 }); if(starting) this.scene.eventBus.emit(CombatEvents.STARTING_SKILL_CHOSEN,{ skillId:id, skill:SKILLS[id] }); this.scene.hud?.update(); }
  update(time){ const s=this.scene; if(s.isGameplayPaused?.()||s.playerData.hp<=0) return; this.updateActive(time); this.passiveUpdaters.forEach(fn=>fn()); this.getOwned().forEach(({id,level})=>{ const cfg=SKILLS[id]; if(cfg.passive) return; const data=cfg.levels[level-1]; const cd=(data.cooldownMs||cfg.cooldownMs)*(1-s.playerData.cooldownReduction); if(time < (this.cooldowns.get(id)||0)) return; if(id==='healing' && s.playerData.hp/s.playerData.maxHp > (data.threshold||0.6)) return; if(id!=='healing' && !this.hasTarget(cfg,data)) return; this.cooldowns.set(id,time+Math.max(300,cd)); this.cast(cfg,data,level); }); }
  hasTarget(cfg,data){ const t=this.scene.targeting; if(cfg.targetType==='nearestAhead') return !!t.nearestAhead(760); if(cfg.targetType==='random') return !!t.random(); if(cfg.targetType==='aroundPlayer') return t.aroundPlayer(data.radius).length>0; if(cfg.targetType==='passive') return false; return true; }
  createCastContext(skillId){ const p=this.scene.playerData; const consumed=skillId!=='healing' && (p.battleMarkStacks||0)>=5; if(consumed){ p.battleMarkStacks=0; p.nextSkillDamageBonus=0; this.scene.floatText(this.scene.player.x,this.scene.player.y-132,'战意爆发','#ffd866'); this.scene.hud?.update(); } return { castId:this.nextCastId++, damageMultiplier:p.skillDamageMultiplier*(consumed?1.45:1), consumedBattleMark:consumed }; }
  damageValue(base,ctx){ return Math.round(base*(ctx?.damageMultiplier||this.scene.playerData.skillDamageMultiplier)); }
  cast(cfg,data,level){ const s=this.scene; s.eventBus.emit(CombatEvents.SKILL_CAST,{ skill:cfg, level }); const ctx=this.createCastContext(cfg.id);
    const handler=SKILL_HANDLERS[cfg.handler||cfg.id]; if(handler?.cast) return handler.cast(this,cfg,data,level,ctx); if(cfg.id==='healing') return this.castHeal(data,level,ctx); if(cfg.id==='fireball') return this.castFireball(cfg,data,level,ctx); if(cfg.id==='lightning') return this.castLightning(cfg,data,level,ctx); if(cfg.id==='spinning_blade') return this.castBlade(cfg,data,level,ctx); if(cfg.id==='poison_cloud') return this.castPoison(cfg,data,level,ctx); if(cfg.id==='sword_wave') return this.castSword(cfg,data,level,ctx); }
  castHeal(data,level,ctx){ const s=this.scene; const heal=Math.round(data.heal); const before=s.playerData.hp; s.playerData.hp=Math.min(s.playerData.maxHp,s.playerData.hp+heal); const actualHeal=s.playerData.hp-before; s.eventBus.emit(CombatEvents.PLAYER_HEALED,{ amount:actualHeal, source:'skill', skillId:'healing' }); if(data.damageReduction) s.statusEffects.add(StatusEffects.DAMAGE_REDUCTION,s.playerData,{ durationMs:data.drMs,value:data.damageReduction,sourceId:'healing' }); if(data.shield) s.statusEffects.add(StatusEffects.SHIELD,s.playerData,{ durationMs:data.shieldMs,value:data.shield,remainingValue:data.shield,sourceId:'healing' }); this.ring(s.player.x,s.player.y,90,0x65dd77); s.floatText(s.player.x,s.player.y-100,`+${heal}`,'#7dff8a'); s.hud?.update(); }
  castFireball(cfg,data,level,ctx){ const s=this.scene; const targets=[]; const first=s.targeting.nearestAhead(760); if(first)targets.push(first); if(data.shots>1){ const second=s.targeting.all().find(e=>e!==first&&e.x>=s.player.x-40)||first; if(second)targets.push(second); } targets.forEach((e,i)=>{ this.projectile(s.player.x,s.player.y-60,e.x,e.y-45,0xff6533); this.hit(e,this.damageValue(data.damage,ctx),cfg,level); if(data.radius>0){ this.ring(e.x,e.y,data.radius,0xff7a33); s.targeting.all().filter(x=>x!==e&&Phaser.Math.Distance.Between(x.x,x.y,e.x,e.y)<=data.radius).forEach(x=>this.hit(x,this.damageValue(data.damage*0.45,ctx),cfg,level)); } }); }
  castLightning(cfg,data,level,ctx){ const s=this.scene; let pool=s.targeting.all(); const hit=[]; for(let i=0;i<data.hits;i++){ let e=pool.find(x=>!hit.includes(x))||pool[0]; if(!e) break; const repeat=hit.includes(e); this.line(e.x,e.y-170,e.x,e.y,0x9ee8ff); this.hit(e,this.damageValue(data.damage*(repeat?(data.repeatScale||0.55):1),ctx),cfg,level); hit.push(e); } }
  castBlade(cfg,data,level,ctx){ const s=this.scene; if(s.artifactSystem) s.artifactSystem.windHits=0; const active={ cfg,data,level,ctx,nextAt:s.getGameplayTime(),endAt:s.getGameplayTime()+(data.ticks-1)*(data.intervalMs||1)+10,count:0 }; this.active.push(active); this.tickBlade(active); }
  updateActive(time){ this.active=this.active.filter(a=>{ if(time>=a.nextAt&&time<=a.endAt+20){ if(a.tick) { a.tick(); a.nextAt=time+(a.data?.intervalMs||80); } else this.tickBlade(a); } const keep=time<=a.endAt; if(!keep) a.onEnd?.(); return keep; }); }
  bindGlobalPassives(){ Object.entries(SKILL_HANDLERS).forEach(([id,h])=>{ if(h.bind&&!this.boundPassives.has(id)) this.boundPassives.set(id,h.bind(this)); }); }
  beforePlayerDamage(payload){ for(const [id,h] of Object.entries(SKILL_HANDLERS)){ if(h.beforePlayerDamage){ const r=h.beforePlayerDamage(this,payload); if(r) return r; } } return null; }
  forceCast(id,meta={}){ const owned=this.getOwned().find(s=>s.id===id); const cfg=SKILLS[id]; if(!owned||!cfg||cfg.passive||id==='time_loan') return; const data=cfg.levels[owned.level-1]; if(!this.hasTarget(cfg,data)) return; this.cast(cfg,data,owned.level,meta); }
  tickBlade(a){ const s=this.scene; a.count+=1; a.nextAt=s.getGameplayTime()+(a.data.intervalMs||999999); this.ring(s.player.x,s.player.y,a.data.radius,a.count%2?0xd7d7d7:0x99ccff); s.targeting.aroundPlayer(a.data.radius).forEach(e=>this.hit(e,this.damageValue(a.data.damage,a.ctx),a.cfg,a.level)); }
  castPoison(cfg,data,level,ctx){ const s=this.scene; const e=s.targeting.nearestAhead(760); if(!e)return; const cloud=this.scene.add.circle(e.x,e.y,data.radius,0x35cc55,0.25).setDepth(120); this.scene.tweens.add({targets:cloud,alpha:0.08,duration:data.durationMs,onComplete:()=>cloud.destroy()}); s.targeting.all().filter(x=>Phaser.Math.Distance.Between(x.x,x.y,e.x,e.y)<=data.radius).forEach(x=>this.applyPoison(x,data,cfg,level,ctx)); }
  applyPoison(e,data,cfg,level,ctx){ const dur=data.durationMs+(this.scene.playerData.artifacts.includes('venom_sac')?1200:0); this.scene.statusEffects.add(StatusEffects.POISON,e,{ durationMs:dur, intervalMs:data.intervalMs, value:data.damage, sourceId:'poison_cloud', canSpread:level>=3, spreadRadius:this.scene.playerData.artifacts.includes('venom_sac')?145:105, spreadDamage:5, spreadDurationMs:2200, damageMultiplier:ctx?.damageMultiplier||1 }); this.hit(e,1,cfg,level); }
  castSword(cfg,data,level,ctx){ const s=this.scene; const targets=s.targeting.all().filter(e=>e.x>=s.player.x&&Math.abs(e.y-s.player.y)<180).sort((a,b)=>a.x-b.x).slice(0,data.pierce); const slash=s.add.rectangle(s.player.x+160,s.player.y-65,300,data.width,0xb8f7ff,0.45).setDepth(130); s.tweens.add({targets:slash,x:slash.x+280,alpha:0,duration:260,onComplete:()=>slash.destroy()}); targets.forEach(e=>{ this.hit(e,this.damageValue(data.damage,ctx),cfg,level); if(data.knockback&&e.body){ e.x+=Math.min(data.knockback,Math.max(0,s.player.x+620-e.x)); } }); }
  hit(enemy, damage, skill, level){ this.scene.combatSystem.damageEnemy(enemy, Math.max(1,Math.round(damage)), { source:'skill', skillId:skill.id, tags:skill.tags, level }); this.scene.eventBus.emit(CombatEvents.SKILL_HIT,{ enemy, damage, skill, tags:skill.tags, level }); }
  ring(x,y,r,c){ const o=this.scene.add.circle(x,y,r,c,0.18).setStrokeStyle(4,c,0.9).setDepth(140); this.scene.tweens.add({targets:o,alpha:0,scale:1.15,duration:350,onComplete:()=>o.destroy()}); }
  line(x1,y1,x2,y2,c){ const g=this.scene.add.graphics().setDepth(150); g.lineStyle(6,c,1).lineBetween(x1,y1,x2,y2); this.scene.tweens.add({targets:g,alpha:0,duration:180,onComplete:()=>g.destroy()}); }
  projectile(x1,y1,x2,y2,c){ const o=this.scene.add.circle(x1,y1,18,c,1).setDepth(145); this.scene.tweens.add({targets:o,x:x2,y:y2,duration:170,onComplete:()=>o.destroy()}); }
}
