const Phaser = globalThis.Phaser || { Math:{ Distance:{ Between:(x1,y1,x2,y2)=>Math.hypot(x2-x1,y2-y1) } } };
import { CombatEvents } from '../core/CombatEvents.js';
import { SKILLS } from '../config/skills.js';
import { StatusEffects } from './StatusEffectSystem.js';
import { SKILL_HANDLERS } from '../skills/handlers/index.js';
import { TAGS } from '../config/tags.js';
import { TUNING } from '../config/tuning.js';
import { hasAnyTag, mergeTags } from '../utils/tagUtils.js';
export const MAX_SKILL_SLOTS = 6;
const POST_UPDATE_EVENT=Phaser.Scenes?.Events?.POST_UPDATE||'postupdate';
const SHUTDOWN_EVENT=Phaser.Scenes?.Events?.SHUTDOWN||'shutdown';
export function migrateLegacyGravityFieldSkills(playerData){ const skills=playerData?.skills; if(!Array.isArray(skills)) return; let best=0; const kept=[]; for(const item of skills){ if(!item) continue; if(item.id==='gravity_field'||item.id==='gravity_reversal'){ best=Math.max(best, Math.min(9, Number(item.level)||1)); if(item.id==='gravity_field') continue; } if(item.id!=='gravity_reversal') kept.push(item); } if(best>0) kept.push({id:'gravity_reversal',level:best}); playerData.skills=kept; }
export default class SkillSystem { constructor(scene){ migrateLegacyGravityFieldSkills(scene?.playerData); this.scene=scene; this.cooldowns=new Map(); this.active=[]; this.nextCastId=1; this.boundPassives=new Map(); this.passiveState={}; this.passiveUpdaters=[]; this.attachedVisualSyncers=[...new Set(Object.values(SKILL_HANDLERS).map(handler=>handler?.syncAttachedVisuals).filter(sync=>typeof sync==='function'))]; this.postUpdateAttachedVisualSync=()=>this.scene.syncAttachedVisuals?.(); this.scene.events?.on?.(POST_UPDATE_EVENT,this.postUpdateAttachedVisualSync); this.scene.events?.once?.(SHUTDOWN_EVENT,()=>this.scene.events?.off?.(POST_UPDATE_EVENT,this.postUpdateAttachedVisualSync)); this.bindGlobalPassives(); } shiftTimers(pausedDuration, pausedAt){ this.cooldowns.forEach((readyAt,id)=>{ if(readyAt>pausedAt) this.cooldowns.set(id, readyAt+pausedDuration); }); this.active.forEach(a=>{ if(a.nextAt>pausedAt)a.nextAt+=pausedDuration; if(a.endAt>pausedAt)a.endAt+=pausedDuration; }); if(this.passiveState.mirrorUntil>pausedAt) this.passiveState.mirrorUntil+=pausedDuration; Object.values(SKILL_HANDLERS).forEach(handler=>handler?.shiftTimers?.(this,pausedDuration,pausedAt)); } reset(){ SKILL_HANDLERS.black_hole?.destroyRuntime?.(this); this.cooldowns.clear(); this.active.forEach(a=>a.onEnd?.('reset')); this.active=[]; this.boundPassives.forEach(off=>off?.()); this.boundPassives.clear(); this.passiveState.mirrorClones?.forEach(o=>o.destroy()); this.nextCastId=1; this.passiveState={}; this.passiveUpdaters=[]; } getOwned(){ return this.scene.playerData.skills; } getLevel(id){ return this.getOwned().find(s=>s.id===id)?.level||0; } getConfig(id){ return SKILLS[id]; } getData(id,level=this.getLevel(id)){ return SKILLS[id]?.levels[level-1]; } addOrLevel(id,{starting=false,replaceIndex=null}={}){ if(id==='gravity_field') id='gravity_reversal'; migrateLegacyGravityFieldSkills(this.scene?.playerData); const owned=this.getOwned().find(s=>s.id===id); if(owned){ owned.level=Math.min(SKILLS[id].maxLevel, owned.level+1); } else if(replaceIndex!==null && replaceIndex>=0){ const old=this.scene.playerData.skills[replaceIndex]?.id; if(old) this.removeSkillRuntime(old); this.scene.playerData.skills.splice(replaceIndex,1,{ id, level:1 }); } else if(this.scene.playerData.skills.length<MAX_SKILL_SLOTS){ this.scene.playerData.skills.push({ id, level:1 }); } else { return { needsReplacement:true, skillId:id }; } this.ensurePassiveBound(id); if(starting) this.scene.eventBus.emit(CombatEvents.STARTING_SKILL_CHOSEN,{ skillId:id, skill:SKILLS[id] }); this.scene.hud?.update(); this.scene.skillBar?.update(); return { applied:true }; }
  removeSkillRuntime(id){ this.cooldowns.delete(id); this.active.forEach(a=>{ if(a.skillId===id||a.cfg?.id===id) a.onEnd?.('removed'); }); this.active=this.active.filter(a=>!(a.skillId===id||a.cfg?.id===id)); if(id==='mirror_march'){ this.passiveState.mirrorClones?.forEach(o=>o.destroy?.()); delete this.passiveState.mirrorClones; delete this.passiveState.mirrorData; this.passiveState.mirrorUntil=0; } if(id==='bullet_eater') delete this.passiveState.bulletEaterReadyAt; const cfg=SKILLS[id], key=cfg?.handler||id; const off=this.boundPassives.get(key); if(off){ off?.(); this.boundPassives.delete(key); } const handler=SKILL_HANDLERS[key]; handler?.cleanup?.(this); }
  replaceSkill(index,id){ return this.addOrLevel(id,{replaceIndex:index}); }
  getManaCost(cfg,data){ return Math.max(0, Number(data?.manaCost ?? cfg?.manaCost ?? 0)||0); }
  canSpendMana(cost){ return (this.scene.playerData.mana??0) >= cost; }
  spendMana(cost){ const p=this.scene.playerData; if(cost<=0) return true; if(!this.canSpendMana(cost)) return false; p.mana=Math.max(0,(p.mana??0)-cost); this.scene.hud?.update(); return true; }
  recoverMana(amount){ const p=this.scene.playerData; const value=Math.max(0,Number(amount)||0); if(value<=0) return 0; const before=p.mana??0; p.mana=Math.min(p.maxMana??0,before+value); if(p.mana!==before) this.scene.hud?.update(); return p.mana-before; }
  updateManaRegen(time){ const p=this.scene.playerData; const rate=TUNING.leveling.playerManaRegenPerSecond||0; if(rate<=0) return; this.passiveState.nextManaRegenAt ??= time; if(time<this.passiveState.nextManaRegenAt) return; const elapsed=Math.max(0,time-this.passiveState.nextManaRegenAt+250); this.passiveState.nextManaRegenAt=time+250; this.recoverMana(rate*(elapsed/1000)); }
  getFireSeedBoost(){ return this.getLevel('solar_flame')>0 ? (this.getData('solar_flame')?.fireSeedBonus||{}) : {}; }

  syncAttachedVisuals(){ this.attachedVisualSyncers.forEach(sync=>sync(this)); }
  update(time){ const s=this.scene; if(s.isGameplayPaused?.()||s.playerData.hp<=0) return; this.updateManaRegen(time); this.updateActive(time); this.passiveUpdaters.forEach(fn=>fn()); this.getOwned().forEach(({id,level})=>{ const cfg=SKILLS[id]; if(cfg.passive) return; const data=cfg.levels[level-1]; const cd=(data.cooldownMs||cfg.cooldownMs)*(1-s.playerData.cooldownReduction); if(time < (this.cooldowns.get(id)||0)) return; if(id==='healing' && s.playerData.hp/s.playerData.maxHp > (data.threshold||0.6)) return; if(id!=='healing' && !this.hasTarget(cfg,data)) return; const handler=SKILL_HANDLERS[cfg.handler||cfg.id]; const preflight=handler?.canCast?.(this,cfg,data,level); if(preflight===false || preflight?.failed) return; const manaCost=this.getManaCost(cfg,data); if(!this.canSpendMana(manaCost)) return; const result=this.cast(cfg,data,level,{manaCost}); if(!result?.failed && !result?.noCooldown) this.cooldowns.set(id,time+Math.max(300,cd)); }); }
  hasTarget(cfg,data){ const t=this.scene.targeting; if(cfg.targetType==='nearestAhead') return !!t.nearestAhead(760); if(cfg.targetType==='random') return !!t.random(); if(cfg.targetType==='aroundPlayer') return t.aroundPlayer(data.radius).length>0; if(cfg.targetType==='passive') return false; return true; }
  createCastContext(skillId){ const p=this.scene.playerData; const battleNeed=this.scene.artifactSystem?.level?.('battle_mark')>=2?4:5; const consumed=skillId!=='healing' && (p.battleMarkStacks||0)>=battleNeed; if(consumed){ p.battleMarkStacks=0; p.nextSkillDamageBonus=0; this.scene.floatText(this.scene.player.x,this.scene.player.y-132,'战意爆发','#ffd866'); this.scene.hud?.update(); } const professionMultiplier=this.scene.professionSystem?.getDamageMultiplier?.({ type:'activeSkill', damaging:skillId!=='healing' })||1; this.scene.professionSystem?.onActiveSkillCast?.({ damaging:skillId!=='healing', skillId }); const baseDamageMultiplierWithoutProfession=p.skillDamageMultiplier*(consumed?1.45:1)*(this.scene.artifactSystem?.highHpDamageMultiplier?.()||1); return { castId:this.nextCastId++, damageMultiplier:baseDamageMultiplierWithoutProfession*professionMultiplier, baseDamageMultiplierWithoutProfession, professionMultiplier, consumedBattleMark:consumed }; }
  damageValue(base,ctx){ return Math.round(base*(ctx?.damageMultiplier||this.scene.playerData.skillDamageMultiplier)); }
  baseDamageValue(base,ctx){ return Math.round(base*(ctx?.baseDamageMultiplierWithoutProfession||this.scene.playerData.skillDamageMultiplier)); }
  cast(cfg,data,level,meta={}){ const s=this.scene; s.eventBus.emit(CombatEvents.SKILL_CAST,{ skill:cfg, level }); const ctx={ ...this.createCastContext(cfg.id), ...meta };
    const handler=SKILL_HANDLERS[cfg.handler||cfg.id]; let result;
    if(handler?.cast) result=handler.cast(this,cfg,data,level,ctx); else if(cfg.id==='healing') result=this.castHeal(data,level,ctx); else if(cfg.id==='fireball') result=this.castFireball(cfg,data,level,ctx); else if(cfg.id==='lightning') result=this.castLightning(cfg,data,level,ctx); else if(cfg.id==='spinning_blade') result=this.castBlade(cfg,data,level,ctx); else if(cfg.id==='poison_cloud') result=this.castPoison(cfg,data,level,ctx); else if(cfg.id==='sword_wave') result=this.castSword(cfg,data,level,ctx);
    if(!result?.failed) this.spendMana(ctx.manaCost||0); if(!result?.failed && !ctx.fromMyriadAfterimage) s.eventBus.emit(CombatEvents.SKILL_CAST_COMPLETED,{ skillId:cfg.id, skill:cfg, level, data, ctx, target:ctx.originalTarget||null, targets:ctx.originalTargets||[], fromMyriadAfterimage:false });
    return result; }
  castHeal(data,level,ctx){ const s=this.scene; const heal=Math.round(data.heal); const actualHeal=s.healPlayer?.(heal,'skill',{skillId:'healing'})||0; if(data.damageReduction) s.statusEffects.add(StatusEffects.DAMAGE_REDUCTION,s.playerData,{ durationMs:data.drMs,value:data.damageReduction,sourceId:'healing' }); if(data.shield) s.statusEffects.add(StatusEffects.SHIELD,s.playerData,{ durationMs:data.shieldMs,value:data.shield,remainingValue:data.shield,sourceId:'healing' }); this.ring(s.player.x,s.player.y,90,0x65dd77); if(actualHeal>0) s.floatText(s.player.x,s.player.y-100,`+${actualHeal}`,'#7dff8a'); s.hud?.update(); }
  castFireball(cfg,data,level,ctx){ const s=this.scene; const targets=[]; const all=s.targeting.all().sort((a,b)=>Phaser.Math.Distance.Between(s.player.x,s.player.y,a.x,a.y)-Phaser.Math.Distance.Between(s.player.x,s.player.y,b.x,b.y)); const first=all[0]; if(first)targets.push(first); if(data.shots>1){ const second=all.find(e=>e!==first)||first; if(second)targets.push(second); } const directTargets=new Set(targets); targets.forEach((e,i)=>{ this.projectile(s.player.x,s.player.y-60,e.x,e.y-45,0xff6533); this.hit(e,this.damageValue(data.damage,ctx),cfg,level,ctx,this.baseDamageValue(data.damage,ctx),[TAGS.MAGIC,TAGS.SPELL,TAGS.FIRE,TAGS.PROJECTILE]); if(data.burnDamage){ s.statusEffects.add(StatusEffects.BURN,e,{ durationMs:data.burnMs||3200, intervalMs:data.burnIntervalMs||600, value:data.burnDamage, stacks:1, maxStacks:5, sourceId:`fireball_${ctx.castId}`, damageMultiplier:ctx?.damageMultiplier||1, baseDamageMultiplierWithoutProfession:ctx?.baseDamageMultiplierWithoutProfession||1, professionMultiplier:ctx?.professionMultiplier||1, professionApplied:true, tags:[TAGS.MAGIC,TAGS.SPELL,TAGS.FIRE,TAGS.DOT] }); } if(data.radius>0){ this.ring(e.x,e.y,data.radius,0xff7a33); s.targeting.all().filter(x=>!directTargets.has(x)&&Phaser.Math.Distance.Between(x.x,x.y,e.x,e.y)<=data.radius).forEach(x=>{ this.hit(x,this.damageValue(data.damage*(data.explosionScale||0.45),ctx),cfg,level,ctx,this.baseDamageValue(data.damage*(data.explosionScale||0.45),ctx),[TAGS.MAGIC,TAGS.SPELL,TAGS.FIRE,'area']); s.statusEffects.add(StatusEffects.BURN,x,{ durationMs:data.burnMs||3200, intervalMs:data.burnIntervalMs||600, value:data.burnDamage||5, stacks:1, maxStacks:5, sourceId:`fireball_${ctx.castId}`, damageMultiplier:ctx?.damageMultiplier||1, baseDamageMultiplierWithoutProfession:ctx?.baseDamageMultiplierWithoutProfession||1, professionMultiplier:ctx?.professionMultiplier||1, professionApplied:true, tags:[TAGS.MAGIC,TAGS.SPELL,TAGS.FIRE,TAGS.DOT] }); }); } }); }
  castLightning(cfg,data,level,ctx){ const s=this.scene; let pool=s.targeting.all(); const hit=[]; for(let i=0;i<data.hits;i++){ let e=pool.find(x=>!hit.includes(x))||pool[0]; if(!e) break; const repeat=hit.includes(e); this.line(e.x,e.y-170,e.x,e.y,0x9ee8ff); const scale=repeat?(data.repeatScale||0.55):1; this.hit(e,this.damageValue(data.damage*scale,ctx),cfg,level,ctx,this.baseDamageValue(data.damage*scale,ctx)); if(data.chainRadius){ s.targeting.all().filter(x=>x!==e&&Phaser.Math.Distance.Between(x.x,x.y,e.x,e.y)<=data.chainRadius).slice(0,1).forEach(x=>this.hit(x,this.damageValue(data.damage*(data.chainDamageScale||0.4),ctx),cfg,level,ctx,this.baseDamageValue(data.damage*(data.chainDamageScale||0.4),ctx))); } hit.push(e); } }
  castBlade(cfg,data,level,ctx){ const s=this.scene; if(s.artifactSystem) s.artifactSystem.windHits=0; const active={ skillId:cfg.id,cfg,data,level,ctx,nextAt:s.getGameplayTime(),endAt:s.getGameplayTime()+(data.ticks-1)*(data.intervalMs||1)+10,count:0 }; this.active.push(active); this.tickBlade(active); }
  updateActive(time){ this.active=this.active.filter(a=>{ if(a.ended) return false; if(time>=a.nextAt){ if(a.tick) { a.tick(); if(!a.ended && a.data?.intervalMs) a.nextAt=this.scene.getGameplayTime()+a.data.intervalMs; } else this.tickBlade(a); } const keep=!a.ended && time<=a.endAt; if(!keep) a.onEnd?.('complete'); return !a.ended && time<=a.endAt; }); }
  bindGlobalPassives(){ Object.entries(SKILL_HANDLERS).forEach(([id,h])=>{ if(h.bind&&!this.boundPassives.has(id)) this.boundPassives.set(id,h.bind(this)); }); }
  ensurePassiveBound(id){ const cfg=SKILLS[id]; const key=cfg?.handler||id, handler=SKILL_HANDLERS[key]; if(!cfg||(!cfg.passive&&!handler?.runtimeBind)) return; if(handler?.bind&&!this.boundPassives.has(key)) this.boundPassives.set(key,handler.bind(this)); handler?.onAcquire?.(this); }
  beforePlayerDamage(payload){ for(const [id,h] of Object.entries(SKILL_HANDLERS)){ if(h.beforePlayerDamage){ const r=h.beforePlayerDamage(this,payload); if(r) return r; } } return null; }
  beforePlayerHpDamage(payload){ for(const [id,h] of Object.entries(SKILL_HANDLERS)){ if(h.beforePlayerHpDamage){ const r=h.beforePlayerHpDamage(this,payload); if(r) return r; } } return null; }
  reduceActiveCooldowns(amountMs,{excludeSkillIds=[],sourceSkillId=''}={}){ const now=this.scene.getGameplayTime(); const amount=Math.max(0,Math.floor(Number(amountMs)||0)); if(amount<=0) return 0; const excluded=new Set(excludeSkillIds); let changed=0; this.getOwned().forEach(({id})=>{ if(excluded.has(id)) return; const cfg=SKILLS[id]; if(!cfg||cfg.passive) return; const readyAt=this.cooldowns.get(id)||0; if(readyAt<=now) return; const next=Math.max(now,readyAt-amount); if(next!==readyAt){ this.cooldowns.set(id,next); changed+=1; } }); return changed; }
  forceCast(id,meta={}){ const owned=this.getOwned().find(s=>s.id===id); const cfg=SKILLS[id]; if(!owned||!cfg||cfg.passive) return; const data=cfg.levels[owned.level-1]; if(!this.hasTarget(cfg,data)) return; const handler=SKILL_HANDLERS[cfg.handler||cfg.id]; const preflight=handler?.canCast?.(this,cfg,data,owned.level); if(preflight===false || preflight?.failed) return; this.cast(cfg,data,owned.level,meta); }
  tickBlade(a){ const s=this.scene; a.count+=1; a.nextAt=s.getGameplayTime()+(a.data.intervalMs||999999); this.ring(s.player.x,s.player.y,a.data.radius,a.count%2?0xd7d7d7:0x99ccff); s.targeting.aroundPlayer(a.data.radius).forEach(e=>{ this.hit(e,this.damageValue(a.data.damage,a.ctx),a.cfg,a.level,a.ctx,this.baseDamageValue(a.data.damage,a.ctx)); if(a.data.knockback&&e.body){ if(e.isBoss) s.combatSystem?.applyKnockback(e,{knockback:a.data.knockback,source:'skill'}); else { e.x=Math.min((s.balance.stageWorldWidth||14900)-e.width/2-8,e.x+a.data.knockback); e.body?.reset?.(e.x,e.y); } } }); if(a.count>=a.data.ticks&&a.data.finalBurstDamage){ this.ring(s.player.x,s.player.y,a.data.finalBurstRadius||a.data.radius,0xd7d7d7); s.targeting.aroundPlayer(a.data.finalBurstRadius||a.data.radius).forEach(e=>this.hit(e,this.damageValue(a.data.finalBurstDamage,a.ctx),a.cfg,a.level,a.ctx,this.baseDamageValue(a.data.finalBurstDamage,a.ctx))); } }
  castPoison(cfg,data,level,ctx){ const s=this.scene; const e=s.targeting.nearestAhead(760); if(!e)return; const cloud=this.scene.add.circle(e.x,e.y,data.radius,0x35cc55,0.25).setDepth(120); this.scene.tweens.add({targets:cloud,alpha:0.08,duration:data.durationMs,onComplete:()=>cloud.destroy()}); s.targeting.all().filter(x=>Phaser.Math.Distance.Between(x.x,x.y,e.x,e.y)<=data.radius).forEach(x=>this.applyPoison(x,data,cfg,level,ctx)); }
  applyPoison(e,data,cfg,level,ctx){ const dur=data.durationMs+(this.scene.artifactSystem?.has?.('venom_sac')?(this.scene.artifactSystem.level('venom_sac')>=2?1800:1200):0); this.scene.statusEffects.add(StatusEffects.POISON,e,{ durationMs:dur, intervalMs:data.intervalMs, value:data.damage, sourceId:'poison_cloud', canSpread:level>=3, spreadRadius:this.scene.artifactSystem?.has?.('venom_sac')?(this.scene.artifactSystem.level('venom_sac')>=2?170:145):105, spreadDamage:5, spreadDurationMs:2200, damageMultiplier:ctx?.damageMultiplier||1, baseDamageMultiplierWithoutProfession:ctx?.baseDamageMultiplierWithoutProfession||1, professionMultiplier:ctx?.professionMultiplier||1, professionApplied:true }); this.hit(e,1,cfg,level,ctx,1); }
  castSword(cfg,data,level,ctx){ const s=this.scene; const range=data.range||620; const targets=s.targeting.all().filter(e=>e.x>=s.player.x&&e.x-s.player.x<=range&&Math.abs(e.y-s.player.y)<180).sort((a,b)=>a.x-b.x).slice(0,data.pierce); const slash=s.add.rectangle(s.player.x+160,s.player.y-65,Math.min(420,range),data.width,0xb8f7ff,0.45).setDepth(130); s.tweens.add({targets:slash,x:slash.x+280,alpha:0,duration:260,onComplete:()=>slash.destroy()}); targets.forEach(e=>{ this.hit(e,this.damageValue(data.damage,ctx),cfg,level,ctx,this.baseDamageValue(data.damage,ctx)); if(data.knockback&&e.body){ if(e.isBoss) s.combatSystem?.applyKnockback(e,{knockback:data.knockback,source:'skill'}); else { e.x+=Math.min(data.knockback,Math.max(0,s.player.x+range-e.x)); e.body?.reset?.(e.x,e.y); } } if(data.secondSlash) this.hit(e,this.damageValue(data.damage*(data.secondSlashScale||0.5),ctx),cfg,level,ctx,this.baseDamageValue(data.damage*(data.secondSlashScale||0.5),ctx)); }); }
  hit(enemy, damage, skill, level, ctx=null, baseDamage=null, extraTags=[]){ if(!this.scene.targeting.isEnemyFullyInsideViewport(enemy)) return false; const baseAmount=baseDamage ?? (ctx ? this.baseDamageValue(damage/(ctx.damageMultiplier||1),ctx) : damage); const tags=mergeTags(skill.tags, extraTags); const damaged=this.scene.combatSystem.damageEnemy(enemy, Math.max(1,Math.round(damage)), { source:'skill', skillId:skill.id, tags, level, professionApplied:true, professionMultiplier:ctx?.professionMultiplier||1, baseAmountBeforeProfession:Math.max(1,Math.round(baseAmount)), noKnockback:!!ctx?.noKnockback }); if(!damaged) return false; this.scene.eventBus.emit(CombatEvents.SKILL_HIT,{ enemy, damage, skill, tags, level }); if(!ctx?.noRangerMark && !hasAnyTag(tags,[TAGS.DOT,TAGS.SUMMON])) this.scene.professionSystem?.onDirectHit?.({ enemy, source:'skill', baseDamage:baseAmount }); return true; }
  ring(x,y,r,c){ const o=this.scene.add.circle(x,y,r,c,0.18).setStrokeStyle(4,c,0.9).setDepth(140); this.scene.tweens.add({targets:o,alpha:0,scale:1.15,duration:350,onComplete:()=>o.destroy()}); }
  line(x1,y1,x2,y2,c){ const g=this.scene.add.graphics().setDepth(145); g.lineStyle(5,c,0.9).lineBetween(x1,y1,x2,y2); this.scene.tweens.add({targets:g,alpha:0,duration:220,onComplete:()=>g.destroy()}); }
  projectile(x1,y1,x2,y2,c,duration=180){ const o=this.scene.add.circle(x1,y1,10,c,1).setDepth(145); this.scene.tweens.add({targets:o,x:x2,y:y2,duration,onComplete:()=>o.destroy()}); }
}
