import { ACTIVE_STATES, CombatEvents } from '../core/CombatEvents.js';
import { SKILLS } from '../config/skills.js';
export default class SkillSystem { constructor(scene){ this.scene=scene; this.cooldowns=new Map(); } reset(){ this.cooldowns.clear(); } getOwned(){ return this.scene.playerData.skills; } getLevel(id){ return this.getOwned().find(s=>s.id===id)?.level||0; } addOrLevel(id){ const owned=this.getOwned().find(s=>s.id===id); if(owned) owned.level=Math.min(SKILLS[id].maxLevel, owned.level+1); else this.scene.playerData.skills.push({ id, level:1 }); this.scene.hud?.update(); }
  update(time){ const s=this.scene; if((!ACTIVE_STATES.has(s.runState) && s.runState!==undefined)||s.playerData.hp<=0) return; this.getOwned().forEach(({id,level})=>{ const cfg=SKILLS[id]; const data=cfg.levels[level-1]; const cd=(data.cooldownMs||cfg.cooldownMs)*(1-s.playerData.cooldownReduction); if(time < (this.cooldowns.get(id)||0)) return; if(cfg.triggerType==='lowHp' && s.playerData.hp/s.playerData.maxHp > (data.threshold||0.6)) return; if(cfg.triggerType!=='lowHp' && !this.hasTarget(cfg,data)) return; this.cooldowns.set(id,time+Math.max(300,cd)); this.cast(cfg,data,level); }); }
  hasTarget(cfg,data){ const t=this.scene.targeting; if(cfg.targetType==='nearestAhead') return !!t.nearestAhead(700); if(cfg.targetType==='random') return !!t.random(); if(cfg.targetType==='aroundPlayer') return t.aroundPlayer(data.radius).length>0; return true; }
  cast(cfg,data,level){ const s=this.scene; s.eventBus.emit(CombatEvents.SKILL_CAST,{ skill:cfg, level }); if(cfg.id==='healing'){ const heal=Math.round(data.heal); s.playerData.hp=Math.min(s.playerData.maxHp,s.playerData.hp+heal); s.floatText(s.player.x,s.player.y-100,`+${heal}`,'#7dff8a'); s.hud?.update(); return; } if(cfg.id==='fireball'){ const e=s.targeting.nearestAhead(700); if(e) this.hit(e, Math.round(data.damage*s.playerData.skillDamageMultiplier), cfg, level); if(e&&data.radius>0) s.targeting.aroundPlayer(9999).filter(x=>x!==e&&Math.abs(x.x-e.x)<=data.radius).forEach(x=>this.hit(x, Math.round(data.damage*0.45*s.playerData.skillDamageMultiplier), cfg, level)); }
    if(cfg.id==='lightning'){ let hit=s.targeting.random(); const done=new Set(); for(let i=0; hit&&i<=(data.bounces||0); i++){ done.add(hit); this.hit(hit, Math.round(data.damage*s.playerData.skillDamageMultiplier), cfg, level); hit=s.targeting.all().filter(e=>!done.has(e))[0]; } }
    if(cfg.id==='spinning_blade') s.targeting.aroundPlayer(data.radius).forEach(e=>this.hit(e, Math.round(data.damage*s.playerData.skillDamageMultiplier), cfg, level)); }
  hit(enemy, damage, skill, level){ this.scene.combatSystem.damageEnemy(enemy, damage, { source:'skill', skillId:skill.id, tags:skill.tags, level }); this.scene.eventBus.emit(CombatEvents.SKILL_HIT,{ enemy, damage, skill, tags:skill.tags, level }); }
}
