import { ENEMIES } from '../config/enemies.js';
import { TUNING } from '../config/tuning.js';
import { CombatEvents, RunStates } from '../core/CombatEvents.js';
import createEnemy, { syncEnemyUi } from '../entities/createEnemy.js';

export const LevelFlowStates = Object.freeze({ GROUP_COMBAT:'GROUP_COMBAT', SKILL_REWARD:'SKILL_REWARD', SHOP:'SHOP', BOSS_RUSH:'BOSS_RUSH', BOSS_INTRO:'BOSS_INTRO', BOSS_FIGHT:'BOSS_FIGHT', ARTIFACT_REWARD:'ARTIFACT_REWARD', PROFESSION_REWARD:'PROFESSION_REWARD', ADVANCED_PROFESSION_STATUE:'ADVANCED_PROFESSION_STATUE', CAMPFIRE:'CAMPFIRE', VICTORY:'VICTORY' });
export const FLOW_GROUPS = [
  { group:1, stage:1, waves:[3,3,3], rangedCounts:[0,0,0], ids:[['grunt'],['grunt'],['grunt']], reward:'skill' },
  { group:2, stage:1, waves:[4,4,4], rangedCounts:[0,0,0], ids:[['grunt','charger'],['grunt','charger'],['charger','grunt']], reward:'skill' },
  { group:3, stage:1, waves:[5,5,5], rangedCounts:[0,1,1], ids:[['grunt','charger'],['grunt','bomber'],['charger','grunt','bomber']], reward:'skill', after:'shop1' },
  { group:4, stage:2, waves:[6,6,6], rangedCounts:[2,2,2], ids:[['grunt','bomber'],['charger','bomber'],['grunt','bomber']], reward:'skill' },
  { group:5, stage:2, waves:[7,7,7], rangedCounts:[2,3,2], ids:[['charger','bomber'],['grunt','bomber'],['armored_guard','bomber']], reward:'skill' },
  { group:6, stage:2, waves:[8,8,8], rangedCounts:[1,2,2], ids:[['armored_guard','healer'],['charger','bomber','healer'],['elite','grunt','bomber']], reward:'skill', after:'shop2' },
  { group:7, stage:3, waves:[9,9,9], ids:[['grunt','charger','armored_guard'],['charger','bomber'],['armored_guard','healer']], reward:'skill' },
  { group:8, stage:3, waves:[10,10,10], ids:[['bomber','charger','elite'],['bomber','armored_guard'],['elite','bomber','healer']], reward:'skill' },
  { group:9, stage:3, waves:[11,12,12], ids:[['charger','bomber','armored_guard'],['elite','bomber','healer'],['elite','charger','bomber','healer']], reward:'skill', after:'advancedStatue' },
];
const RUSHES={ boss1:{count:[12,15], boss:'boss1', enemyId:'berserker_boss'}, boss2:{count:[15,18], boss:'boss2', enemyId:'mid_boss'}, boss3:{count:[18,22], boss:'boss3', enemyId:'boss'} };
const BOSS_TITLES={ boss1:'Boss 1 出现：狂暴巨兽', boss2:'Boss 2 出现：铁甲暴君', boss3:'Boss 3 出现：训练场守卫' };
const BOSS_EVENT={ boss1:'boss1', boss2:'mid', boss3:'final' };
const RANGED_IDS=new Set(['bomber','healer']);
export default class StageSystem{
  constructor(scene){ this.scene=scene; this.reset(); }
  reset(){ this.flowState=LevelFlowStates.GROUP_COMBAT; this.currentStage=1; this.groupIndex=0; this.currentGroup=1; this.currentWave=0; this.currentWaveSize=0; this.waveQueue=[]; this.waveState='idle'; this.nextWaveAt=0; this.waveSpawnFinished=false; this.nodeDone=new Set(); this.bossKilled={boss1:false,boss2:false,boss3:false}; this.activeRush=null; this.rushSpawned=false; this.bossSpawned=false; this.campfireCount=0; }
  start(){ this.scene.physics.world.setBounds(0,0,this.scene.balance.stageWorldWidth,this.scene.scale.height); this.scene.cameras.main.setBounds(0,0,this.scene.balance.stageWorldWidth,this.scene.scale.height); this.updateHud(); }
  phase(){ return { id:this.flowState, name:`阶段${this.currentStage}`}; }
  activeEnemyCount(){ return this.scene.enemies.filter(e=>e.active&&!e.isDefeated).length; }
  tunedEnemy(id){ const base=ENEMIES[id]; const key=base.kind; return { ...base, hp:Math.round(base.hp*(TUNING.difficulty[`${key}HpMultiplier`]||1)), damage:Math.round(base.damage*(TUNING.difficulty[`${key}DamageMultiplier`]||1)), xp:0 }; }
  spawnXFor(id){ const cfg=ENEMIES[id]||ENEMIES.grunt, cam=this.scene.cameras?.main, right=cam?.worldView?.right ?? ((cam?.scrollX||0)+(cam?.width||720)); return Math.min(this.scene.balance.stageWorldWidth-cfg.width/2-8, right+cfg.width+(this.scene.balance.enemies?.respawnPadding??96)); }
  spawn(id,x){ if(this.activeEnemyCount()>=this.scene.balance.enemyPopulation.hardCap) return null; const e=createEnemy(this.scene,this.tunedEnemy(id),x??this.spawnXFor(id),this.scene.balance.groundTopY); e.combatSpeed=e.speed; e.entrySpeed=this.scene.balance.enemies?.entrySpeed||260; this.scene.enemies.push(e); this.scene.enemyBehaviors?.attach(e); if(e.isElite) this.scene.eventBus.emit(CombatEvents.ELITE_SPAWNED,{enemy:e}); return e; }
  update(time){ if(this.scene.isGameplayPaused?.()) return; this.drainWaveQueue(time); this.scene.enemyBehaviors?.update(time); this.separateEnemies(); this.scene.enemies.forEach(syncEnemyUi); if(this.flowState===LevelFlowStates.GROUP_COMBAT) this.updateGroup(time); else if(this.flowState===LevelFlowStates.BOSS_RUSH) this.updateRush(time); }
  updateGroup(time){ if(this.waveQueue.length||this.activeEnemyCount()>0) return; if(this.waveSpawnFinished){ if(this.currentWave>=3) return this.finishGroup(); this.nextWaveAt=time+1500; this.waveSpawnFinished=false; this.waveState='waitingNextWave'; }
    if(this.waveState==='waitingNextWave'&&time<this.nextWaveAt) return; if(this.waveState==='idle'||this.waveState==='waitingNextWave') this.queueGroupWave(time); }
  queueGroupWave(time){ const g=FLOW_GROUPS[this.groupIndex]; this.currentStage=g.stage; this.currentGroup=g.group; this.currentWave+=1; const count=g.waves[this.currentWave-1]; this.currentWaveSize=count; const ids=this.makeWaveIds(g.ids[this.currentWave-1],count,g.rangedCounts?.[this.currentWave-1]??0); let at=time; ids.forEach((id,i)=>{ if(i>0) at+=ids[i-1].role===id.role?this.scene.balance.enemyPopulation.sameTypeSpawnIntervalMs:this.scene.balance.enemyPopulation.typeSwitchSpawnIntervalMs; this.waveQueue.push({at,id:id.id}); }); this.waveState='spawning'; this.updateHud(); }
  makeWaveIds(pool,count,rangedCount=0){ const backPool=pool.filter(id=>RANGED_IDS.has(id)); const frontPool=pool.filter(id=>!RANGED_IDS.has(id)&&id!=='healer'&&id!=='elite'); const special=[]; if(pool.includes('elite')) special.push('elite'); const healerCount=pool.includes('healer')?1:0; const backCount=Math.min(count-special.length, Math.max(healerCount, rangedCount)); const frontCount=Math.max(0,count-special.length-backCount); const front=[]; for(let i=0;i<frontCount;i+=1) front.push({id:frontPool[i%Math.max(1,frontPool.length)]||'grunt',role:'front'}); special.forEach(id=>front.unshift({id,role:'front'})); const back=[]; const rangedOnly=backPool.filter(id=>id!=='healer'); for(let i=0;i<backCount-healerCount;i+=1) back.push({id:rangedOnly[i%Math.max(1,rangedOnly.length)]||'bomber',role:'back'}); for(let i=0;i<healerCount;i+=1) back.push({id:'healer',role:'back'}); return [...front,...back].slice(0,count); }
  drainWaveQueue(time){ while(this.waveQueue.length&&time>=this.waveQueue[0].at){ const item=this.waveQueue.shift(); this.spawn(item.id); } if(this.waveState==='spawning'&&!this.waveQueue.length){ this.waveState='fighting'; this.waveSpawnFinished=true; } }
  finishGroup(){ const g=FLOW_GROUPS[this.groupIndex]; const key=`skill_${g.group}`; this.flowState=LevelFlowStates.SKILL_REWARD; if(!this.nodeDone.has(key)){ this.nodeDone.add(key); this.scene.playerData.level=Math.max(this.scene.playerData.level,g.group+1); this.scene.showSkillReward?.(`第${g.group}组三波清空：技能三选一`); } }
  onSkillRewardClosed(){ const g=FLOW_GROUPS[this.groupIndex]; if(g.after==='shop1') return this.enterShop('first'); if(g.after==='shop2') return this.enterShop('second'); if(g.after==='advancedStatue') return this.enterAdvancedStatue(); this.groupIndex+=1; this.currentWave=0; this.waveState='idle'; this.waveSpawnFinished=false; this.flowState=LevelFlowStates.GROUP_COMBAT; this.updateHud(); }
  enterShop(reason){ this.flowState=LevelFlowStates.SHOP; if(!this.nodeDone.has(`shop_${reason}`)){ this.nodeDone.add(`shop_${reason}`); this.scene.queueShop?.(reason); } }
  onShopClosed(reason){ if(reason==='first') this.startRush('boss1'); else if(reason==='second') this.startRush('boss2'); }
  startRush(id){ this.flowState=LevelFlowStates.BOSS_RUSH; this.activeRush=id; this.rushSpawned=false; this.bossSpawned=false; this.waveState='idle'; this.waveQueue=[]; this.scene.hud?.setStatus('Boss 前怪潮来袭'); }
  updateRush(time){ if(!this.rushSpawned){ const cfg=RUSHES[this.activeRush], count=(cfg.count[0]+Math.floor(Math.random()*(cfg.count[1]-cfg.count[0]+1))); const pool=this.activeRush==='boss1'?['grunt','charger','bomber']:this.activeRush==='boss2'?['charger','armored_guard','bomber','healer','elite']:['charger','armored_guard','bomber','healer','elite']; for(let i=0;i<count;i+=1) this.waveQueue.push({at:time+i*80,id:pool[i%pool.length]}); this.waveState='spawning'; this.rushSpawned=true; } if(this.rushSpawned&&!this.waveQueue.length&&this.activeEnemyCount()===0&&!this.bossSpawned) this.spawnBoss(this.activeRush); }
  spawnBoss(id){ const cfg=RUSHES[id]; this.flowState=LevelFlowStates.BOSS_FIGHT; this.bossSpawned=true; const b=this.spawn(cfg.enemyId); this.scene.runState=RunStates.BOSS; this.scene.eventBus.emit(CombatEvents.BOSS_SPAWNED,{enemy:b,bossType:BOSS_EVENT[id],flowBossType:id}); this.scene.hud?.setStatus(BOSS_TITLES[id]); }
  onBossKilled(id){ if(this.nodeDone.has(`bossKilled_${id}`)) return; this.nodeDone.add(`bossKilled_${id}`); this.bossKilled[id]=true; if(id==='boss3'){ this.flowState=LevelFlowStates.VICTORY; this.scene.finishRun?.(true); return; } this.flowState=LevelFlowStates.ARTIFACT_REWARD; this.scene.queueArtifactReward?.({id,name:BOSS_TITLES[id]},{afterBoss:id}); this.scene.resumeModalFlow?.(); }
  beginAfterBossReward(id){ if(id==='boss1') return this.enterCampfire('boss1'); if(id==='boss2') return this.enterProfessionReward(); }
  enterProfessionReward(){ this.flowState=LevelFlowStates.PROFESSION_REWARD; if(!this.nodeDone.has('profession1')){ this.nodeDone.add('profession1'); this.scene.showProfessionChoice?.(); } }
  onProfessionChosen(){ if(this.flowState===LevelFlowStates.PROFESSION_REWARD) this.enterCampfire('boss2'); }
  enterAdvancedStatue(){ this.flowState=LevelFlowStates.ADVANCED_PROFESSION_STATUE; if(!this.nodeDone.has('advancedProfession')){ this.nodeDone.add('advancedProfession'); this.scene.showAdvancedProfessionChoice?.(); } }
  onAdvancedProfessionChosen(){ if(this.flowState===LevelFlowStates.ADVANCED_PROFESSION_STATUE) this.enterCampfire('advanced'); }
  enterCampfire(source){ this.flowState=LevelFlowStates.CAMPFIRE; if(this.nodeDone.has(`campfire_${source}`)) return; this.nodeDone.add(`campfire_${source}`); this.campfireCount+=1; this.scene.showCampfire?.(source); }
  onCampfireClosed(source){ if(source==='boss1'){ this.groupIndex=3; this.currentWave=0; this.flowState=LevelFlowStates.GROUP_COMBAT; } else if(source==='boss2'){ this.groupIndex=6; this.currentWave=0; this.flowState=LevelFlowStates.GROUP_COMBAT; } else if(source==='advanced') this.startRush('boss3'); this.waveState='idle'; this.waveSpawnFinished=false; this.updateHud(); }
  shiftTimers(delta, after){ if(this.nextWaveAt>after) this.nextWaveAt+=delta; this.waveQueue.forEach(i=>{ if(i.at>after)i.at+=delta; }); }
  updateHud(){ this.scene.hud?.setStage(`阶段${this.currentStage} 第${this.currentGroup}组 第${this.currentWave||1}/3波`); this.scene.hud?.update(); }
  shouldHoldPlayerForBossIntro(){ return false; }
  clearBossMinions(){ this.scene.enemies.filter(e=>!e.isBoss&&!e.isDefeated).forEach(e=>{ e.isDefeated=true; this.scene.enemyBehaviors?.destroyEnemy(e); this.scene.statusEffects?.clearTarget(e); [e.hpBarBg,e.hpBar,e.nameText,e].forEach(o=>o?.destroy()); e.destroy(); }); this.scene.enemies=this.scene.enemies.filter(e=>e.isBoss&&!e.isDefeated); }
  clearEnemies(){ this.waveQueue=[]; this.scene.enemies.forEach(e=>{ this.scene.enemyBehaviors?.destroyEnemy(e); [e.hpBarBg,e.hpBar,e.nameText,e].forEach(o=>o?.destroy()); e.destroy(); }); this.scene.enemies=[]; }
  separateEnemies(){ const enemies=this.scene.enemies.filter(e=>!e.isDefeated&&e.active); for(let i=0;i<enemies.length;i++) for(let j=i+1;j<enemies.length;j++){ const a=enemies[i],b=enemies[j],min=((a.body?.width||a.width)/2)+((b.body?.width||b.width)/2)+8,dx=b.x-a.x,overlap=min-Math.abs(dx); if(overlap>0){ const dir=dx>=0?1:-1,shift=Math.min(overlap/2,10); if(!a.isBoss)a.x-=dir*shift; if(!b.isBoss)b.x+=dir*shift; } } }
}
