import { getEnemyAttackDelay } from './EnemyGravityControl.js';
import { ENEMIES } from '../config/enemies.js';
import { TUNING } from '../config/tuning.js';
import { CombatEvents, RunStates } from '../core/CombatEvents.js';
import createEnemy, { syncEnemyUi } from '../entities/createEnemy.js';
import { destroyEnemyStatusIndicators } from '../ui/EnemyStatusIndicators.js';

export const LevelFlowStates = Object.freeze({ GROUP_COMBAT:'GROUP_COMBAT', SKILL_REWARD:'SKILL_REWARD', SHOP:'SHOP', BOSS_RUSH:'BOSS_RUSH', BOSS_INTRO:'BOSS_INTRO', BOSS_FIGHT:'BOSS_FIGHT', ARTIFACT_REWARD:'ARTIFACT_REWARD', PROFESSION_REWARD:'PROFESSION_REWARD', ADVANCED_PROFESSION_STATUE:'ADVANCED_PROFESSION_STATUE', CAMPFIRE:'CAMPFIRE', VICTORY:'VICTORY' });
export const FLOW_GROUPS = [
  { group:1, stage:1, waves:[3,3,3], rangedCounts:[0,0,0], ids:[['grunt'],['grunt'],['grunt']], reward:'skill' },
  { group:2, stage:1, waves:[4,4,4], rangedCounts:[0,0,0], ids:[['grunt','armored_guard'],['grunt','armored_guard'],['armored_guard','grunt']], reward:'skill' },
  { group:3, stage:1, waves:[5,5,5], rangedCounts:[0,0,0], ids:[['grunt','armored_guard'],['grunt','armored_guard'],['armored_guard','grunt']], reward:'skill', after:'shop1' },
  { group:4, stage:2, waves:[6,6,6], rangedCounts:[2,2,2], ids:[['grunt','archer'],['charger','archer'],['grunt','archer']], reward:'skill' },
  { group:5, stage:2, waves:[7,7,7], rangedCounts:[2,3,2], ids:[['charger','archer'],['grunt','archer'],['armored_guard','archer']], reward:'skill' },
  { group:6, stage:2, waves:[8,8,8], rangedCounts:[1,2,2], ids:[['armored_guard','healer'],['charger','archer','healer'],['elite','grunt','archer']], reward:'skill', after:'shop2' },
  { group:7, stage:3, waves:[9,9,9], rangedCounts:[2,2,2], ids:[['grunt','charger','armored_guard','archer'],['charger','archer'],['armored_guard','archer','healer']], reward:'skill' },
  { group:8, stage:3, waves:[10,10,10], rangedCounts:[2,3,3], ids:[['archer','charger','elite'],['archer','armored_guard'],['elite','archer','healer']], reward:'skill' },
  { group:9, stage:3, waves:[11,12,12], rangedCounts:[3,3,4], ids:[['charger','archer','armored_guard'],['elite','archer','healer'],['elite','charger','archer','healer']], reward:'skill', after:'advancedStatue' },
  { group:10, stage:4, waves:[12,12,13], rangedCounts:[3,3,4], ids:[['charger','armored_guard','archer'],['elite','grunt','archer','healer'],['charger','archer','healer','elite']], reward:'skill' },
  { group:11, stage:4, waves:[13,13,14], rangedCounts:[3,4,4], ids:[['armored_guard','archer','healer'],['charger','elite','archer'],['elite','charger','archer','healer']], reward:'skill' },
  { group:12, stage:4, waves:[14,15,15], rangedCounts:[4,4,5], ids:[['elite','armored_guard','archer'],['charger','archer','healer','elite'],['elite','charger','armored_guard','archer','bomber','healer']], reward:'skill', after:'shop3' },
  { group:13, stage:5, waves:[15,15,16], rangedCounts:[4,5,5], ids:[['charger','elite','archer'],['armored_guard','archer','healer','elite'],['elite','charger','archer','healer']], reward:'skill' },
  { group:14, stage:5, waves:[16,16,17], rangedCounts:[5,5,6], ids:[['elite','charger','armored_guard','archer'],['elite','archer','healer'],['charger','armored_guard','archer','bomber','healer','elite']], reward:'skill' },
  { group:15, stage:5, waves:[17,18,18], rangedCounts:[5,6,6], ids:[['elite','charger','archer'],['elite','armored_guard','archer','healer'],['elite','charger','armored_guard','archer','healer']], reward:'skill', after:'shop4' },
  { group:16, stage:6, waves:[18,18,19], rangedCounts:[6,6,7], ids:[['elite','charger','armored_guard','archer'],['elite','archer','healer'],['elite','charger','archer','bomber','healer']], reward:'skill' },
  { group:17, stage:6, waves:[19,20,20], rangedCounts:[6,7,7], ids:[['elite','charger','armored_guard','archer','healer'],['elite','archer','healer'],['elite','charger','armored_guard','archer','bomber','healer']], reward:'skill' },
  { group:18, stage:6, waves:[20,21,22], rangedCounts:[7,7,8], ids:[['elite','charger','armored_guard','archer'],['elite','charger','archer','healer'],['elite','charger','armored_guard','archer','bomber','healer']], reward:'skill', after:'shop5' },
];
const RUSHES={ boss1:{count:[10,10],boss:'boss1',enemyId:'berserker_boss'}, boss2:{count:[15,18],boss:'boss2',enemyId:'mid_boss'}, boss3:{count:[18,22],boss:'boss3',enemyId:'boss'}, boss4:{count:[20,24],boss:'boss4',enemyId:'berserker_boss',overrides:{id:'abyss_devourer',name:'深渊吞噬者',bossType:'boss4',hp:2300,damage:24,chargeDamage:34,chargeCooldownMs:3100,attackIntervalMs:1180,speed:286,color:0x7c1d6f,stroke:0x2e0a2a}}, boss5:{count:[23,27],boss:'boss5',enemyId:'mid_boss',overrides:{id:'thunder_war_machine',name:'雷霆战争机',bossType:'boss5',hp:3300,damage:30,slamDamage:25,chargeDamage:30,attackIntervalMs:1080,enragedAttackIntervalMs:760,speed:296,color:0x2563eb,stroke:0x0f172a}}, boss6:{count:[26,30],boss:'boss6',enemyId:'boss',overrides:{id:'void_monarch',name:'虚空君王',bossType:'boss6',hp:4700,damage:38,attackIntervalMs:950,enragedAttackIntervalMs:620,speed:308,color:0x111827,stroke:0xa855f7}} };
const BOSS_TITLES={ boss1:'Boss 1 出现：狂暴巨兽', boss2:'Boss 2 出现：铁甲暴君', boss3:'Boss 3 出现：训练场守卫', boss4:'Boss 4 出现：深渊吞噬者', boss5:'Boss 5 出现：雷霆战争机', boss6:'Boss 6 出现：虚空君王' };
const BOSS_EVENT={ boss1:'boss1', boss2:'mid', boss3:'boss3', boss4:'boss4', boss5:'boss5', boss6:'final' };
const RANGED_IDS=new Set(['archer','bomber','healer']);
export default class StageSystem{
  constructor(scene){ this.scene=scene; this.reset(); }
  reset(){ this.flowState=LevelFlowStates.GROUP_COMBAT; this.currentStage=1; this.groupIndex=0; this.currentGroup=1; this.currentWave=0; this.currentWaveSize=0; this.waveQueue=[]; this.waveState='idle'; this.nextWaveAt=0; this.waveSpawnFinished=false; this.nodeDone=new Set(); this.bossKilled={boss1:false,boss2:false,boss3:false,boss4:false,boss5:false,boss6:false}; this.activeRush=null; this.rushSpawned=false; this.bossSpawned=false; this.campfireCount=0; this.awaitingSkillRewardClose=false; this.currentEnemyLevel=1; this.pendingLevelUp=false; this.completedWaveCount=0; }
  start(){ this.scene.physics.world.setBounds(0,0,this.scene.balance.stageWorldWidth,this.scene.scale.height); this.scene.cameras.main.setBounds(0,0,this.scene.balance.stageWorldWidth,this.scene.scale.height); this.updateHud(); }
  phase(){ return { id:this.flowState, name:`阶段${this.currentStage}`}; }
  activeEnemyCount(){ return this.scene.enemies.filter(e=>e.active&&!e.isDefeated).length; }
  progressionWaveIndex(){ return Math.max(0,this.groupIndex*3+Math.max(0,this.currentWave-1)); }
  enemyLevelForCompletedWaves(completedWaveCount=this.completedWaveCount){ return Math.floor(Math.max(0,completedWaveCount)/(TUNING.leveling.wavesPerLevel||3))+1; }
  tunedEnemy(id,overrides=null){ const base={...ENEMIES[id],...(overrides||{})}; const key=base.kind; const difficulty=TUNING.difficulty; const leveling=TUNING.leveling; const enemyLevel=this.currentEnemyLevel||1; const levelOffset=Math.max(0,enemyLevel-1); const enemyLevelHpMultiplier=1+levelOffset*(leveling.enemyHpGrowthPerLevel||0); const enemyLevelDamageMultiplier=1+levelOffset*(leveling.enemyDamageGrowthPerLevel||0); return { ...base, level:enemyLevel, hp:Math.round(base.hp*(difficulty[`${key}HpMultiplier`]||1)*enemyLevelHpMultiplier), damage:Math.max(1,Math.round(base.damage*(difficulty[`${key}DamageMultiplier`]||1)*enemyLevelDamageMultiplier)), xp:0 }; }
  spawnXFor(id){ const cfg=ENEMIES[id]||ENEMIES.grunt, cam=this.scene.cameras?.main, right=cam?.worldView?.right ?? ((cam?.scrollX||0)+(cam?.width||720)); return Math.min(this.scene.balance.stageWorldWidth-cfg.width/2-8, right+cfg.width+(this.scene.balance.enemies?.respawnPadding??96)); }
  spawn(id,x,overrides=null){ if(this.activeEnemyCount()>=this.scene.balance.enemyPopulation.hardCap) return null; const e=createEnemy(this.scene,this.tunedEnemy(id,overrides),x??this.spawnXFor(id),this.scene.balance.groundTopY); this.scene.enemies.push(e); this.scene.enemyBehaviors?.attach(e); if(e.isElite) this.scene.eventBus.emit(CombatEvents.ELITE_SPAWNED,{enemy:e}); return e; }
  update(time){ if(this.scene.isGameplayPaused?.()) return; this.drainWaveQueue(time); this.scene.enemyBehaviors?.update(time); this.updateBossKnockbackCounterattacks(time); this.scene.enemies.forEach(syncEnemyUi); if(this.flowState===LevelFlowStates.GROUP_COMBAT) this.updateGroup(time); else if(this.flowState===LevelFlowStates.BOSS_RUSH) this.updateRush(time); }
  updateBossKnockbackCounterattacks(time){ const s=this.scene; s.enemies.filter(e=>e.active&&!e.isDefeated&&e.isBoss&&e.isKnockbackActive).forEach(e=>{ const range=(e.attackRange||155)+120; if(time<(e.nextAttackAt||0)) return; const target=s.combatSystem?.chooseEnemyAttackTarget?.(e,range); if(!target) return; e.nextAttackAt=time+getEnemyAttackDelay(e,e.attackIntervalMs||1400,time); s.combatSystem?.damageAttackTarget?.(target,e.damage,{ enemy:e, source:'bossKnockbackCounter', attackType:'melee', dodgeable:true, singleTarget:true }); }); }
  updateGroup(time){ if(this.waveQueue.length||this.activeEnemyCount()>0) return; if(this.waveSpawnFinished){ if(this.currentWave>=3) return this.finishGroup(); this.nextWaveAt=time+1500; this.waveSpawnFinished=false; this.waveState='waitingNextWave'; } if(this.waveState==='waitingNextWave'&&time<this.nextWaveAt) return; if(this.waveState==='idle'||this.waveState==='waitingNextWave') this.queueGroupWave(time); }
  queueGroupWave(time){ const g=FLOW_GROUPS[this.groupIndex]; this.currentStage=g.stage; this.currentGroup=g.group; this.currentWave+=1; const count=g.waves[this.currentWave-1]; this.currentWaveSize=count; const ids=this.assignWaveSpawnXs(this.makeWaveIds(g.ids[this.currentWave-1],count,g.rangedCounts?.[this.currentWave-1]??0)); let at=time; ids.forEach((id,i)=>{ if(i>0) at+=ids[i-1].role===id.role?this.scene.balance.enemyPopulation.sameTypeSpawnIntervalMs:this.scene.balance.enemyPopulation.typeSwitchSpawnIntervalMs; this.waveQueue.push({at,id:id.id,x:id.x}); }); this.waveState='spawning'; this.scene.eventBus.emit(CombatEvents.COMBAT_STARTED,{kind:'wave',group:this.currentGroup,wave:this.currentWave}); this.updateHud(); }
  assignWaveSpawnXs(items){ const safety=10, worldWidth=this.scene.balance.stageWorldWidth; let prev=null; const placed=items.map(item=>{ const cfg=ENEMIES[item.id]||ENEMIES.grunt, half=(cfg.bodyWidth||cfg.width)/2; const minX=half+8, maxX=worldWidth-half-8; const base=Math.max(minX,Math.min(maxX,this.spawnXFor(item.id))); const minFromPrev=prev?prev.x+prev.half+half+safety:base; const x=Math.max(base,minFromPrev); prev={x,half}; return {...item,x,half,maxX,minX}; }); const overflow=Math.max(0,...placed.map(p=>p.x-p.maxX)); if(overflow>0){ const shift=Math.min(overflow,Math.min(...placed.map(p=>p.x-p.minX))); placed.forEach(p=>{p.x-=shift;}); } for(let i=1;i<placed.length;i+=1){ const need=placed[i-1].half+placed[i].half+safety; if(placed[i].x-placed[i-1].x<need) placed[i].x=Math.min(placed[i].maxX,placed[i-1].x+need); } return placed.map(({half,maxX,minX,...item})=>item); }
  makeWaveIds(pool,count,rangedCount=0){ const frontPool=pool.filter(id=>!RANGED_IDS.has(id)&&id!=='elite'); const special=[]; if(pool.includes('elite')) special.push('elite'); const healerCount=pool.includes('healer')?1:0; const bomberCount=pool.includes('bomber')?1:0; const desiredBackCount=Math.min(count-special.length,Math.max(rangedCount,healerCount+bomberCount)); const archerCount=Math.max(0,desiredBackCount-healerCount-bomberCount); const frontCount=Math.max(0,count-special.length-desiredBackCount); const front=[]; for(let i=0;i<frontCount;i+=1) front.push({id:frontPool[i%Math.max(1,frontPool.length)]||'grunt',role:'front'}); special.forEach(id=>front.unshift({id,role:'front'})); const back=[]; for(let i=0;i<archerCount;i+=1) back.push({id:'archer',role:'back'}); if(bomberCount) back.push({id:'bomber',role:'back'}); if(healerCount) back.push({id:'healer',role:'back'}); return [...front,...back].slice(0,count); }
  drainWaveQueue(time){ while(this.waveQueue.length&&time>=this.waveQueue[0].at){ const item=this.waveQueue.shift(); this.spawn(item.id,item.x); } if(this.waveState==='spawning'&&!this.waveQueue.length){ this.waveState='fighting'; this.waveSpawnFinished=true; } }
  finishGroup(){ const g=FLOW_GROUPS[this.groupIndex]; const key=`skill_${g.group}`; this.flowState=LevelFlowStates.SKILL_REWARD; if(!this.nodeDone.has(key)){ this.nodeDone.add(key); this.awaitingSkillRewardClose=true; this.completedWaveCount=(this.groupIndex+1)*(TUNING.leveling.wavesPerLevel||3); this.pendingLevelUp=true; this.scene.showSkillReward?.(`第${g.group}组三波清空：技能三选一`); } }
  applyPendingLevelUp(){ if(!this.pendingLevelUp) return false; this.pendingLevelUp=false; const p=this.scene.playerData, leveling=TUNING.leveling, nextLevel=this.enemyLevelForCompletedWaves(this.completedWaveCount); if(nextLevel<=p.level&&nextLevel<=this.currentEnemyLevel) return false; const hpGain=leveling.playerHpPerLevel||0, manaGain=leveling.playerManaPerLevel||0; p.level=Math.max(p.level,nextLevel); p.maxHp+=hpGain; p.hp=Math.min(p.maxHp,p.hp+hpGain); p.maxMana=(p.maxMana??leveling.initialPlayerMana)+manaGain; p.mana=Math.min(p.maxMana,(p.mana??0)+manaGain); this.currentEnemyLevel=Math.max(this.currentEnemyLevel,nextLevel); this.scene.hud?.update(); this.scene.floatText?.(this.scene.player.x,this.scene.player.y-120,`等级提升 Lv.${p.level}\n生命上限 +${hpGain}\n法力上限 +${manaGain}`,'#7dd3fc'); return true; }
  onSkillRewardClosed(){ if(this.flowState!==LevelFlowStates.SKILL_REWARD||!this.awaitingSkillRewardClose) return false; this.awaitingSkillRewardClose=false; this.applyPendingLevelUp(); const g=FLOW_GROUPS[this.groupIndex]; if(g.after==='shop1') return this.enterShop('first'); if(g.after==='shop2') return this.enterShop('second'); if(g.after==='advancedStatue') return this.enterAdvancedStatue(); if(g.after==='shop3') return this.enterShop('third'); if(g.after==='shop4') return this.enterShop('fourth'); if(g.after==='shop5') return this.enterShop('fifth'); this.groupIndex+=1; this.currentWave=0; this.waveState='idle'; this.waveSpawnFinished=false; this.flowState=LevelFlowStates.GROUP_COMBAT; this.updateHud(); return true; }
  enterShop(reason){ this.flowState=LevelFlowStates.SHOP; if(!this.nodeDone.has(`shop_${reason}`)){ this.nodeDone.add(`shop_${reason}`); this.scene.queueShop?.(reason); } }
  onShopClosed(reason){ if(reason==='first') this.startRush('boss1'); else if(reason==='second') this.startRush('boss2'); else if(reason==='third') this.startRush('boss4'); else if(reason==='fourth') this.startRush('boss5'); else if(reason==='fifth') this.startRush('boss6'); }
  startRush(id){ this.flowState=LevelFlowStates.BOSS_RUSH; this.activeRush=id; this.rushSpawned=false; this.bossSpawned=false; this.waveState='idle'; this.waveQueue=[]; this.scene.hud?.setStatus('Boss 前怪潮来袭'); }
  updateRush(time){ if(!this.rushSpawned){ const cfg=RUSHES[this.activeRush], count=cfg.count[0]+Math.floor(Math.random()*(cfg.count[1]-cfg.count[0]+1)); const pool=this.activeRush==='boss1'?['grunt','armored_guard']:['charger','armored_guard','elite']; const eliteCap=this.activeRush==='boss2'?1:(this.activeRush==='boss3'?2:Math.min(4,1+Number(this.activeRush.replace('boss',''))-2)); let eliteCount=0; const items=Array.from({length:count},(_,i)=>{ let id=pool[i%pool.length]; if(id==='elite'){ if(eliteCount>=eliteCap) id='armored_guard'; else eliteCount+=1; } return {id}; }); this.assignWaveSpawnXs(items).forEach((item,i)=>this.waveQueue.push({at:time+i*80,id:item.id,x:item.x})); this.waveState='spawning'; this.rushSpawned=true; this.scene.eventBus.emit(CombatEvents.COMBAT_STARTED,{kind:'bossRush',group:this.currentGroup,wave:this.currentWave,flowBossType:this.activeRush}); } if(this.rushSpawned&&!this.waveQueue.length&&this.activeEnemyCount()===0&&!this.bossSpawned) this.spawnBoss(this.activeRush); }
  spawnBoss(id){ const cfg=RUSHES[id]; this.flowState=LevelFlowStates.BOSS_FIGHT; this.bossSpawned=true; const b=this.spawn(cfg.enemyId,undefined,cfg.overrides); if(b){ b.flowBossType=id; b.isFinalBoss=id==='boss6'; } this.scene.runState=RunStates.BOSS; this.scene.eventBus.emit(CombatEvents.COMBAT_STARTED,{kind:'boss',group:this.currentGroup,wave:this.currentWave,bossId:cfg.enemyId,flowBossType:id}); this.scene.eventBus.emit(CombatEvents.BOSS_SPAWNED,{enemy:b,bossType:BOSS_EVENT[id],flowBossType:id}); this.scene.hud?.setStatus(BOSS_TITLES[id]); }
  onBossKilled(id){ const resolvedId=this.activeRush&&RUSHES[this.activeRush]?this.activeRush:id; if(this.nodeDone.has(`bossKilled_${resolvedId}`)) return; this.nodeDone.add(`bossKilled_${resolvedId}`); this.bossKilled[resolvedId]=true; if(resolvedId==='boss6'){ this.flowState=LevelFlowStates.VICTORY; this.scene.finishRun?.(true); return; } this.flowState=LevelFlowStates.ARTIFACT_REWARD; this.scene.queueArtifactReward?.({id:resolvedId,name:BOSS_TITLES[resolvedId]},{afterBoss:resolvedId}); this.scene.resumeModalFlow?.(); }
  beginAfterBossReward(id){ if(id==='boss1') return this.enterCampfire('boss1'); if(id==='boss2') return this.enterProfessionReward(); if(id==='boss3') return this.enterCampfire('boss3'); if(id==='boss4') return this.enterCampfire('boss4'); if(id==='boss5') return this.enterCampfire('boss5'); }
  enterProfessionReward(){ this.flowState=LevelFlowStates.PROFESSION_REWARD; if(!this.nodeDone.has('profession1')){ this.nodeDone.add('profession1'); this.scene.showProfessionChoice?.(); } }
  onProfessionChosen(){ if(this.flowState===LevelFlowStates.PROFESSION_REWARD) this.enterCampfire('boss2'); }
  enterAdvancedStatue(){ this.flowState=LevelFlowStates.ADVANCED_PROFESSION_STATUE; if(!this.nodeDone.has('advancedProfession')){ this.nodeDone.add('advancedProfession'); this.scene.showAdvancedProfessionChoice?.(); } }
  onAdvancedProfessionChosen(){ if(this.flowState===LevelFlowStates.ADVANCED_PROFESSION_STATUE) this.enterCampfire('advanced'); }
  enterCampfire(source){ this.flowState=LevelFlowStates.CAMPFIRE; if(this.nodeDone.has(`campfire_${source}`)) return; this.nodeDone.add(`campfire_${source}`); this.campfireCount+=1; this.scene.showCampfire?.(source); }
  onCampfireClosed(source){ if(source==='boss1'){ this.groupIndex=3; this.currentWave=0; this.flowState=LevelFlowStates.GROUP_COMBAT; } else if(source==='boss2'){ this.groupIndex=6; this.currentWave=0; this.flowState=LevelFlowStates.GROUP_COMBAT; } else if(source==='advanced') this.startRush('boss3'); else if(source==='boss3'){ this.groupIndex=9; this.currentWave=0; this.flowState=LevelFlowStates.GROUP_COMBAT; } else if(source==='boss4'){ this.groupIndex=12; this.currentWave=0; this.flowState=LevelFlowStates.GROUP_COMBAT; } else if(source==='boss5'){ this.groupIndex=15; this.currentWave=0; this.flowState=LevelFlowStates.GROUP_COMBAT; } this.waveState='idle'; this.waveSpawnFinished=false; this.updateHud(); }
  shiftTimers(delta,after){ if(this.nextWaveAt>after) this.nextWaveAt+=delta; this.waveQueue.forEach(item=>{ if(item.at>after) item.at+=delta; }); }
  updateHud(){ this.scene.hud?.setStage(`阶段${this.currentStage} 第${this.currentGroup}组 第${this.currentWave||1}/3波`); this.scene.hud?.update(); }
  shouldHoldPlayerForBossIntro(){ return false; }
  clearBossMinions(){ this.scene.enemies.filter(e=>!e.isBoss&&!e.isDefeated).forEach(e=>{ e.isDefeated=true; this.scene.combatSystem?.clearKnockback?.(e); this.scene.enemyBehaviors?.destroyEnemy(e); this.scene.statusEffects?.clearTarget(e); destroyEnemyStatusIndicators(e); [e.hpBarBg,e.hpBar,e.nameText,e.levelText,e].forEach(o=>o?.destroy()); e.destroy(); }); this.scene.enemies=this.scene.enemies.filter(e=>e.isBoss&&!e.isDefeated); }
  clearEnemies(){ this.waveQueue=[]; this.scene.enemies.forEach(e=>{ this.scene.combatSystem?.clearKnockback?.(e); this.scene.enemyBehaviors?.destroyEnemy(e); destroyEnemyStatusIndicators(e); [e.hpBarBg,e.hpBar,e.nameText,e.levelText,e].forEach(o=>o?.destroy()); e.destroy(); }); this.scene.enemies=[]; }
}
