export const StatusEffects = Object.freeze({ BURN:'BURN', POISON:'POISON', DAMAGE_REDUCTION:'DAMAGE_REDUCTION', SHIELD:'SHIELD' });
export default class StatusEffectSystem {
  constructor(scene){ this.scene=scene; this.effects=new Map(); this.nextId=1; }
  reset(){ this.effects.clear(); this.nextId=1; const p=this.scene.playerData; if(p){ p.temporaryDamageReduction=0; p.shield=0; p.permanentShield=0; } }
  shiftTimers(pausedDuration, pausedAt){ this.effects.forEach(e=>{ if(e.expiresAt>pausedAt)e.expiresAt+=pausedDuration; if(e.nextTickAt&&e.nextTickAt>pausedAt)e.nextTickAt+=pausedDuration; }); }
  add(type,target,options={}){ const { sourceId='', durationMs=1000, intervalMs=0, stacks=1, value=0, maxStacks=5 }=options; if(!target) return null; const now=this.scene.getGameplayTime(); const shieldKey=type===StatusEffects.SHIELD?`${sourceId || 'shield'}:${this.nextId}`:sourceId; const old=type===StatusEffects.SHIELD?null:[...this.effects.values()].find(e=>e.type===type&&e.target===target&&e.sourceId===sourceId); if(old){ old.durationMs=durationMs; old.expiresAt=now+durationMs; old.stacks=Math.min(maxStacks,(old.stacks||1)+stacks); old.value=value||old.value; Object.assign(old, options); this.syncPlayerDerived(); return old; } const e={ id:this.nextId++, type, target, sourceId:shieldKey, durationMs, expiresAt:now+durationMs, nextTickAt:intervalMs?now+intervalMs:0, intervalMs, stacks, value, ...options }; if(type===StatusEffects.SHIELD){ const p=this.scene.playerData; const room=Math.max(0,p.maxShield-(p.shield||0)); e.remainingValue=Math.min(room, Math.max(0, options.remainingValue ?? value)); if(e.remainingValue<=0) return null; } this.effects.set(e.id,e); this.syncPlayerDerived(); return e; }
  update(time){ if(this.scene.isGameplayPaused?.()) return; this.effects.forEach(e=>{ if(!this.validTarget(e.target)){ this.effects.delete(e.id); return; } if(e.intervalMs){ while(time>=e.nextTickAt && time<e.expiresAt && this.validTarget(e.target)){ const source=e.type===StatusEffects.BURN?'burn':'poison'; this.scene.combatSystem.damageEnemy(e.target, Math.round(e.value*(e.stacks||1)*(e.damageMultiplier||1)), { source, tags:[source], canTriggerArtifacts:false, statusId:e.id, professionApplied:!!e.professionApplied }); e.nextTickAt+=e.intervalMs; } } if(time>=e.expiresAt || (e.type===StatusEffects.SHIELD && e.remainingValue<=0)) this.effects.delete(e.id); }); this.syncPlayerDerived(); }
  validTarget(t){ return t===this.scene.playerData || this.scene.targeting?.valid(t); }
  clearTarget(target){ this.effects.forEach(e=>{ if(e.target===target) this.effects.delete(e.id); }); this.syncPlayerDerived(); }
  clearNegativeEffects(target){ this.effects.forEach(e=>{ if(e.target===target&&(e.type===StatusEffects.BURN||e.type===StatusEffects.POISON)) this.effects.delete(e.id); }); this.syncPlayerDerived(); }
  has(target,type){ return this.getEffects(target,type).length>0; }
  getEffects(target,type){ return [...this.effects.values()].filter(e=>e.target===target&&e.type===type); }
  absorbShield(damage){ const p=this.scene.playerData; let remaining=damage; const shields=this.getEffects(p,StatusEffects.SHIELD).sort((a,b)=>a.expiresAt-b.expiresAt); for(const e of shields){ if(remaining<=0) break; const used=Math.min(e.remainingValue||0,remaining); e.remainingValue-=used; remaining-=used; if(e.remainingValue<=0) this.effects.delete(e.id); } if(remaining>0 && (p.permanentShield||0)>0){ const used=Math.min(p.permanentShield,remaining); p.permanentShield-=used; remaining-=used; } this.syncPlayerDerived(); return { absorbed: damage-remaining, remainingDamage: remaining }; }
  addPermanentShield(amount){ const p=this.scene.playerData; p.permanentShield=Math.min(p.maxShield, (p.permanentShield||0)+amount); this.syncPlayerDerived(); }
  syncPlayerDerived(){ const p=this.scene.playerData; if(!p) return; p.temporaryDamageReduction=0; this.effects.forEach(e=>{ if(e.target===p&&e.type===StatusEffects.DAMAGE_REDUCTION) p.temporaryDamageReduction=Math.max(p.temporaryDamageReduction,e.value); }); const temp=this.getEffects(p,StatusEffects.SHIELD).reduce((sum,e)=>sum+(e.remainingValue||0),0); const capped=Math.min(p.maxShield, temp+(p.permanentShield||0)); if(temp+(p.permanentShield||0)>p.maxShield) p.permanentShield=Math.max(0,p.maxShield-temp); p.shield=capped; }
}
