import Phaser from 'phaser';
import { SKILLS } from '../config/skills.js';
import { UPGRADE_RARITY_WEIGHTS, STARTING_RARITIES } from '../config/rarities.js';
import { RunStates, CombatEvents } from '../core/CombatEvents.js';
export const ATTRIBUTE_UPGRADES = [
  { id:'attack_15', title:'攻击强化\n攻击力 +15%', apply:p=>{p.attack=Math.round(p.attack*1.15);} }, { id:'hp_20', title:'生命强化\n最大生命 +20', apply:p=>{p.maxHp+=20;p.hp=Math.min(p.maxHp,p.hp+20);} }, { id:'as_10', title:'攻速强化\n攻击速度 +10%', apply:p=>{p.attackSpeedMultiplier+=0.1;} }, { id:'skill_15', title:'技能强化\n技能伤害 +15%', apply:p=>{p.skillDamageMultiplier+=0.15;} }, { id:'cdr_8', title:'冷却强化\n冷却缩减 +8%', apply:p=>{p.cooldownReduction=Math.min(0.5,p.cooldownReduction+0.08);} }, { id:'crit_5', title:'暴击强化\n暴击率 +5%', apply:p=>{p.critChance=Math.min(0.8,p.critChance+0.05);} },
];
export default class UpgradeSystem {
  constructor(scene){ this.scene=scene; this.pending=0; this.panelOpen=false; this.attrOnlyStreak=0; }
  reset(){ this.pending=0; this.panelOpen=false; this.attrOnlyStreak=0; }
  gainExperience(amount,{defer=false}={}){ const p=this.scene.playerData; p.xp+=amount; while(p.xp>=p.xpToNext){ p.xp-=p.xpToNext; p.level+=1; p.xpToNext+=this.scene.balance.leveling.growth; this.pending+=1; } this.scene.hud?.update(); if(!defer) this.maybeShow(); }
  maybeShow(){ const s=this.scene; if(this.panelOpen||this.pending<=0) return; if(s.upgradePanel?.isOpen||s.rewardPanel?.isOpen||s.resultPanel?.isOpen) return; if([RunStates.REWARD,RunStates.VICTORY,RunStates.DEFEAT].includes(s.runState)) return; this.panelOpen=true; s.beginGameplayPause(); s.runState=RunStates.UPGRADING; s.eventBus.emit(CombatEvents.LEVEL_UP,{level:s.playerData.level}); s.upgradePanel.show('升级三选一',this.rollOptions(),o=>this.applyOption(o)); }
  rollOptions(){ const p=this.scene.playerData; const weighted=[]; const add=(o,w)=>{ for(let i=0;i<w;i++) weighted.push(o); }; Object.values(SKILLS).forEach(skill=>{ const own=p.skills.find(s=>s.id===skill.id); const rw=UPGRADE_RARITY_WEIGHTS[skill.rarity]||0; if(rw<=0&&!own) return; if(!own) add({type:'newSkill',id:`new_${skill.id}`,title:`获得技能：${skill.name}`,skillId:skill.id}, Math.max(1,Math.round(rw*(p.skills.length>=4?0.35:1)))); else if(own.level<skill.maxLevel) add({type:'skillLevel',id:`lv_${skill.id}`,title:`升级技能：${skill.name} Lv.${own.level+1}`,skillId:skill.id},5); }); ATTRIBUTE_UPGRADES.forEach(a=>add({type:'attr',id:a.id,title:a.title,attr:a},2)); const shuffled=Phaser.Utils.Array.Shuffle(weighted); const result=[]; const usedSkills=new Set(); for(const o of shuffled){ if(result.length>=3) break; if(o.skillId&&usedSkills.has(o.skillId)) continue; if(result.some(x=>x.id===o.id)) continue; result.push(o); if(o.skillId) usedSkills.add(o.skillId); }
    if(!result.some(o=>o.skillId)&&this.attrOnlyStreak<1){ const skillOpt=shuffled.find(o=>o.skillId&&!usedSkills.has(o.skillId)); if(skillOpt) result[0]=skillOpt; } while(result.length<3){ const a=Phaser.Utils.Array.GetRandom(ATTRIBUTE_UPGRADES); if(!result.some(o=>o.id===a.id)) result.push({type:'attr',id:a.id,title:a.title,attr:a}); } this.attrOnlyStreak=result.every(o=>o.type==='attr')?this.attrOnlyStreak+1:0; return result.slice(0,3); }
  rollStartingOptions(){ return Phaser.Utils.Array.Shuffle(Object.values(SKILLS).filter(skill=>STARTING_RARITIES.has(skill.rarity))).slice(0,3).map(skill=>({type:'startingSkill',id:`start_${skill.id}`,title:`获得技能：${skill.name}`,skillId:skill.id})); }
  applyOption(o){ const p=this.scene.playerData; if(o.type==='newSkill'||o.type==='skillLevel') this.scene.skillSystem.addOrLevel(o.skillId); if(o.type==='attr') o.attr.apply(p); p.upgradesChosen.push(o.id); this.scene.eventBus.emit(CombatEvents.UPGRADE_CHOSEN,{ optionId:o.id, option:o, skillId:o.skillId, type:o.type, level:p.level }); this.pending=Math.max(0,this.pending-1); this.panelOpen=false; this.scene.upgradePanel.hide(); this.scene.hud?.update(); this.scene.resumeModalFlow(); }
}
