import Phaser from 'phaser';
import { DESIGN_HEIGHT, DESIGN_WIDTH } from '../config/gameConfig.js';
import { BALANCE, createPlayerRuntime } from '../config/balance.js';
import EventBus from '../core/EventBus.js';
import { CombatEvents, RunStates, ACTIVE_STATES } from '../core/CombatEvents.js';
import createPlayer from '../entities/createPlayer.js';
import TargetingSystem from '../systems/TargetingSystem.js';
import MovementSystem from '../systems/MovementSystem.js';
import CombatSystem from '../systems/CombatSystem.js';
import SkillSystem from '../systems/SkillSystem.js';
import ArtifactSystem from '../systems/ArtifactSystem.js';
import UpgradeSystem from '../systems/UpgradeSystem.js';
import StageSystem from '../systems/StageSystem.js';
import StatusEffectSystem from '../systems/StatusEffectSystem.js';
import FlyingSwordSystem from '../systems/FlyingSwordSystem.js';
import AfterimageSystem from '../systems/AfterimageSystem.js';
import Hud from '../ui/Hud.js';
import UpgradePanel from '../ui/UpgradePanel.js';
import ArtifactRewardPanel from '../ui/ArtifactRewardPanel.js';
import ResultPanel from '../ui/ResultPanel.js';
import SkillBar from '../ui/SkillBar.js';
import RunStatsSystem from '../systems/RunStatsSystem.js';
import ProfessionSystem from '../systems/ProfessionSystem.js';
import PlaytestPanel from '../ui/PlaytestPanel.js';
import { collectBuildTagStats } from '../utils/buildTags.js';
import RestPanel from '../ui/RestPanel.js';
import ProfessionPanel from '../ui/ProfessionPanel.js';
import PlayerInfoPanel from '../ui/PlayerInfoPanel.js';
import PlayerHealthBar from '../ui/PlayerHealthBar.js';
import ShopSystem from '../systems/ShopSystem.js';
import ShopPanel from '../ui/ShopPanel.js';
import { onShopClosed as closeShopFlow } from '../systems/ShopFlow.js';
import ProfessionWeaponView from '../views/ProfessionWeaponView.js';
import EnemyBehaviorManager from '../enemies/behaviors/EnemyBehaviorManager.js';
import { GAME_VERSION_LABEL } from '../config/version.js';
import { applyCampfireSkillUpgrade } from '../systems/CampfireReward.js';
import { destroyEnemyStatusIndicators } from '../ui/EnemyStatusIndicators.js';

const updateDebugStatus = (message) => window.updateGameDebugStatus?.(message);

export default class GameScene extends Phaser.Scene {
  constructor(){ super('GameScene'); this.initStage='尚未开始'; }
  create(){ try { this.balance=BALANCE; this.queryParams=new URLSearchParams(window.location.search); this.debugMode=this.queryParams.get('debug')==='1'; this.debugTest=this.queryParams.get('test')||''; this.runState=RunStates.STARTING; this.playerData=createPlayerRuntime(); this.enemies=[]; this.killCount=0; this.restCompleted=false; this.claimingProfession=false;  this.currentTarget=null; this.pendingArtifactReward=null; this.pendingShop=null; this.delayedUpgradeUnlockAt=0; this.modalPausedAt=null; this.eventBus=new EventBus(); this.configureWorld(); this.createBackground(); this.createGround(); this.player=createPlayer(this,BALANCE.player,BALANCE.groundTopY); this.physics.add.collider(this.player,this.physicsGround); this.configurePlayerCamera(); this.targeting=new TargetingSystem(this); this.movementSystem=new MovementSystem(this); this.professionSystem=new ProfessionSystem(this); this.professionWeaponView=new ProfessionWeaponView(this); this.combatSystem=new CombatSystem(this); this.skillSystem=new SkillSystem(this); this.artifactSystem=new ArtifactSystem(this); this.statusEffects=new StatusEffectSystem(this); this.flyingSwords=new FlyingSwordSystem(this); this.afterimages=new AfterimageSystem(this); this.enemyBehaviors=new EnemyBehaviorManager(this); this.runStats=new RunStatsSystem(this); this.shopSystem=new ShopSystem(this); this.upgradeSystem=new UpgradeSystem(this); this.stageSystem=new StageSystem(this); this.hud=new Hud(this); this.playerHealthBar=new PlayerHealthBar(this); this.skillBar=new SkillBar(this); this.upgradePanel=new UpgradePanel(this); this.artifactRewardPanel=new ArtifactRewardPanel(this); this.resultPanel=new ResultPanel(this); this.restPanel=new RestPanel(this); this.professionPanel=new ProfessionPanel(this); this.playerInfoPanel=new PlayerInfoPanel(this); this.shopPanel=new ShopPanel(this); if(this.debugMode) this.playtestPanel=new PlaytestPanel(this); this.createTitle(); this.createRestartButton(); this.createPlayerInfoButton(); this.createDebugOverlay(); this.stageSystem.start(); this.artifactSystem.load(); this.showStartingSkillChoice(); this.hud.update(); this.events.once(Phaser.Scenes.Events.SHUTDOWN,()=>this.cleanupRun()); updateDebugStatus(GAME_VERSION_LABEL); if(this.debugMode&&this.debugTest==='profession-flow') this.time.delayedCall(80,()=>this.runDebugProfessionFlowTest()); } catch(e){ this.showInitError(e); throw e; } }
  update(time){ if(!this.isGameplayPaused()){ this.movementSystem.update(time); this.combatSystem.update(time); this.skillSystem.update(time); this.artifactSystem.update(time); this.statusEffects.update(time); this.flyingSwords.update(time); this.afterimages.update(time); this.stageSystem.update(time); this.syncAttachedVisuals(); } else this.player?.body?.setVelocityX(0); this.professionWeaponView?.update(); this.recoverStaleModalPause?.(); this.hud?.update(); this.playerHealthBar?.update(); this.skillBar?.update(); this.playtestPanel?.update(); this.updateDebugOverlay(); }
  syncAttachedVisuals(){ this.afterimages?.syncAttachedVisuals?.(); this.skillSystem?.syncAttachedVisuals?.(); this.flyingSwords?.syncAttachedVisuals?.(); }
  hasBlockingModal(){ return !ACTIVE_STATES.has(this.runState)||this.upgradePanel?.isOpen||this.artifactRewardPanel?.isOpen||this.resultPanel?.isOpen||this.playtestPanel?.isOpen||this.restPanel?.isOpen||this.professionPanel?.isOpen||this.playerInfoPanel?.isOpen||this.shopPanel?.isOpen||!!this.upgradeSystem?.panelOpen; }
  isGameplayPaused(){ return this.hasBlockingModal(); }
  getGameplayTime(){ return this.modalPausedAt ?? this.time.now; }
  beginGameplayPause(){ if(this.modalPausedAt!==null) return; this.modalPausedAt=this.time.now; this.player?.body?.setVelocityX(0); this.combatSystem?.pauseKnockbacks(); this.enemyBehaviors?.pause(); this.enemies?.forEach(e=>{ if(e?.active&&e.body&&!e.isDefeated) e.body.setVelocityX(0); }); }
  canEndGameplayPause(){ return this.runState!==RunStates.STARTING&&!this.hasBlockingModal(); }
  endGameplayPause(){ if(this.modalPausedAt===null||!this.canEndGameplayPause()) return; if([RunStates.VICTORY,RunStates.DEFEAT].includes(this.runState)) return; const pausedAt=this.modalPausedAt; const pausedDuration=Math.max(0,this.time.now-pausedAt); this.modalPausedAt=null; if(pausedDuration>0){ this.combatSystem?.shiftTimers(pausedDuration,pausedAt); this.skillSystem?.shiftTimers(pausedDuration,pausedAt); this.artifactSystem?.shiftTimers(pausedDuration,pausedAt); this.professionSystem?.shiftTimers(pausedDuration,pausedAt); this.statusEffects?.shiftTimers(pausedDuration,pausedAt); this.flyingSwords?.shiftTimers(pausedDuration,pausedAt); this.afterimages?.shiftTimers(pausedDuration,pausedAt); this.enemyBehaviors?.shiftTimers(pausedDuration,pausedAt); this.stageSystem?.shiftTimers(pausedDuration,pausedAt); this.runStats?.addPausedDuration(pausedDuration); } this.combatSystem?.resumeKnockbacks(); this.enemyBehaviors?.resume(); }
  recoverStaleModalPause(){ if(this.modalPausedAt===null||![RunStates.RUNNING,RunStates.BOSS].includes(this.runState)) return; const realOpen=this.upgradePanel?.isOpen||this.artifactRewardPanel?.isOpen||this.resultPanel?.isOpen||this.playtestPanel?.isOpen||this.restPanel?.isOpen||this.professionPanel?.isOpen||this.playerInfoPanel?.isOpen||this.shopPanel?.isOpen; if(realOpen) return; if(this.upgradeSystem) this.upgradeSystem.panelOpen=false; this.endGameplayPause(); if(this.debugMode&&!this.flowRecoveryLogged){ this.flowRecoveryLogged=true; console.info('[FLOW_RECOVERY] cleared stale modal pause'); } }
  configureWorld(){ const width=BALANCE.stageWorldWidth||12400; this.physics.world.setBounds(0,0,width,DESIGN_HEIGHT); this.cameras.main.setBounds(0,0,width,DESIGN_HEIGHT); }
  configurePlayerCamera(){ const camera=this.cameras.main; const anchor=this.balance.camera?.playerScreenAnchorX ?? 0.5; const offsetX=DESIGN_WIDTH*(anchor-0.5); camera.startFollow(this.player,false,1,0,offsetX,0); }
  createBackground(){ this.cameras.main.setBackgroundColor('#202638'); for(let x=300;x<(BALANCE.stageWorldWidth||12400);x+=420){ this.add.rectangle(x,BALANCE.groundTopY-92,12,185,0x2f3547,0.75).setDepth(5); } }
  createGround(){ const w=BALANCE.stageWorldWidth||12400; this.add.rectangle(w/2,BALANCE.groundTopY+BALANCE.groundHeight/2,w,BALANCE.groundHeight,0x253522,1).setDepth(10); this.physicsGround=this.add.rectangle(w/2,BALANCE.groundTopY+BALANCE.groundHeight/2,w,BALANCE.groundHeight,0x000000,0); this.physics.add.existing(this.physicsGround,true); }
  createTitle(){ this.add.text(DESIGN_WIDTH/2,28,'自动战斗肉鸽',{fontFamily:'Arial',fontSize:'24px',color:'#e9efff',stroke:'#000',strokeThickness:5}).setOrigin(0.5,0).setScrollFactor(0).setDepth(1000); }
  createRestartButton(){ this.restartButton=this.add.text(DESIGN_WIDTH-22,28,'重新开始',{fontFamily:'Arial',fontSize:'24px',color:'#fff',backgroundColor:'#333',padding:{left:12,right:12,top:8,bottom:8}}).setOrigin(1,0).setScrollFactor(0).setInteractive({useHandCursor:true}).setDepth(2000); this.restartButton.on('pointerdown',()=>this.scene.restart()); }
  createPlayerInfoButton(){ this.playerInfoButton=this.add.text(DESIGN_WIDTH-172,28,'角色',{fontFamily:'Arial',fontSize:'24px',color:'#fff',backgroundColor:'#24415f',padding:{left:16,right:16,top:8,bottom:8}}).setOrigin(1,0).setScrollFactor(0).setInteractive({useHandCursor:true}).setDepth(2000); this.playerInfoButton.on('pointerdown',()=>this.openPlayerInfoPanel()); }
  openPlayerInfoPanel(){ if(this.hasBlockingModal()) return false; this.playerInfoPanel?.show(); return true; }
  showProfessionChoice(){ if(this.playerData.professionId) return false; if(this.playerInfoPanel?.isOpen){ return false; } this.beginGameplayPause(); this.professionPanel.show((id)=>this.claimProfession(id)); return true; }
  profLog(message, extra={}){ if(this.debugMode) console.info(`[PROF_FLOW] ${message}`, extra); }
  claimProfession(id){
    if(this.claimingProfession){ console.warn('[GameScene] duplicate profession claim ignored', { professionId:id, currentProfession:this.playerData.professionId }); return false; }
    if(this.playerData.professionId){ console.warn('[GameScene] profession claim ignored because profession already chosen', { professionId:id, currentProfession:this.playerData.professionId }); return false; }
    this.claimingProfession=true;
    const selected=this.professionSystem.selectProfession(id);
    if(!selected){ this.claimingProfession=false;  console.error('[GameScene] profession claim failed; reward flow remains paused for retry', { professionId:id, runState:this.runState, pendingLevelUps:this.upgradeSystem?.pending }); return false; }
    this.profLog('profession confirmed', { professionId:id });
    try { this.hud?.setStatus('职业觉醒完成'); } catch(error){ console.error('[GameScene] profession status UI refresh failed', { professionId:id, error }); }
    return true;
  }
  onProfessionPanelClosed(){ this.claimingProfession=false; this.stageSystem?.onProfessionChosen?.(); this.resumeModalFlow(); }
  showStartingSkillChoice(){ this.beginGameplayPause(); const options=this.upgradeSystem.rollStartingOptions(); this.upgradePanel.show({ title:'', hideTitle:true, options, onConfirm:(o)=>this.claimStartingSkill(o) }); }
  claimStartingSkill(option){ this.skillSystem.addOrLevel(option.skillId,{starting:true}); this.upgradePanel.hide(); this.hud?.setStatus('自动战斗开始'); this.runState=RunStates.RUNNING; this.endGameplayPause(); }
  queueArtifactReward(enemy, meta={}){ if(this.pendingArtifactReward||[RunStates.VICTORY,RunStates.DEFEAT].includes(this.runState)) return; this.pendingArtifactReward={ enemyId:enemy.id, enemyName:enemy.name, ...meta }; }
  showArtifactReward(){ if(!this.pendingArtifactReward||[RunStates.VICTORY,RunStates.DEFEAT].includes(this.runState)||this.artifactRewardPanel?.isOpen) return; this.beginGameplayPause(); this.runState=RunStates.REWARD; const options=this.artifactSystem.rollRewardOptions(3); this.artifactRewardPanel.show({ title:'获得一个法宝奖励', options, onConfirm:(o)=>this.claimArtifactReward(o) }); }
  claimArtifactReward(option){ if(!this.pendingArtifactReward) return false; const reward=this.pendingArtifactReward; if(option.type==='fallback') this.artifactSystem.applyFallback(option); else this.artifactSystem.add(option.artifactId); this.eventBus.emit(CombatEvents.ARTIFACT_CHOSEN,{ artifactId:option.artifactId, option }); this.pendingArtifactReward=null; this.artifactRewardPanel.hide(); if(reward.afterBoss) this.stageSystem?.beginAfterBossReward?.(reward.afterBoss); this.resumeModalFlow(); return true; }
  resumeModalFlow(){ if([RunStates.VICTORY,RunStates.DEFEAT].includes(this.runState)) return; if(this.resultPanel?.isOpen||this.artifactRewardPanel?.isOpen||this.upgradePanel?.isOpen||this.playtestPanel?.isOpen||this.restPanel?.isOpen||this.professionPanel?.isOpen||this.playerInfoPanel?.isOpen||this.shopPanel?.isOpen) return; if(this.pendingArtifactReward){ this.showArtifactReward(); return; } if(this.pendingShop){ const reason=this.pendingShop; this.pendingShop=null; this.shopSystem?.open(reason); return; } const activeState=this.enemies?.some(e=>e.isFinalBoss&&!e.isDefeated)?RunStates.BOSS:RunStates.RUNNING; if(this.upgradeSystem?.pending>0){ this.runState=activeState; this.upgradeSystem.panelOpen=false; this.upgradeSystem.maybeShow({force:true}); return; } this.runState=activeState; this.endGameplayPause(); }

  showSkillReward(title){ this.upgradeSystem?.requestSkillReward(title, { source:'stageSkillReward' }); }
  showAdvancedProfessionChoice(){ if(!this.playerData.professionId||this.playerData.advancedProfessionId) return false; this.beginGameplayPause(); this.runState=RunStates.REWARD; this.player?.body?.setVelocityX(0); this.professionPanel.show((id)=>this.claimAdvancedProfession(id), { advanced:true }); return true; }
  claimAdvancedProfession(id){ const ok=this.professionSystem.selectAdvancedProfession(id); if(!ok) return false; this.professionPanel.hide(); this.stageSystem?.onAdvancedProfessionChosen?.(); this.resumeModalFlow(); return true; }
  showCampfire(source='campfire'){ if(this.campfirePanelOpen) return; this.campfirePanelOpen=true; this.beginGameplayPause(); this.runState=RunStates.REST; const p=this.playerData; const before={hp:p.hp,mana:p.mana??0,stamina:p.stamina??0}; const upgraded=applyCampfireSkillUpgrade(this); p.hp=Math.min(p.maxHp,p.hp+Math.round(p.maxHp*0.25)); p.mana=Math.min(p.maxMana??0,(p.mana??0)+Math.round((p.maxMana??0)*0.30)); p.stamina=Math.min(p.maxStamina??0,(p.stamina??0)+Math.round((p.maxStamina??0)*0.35)); this.hud?.update(); const msg=`篝火休整
${upgraded?`技能 ${this.skillSystem.getConfig(upgraded.id)?.name||upgraded.id} 升至 Lv.${upgraded.level}`:'没有可升级技能'}
生命 +${p.hp-before.hp} 法力 +${(p.mana??0)-before.mana} 体力 +${(p.stamina??0)-before.stamina}`; const panel=this.add.text(DESIGN_WIDTH/2,DESIGN_HEIGHT/2,msg,{fontFamily:'Arial',fontSize:'30px',color:'#fff',backgroundColor:'rgba(35,23,12,0.9)',padding:{left:28,right:28,top:22,bottom:22},align:'center',stroke:'#000',strokeThickness:4}).setOrigin(0.5).setScrollFactor(0).setDepth(5000).setInteractive({useHandCursor:true}); panel.on('pointerdown',()=>{ panel.destroy(); this.campfirePanelOpen=false; this.runState=RunStates.RUNNING; this.stageSystem?.onCampfireClosed(source); this.resumeModalFlow(); }); }
  showRestPoint(){ if(this.restPanel?.isOpen||this.restCompleted) return; this.beginGameplayPause(); this.runState=RunStates.REST; this.player?.body?.setVelocityX(0); this.restPanel.show(()=>this.claimRestHeal(),()=>this.claimRestSkill()); }
  finishRest(){ if(this.restCompleted) return; this.restCompleted=true; this.restPanel.hide(); this.runState=RunStates.RUNNING; this.pendingShop='second'; this.resumeModalFlow(); }
  claimRestHeal(){ const heal=Math.round(this.playerData.maxHp*0.6); const actual=this.healPlayer(heal,'rest'); this.statusEffects?.clearNegativeEffects?.(this.playerData); this.eventBus.emit(CombatEvents.REST_CHOSEN,{choice:'heal', healing:actual}); this.hud?.update(); this.finishRest(); }
  claimRestSkill(){ this.eventBus.emit(CombatEvents.REST_CHOSEN,{choice:'skill', healing:0}); this.restPanel.hide(); this.beginGameplayPause(); this.upgradePanel.show('休息点突破：高品质技能三选一', this.upgradeSystem.rollHighQualityOptions(), o=>{ this.upgradeSystem.applyFreeOption(o,{source:'otherFreeReward', rewardKind:'restSkill'}); this.eventBus.emit(CombatEvents.REST_CHOSEN,{choice:'skill', skillId:o.skillId, option:o}); this.upgradePanel.hide(); this.finishRest(); }); }

  awardGold(amount, source='enemy'){ const value=Math.max(0,Math.floor(Number(amount)||0)); if(value<=0) return 0; this.playerData.gold=(this.playerData.gold||0)+value; this.runStats?.recordGold?.(value,source); this.hud?.update(); return value; }
  healPlayer(amount, source='heal', meta={}){ const baseValue=Math.max(0,Math.floor(Number(amount)||0)); const lastStand=this.skillSystem?.passiveState?.lastStand; const isLifeSteal=source==='lifeSteal'||meta?.lifeSteal===true; if(lastStand?.active&&!isLifeSteal) return 0; if(baseValue<=0||this.playerData.hp>=this.playerData.maxHp) return 0; this.playerData.healingReceivedMultiplierBonuses??={}; const multiplier=1+Object.values(this.playerData.healingReceivedMultiplierBonuses).reduce((sum,value)=>sum+(Number(value)||0),0); const value=Math.max(0,Math.floor(baseValue*multiplier)); if(value<=0) return 0; const before=this.playerData.hp; this.playerData.hp=Math.min(this.playerData.maxHp,this.playerData.hp+value); const actual=this.playerData.hp-before; if(actual<=0) return 0; this.eventBus.emit(CombatEvents.PLAYER_HEALED,{amount:actual,source,...meta}); this.hud?.update(); this.playerHealthBar?.update(); return actual; }
  queueShop(reason){ if(this.pendingShop||[RunStates.VICTORY,RunStates.DEFEAT].includes(this.runState)) return; if(this.shopSystem?.openedReasons?.has(reason)) return; this.pendingShop=reason; this.resumeModalFlow(); }
  onShopClosed(reason){ const r=closeShopFlow(this, reason); this.stageSystem?.onShopClosed?.(reason); return r; }
  finishRun(won){ if([RunStates.VICTORY,RunStates.DEFEAT].includes(this.runState)||this.resultPanel?.isOpen) return; this.beginGameplayPause(); this.runState=won?RunStates.VICTORY:RunStates.DEFEAT; this.player?.body?.setVelocityX(0); this.combatSystem?.reset(); this.skillSystem?.reset(); this.statusEffects?.reset(); this.flyingSwords?.reset(); this.afterimages?.reset(); this.enemyBehaviors?.destroy(); this.pendingArtifactReward=null; this.upgradeSystem?.reset(); this.shopSystem?.reset(); this.shopPanel?.hide({resume:false}); this.playerInfoPanel?.hide(); this.upgradePanel?.hide(); this.artifactRewardPanel?.hide(); this.playerHealthBar?.update(); this.eventBus.emit(CombatEvents.RUN_ENDED,{ won }); this.resultPanel.show(won,()=>this.scene.restart()); }
  floatText(x,y,text,color){ const t=this.add.text(x,y,text,{fontFamily:'Arial',fontSize:'24px',color,stroke:'#000',strokeThickness:4}).setOrigin(0.5).setDepth(2500); this.tweens.add({targets:t,y:y-42,alpha:0,duration:650,onComplete:()=>t.destroy()}); }
  createDebugOverlay(){ if(!this.debugMode) return; this.debugOverlay=this.add.text(18,260,'',{fontFamily:'monospace',fontSize:'18px',color:'#00ff66',backgroundColor:'rgba(0,0,0,0.72)',padding:{left:10,right:10,top:8,bottom:8}}).setScrollFactor(0).setDepth(2500); }
  updateDebugOverlay(){ if(!this.debugOverlay) return; const cds=[...this.skillSystem.cooldowns.entries()].map(([id,t])=>`${id}:${Math.max(0,Math.ceil((t-this.getGameplayTime())/1000))}`).join(' '); const prof=this.playerData.professionId ? this.playerData.professionId : '-'; const cfg=this.playerData.professionId ? (this.professionSystem?.currentConfig?.() || null) : null; const st=this.playerData.professionState||{}; const buildTags=collectBuildTagStats({ skills:this.playerData.skills, artifacts:this.playerData.artifacts, professionId:this.playerData.professionId }).dominantTags.join(',') || '-'; this.debugOverlay.setText([`state:${this.runState}`,`playerX:${Math.round(this.player.x)}`,`playerScreenX:${Math.round(this.player.x-(this.cameras.main?.scrollX||0))}`,`target:${this.currentTarget?.name||'-'}`,`targetFull:${this.currentTarget?this.targeting.isEnemyFullyInsideViewport(this.currentTarget):false}`,`enemies:${this.enemies.length}`,`enemyState:${this.enemies.map(e=>e.entryState||'-').join(',')||'-'}`,`recycles:${this.enemyRecycleCount||0}`,`skills:${cds||'-'}`,`profession:${prof}`,`weapon:${cfg?.professionWeaponId||'-'}`,`attack:${cfg?.professionAttackProfile||'-'}`,`剑客增伤:${Math.max(0,((st.warriorBuffUntil||0)-this.getGameplayTime())/1000).toFixed(1)}s`, `学者计数:${st.mageCastCount||0}/5${st.mageEmpoweredNext?' ready':''}`,`猎印:${st.rangerLastTargetMarks||0}/3 ${st.rangerLastTargetId||'-'}`,`破军:${this.artifactSystem?.highHpDamageMultiplier?.()>1?'ON':'OFF'}`,`stage:${this.stageSystem.stage.name}`,`buildTags:${buildTags}`,...(this.lastRewardBiasDebug?[`bias:${this.lastRewardBiasDebug.kind} ${this.lastRewardBiasDebug.enabled?'ON':'OFF'}`,`biasPicked:${this.lastRewardBiasDebug.picked?.join(',')||'-'}`,`biasWeights:${(this.lastRewardBiasDebug.candidates||[]).slice(0,5).map(c=>`${c.id}:${c.weight}`).join(' ')||'-'}`]:[]) ]); }
  cleanupRun(){ this.combatSystem?.clearAllKnockbacks(); this.time.removeAllEvents(); this.tweens.killAll(); this.pendingArtifactReward=null; this.claimingProfession=false;  this.modalPausedAt=null; this.enemyBehaviors?.resume(); this.upgradeSystem?.reset(); this.shopSystem?.reset(); this.artifactSystem?.cleanup(); this.statusEffects?.reset(); this.flyingSwords?.destroy(); this.afterimages?.destroy(); this.professionWeaponView?.destroy(); this.professionSystem?.destroy(); this.runStats?.destroy(); this.eventBus?.destroy(); this.shopPanel?.hide({resume:false}); this.playerInfoPanel?.hide(); this.upgradePanel?.hide(); this.artifactRewardPanel?.hide(); this.resultPanel?.hide(); this.restPanel?.hide(); this.shopPanel?.hide({resume:false}); this.professionPanel?.hide(); this.playerInfoPanel?.hide(); this.enemies?.forEach(e=>{ this.enemyBehaviors?.destroyEnemy(e); destroyEnemyStatusIndicators(e); [e.hpBarBg,e.hpBar,e.nameText,e.levelText,e].forEach(o=>o?.destroy()); }); this.enemies=[]; this.skillBar?.destroy(); this.playerHealthBar?.destroy(); this.hud?.destroy(); this.debugOverlay?.destroy(); this.playtestPanel?.destroy(); }
  showInitError(error){ this.add.text(24,220,`初始化失败：${this.initStage}
${error.name||'Error'}: ${error.message||String(error)}`,{fontFamily:'Arial',fontSize:'28px',color:'#fff',backgroundColor:'rgba(190,0,0,0.92)',padding:{left:18,right:18,top:14,bottom:14},wordWrap:{width:DESIGN_WIDTH-48}}).setOrigin(0,0).setScrollFactor(0).setDepth(10000); }
}
