import Phaser from 'phaser';
import { DESIGN_HEIGHT, DESIGN_WIDTH } from '../config/gameConfig.js';
import { BALANCE, createPlayerRuntime } from '../config/balance.js';
import EventBus from '../core/EventBus.js';
import { CombatEvents, RunStates, ACTIVE_STATES } from '../core/CombatEvents.js';
import createPlayer from '../entities/createPlayer.js';
import TargetingSystem from '../systems/TargetingSystem.js';
import MovementSystem from '../systems/MovementSystem.js';
import CombatSystem from '../systems/CombatSystem.js';
import SkillSystem from '../systems/SkillSystem.js';
import ArtifactSystem from '../systems/ArtifactSystem.js';
import UpgradeSystem from '../systems/UpgradeSystem.js';
import StageSystem from '../systems/StageSystem.js';
import StatusEffectSystem from '../systems/StatusEffectSystem.js';
import Hud from '../ui/Hud.js';
import UpgradePanel from '../ui/UpgradePanel.js';
import ArtifactRewardPanel from '../ui/ArtifactRewardPanel.js';
import ResultPanel from '../ui/ResultPanel.js';
import SkillBar from '../ui/SkillBar.js';
import RunStatsSystem from '../systems/RunStatsSystem.js';
import ProfessionSystem from '../systems/ProfessionSystem.js';
import PlaytestPanel from '../ui/PlaytestPanel.js';
import { collectBuildTagStats } from '../utils/buildTags.js';
import RestPanel from '../ui/RestPanel.js';
import ProfessionPanel from '../ui/ProfessionPanel.js';
import PlayerInfoPanel from '../ui/PlayerInfoPanel.js';
import PlayerHealthBar from '../ui/PlayerHealthBar.js';
import ShopSystem from '../systems/ShopSystem.js';
import ShopPanel from '../ui/ShopPanel.js';
import { onShopClosed as closeShopFlow } from '../systems/ShopFlow.js';
import ProfessionWeaponView from '../views/ProfessionWeaponView.js';
import EnemyBehaviorManager from '../enemies/behaviors/EnemyBehaviorManager.js';
import { GAME_VERSION_LABEL } from '../config/version.js';

const updateDebugStatus = (message) => window.updateGameDebugStatus?.(message);

export default class GameScene extends Phaser.Scene {
  constructor(){ super('GameScene'); this.initStage='尚未开始'; }
  create(){ try { this.balance=BALANCE; this.queryParams=new URLSearchParams(window.location.search); this.debugMode=this.queryParams.get('debug')==='1'; this.debugTest=this.queryParams.get('test')||''; this.runState=RunStates.STARTING; this.playerData=createPlayerRuntime(); this.enemies=[]; this.killCount=0; this.restCompleted=false; this.midBossRewardOpen=false; this.midBossPostFightFlowStarted=false; this.midBossFlowStep='complete'; this.claimingProfession=false;  this.currentTarget=null; this.pendingArtifactReward=null; this.pendingShop=null; this.delayedUpgradeUnlockAt=0; this.modalPausedAt=null; this.eventBus=new EventBus(); this.configureWorld(); this.createBackground(); this.createGround(); this.player=createPlayer(this,BALANCE.player,BALANCE.groundTopY); this.physics.add.collider(this.player,this.physicsGround); this.configurePlayerCamera(); this.targeting=new TargetingSystem(this); this.movementSystem=new MovementSystem(this); this.professionSystem=new ProfessionSystem(this); this.professionWeaponView=new ProfessionWeaponView(this); this.combatSystem=new CombatSystem(this); this.skillSystem=new SkillSystem(this); this.artifactSystem=new ArtifactSystem(this); this.statusEffects=new StatusEffectSystem(this); this.enemyBehaviors=new EnemyBehaviorManager(this); this.runStats=new RunStatsSystem(this); this.shopSystem=new ShopSystem(this); this.upgradeSystem=new UpgradeSystem(this); this.stageSystem=new StageSystem(this); this.hud=new Hud(this); this.playerHealthBar=new PlayerHealthBar(this); this.skillBar=new SkillBar(this); this.upgradePanel=new UpgradePanel(this); this.artifactRewardPanel=new ArtifactRewardPanel(this); this.resultPanel=new ResultPanel(this); this.restPanel=new RestPanel(this); this.professionPanel=new ProfessionPanel(this); this.playerInfoPanel=new PlayerInfoPanel(this); this.shopPanel=new ShopPanel(this); if(this.debugMode) this.playtestPanel=new PlaytestPanel(this); this.createTitle(); this.createRestartButton(); this.createPlayerInfoButton(); this.createDebugOverlay(); this.stageSystem.start(); this.artifactSystem.load(); this.showStartingSkillChoice(); this.hud.update(); this.events.once(Phaser.Scenes.Events.SHUTDOWN,()=>this.cleanupRun()); updateDebugStatus(GAME_VERSION_LABEL); if(this.debugMode&&this.debugTest==='profession-flow') this.time.delayedCall(80,()=>this.runDebugProfessionFlowTest()); } catch(e){ this.showInitError(e); throw e; } }
  update(time){ if(!this.isGameplayPaused()){ this.movementSystem.update(time); this.combatSystem.update(time); this.skillSystem.update(time); this.artifactSystem.update(time); this.statusEffects.update(time); this.stageSystem.update(time); } else this.player?.body?.setVelocityX(0); this.professionWeaponView?.update(); this.recoverStaleModalPause?.(); this.hud?.update(); this.playerHealthBar?.update(); this.skillBar?.update(); this.playtestPanel?.update(); this.updateDebugOverlay(); }
  hasBlockingModal(){ return !ACTIVE_STATES.has(this.runState)||this.upgradePanel?.isOpen||this.artifactRewardPanel?.isOpen||this.resultPanel?.isOpen||this.playtestPanel?.isOpen||this.restPanel?.isOpen||this.midBossRewardOpen||this.professionPanel?.isOpen||this.playerInfoPanel?.isOpen||this.shopPanel?.isOpen||!!this.upgradeSystem?.panelOpen; }
  isGameplayPaused(){ return this.hasBlockingModal(); }
  getGameplayTime(){ return this.modalPausedAt ?? this.time.now; }
  beginGameplayPause(){ if(this.modalPausedAt!==null) return; this.modalPausedAt=this.time.now; this.player?.body?.setVelocityX(0); this.enemyBehaviors?.pause(); this.enemies?.forEach(e=>{ if(e?.active&&e.body&&!e.isDefeated) e.body.setVelocityX(0); }); }
  canEndGameplayPause(){ return this.runState!==RunStates.STARTING&&!this.hasBlockingModal(); }
  endGameplayPause(){ if(this.modalPausedAt===null||!this.canEndGameplayPause()) return; if([RunStates.VICTORY,RunStates.DEFEAT].includes(this.runState)) return; const pausedAt=this.modalPausedAt; const pausedDuration=Math.max(0,this.time.now-pausedAt); this.modalPausedAt=null; if(pausedDuration>0){ this.combatSystem?.shiftTimers(pausedDuration,pausedAt); this.skillSystem?.shiftTimers(pausedDuration,pausedAt); this.artifactSystem?.shiftTimers(pausedDuration,pausedAt); this.professionSystem?.shiftTimers(pausedDuration,pausedAt); this.statusEffects?.shiftTimers(pausedDuration,pausedAt); this.enemyBehaviors?.shiftTimers(pausedDuration,pausedAt); this.runStats?.addPausedDuration(pausedDuration); } this.enemyBehaviors?.resume(); }
  recoverStaleModalPause(){ if(this.modalPausedAt===null||![RunStates.RUNNING,RunStates.BOSS].includes(this.runState)) return; const realOpen=this.upgradePanel?.isOpen||this.artifactRewardPanel?.isOpen||this.resultPanel?.isOpen||this.playtestPanel?.isOpen||this.restPanel?.isOpen||this.midBossRewardOpen||this.professionPanel?.isOpen||this.playerInfoPanel?.isOpen||this.shopPanel?.isOpen; if(realOpen) return; if(this.upgradeSystem) this.upgradeSystem.panelOpen=false; this.midBossRewardOpen=false; this.endGameplayPause(); if(this.debugMode&&!this.flowRecoveryLogged){ this.flowRecoveryLogged=true; console.info('[FLOW_RECOVERY] cleared stale modal pause'); } }
  configureWorld(){ const width=BALANCE.stageWorldWidth||12400; this.physics.world.setBounds(0,0,width,DESIGN_HEIGHT); this.cameras.main.setBounds(0,0,width,DESIGN_HEIGHT); }
  configurePlayerCamera(){ const camera=this.cameras.main; const anchor=this.balance.camera?.playerScreenAnchorX ?? 0.5; const offsetX=DESIGN_WIDTH*(anchor-0.5); camera.startFollow(this.player,false,1,0,offsetX,0); }
  createBackground(){ this.cameras.main.setBackgroundColor('#202638'); for(let x=300;x<(BALANCE.stageWorldWidth||12400);x+=420){ this.add.rectangle(x,BALANCE.groundTopY-92,12,185,0x2f3547,0.75).setDepth(5); } }
  createGround(){ const w=BALANCE.stageWorldWidth||12400; this.add.rectangle(w/2,BALANCE.groundTopY+BALANCE.groundHeight/2,w,BALANCE.groundHeight,0x253522,1).setDepth(10); this.physicsGround=this.add.rectangle(w/2,BALANCE.groundTopY+BALANCE.groundHeight/2,w,BALANCE.groundHeight,0x000000,0); this.physics.add.existing(this.physicsGround,true); }
  createTitle(){ this.add.text(DESIGN_WIDTH/2,28,'自动战斗肉鸽',{fontFamily:'Arial',fontSize:'24px',color:'#e9efff',stroke:'#000',strokeThickness:5}).setOrigin(0.5,0).setScrollFactor(0).setDepth(1000); }
  createRestartButton(){ this.restartButton=this.add.text(DESIGN_WIDTH-22,28,'重新开始',{fontFamily:'Arial',fontSize:'24px',color:'#fff',backgroundColor:'#333',padding:{left:12,right:12,top:8,bottom:8}}).setOrigin(1,0).setScrollFactor(0).setInteractive({useHandCursor:true}).setDepth(2000); this.restartButton.on('pointerdown',()=>this.scene.restart()); }
  createPlayerInfoButton(){ this.playerInfoButton=this.add.text(DESIGN_WIDTH-172,28,'角色',{fontFamily:'Arial',fontSize:'24px',color:'#fff',backgroundColor:'#24415f',padding:{left:16,right:16,top:8,bottom:8}}).setOrigin(1,0).setScrollFactor(0).setInteractive({useHandCursor:true}).setDepth(2000); this.playerInfoButton.on('pointerdown',()=>this.openPlayerInfoPanel()); }
  openPlayerInfoPanel(){ if(this.hasBlockingModal()) return false; this.playerInfoPanel?.show(); return true; }
  showProfessionChoice(){ if(this.playerData.professionId) return false; if(this.playerInfoPanel?.isOpen){ this.midBossFlowStep='profession'; return false; } this.midBossFlowStep='profession'; this.midBossConsumedOneUpgrade=false; this.beginGameplayPause(); this.professionPanel.show((id)=>this.claimProfession(id)); return true; }
  profLog(message, extra={}){ if(this.debugMode) console.info(`[PROF_FLOW] ${message}`, extra); }
  claimProfession(id){
    if(this.claimingProfession){ console.warn('[GameScene] duplicate profession claim ignored', { professionId:id, currentProfession:this.playerData.professionId }); return false; }
    if(this.playerData.professionId){ console.warn('[GameScene] profession claim ignored because profession already chosen', { professionId:id, currentProfession:this.playerData.professionId }); return false; }
    this.claimingProfession=true;
    const selected=this.professionSystem.selectProfession(id);
    if(!selected){ this.claimingProfession=false;  console.error('[GameScene] profession claim failed; reward flow remains paused for retry', { professionId:id, runState:this.runState, pendingLevelUps:this.upgradeSystem?.pending }); return false; }
    this.profLog('profession confirmed', { professionId:id });
    try { this.hud?.setStatus('职业觉醒完成'); } catch(error){ console.error('[GameScene] profession status UI refresh failed', { professionId:id, error }); }
    return true;
  }
  onProfessionPanelClosed(){ this.claimingProfession=false; if(this.midBossPostFightFlowStarted) this.midBossFlowStep='levelUps'; this.resumeModalFlow(); }
  showStartingSkillChoice(){ this.beginGameplayPause(); const options=this.upgradeSystem.rollStartingOptions(); this.upgradePanel.show({ title:'', hideTitle:true, options, onConfirm:(o)=>this.claimStartingSkill(o) }); }
  claimStartingSkill(option){ this.skillSystem.addOrLevel(option.skillId,{starting:true}); this.upgradePanel.hide(); this.hud?.setStatus('自动战斗开始'); this.runState=RunStates.RUNNING; this.endGameplayPause(); }
  queueArtifactReward(enemy, meta={}){ if(this.pendingArtifactReward||[RunStates.VICTORY,RunStates.DEFEAT].includes(this.runState)) return; this.pendingArtifactReward={ enemyId:enemy.id, enemyName:enemy.name, ...meta }; }
  showArtifactReward(){ if(!this.pendingArtifactReward||[RunStates.VICTORY,RunStates.DEFEAT].includes(this.runState)||this.artifactRewardPanel?.isOpen) return; this.beginGameplayPause(); this.runState=RunStates.REWARD; const options=this.artifactSystem.rollRewardOptions(3); this.artifactRewardPanel.show({ title:'获得一个法宝奖励', options, onConfirm:(o)=>this.claimArtifactReward(o) }); }
  claimArtifactReward(option){ if(!this.pendingArtifactReward) return false; const reward=this.pendingArtifactReward; if(option.type==='fallback') this.artifactSystem.applyFallback(option); else this.artifactSystem.add(option.artifactId); this.eventBus.emit(CombatEvents.ARTIFACT_CHOSEN,{ artifactId:option.artifactId, option }); this.pendingArtifactReward=null; this.artifactRewardPanel.hide(); if(reward.afterBoss==='boss2'){ this.midBossFlowStep='complete'; this.midBossRewardOpen=false; this.midBossPostFightFlowStarted=false; this.claimingProfession=false; } if(reward.afterBoss) this.stageSystem?.beginAfterBossReward?.(reward.afterBoss); this.resumeModalFlow(); return true; }
  resumeModalFlow(){ if([RunStates.VICTORY,RunStates.DEFEAT].includes(this.runState)) return; if(this.resultPanel?.isOpen||this.artifactRewardPanel?.isOpen||this.upgradePanel?.isOpen||this.playtestPanel?.isOpen||this.restPanel?.isOpen||this.professionPanel?.isOpen||this.playerInfoPanel?.isOpen||this.shopPanel?.isOpen) return; if(this.midBossPostFightFlowStarted){ if(!this.playerData.professionId||this.midBossFlowStep==='profession'){ this.showProfessionChoice(); return; } this.midBossFlowStep='artifactReward'; this.showActualMidBossReward(); return; } if(this.pendingArtifactReward){ this.showArtifactReward(); return; } if(this.pendingShop){ const reason=this.pendingShop; this.pendingShop=null; this.shopSystem?.open(reason); return; } const activeState=this.enemies?.some(e=>e.isFinalBoss&&!e.isDefeated)?RunStates.BOSS:RunStates.RUNNING; if(this.upgradeSystem?.pending>0){ this.runState=activeState; this.upgradeSystem.panelOpen=false; this.upgradeSystem.maybeShow(); return; } this.runState=activeState; this.endGameplayPause(); }


  startMidBossPostFightFlow(){ if(this.midBossPostFightFlowStarted) return; this.midBossPostFightFlowStarted=true; this.midBossFlowStep='profession'; this.midBossConsumedOneUpgrade=false; this.beginGameplayPause(); this.runState=RunStates.REWARD; this.player?.body?.setVelocityX(0); this.showProfessionChoice(); }
  showMidBossReward(){ this.resumeModalFlow(); }
  processPendingMidBossLevelUps(){ this.resumeModalFlow(); }
  showActualMidBossReward(){ if(!this.midBossPostFightFlowStarted||this.midBossRewardOpen||this.artifactRewardPanel?.isOpen) return; this.midBossRewardOpen=true; this.queueArtifactReward({ id:'boss2', name:'铁甲暴君' }, { afterBoss:'boss2' }); this.showArtifactReward(); }
  finishMidBossRewardFlow(){ this.midBossFlowStep='complete'; this.professionPanel?.hide(); this.midBossRewardOpen=false; this.midBossPostFightFlowStarted=false; this.claimingProfession=false; this.runState=RunStates.RUNNING; this.stageSystem?.beginAfterBossReward?.('boss2'); this.endGameplayPause(); this.profLog('gameplay resumed', this.professionFlowSnapshot()); }
  professionFlowSnapshot(){ return { runState:this.runState, modalPausedAt:this.modalPausedAt, professionPanelOpen:!!this.professionPanel?.isOpen, upgradePanelOpen:!!this.upgradePanel?.isOpen, artifactRewardPanelOpen:!!this.artifactRewardPanel?.isOpen, pendingLevelUps:this.upgradeSystem?.pending||0, midBossRewardOpen:this.midBossRewardOpen, midBossPostFightFlowStarted:this.midBossPostFightFlowStarted, midBossFlowStep:this.midBossFlowStep, playerVelocityX:this.player?.body?.velocity?.x||0 }; }
  resetDebugProfessionCase(pending=0){ this.playerInfoPanel?.hide(); this.professionPanel?.hide(); this.upgradePanel?.hide(); this.artifactRewardPanel?.hide(); this.resultPanel?.hide(); this.restPanel?.hide(); this.playerData=createPlayerRuntime(); this.delayedUpgradeUnlockAt=0; this.midBossConsumedOneUpgrade=false; this.playerData.skills=[{id:'fireball',level:1},{id:'lightning',level:1}]; this.upgradeSystem.reset(); this.upgradeSystem.pending=pending; this.runState=RunStates.RUNNING; this.midBossRewardOpen=false; this.midBossPostFightFlowStarted=false; this.midBossFlowStep='complete'; this.claimingProfession=false; this.pendingArtifactReward=null; this.pendingShop=null; this.delayedUpgradeUnlockAt=0; this.modalPausedAt=null; this.player?.body?.setVelocityX(0); }
  selectPanelTwice(panel,index=0){ panel.select(index); panel.select(index); }
  settleAllDebugUpgrades(){ let guard=0; while(this.upgradeSystem.pending>0&&guard<8){ if(!this.upgradePanel.isOpen){ this.resumeModalFlow(); if(!this.upgradePanel.isOpen) throw new Error('pending upgrade panel did not open'); } this.selectPanelTwice(this.upgradePanel,0); guard+=1; } }
  assertDebugProfessionFinal(label){ for(let i=0;i<8;i++) this.update(this.time.now+i*16); const velocity=this.player?.body?.velocity?.x||0; const checks={ professionPanelClosed:this.professionPanel?.isOpen===false, playerInfoClosed:this.playerInfoPanel?.isOpen===false, upgradePanelClosed:this.upgradePanel?.isOpen===false, upgradePanelUnlocked:this.upgradeSystem?.panelOpen===false, midBossRewardClosed:this.midBossRewardOpen===false, midBossFlowClosed:this.midBossPostFightFlowStarted===false, claimClosed:this.claimingProfession===false, running:this.runState===RunStates.RUNNING, unpaused:this.modalPausedAt===null, unblocked:this.hasBlockingModal()===false, moving:velocity>0 };
    const failed=Object.entries(checks).filter(([,ok])=>!ok).map(([k])=>k); if(failed.length) throw new Error(`${label} failed: ${failed.join(',')} velocity=${velocity}`); return velocity; }
  runDebugProfessionCase({pending, professionIndex, occupyPlayerInfo=false, retryFailure=false}){ const professionId=['warrior','mage','ranger'][professionIndex]; this.resetDebugProfessionCase(pending); if(occupyPlayerInfo) this.playerInfoPanel.show(); this.startMidBossPostFightFlow(); if(occupyPlayerInfo){ if(this.professionPanel.isOpen) throw new Error('profession panel stacked over player info'); this.playerInfoPanel.hide(); }
    if(!this.professionPanel.isOpen) throw new Error('profession panel did not open'); if(retryFailure&&this.claimProfession('invalid-profession')!==false) throw new Error('invalid profession should fail'); this.selectPanelTwice(this.professionPanel,professionIndex); if(this.playerData.professionId!==professionId) throw new Error(`profession mismatch ${this.playerData.professionId} !== ${professionId}`); this.professionPanel.select(professionIndex); if(this.playerData.professionId!==professionId) throw new Error('rapid repeat click changed profession'); if(this.upgradePanel.isOpen) throw new Error('pending upgrade preempted boss2 profession/artifact flow'); if(!this.artifactRewardPanel.isOpen) this.resumeModalFlow(); if(!this.artifactRewardPanel.isOpen||!this.midBossRewardOpen) throw new Error('boss2 artifact reward did not open'); if(pending>0 && this.upgradeSystem.pending!==pending) throw new Error('pending upgrades were consumed before boss2 artifact'); this.selectPanelTwice(this.artifactRewardPanel,0); if(pending>0&&this.upgradePanel.isOpen) this.selectPanelTwice(this.upgradePanel,0); const velocity=this.assertDebugProfessionFinal(`pending=${pending} profession=${professionId}${occupyPlayerInfo?' playerInfo':''}`); return { pending, professionId, occupyPlayerInfo, velocity }; }
  runDebugProfessionFlowTest(){ const results=[]; try { [0,1,3].forEach((pending)=>{ [0,1,2].forEach((professionIndex)=>results.push(this.runDebugProfessionCase({pending,professionIndex,retryFailure:pending===0&&professionIndex===0}))); }); results.push(this.runDebugProfessionCase({pending:1,professionIndex:0,occupyPlayerInfo:true})); this.debugProfessionFlowResults=results; const speed=Math.max(...results.map(r=>r.velocity)); const message=`[PROFESSION_FLOW_TEST] PASS pending=0/1/3 professions=warrior/mage/ranger playerInfo=PASS maxVelocity=${speed}`; console.info(message, results); updateDebugStatus(message); this.add.text(DESIGN_WIDTH/2,210,`职业流程测试 PASS\n最大速度 ${speed}`,{fontFamily:'Arial',fontSize:'28px',color:'#9fffb6',backgroundColor:'rgba(0,0,0,0.72)',padding:{left:16,right:16,top:12,bottom:12},align:'center'}).setOrigin(0.5).setScrollFactor(0).setDepth(9000); } catch(error){ console.error('[PROFESSION_FLOW_TEST] FAIL', error, results); updateDebugStatus(`[PROFESSION_FLOW_TEST] FAIL ${error.message}`); this.add.text(DESIGN_WIDTH/2,210,`职业流程测试 FAIL\n${error.message}`,{fontFamily:'Arial',fontSize:'24px',color:'#ff8585',backgroundColor:'rgba(0,0,0,0.82)',padding:{left:16,right:16,top:12,bottom:12},align:'center',wordWrap:{width:650}}).setOrigin(0.5).setScrollFactor(0).setDepth(9000); } }
  showRestPoint(){ if(this.restPanel?.isOpen||this.restCompleted) return; this.beginGameplayPause(); this.runState=RunStates.REST; this.player?.body?.setVelocityX(0); this.restPanel.show(()=>this.claimRestHeal(),()=>this.claimRestSkill()); }
  finishRest(){ if(this.restCompleted) return; this.restCompleted=true; this.restPanel.hide(); this.runState=RunStates.RUNNING; this.pendingShop='second'; this.resumeModalFlow(); }
  claimRestHeal(){ const before=this.playerData.hp; const heal=Math.round(this.playerData.maxHp*0.6); this.playerData.hp=Math.min(this.playerData.maxHp,this.playerData.hp+heal); const actual=this.playerData.hp-before; this.statusEffects?.clearNegativeEffects?.(this.playerData); this.eventBus.emit(CombatEvents.PLAYER_HEALED,{amount:actual,source:'rest'}); this.eventBus.emit(CombatEvents.REST_CHOSEN,{choice:'heal', healing:actual}); this.hud?.update(); this.finishRest(); }
  claimRestSkill(){ this.eventBus.emit(CombatEvents.REST_CHOSEN,{choice:'skill', healing:0}); this.restPanel.hide(); this.beginGameplayPause(); this.upgradePanel.show('休息点突破：高品质技能三选一', this.upgradeSystem.rollHighQualityOptions(), o=>{ this.upgradeSystem.applyFreeOption(o,{source:'restSkill'}); this.eventBus.emit(CombatEvents.REST_CHOSEN,{choice:'skill', skillId:o.skillId, option:o}); this.upgradePanel.hide(); this.finishRest(); }); }

  awardGold(amount, source='enemy'){ const value=Math.max(0,Math.floor(Number(amount)||0)); if(value<=0) return 0; this.playerData.gold=(this.playerData.gold||0)+value; this.runStats?.recordGold?.(value,source); this.hud?.update(); return value; }
  healPlayer(amount, source='heal'){ const value=Math.max(0,Math.floor(Number(amount)||0)); if(value<=0||this.playerData.hp>=this.playerData.maxHp) return 0; const before=this.playerData.hp; this.playerData.hp=Math.min(this.playerData.maxHp,this.playerData.hp+value); const actual=this.playerData.hp-before; if(actual<=0) return 0; this.eventBus.emit(CombatEvents.PLAYER_HEALED,{amount:actual,source}); this.hud?.update(); this.playerHealthBar?.update(); return actual; }
  queueShop(reason){ if(this.pendingShop||[RunStates.VICTORY,RunStates.DEFEAT].includes(this.runState)) return; if(this.shopSystem?.openedReasons?.has(reason)) return; this.pendingShop=reason; this.resumeModalFlow(); }
  onShopClosed(reason){ return closeShopFlow(this, reason); }
  finishRun(won){ if([RunStates.VICTORY,RunStates.DEFEAT].includes(this.runState)||this.resultPanel?.isOpen) return; this.beginGameplayPause(); this.runState=won?RunStates.VICTORY:RunStates.DEFEAT; this.player?.body?.setVelocityX(0); this.combatSystem?.reset(); this.skillSystem?.reset(); this.statusEffects?.reset(); this.enemyBehaviors?.destroy(); this.pendingArtifactReward=null; this.upgradeSystem?.reset(); this.shopSystem?.reset(); this.shopPanel?.hide({resume:false}); this.playerInfoPanel?.hide(); this.upgradePanel?.hide(); this.artifactRewardPanel?.hide(); this.playerHealthBar?.update(); this.eventBus.emit(CombatEvents.RUN_ENDED,{ won }); this.resultPanel.show(won,()=>this.scene.restart()); }
  floatText(x,y,text,color){ const t=this.add.text(x,y,text,{fontFamily:'Arial',fontSize:'24px',color,stroke:'#000',strokeThickness:4}).setOrigin(0.5).setDepth(2500); this.tweens.add({targets:t,y:y-42,alpha:0,duration:650,onComplete:()=>t.destroy()}); }
  createDebugOverlay(){ if(!this.debugMode) return; this.debugOverlay=this.add.text(18,260,'',{fontFamily:'monospace',fontSize:'18px',color:'#00ff66',backgroundColor:'rgba(0,0,0,0.72)',padding:{left:10,right:10,top:8,bottom:8}}).setScrollFactor(0).setDepth(2500); }
  updateDebugOverlay(){ if(!this.debugOverlay) return; const cds=[...this.skillSystem.cooldowns.entries()].map(([id,t])=>`${id}:${Math.max(0,Math.ceil((t-this.getGameplayTime())/1000))}`).join(' '); const prof=this.playerData.professionId ? this.playerData.professionId : '-'; const cfg=this.playerData.professionId ? (this.professionSystem?.currentConfig?.() || null) : null; const st=this.playerData.professionState||{}; const buildTags=collectBuildTagStats({ skills:this.playerData.skills, artifacts:this.playerData.artifacts, professionId:this.playerData.professionId }).dominantTags.join(',') || '-'; this.debugOverlay.setText([`state:${this.runState}`,`playerX:${Math.round(this.player.x)}`,`playerScreenX:${Math.round(this.player.x-(this.cameras.main?.scrollX||0))}`,`target:${this.currentTarget?.name||'-'}`,`targetFull:${this.currentTarget?this.targeting.isEnemyFullyInsideViewport(this.currentTarget):false}`,`enemies:${this.enemies.length}`,`enemyState:${this.enemies.map(e=>e.entryState||'-').join(',')||'-'}`,`recycles:${this.enemyRecycleCount||0}`,`skills:${cds||'-'}`,`profession:${prof}`,`weapon:${cfg?.professionWeaponId||'-'}`,`attack:${cfg?.professionAttackProfile||'-'}`,`剑客增伤:${Math.max(0,((st.warriorBuffUntil||0)-this.getGameplayTime())/1000).toFixed(1)}s`, `学者计数:${st.mageCastCount||0}/5${st.mageEmpoweredNext?' ready':''}`,`猎印:${st.rangerLastTargetMarks||0}/3 ${st.rangerLastTargetId||'-'}`,`破军:${this.artifactSystem?.highHpDamageMultiplier?.()>1?'ON':'OFF'}`,`stage:${this.stageSystem.stage.name}`,`buildTags:${buildTags}`,...(this.lastRewardBiasDebug?[`bias:${this.lastRewardBiasDebug.kind} ${this.lastRewardBiasDebug.enabled?'ON':'OFF'}`,`biasPicked:${this.lastRewardBiasDebug.picked?.join(',')||'-'}`,`biasWeights:${(this.lastRewardBiasDebug.candidates||[]).slice(0,5).map(c=>`${c.id}:${c.weight}`).join(' ')||'-'}`]:[]) ]); }
  cleanupRun(){ this.time.removeAllEvents(); this.tweens.killAll(); this.pendingArtifactReward=null; this.midBossRewardOpen=false; this.midBossPostFightFlowStarted=false; this.midBossFlowStep='complete'; this.claimingProfession=false;  this.modalPausedAt=null; this.enemyBehaviors?.resume(); this.upgradeSystem?.reset(); this.shopSystem?.reset(); this.artifactSystem?.cleanup(); this.statusEffects?.reset(); this.professionWeaponView?.destroy(); this.professionSystem?.destroy(); this.runStats?.destroy(); this.eventBus?.destroy(); this.shopPanel?.hide({resume:false}); this.playerInfoPanel?.hide(); this.upgradePanel?.hide(); this.artifactRewardPanel?.hide(); this.resultPanel?.hide(); this.restPanel?.hide(); this.shopPanel?.hide({resume:false}); this.professionPanel?.hide(); this.playerInfoPanel?.hide(); this.enemies?.forEach(e=>{ this.enemyBehaviors?.destroyEnemy(e); [e.hpBarBg,e.hpBar,e.nameText,e].forEach(o=>o?.destroy()); }); this.enemies=[]; this.skillBar?.destroy(); this.playerHealthBar?.destroy(); this.hud?.destroy(); this.debugOverlay?.destroy(); this.playtestPanel?.destroy(); }
  showInitError(error){ this.add.text(24,220,`初始化失败：${this.initStage}\n${error.name||'Error'}: ${error.message||String(error)}`,{fontFamily:'Arial',fontSize:'28px',color:'#fff',backgroundColor:'rgba(190,0,0,0.92)',padding:{left:18,right:18,top:14,bottom:14},wordWrap:{width:DESIGN_WIDTH-48}}).setOrigin(0,0).setScrollFactor(0).setDepth(10000); }
}
