import Phaser from 'phaser';
import { DESIGN_HEIGHT, DESIGN_WIDTH } from '../config/gameConfig.js';
import { BALANCE, createPlayerRuntime } from '../config/balance.js';
import EventBus from '../core/EventBus.js';
import { CombatEvents, RunStates, ACTIVE_STATES } from '../core/CombatEvents.js';
import createPlayer from '../entities/createPlayer.js';
import TargetingSystem from '../systems/TargetingSystem.js';
import MovementSystem from '../systems/MovementSystem.js';
import CombatSystem from '../systems/CombatSystem.js';
import SkillSystem from '../systems/SkillSystem.js';
import ArtifactSystem from '../systems/ArtifactSystem.js';
import UpgradeSystem from '../systems/UpgradeSystem.js';
import StageSystem from '../systems/StageSystem.js';
import StatusEffectSystem from '../systems/StatusEffectSystem.js';
import Hud from '../ui/Hud.js';
import UpgradePanel from '../ui/UpgradePanel.js';
import ResultPanel from '../ui/ResultPanel.js';
import SkillBar from '../ui/SkillBar.js';
import RunStatsSystem from '../systems/RunStatsSystem.js';
import ProfessionSystem from '../systems/ProfessionSystem.js';
import PlaytestPanel from '../ui/PlaytestPanel.js';
import { collectBuildTagStats } from '../utils/buildTags.js';
import RestPanel from '../ui/RestPanel.js';
import ProfessionPanel from '../ui/ProfessionPanel.js';
import ProfessionWeaponView from '../views/ProfessionWeaponView.js';
import EnemyBehaviorManager from '../enemies/behaviors/EnemyBehaviorManager.js';
import { GAME_VERSION_LABEL } from '../config/version.js';

const updateDebugStatus = (message) => window.updateGameDebugStatus?.(message);

export default class GameScene extends Phaser.Scene {
  constructor(){ super('GameScene'); this.initStage='尚未开始'; }
  create(){ try { this.balance=BALANCE; this.debugMode=new URLSearchParams(window.location.search).get('debug')==='1'; this.runState=RunStates.STARTING; this.playerData=createPlayerRuntime(); this.enemies=[]; this.killCount=0; this.restCompleted=false; this.midBossRewardOpen=false; this.midBossPostFightFlowStarted=false; this.claimingProfession=false; this.currentTarget=null; this.pendingArtifactReward=null; this.modalPausedAt=null; this.eventBus=new EventBus(); this.configureWorld(); this.createBackground(); this.createGround(); this.player=createPlayer(this,BALANCE.player,BALANCE.groundTopY); this.physics.add.collider(this.player,this.physicsGround); this.configurePlayerCamera(); this.targeting=new TargetingSystem(this); this.movementSystem=new MovementSystem(this); this.professionSystem=new ProfessionSystem(this); this.professionWeaponView=new ProfessionWeaponView(this); this.combatSystem=new CombatSystem(this); this.skillSystem=new SkillSystem(this); this.artifactSystem=new ArtifactSystem(this); this.statusEffects=new StatusEffectSystem(this); this.enemyBehaviors=new EnemyBehaviorManager(this); this.runStats=new RunStatsSystem(this); this.upgradeSystem=new UpgradeSystem(this); this.stageSystem=new StageSystem(this); this.hud=new Hud(this); this.skillBar=new SkillBar(this); this.upgradePanel=new UpgradePanel(this); this.rewardPanel=new UpgradePanel(this); this.resultPanel=new ResultPanel(this); this.restPanel=new RestPanel(this); this.professionPanel=new ProfessionPanel(this); if(this.debugMode) this.playtestPanel=new PlaytestPanel(this); this.createTitle(); this.createRestartButton(); this.createDebugOverlay(); this.stageSystem.start(); this.artifactSystem.load(); this.hud.setStatus('选择开局技能'); this.showStartingSkillChoice(); this.hud.update(); this.events.once(Phaser.Scenes.Events.SHUTDOWN,()=>this.cleanupRun()); updateDebugStatus(GAME_VERSION_LABEL); } catch(e){ this.showInitError(e); throw e; } }
  update(time){ if(!this.isGameplayPaused()){ this.movementSystem.update(time); this.combatSystem.update(time); this.skillSystem.update(time); this.artifactSystem.update(time); this.statusEffects.update(time); this.stageSystem.update(time); } else this.player?.body?.setVelocityX(0); this.professionWeaponView?.update(); this.hud?.update(); this.skillBar?.update(); this.playtestPanel?.update(); this.updateDebugOverlay(); }
  hasBlockingModal(){ return !ACTIVE_STATES.has(this.runState)||this.upgradePanel?.isOpen||this.rewardPanel?.isOpen||this.resultPanel?.isOpen||this.playtestPanel?.isOpen||this.restPanel?.isOpen||this.midBossRewardOpen||this.professionPanel?.isOpen||!!this.pendingArtifactReward||!!(this.upgradeSystem?.pending>0)||!!this.upgradeSystem?.panelOpen; }
  isGameplayPaused(){ return this.hasBlockingModal(); }
  getGameplayTime(){ return this.modalPausedAt ?? this.time.now; }
  beginGameplayPause(){ if(this.modalPausedAt!==null) return; this.modalPausedAt=this.time.now; this.player?.body?.setVelocityX(0); this.enemyBehaviors?.pause(); this.enemies?.forEach(e=>{ if(e?.active&&e.body&&!e.isDefeated) e.body.setVelocityX(0); }); }
  canEndGameplayPause(){ return this.runState!==RunStates.STARTING&&!this.hasBlockingModal(); }
  endGameplayPause(){ if(this.modalPausedAt===null||!this.canEndGameplayPause()) return; if([RunStates.VICTORY,RunStates.DEFEAT].includes(this.runState)) return; const pausedAt=this.modalPausedAt; const pausedDuration=Math.max(0,this.time.now-pausedAt); this.modalPausedAt=null; if(pausedDuration>0){ this.combatSystem?.shiftTimers(pausedDuration,pausedAt); this.skillSystem?.shiftTimers(pausedDuration,pausedAt); this.artifactSystem?.shiftTimers(pausedDuration,pausedAt); this.professionSystem?.shiftTimers(pausedDuration,pausedAt); this.statusEffects?.shiftTimers(pausedDuration,pausedAt); this.enemyBehaviors?.shiftTimers(pausedDuration,pausedAt); this.runStats?.addPausedDuration(pausedDuration); } this.enemyBehaviors?.resume(); }
  configureWorld(){ const width=7600; this.physics.world.setBounds(0,0,width,DESIGN_HEIGHT); this.cameras.main.setBounds(0,0,width,DESIGN_HEIGHT); }
  configurePlayerCamera(){ const camera=this.cameras.main; const anchor=this.balance.camera?.playerScreenAnchorX ?? 0.5; const offsetX=DESIGN_WIDTH*(anchor-0.5); camera.startFollow(this.player,false,1,0,offsetX,0); }
  createBackground(){ this.cameras.main.setBackgroundColor('#202638'); for(let x=300;x<7600;x+=420){ this.add.rectangle(x,BALANCE.groundTopY-92,12,185,0x2f3547,0.75).setDepth(5); } }
  createGround(){ this.add.rectangle(3800,BALANCE.groundTopY+BALANCE.groundHeight/2,7600,BALANCE.groundHeight,0x253522,1).setDepth(10); this.physicsGround=this.add.rectangle(3800,BALANCE.groundTopY+BALANCE.groundHeight/2,7600,BALANCE.groundHeight,0x000000,0); this.physics.add.existing(this.physicsGround,true); }
  createTitle(){ this.add.text(DESIGN_WIDTH/2,34,'自动战斗肉鸽框架 Demo',{fontFamily:'Arial',fontSize:'32px',color:'#e9efff',stroke:'#000',strokeThickness:5}).setOrigin(0.5,0).setScrollFactor(0).setDepth(1000); }
  createRestartButton(){ this.restartButton=this.add.text(DESIGN_WIDTH-22,28,'重新开始',{fontFamily:'Arial',fontSize:'24px',color:'#fff',backgroundColor:'#333',padding:{left:12,right:12,top:8,bottom:8}}).setOrigin(1,0).setScrollFactor(0).setInteractive({useHandCursor:true}).setDepth(2000); this.restartButton.on('pointerdown',()=>this.scene.restart()); }
  showProfessionChoice(){ this.beginGameplayPause(); this.professionPanel.show((id)=>this.claimProfession(id)); }
  claimProfession(id){
    if(this.claimingProfession){ console.warn('[GameScene] duplicate profession claim ignored', { professionId:id, currentProfession:this.playerData.professionId }); return false; }
    if(this.playerData.professionId){ console.warn('[GameScene] profession claim ignored because profession already chosen', { professionId:id, currentProfession:this.playerData.professionId }); return false; }
    this.claimingProfession=true;
    const selected=this.professionSystem.selectProfession(id);
    if(!selected){ this.claimingProfession=false; console.error('[GameScene] profession claim failed; reward flow remains paused for retry', { professionId:id, runState:this.runState, pendingLevelUps:this.upgradeSystem?.pending }); return false; }
    try { this.hud?.setStatus('职业觉醒完成'); } catch(error){ console.error('[GameScene] profession status UI refresh failed', { professionId:id, error }); }
    if(this.midBossPostFightFlowStarted){ console.info('[GameScene] profession chosen; continuing mid-boss reward flow', { professionId:id, pendingLevelUps:this.upgradeSystem?.pending }); this.processPendingMidBossLevelUps(); }
    return true;
  }
  showStartingSkillChoice(){ this.beginGameplayPause(); const options=this.upgradeSystem.rollStartingOptions(); this.upgradePanel.show('开局技能三选一', options, (o)=>this.claimStartingSkill(o)); }
  claimStartingSkill(option){ this.skillSystem.addOrLevel(option.skillId,{starting:true}); this.upgradePanel.hide(); this.hud?.setStatus('自动战斗开始'); this.runState=RunStates.RUNNING; this.endGameplayPause(); }
  queueArtifactReward(enemy){ if(this.pendingArtifactReward||[RunStates.VICTORY,RunStates.DEFEAT].includes(this.runState)) return; this.pendingArtifactReward={ enemyId:enemy.id, enemyName:enemy.name }; }
  showArtifactReward(){ if(!this.pendingArtifactReward||[RunStates.VICTORY,RunStates.DEFEAT].includes(this.runState)||this.rewardPanel.isOpen) return; this.beginGameplayPause(); this.runState=RunStates.REWARD; const options=this.artifactSystem.rollRewardOptions(3); this.rewardPanel.show({ title:'法宝奖励三选一', options, mode:'icon', onConfirm:(o)=>this.claimArtifactReward(o) }); }
  claimArtifactReward(option){ if(!this.pendingArtifactReward) return; if(option.type==='fallback') this.artifactSystem.applyFallback(option); else if(option.type==='upgrade') this.artifactSystem.upgrade(option.artifactId); else this.artifactSystem.add(option.artifactId); this.eventBus.emit(CombatEvents.ARTIFACT_CHOSEN,{ artifactId:option.artifactId, option }); this.pendingArtifactReward=null; this.rewardPanel.hide(); this.resumeModalFlow(); }
  resumeModalFlow(){ if([RunStates.VICTORY,RunStates.DEFEAT].includes(this.runState)) return; if(this.resultPanel?.isOpen||this.rewardPanel?.isOpen||this.upgradePanel?.isOpen||this.playtestPanel?.isOpen||this.restPanel?.isOpen||this.professionPanel?.isOpen) return; if(this.midBossPostFightFlowStarted){ if(this.upgradeSystem?.pending>0){ this.runState=RunStates.RUNNING; this.upgradeSystem.panelOpen=false; this.upgradeSystem.maybeShow(); return; } this.showActualMidBossReward(); return; } if(this.pendingArtifactReward){ this.showArtifactReward(); return; } const activeState=this.enemies?.some(e=>e.isFinalBoss&&!e.isDefeated)?RunStates.BOSS:RunStates.RUNNING; if(this.upgradeSystem?.pending>0){ this.runState=activeState; this.upgradeSystem.panelOpen=false; this.upgradeSystem.maybeShow(); return; } this.runState=activeState; this.endGameplayPause(); }

  startMidBossPostFightFlow(){ if(this.midBossPostFightFlowStarted) return; this.midBossPostFightFlowStarted=true; this.beginGameplayPause(); this.runState=RunStates.REWARD; this.player?.body?.setVelocityX(0); this.showProfessionChoice(); }
  showMidBossReward(){ this.processPendingMidBossLevelUps(); }
  processPendingMidBossLevelUps(){ if(!this.midBossPostFightFlowStarted||this.midBossRewardOpen) return; this.beginGameplayPause(); if(this.upgradeSystem.pending>0){ this.runState=RunStates.RUNNING; this.upgradeSystem.panelOpen=false; this.upgradeSystem.maybeShow(); return; } this.showActualMidBossReward(); }
  showActualMidBossReward(){ if(!this.midBossPostFightFlowStarted||this.midBossRewardOpen||this.upgradePanel?.isOpen) return; this.midBossRewardOpen=true; this.beginGameplayPause(); this.runState=RunStates.REWARD; this.upgradePanel.show('铁甲暴君奖励：高品质技能三选一', this.upgradeSystem.rollHighQualityOptions(), o=>{ this.upgradeSystem.applyFreeOption(o,{source:'midBossReward'}); this.upgradePanel.hide(); this.midBossRewardOpen=false; this.midBossPostFightFlowStarted=false; this.claimingProfession=false; this.runState=RunStates.RUNNING; this.stageSystem?.enterPhaseById('late'); this.endGameplayPause(); }); }
  showRestPoint(){ if(this.restPanel?.isOpen||this.restCompleted) return; this.beginGameplayPause(); this.runState=RunStates.REST; this.player?.body?.setVelocityX(0); this.restPanel.show(()=>this.claimRestHeal(),()=>this.claimRestSkill()); }
  finishRest(){ if(this.restCompleted) return; this.restCompleted=true; this.restPanel.hide(); this.runState=RunStates.RUNNING; this.stageSystem.enterPhaseById('finalBoss'); this.endGameplayPause(); }
  claimRestHeal(){ const before=this.playerData.hp; const heal=Math.round(this.playerData.maxHp*0.6); this.playerData.hp=Math.min(this.playerData.maxHp,this.playerData.hp+heal); const actual=this.playerData.hp-before; this.statusEffects?.clearNegativeEffects?.(this.playerData); this.eventBus.emit(CombatEvents.PLAYER_HEALED,{amount:actual,source:'rest'}); this.eventBus.emit(CombatEvents.REST_CHOSEN,{choice:'heal', healing:actual}); this.hud?.update(); this.finishRest(); }
  claimRestSkill(){ this.eventBus.emit(CombatEvents.REST_CHOSEN,{choice:'skill', healing:0}); this.restPanel.hide(); this.beginGameplayPause(); this.upgradePanel.show('休息点突破：高品质技能三选一', this.upgradeSystem.rollHighQualityOptions(), o=>{ this.upgradeSystem.applyFreeOption(o,{source:'restSkill'}); this.eventBus.emit(CombatEvents.REST_CHOSEN,{choice:'skill', skillId:o.skillId, option:o}); this.upgradePanel.hide(); this.finishRest(); }); }
  finishRun(won){ if([RunStates.VICTORY,RunStates.DEFEAT].includes(this.runState)||this.resultPanel?.isOpen) return; this.beginGameplayPause(); this.runState=won?RunStates.VICTORY:RunStates.DEFEAT; this.player?.body?.setVelocityX(0); this.combatSystem?.reset(); this.skillSystem?.reset(); this.statusEffects?.reset(); this.enemyBehaviors?.destroy(); this.pendingArtifactReward=null; this.upgradeSystem?.reset(); this.upgradePanel?.hide(); this.rewardPanel?.hide(); this.eventBus.emit(CombatEvents.RUN_ENDED,{ won }); this.resultPanel.show(won,()=>this.scene.restart()); }
  floatText(x,y,text,color){ const t=this.add.text(x,y,text,{fontFamily:'Arial',fontSize:'24px',color,stroke:'#000',strokeThickness:4}).setOrigin(0.5).setDepth(2500); this.tweens.add({targets:t,y:y-42,alpha:0,duration:650,onComplete:()=>t.destroy()}); }
  createDebugOverlay(){ if(!this.debugMode) return; this.debugOverlay=this.add.text(18,260,'',{fontFamily:'monospace',fontSize:'18px',color:'#00ff66',backgroundColor:'rgba(0,0,0,0.72)',padding:{left:10,right:10,top:8,bottom:8}}).setScrollFactor(0).setDepth(2500); }
  updateDebugOverlay(){ if(!this.debugOverlay) return; const cds=[...this.skillSystem.cooldowns.entries()].map(([id,t])=>`${id}:${Math.max(0,Math.ceil((t-this.getGameplayTime())/1000))}`).join(' '); const prof=this.playerData.professionId ? this.playerData.professionId : '-'; const cfg=this.playerData.professionId ? (this.professionSystem?.currentConfig?.() || null) : null; const st=this.playerData.professionState||{}; const buildTags=collectBuildTagStats({ skills:this.playerData.skills, artifacts:this.playerData.artifacts, professionId:this.playerData.professionId }).dominantTags.join(',') || '-'; this.debugOverlay.setText([`state:${this.runState}`,`playerX:${Math.round(this.player.x)}`,`playerScreenX:${Math.round(this.player.x-(this.cameras.main?.scrollX||0))}`,`target:${this.currentTarget?.name||'-'}`,`targetFull:${this.currentTarget?this.targeting.isEnemyFullyInsideViewport(this.currentTarget):false}`,`enemies:${this.enemies.length}`,`enemyState:${this.enemies.map(e=>e.entryState||'-').join(',')||'-'}`,`recycles:${this.enemyRecycleCount||0}`,`skills:${cds||'-'}`,`profession:${prof}`,`weapon:${cfg?.professionWeaponId||'-'}`,`attack:${cfg?.professionAttackProfile||'-'}`,`剑客增伤:${Math.max(0,((st.warriorBuffUntil||0)-this.getGameplayTime())/1000).toFixed(1)}s`, `学者计数:${st.mageCastCount||0}/5${st.mageEmpoweredNext?' ready':''}`,`猎印:${st.rangerLastTargetMarks||0}/3 ${st.rangerLastTargetId||'-'}`,`破军:${this.artifactSystem?.highHpDamageMultiplier?.()>1?'ON':'OFF'}`,`stage:${this.stageSystem.stage.name}`,`buildTags:${buildTags}`,...(this.lastRewardBiasDebug?[`bias:${this.lastRewardBiasDebug.kind} ${this.lastRewardBiasDebug.enabled?'ON':'OFF'}`,`biasPicked:${this.lastRewardBiasDebug.picked?.join(',')||'-'}`,`biasWeights:${(this.lastRewardBiasDebug.candidates||[]).slice(0,5).map(c=>`${c.id}:${c.weight}`).join(' ')||'-'}`]:[]) ]); }
  cleanupRun(){ this.time.removeAllEvents(); this.tweens.killAll(); this.pendingArtifactReward=null; this.midBossRewardOpen=false; this.midBossPostFightFlowStarted=false; this.claimingProfession=false; this.modalPausedAt=null; this.enemyBehaviors?.resume(); this.upgradeSystem?.reset(); this.artifactSystem?.cleanup(); this.statusEffects?.reset(); this.professionWeaponView?.destroy(); this.professionSystem?.destroy(); this.runStats?.destroy(); this.eventBus?.destroy(); this.upgradePanel?.hide(); this.rewardPanel?.hide(); this.resultPanel?.hide(); this.restPanel?.hide(); this.professionPanel?.hide(); this.enemies?.forEach(e=>{ this.enemyBehaviors?.destroyEnemy(e); [e.hpBarBg,e.hpBar,e.nameText,e].forEach(o=>o?.destroy()); }); this.enemies=[]; this.skillBar?.destroy(); this.hud?.destroy(); this.debugOverlay?.destroy(); this.playtestPanel?.destroy(); }
  showInitError(error){ this.add.text(24,220,`初始化失败：${this.initStage}\n${error.name||'Error'}: ${error.message||String(error)}`,{fontFamily:'Arial',fontSize:'28px',color:'#fff',backgroundColor:'rgba(190,0,0,0.92)',padding:{left:18,right:18,top:14,bottom:14},wordWrap:{width:DESIGN_WIDTH-48}}).setOrigin(0,0).setScrollFactor(0).setDepth(10000); }
}
