export const CombatEvents = Object.freeze({
  PLAYER_ATTACK: 'PLAYER_ATTACK', PLAYER_HIT: 'PLAYER_HIT', PLAYER_CRIT: 'PLAYER_CRIT', ENEMY_HIT: 'ENEMY_HIT', ENEMY_KILLED: 'ENEMY_KILLED', PLAYER_DAMAGED: 'PLAYER_DAMAGED', PLAYER_LOW_HP: 'PLAYER_LOW_HP', SKILL_CAST: 'SKILL_CAST', SKILL_HIT: 'SKILL_HIT', ARTIFACT_TRIGGERED: 'ARTIFACT_TRIGGERED', LEVEL_UP: 'LEVEL_UP', BOSS_SPAWNED: 'BOSS_SPAWNED', BOSS_KILLED: 'BOSS_KILLED', PLAYER_HEALED: 'PLAYER_HEALED', UPGRADE_CHOSEN: 'UPGRADE_CHOSEN', ARTIFACT_CHOSEN: 'ARTIFACT_CHOSEN', RUN_ENDED: 'RUN_ENDED', STARTING_SKILL_CHOSEN: 'STARTING_SKILL_CHOSEN'
});
export const RunStates = Object.freeze({ STARTING: 'STARTING', RUNNING: 'RUNNING', UPGRADING: 'UPGRADING', REWARD: 'REWARD', BOSS: 'BOSS', VICTORY: 'VICTORY', DEFEAT: 'DEFEAT' });
export const ACTIVE_STATES = new Set([RunStates.RUNNING, RunStates.BOSS]);
